### ISSUE TITLE
remove dependency on worldtimeapi.org

### ISSUE THREAD

**Issue by menduz** [decentraland/issues#10]
When the service fails, it won't finish loading. Instead, the remote header "Date" could be used, when we talk to the selected catalyst server.

<img width="1500" alt="Screen Shot 2021-03-24 at 14 22 25" src="https://user-images.githubusercontent.com/260114/112355410-5e57ad80-8cac-11eb-8c97-2117afd194cb.png">

**Comment by nchamo** [comment]
I don't think that error is the cause of the explorer not loading.

Check [the code](https://github.com/decentraland/explorer/blob/558ff71022e6d749e123395f98ef267df6c36340/kernel/packages/shared/friends/sagas.ts#L121
)

First, it tries to fetch the current time from the catalyst. If it fails, then it goes to worldtimeapi. And if that fails, then it uses the local machine time.

I think there was probably a problem with the catalyst in your case, and it would explain why worldtimeapi was used at all
