### ISSUE TITLE
lagging 

### ISSUE THREAD

**Issue by Diyali007** [decentraland/issues#100]
### What happened?

lagging alot

### Steps to reproduce

smooth playing experience would be great

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

None, played as guest

### CPU

M1

### GPU

Apple M1 512MB

### RAM

8GB

### Kernel Version

1.0.0-1466666616.commit-b3bf440

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

dg

### NameTag

Diyali#5ea9

**Comment by davidejensen** [comment]
The experience has been improved a lot also on the performance side in the past few months, if you still encounter heavy lag or stutter please open a new issue with more detailed information
