### ISSUE TITLE
Dragon city quest Q&A unable to select other options

### ISSUE THREAD

**Issue by jenninghsu** [decentraland/issues#101]
### What happened?

Dragon city quest Q&A unable to select other options

### Steps to reproduce

speak to Robot cow > click next step> unable to select third and fourth options

### Operating System

Chrome MacBook Pro (Retina, 15-inch, Mid 2015)

### Wallet

Metamask

### CPU

2.8 GHz Quad-Core Intel Core i7

### GPU

Intel Iris Pro 1536 MB

### RAM

16 GB 1600 MHz DDR3

### Kernel Version

1.0.0-1466666616.commit-b3bf440

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

unicorn

### NameTag

Jenny#e61d

**Comment by pravusjif** [comment]
We close this issue since the Quests service has been disabled for several months now. It will be reimplemented in the future.
