### ISSUE TITLE
Golfcraft game competition bug

### ISSUE THREAD

**Issue by Billabongo** [decentraland/issues#102]
### What happened?

I often get stuck while logging in to Decentraland, or in particular to the Golfcraft game. When i start a competition the screen gets stuck on a black image and doesn't start. It's very annoying and not good for Decentraland. 

### Steps to reproduce

Fix the problem

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Metamask

### CPU

2,6 GHz Intel Core i5 dual-core

### GPU

Intel Iris OpenGL Engine 1536MB

### RAM

4GB

### Kernel Version

1.0.0-1466666616.commit-b3bf440

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

unicorn

### NameTag

MetaCashJ#3c49

**Comment by pabloes** [comment]
This seem to had been a temporal issue that was already solved.

**Comment by pravusjif** [comment]
This bug has already been fixed
