### ISSUE TITLE
missing!!!!

### ISSUE THREAD

**Issue by tunatime619** [decentraland/issues#103]
### What happened?

I was in the gold land and earned a bunch of coins and also tickets i had 100 tickets and i think 400 coins when i left and came back they were alll gone i spent like 2 hours in here playing to get those 

### Steps to reproduce

not sure 

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Fortmatic

### CPU

intel 9 10th gen 

### GPU

ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.9664) 512MB

### RAM

328gb

### Kernel Version

1.0.0-1466666616.commit-b3bf440

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

unicorn

### NameTag

SWEETFKNMEMORY#e01e

**Comment by D4rWiNSS** [comment]
This can't be fixed on our end since this bug is related to the scene. The content creator should fix it
