### ISSUE TITLE
Polygonal Moles Quest

### ISSUE THREAD

**Issue by Preisolauphenonputenic** [decentraland/issues#104]
### What happened?

I played the Polygonal Mole quest at 7,46 and hit 15 moles (it originally showed I had hit all of them).  My Quest notice is showing I only hit 14.  I tried a 2nd time and only hit 14, but the meter showed 14 the entire time.  So, it's not giving me a completion for that step to earn the POAP badge for this quest.

### Steps to reproduce

Go to 2,47 (or thereabouts) and it should off you the 'Polygonal Mole' quest.  When you go to 7,46, click the mole w/ the mallet and play the game.  If you hit 15 in a row, it's supposed to either take you to a 3rd step in the quest, or give you the POAP badge for the game (not sure, since it won't let me past that).

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Metamask

### CPU

2.6 GHz 6-Core Intel Core i7

### GPU

AMD Radeon Pro 5500M OpenGL Engine 512MB

### RAM

16 GB 2667 MHz DDR4

### Kernel Version

1.0.0-1466666616.commit-b3bf440

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

poseidon

### NameTag

Preisolauphenon#fd26

**Comment by pravusjif** [comment]
Quests service is currently disabled, so we are closing this old issue.
