### ISSUE TITLE
Super buggy....

### ISSUE THREAD

**Issue by donutvan** [decentraland/issues#105]
### What happened?

I completed the gems hunting part in the drink quest but it got stucked at 8/10 gems so I had to restart that part again. Screen was very laggy too. Frames pausing every 2 seconds... Picking up the items for the drink was also buggy

### Steps to reproduce

I was doing the drink of the gods quest. 

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Metamask

### CPU

Intel Core i5 2.3Ghz

### GPU

Intel(R) Iris(TM) Plus Graphics 640 512MB

### RAM

8GB

### Kernel Version

1.0.0-1466666616.commit-b3bf440

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

baldr

### NameTag

definerd#8914

**Comment by pravusjif** [comment]
Quests services are disabled for now, so we are closing this issue.
