### ISSUE TITLE
Progress is not being saved

### ISSUE THREAD

**Issue by Dunscannin** [decentraland/issues#106]
### What happened?

I completed all stages of the DragonCity Tangram Quest, had confirmation that I was awarded 1 POAP and went to the next quest and it appears that the same quest is in my quest log and when I click Jump In it takes me to the start and no progress was saved. I then tried SteamPunk and collect a couple of cogs and TWICE I got the error message "Some errors with Quests API" followed by the attached screenshot. 

I'm new to this game but cannot play it as there's no point if none of your progress is saved. Please investigate and restore my lost progress... Many thanks 

![Screenshot 2021-11-20 at 22 48 54](https://user-images.githubusercontent.com/94765845/142743034-5d9b8c93-1834-440b-99a3-377d765f3221.jpg)
  

### Steps to reproduce

When I log in at my current progress in the game the above error message are displayed. If I click through and attempt to play my the task resets and I have to restart again - but as the same thing happens there is obviously no point in playing:-(

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36

### Wallet

Metamask

### CPU

4.2 GHz Quad-Core Intel Core i7

### GPU

AMD Radeon Pro 580 OpenGL Engine 512MB

### RAM

24GB

### Kernel Version

1.0.0-1466666616.commit-b3bf440

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

dg

### NameTag

Dunscannin#4e97

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
