### ISSUE TITLE
The drink of the gods gem bug

### ISSUE THREAD

**Issue by regalty** [decentraland/issues#109]
### What happened?

Got duplicate gems from clicking vases too fast now my quest is bug (says bring gems to chaman but I already did)

### Steps to reproduce

double click vases very quickly for duplicate gems

### Operating System

Chrome, Windows 10

### Wallet

Metamask

### CPU

Intel i5-6200U 6th generation

### GPU

ANGLE (Intel, Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0, D3D11-21.20.16.4727) 512MB

### RAM

12

### Kernel Version

1.0.0-1466666616.commit-b3bf440

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

dg

### NameTag

Regal#05cd

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
