### ISSUE TITLE
Music still playing with 0 audio in settings

### ISSUE THREAD

**Issue by JalalSinno** [decentraland/issues#110]
### What happened?

I turned down my music to 0 but audio is still playing when I joined a NFT poker session.

### Steps to reproduce

Click the link to join a NFT Gambling server, turned down the music to 0, still able to hear the music with no change in volume.

### Operating System

Chrome/96.0.4664.45

### Wallet

Metamask

### CPU

AMD Ryzen 3700

### GPU

ANGLE (AMD, AMD Radeon RX 5700 XT Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.13025.5005) 512MB

### RAM

32gb

### Kernel Version

1.0.0-1466666616.commit-b3bf440

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

fenrir

### NameTag

CazCrypto#61fd

**Comment by olavra** [comment]
Hi @JalalSinno 

Thank you very much for taking the time to report this bug, and sorry for our delay in getting back to you. 

Over the last few months we have introduced several changes that should have fixed this problem. We have not been able to reproduce it.

Please note that the music bar only affects in-game music (such as in the tutorial or in character creation). The rest of the music is controlled by the scenes, so you can lower it using the "World" slider.

Could you please let us know if this is still happening to you?

Best regards

**Comment by D4rWiNSS** [comment]
Close because there is no answer from the reporter
