### ISSUE TITLE
0,46 Graphics Glitch

### ISSUE THREAD

**Issue by Preisolauphenonputenic** [decentraland/issues#111]
### What happened?

While walking/running (pressing 'W') north along 0's walkway/people-mover, there's a 'light' on the left hand side who's light looks 'solid' for moments, and occasionally, while walking/running through that segment, a glitch appears with pieces from a few of the local squares that crosses into this section.  I sometimes have to jump (press 'Space Bar') to get passed it.  The glitch with all the segments from other sections typically only actually appears when I'm running back the other way/South toward 0,0.  

### Steps to reproduce

Run/walk north along the left-hand sidewalk to the left of the People Mover track along 0,44 to 0,47.  You should see the two light beams as you get close to one of the light posts.  They'll flicker, and disappear off and on depending on how you move.

Also, after you've passed 0,47, if you turn around and walk back the exact same direction, you'll get to around the same place and cross the same place as pieces from other lots flicker in and out of the area while you pass through.  You may also be 'stopped' and have to jump to keep going.

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Metamask

### CPU

2.6 GHz 6-Core Intel Core i7

### GPU

AMD Radeon Pro 5500M OpenGL Engine 512MB

### RAM

16 GB 2667 MHz DDR4

### Kernel Version

1.0.0-1466666616.commit-b3bf440

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

heimdallr

### NameTag

Preisolauphenon#fd26

**Comment by olavra** [comment]
Hi @Preisolauphenonputenic 

Thank you very much for taking the time to report this bug, and sorry for our delay in getting back to you. 

Over the last few months we have introduced several changes that should have fixed this problem. We have not been able to reproduce it.

Could you please let us know if this is still happening to you? If so, it may be a problem with a specific hardware configuration.

Best regards

**Comment by D4rWiNSS** [comment]
Closed because the reporter doesn't answer
