### ISSUE TITLE
Golfcraft - Dissapearing hour boosts, problems with collecting checkpoints, problems with competition challenges

### ISSUE THREAD

**Issue by parunev** [decentraland/issues#112]
### What happened?

Hello,
My name is MetaThug#09a3 

First of all the hour boosts. They basically disappear whenever I get them and play one training with them. EVERY SINGLE TIME.

Second problem is the collecting checkpoints. I collect all of them then suddenly I didn't and I keep collecting and collecting and collecting losing time, gold coins and xp.

Third problem is the competition. I play but then my game do not appear at the award section. Which drives me mad because I do great and not recieving anything in return.

I played for hours and lost at least 800-900, shit tons of coins and not to mention training boosts. 

I'm appealing for fix ASAP. Also I want to receive a boost for 2-3hours because I lost like 5 of them. It's not fair. Spending time in the game, tryharding, collecting tickets and receiving almost nothing in return.

### Steps to reproduce

I got no clue what can do. Maybe the game developer have to do something to fix the nasty glitches which causes US(players) to get mad at this otherwise good game.

### Operating System

Chrome/96.0.4664.55

### Wallet

Metamask

### CPU

Intel Dual-Core i5

### GPU

Intel(R) HD Graphics 6000 1536MB

### RAM

4GB

### Kernel Version

1.0.0-1490772441.commit-c054508

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

marvel

### NameTag

MetaThug#09a3

**Comment by pabloes** [comment]
This issue was solved time ago
