### ISSUE TITLE
The drink of gods quest not fully completed 

### ISSUE THREAD

**Issue by Jasonsutra** [decentraland/issues#113]
### What happened?

![Screenshot 2021-11-23 at 04 49 37](https://user-images.githubusercontent.com/94870378/142933305-c57cb2ba-1ba7-4287-b877-64fcc38d711d.png)

All sub quest completed and also finished off with the final drink with the bartender with the won chalice. But the gem sub quest was laggy and not completed. Please refer to attached screenshot.

### Steps to reproduce

Not sure how to reproduce but I am not able to do this quest anymore.

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Metamask

### CPU

M1

### GPU

Apple M1 512MB

### RAM

16GB

### Kernel Version

1.0.0-1491686062.commit-9e9b8c3

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

dg

### NameTag

JimmyFallon#507b

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
