### ISSUE TITLE
can't save quest progress

### ISSUE THREAD

**Issue by ckayra** [decentraland/issues#114]
### What happened?

finished SteamPunk Quest, last step:talking with Anna

SetQuestProgressState:717faa62-4116-4402-9658-05e1683308a
http:500
details:Unexpected error

### Steps to reproduce

finish SteamPunk Quest and talk to Anna to get the reward

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Fortmatic

### CPU

Intel i7

### GPU

ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.9664) 512MB

### RAM

16GB

### Kernel Version

1.0.0-1491686062.commit-9e9b8c3

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

dg

### NameTag

Chiara#d7ce

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
