### ISSUE TITLE
i saw like 20 cards insteaf of 2 or 3 in the black jack table at the tomynoya casino

### ISSUE THREAD

**Issue by d3fcom** [decentraland/issues#115]
### What happened?

the table was keep doing this bug 
![wtf](https://user-images.githubusercontent.com/23270466/142978264-163d7754-ac5f-4ce8-a542-f4bec05d4347.PNG)
, 

### Steps to reproduce

hide the cards that are not use full no more ( because the past hand is finished).
(it already work well I just don't know why it happened some times )

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

raysen 5 double core

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7196) 512MB

### RAM

32

### Kernel Version

1.0.0-1491686062.commit-9e9b8c3

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

dg

### NameTag

weis#b0e2

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
