### ISSUE TITLE
Tutorial Menu BUG

### ISSUE THREAD

**Issue by MoFaNi** [decentraland/issues#116]
### What happened?

I opened the tutorial and after reaching the "Use the Explore to find scenes with experienced players in them" it is stuck and doesnt move to the next one and doesnt go away either.

### Steps to reproduce

I think when we go to explore tab it doesnt apply to the tutorial

### Operating System

Chrome windows 10

### Wallet

Metamask

### CPU

core i 7

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7168) 512MB

### RAM

32gb

### Kernel Version

1.0.0-1491686062.commit-9e9b8c3

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

dg

### NameTag

OldGeezer#a272

**Comment by olavra** [comment]
Hi @MoFaNi 

Thank you for reporting this issue and sorry for the late response. We have fixed this issue in the tutorial and its working now.

Regards
