### ISSUE TITLE
steampunk quest Issue 

### ISSUE THREAD

**Issue by amiirparsa** [decentraland/issues#117]
### What happened?

at the end of the quest i have a problam when im talking to lady.
she tell me your reward will recive
but in another page it write to me that : SOME ERROR WITH QUEST API
and another one:
set quest progress state:717faa62-4116-4402-9658-05e16863308ahttp:500
detail:unexpected error
this happens to me for 2 days

### Steps to reproduce

fix it pls its enoying

### Operating System

Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

intel i 7 3300

### GPU

ANGLE (Intel, Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0, D3D11-10.18.10.3496) 512MB

### RAM

8

### Kernel Version

1.0.0-1491686062.commit-9e9b8c3

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

dg

### NameTag

Parsa#eabe

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
