### ISSUE TITLE
golfcraft on linux throws SIGILL error and crashes the browser.

### ISSUE THREAD

**Issue by vanackerglenn** [decentraland/issues#118]
### What happened?

Recently I switched back to linux, and got everything set up properly, only golfcraft does not work.
I can mine perfectly, do some quests, etc, but whenever I spend a little time in the golfcraft area (I can't even start a game), either the page of browser crashes with a SIGILL illegal instruction error.
This happens on both chrome and chromium.

### Steps to reproduce

install Kubuntu 18.04, with nvidia 495.44 drivers (with vulkan support). log in to decentraland and go to golfcraft. then wait a few seconds.

### Operating System

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

Ryzen 7

### GPU

ANGLE (NVIDIA Corporation, NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2, OpenGL 4.5.0 NVIDIA 495.44) 512MB

### RAM

16GB

### Kernel Version

1.0.0-1495638678.commit-1e1d6cf

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

dg

### NameTag

Gluckez#1f66

**Comment by pabloes** [comment]
Cannot reproduce
