### ISSUE TITLE
Casino

### ISSUE THREAD

**Issue by KgTrader7** [decentraland/issues#119]
### What happened?

Hi i went to go play blackjack. Every time i went to go add money for my bet, the bet disappeared every time after clicking deal cards. Then i lost my coins and havent got them back and it also wont let me play. Can i get my 1,000 coins back please since i never got to play a hand even? just took my coins and disappeared without any cards being dealt. Thank you.

### Steps to reproduce

Just was a glitch/bug

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36

### Wallet

Metamask

### CPU

intel 9 10th generation

### GPU

Apple M1 512MB

### RAM

32g

### Kernel Version

1.0.0-1495638678.commit-1e1d6cf

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

dg

### NameTag

KgTrader#d2a5

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
