### ISSUE TITLE
The Drink of the gods quest Bug - Complete but Incomplete

### ISSUE THREAD

**Issue by VinnyPiazza** [decentraland/issues#120]
### What happened?

I have completed The drink of the gods quest and was given a drink by the bartender. Nothing else happened and it seemed glitchy. At the top it says 9/10 for Find 10 crystals. When doing the find crystals challenge it was laggy. 

When revisiting it still says 9/10 for Find 10 crystal but the bartender (octopus) say "Amazing, you found everything. Time to do my magic". Click or pressing "E" does not do anything.

Going back to the crystal challenge, I cannot restart the challenge. The character to start the challenge is no longer there.

### Steps to reproduce

Quickly go through the crystal challenge while session is laggy. Do not stop or wait for two crystal counters to match. If complete but crystal count is correct, repeat till complete but crystal count is incorrect. e.g. 9/10.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   1.99 GHz

### GPU

ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8681) 512MB

### RAM

6GB

### Kernel Version

1.0.0-1495638678.commit-1e1d6cf

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

unicorn

### NameTag

VinnyPiazza#0b13

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
