### ISSUE TITLE
Some errors with quest API

### ISSUE THREAD

**Issue by ID0pe** [decentraland/issues#121]
### What happened?

Hello

I finished the quest and it keeps telling me Some errors with quest API and I am not getting POAP, as well as most quests, have delays. 

### Steps to reproduce

I don't know, to be honest, thought you should know about the problem, and it would be nice if you helped or told me whats the issue was.

Tank  you

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

i7

### GPU

AMD Radeon Pro 560X OpenGL Engine 512MB

### RAM

16GB

### Kernel Version

1.0.0-1495638678.commit-1e1d6cf

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

dg

### NameTag

IDope#f495

**Comment by ID0pe** [comment]
<img width="1680" alt="Screen Shot 2021-11-24 at 1 56 34 AM" src="https://user-images.githubusercontent.com/94939674/143148638-daee383e-1443-4e3f-b318-6bb5de56c3b9.png"
<img width="1680" alt="Screen Shot 2021-11-24 at 1 56 25 AM" src="https://user-images.githubusercontent.com/94939674/143148667-21a5f63f-1cc2-4a4c-8575-feebacfe5aa1.png">
>

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
