### ISSUE TITLE
Bug while validating a quest: SteamPunk

### ISSUE THREAD

**Issue by ddeabreu** [decentraland/issues#122]
### What happened?

I finished the quest but there were a bug while requesting the API.

![Capture d’écran 2021-11-24 à 01 26 11](https://user-images.githubusercontent.com/10730772/143152336-e3916312-d02f-43a8-8931-536f3774d9d9.png)

### Steps to reproduce

Make the quest SteamPunk. See that all elements in front are ok ( confirmation modale, gears rotating, door open, electricity ok )

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Metamask

### CPU

I7

### GPU

Intel(R) Iris(TM) Plus Graphics 650 512MB

### RAM

16G

### Kernel Version

1.0.0-1495638678.commit-1e1d6cf

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

dg

### NameTag

Twitifyoucan#b0a8

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
