### ISSUE TITLE
Steampunk complete mission bug

### ISSUE THREAD

**Issue by 909v** [decentraland/issues#123]
### What happened?

after u finish the mission u just dont recieve the reward

### Steps to reproduce

![image](https://user-images.githubusercontent.com/94948442/143175676-1dd8a6f2-dd71-4be3-9946-06c43e4ab630.png)

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 OPR/81.0.4196.52

### Wallet

Metamask

### CPU

Ryzen 5 2600

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7168) 512MB

### RAM

16GB

### Kernel Version

1.0.0-1495638678.commit-1e1d6cf

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

dg

### NameTag

909#f045

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
