### ISSUE TITLE
Some errors with Quests API

### ISSUE THREAD

**Issue by Jtrahan88** [decentraland/issues#124]
### What happened?

Trying to complete the steam punk dapper quest but I get the above error. with a long error message after ending with details: Unexpected error

### Steps to reproduce

Just talk to the steam punk girl anna after I have complete all the steps in the quest to collect the poap. 

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx     2.10 GHz

### GPU

ANGLE (AMD, AMD Radeon(TM) Vega 8 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-26.20.14036.4002) 512MB

### RAM

8gb

### Kernel Version

1.0.0-1495638678.commit-1e1d6cf

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

fenrir

### NameTag

JQTs#cee1

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
