### ISSUE TITLE
quest api error

### ISSUE THREAD

**Issue by francismariecayaco** [decentraland/issues#125]
### What happened?

i cannot claim my prize in the quest 

### Steps to reproduce

i 
![image](https://user-images.githubusercontent.com/40144457/143191538-d353545b-25f6-4571-bf4b-8953a09da43c.png)

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

ryzen 7

### GPU

ANGLE (AMD, AMD Radeon(TM) Vega 8 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.13033.1000) 512MB

### RAM

16

### Kernel Version

1.0.0-1495638678.commit-1e1d6cf

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

dg

### NameTag

LabanosGaming#aede

**Comment by Berghain69** [comment]
Same with me

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
