### ISSUE TITLE
Completed Gear  SteamPunk by DappCraft Quest

### ISSUE THREAD

**Issue by irie-i** [decentraland/issues#126]
### What happened?

I completed the quest and am getting a an error when it comes to collecting my reward. 
I keep Getting:
Notification 1:
Some errors with Quests API.
Notification 2:
SetQuestProgressState:717Faa62-4116-4402-9658-05e16863308a 
http:500
details:Unexpected error

### Steps to reproduce

Complete the quest and collect the reward. 

### Operating System

 Chrome Windows 10 pro

### Wallet

Metamask

### CPU

Ryzen 7 2700

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 2080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9676) 512MB

### RAM

16GB

### Kernel Version

1.0.0-1495638678.commit-1e1d6cf

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

unicorn

### NameTag

Irie#ac9b

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
