### ISSUE TITLE
Startup/walkthrough

### ISSUE THREAD

**Issue by Omlandos** [decentraland/issues#129]
### What happened?

During the walkthrough/controller help thing in the beginning of Decentraland with the little robot it covers up the bottom left when you're supposed to text/talk to move on. This makes the little robot stay there with you having to find out what buttons to press. Like "T" or "ENTER". 

### Steps to reproduce

Start up the game with a new user I guess.

### Operating System

Google Chrome Versjon 95.0.4638.69 (Offisiell delversjon) (x86_64) on macOS Monterey 12.0.1

### Wallet

Metamask

### CPU

Intel Core i5

### GPU

Intel(R) Iris(TM) Graphics 6100 1536MB

### RAM

8 GB

### Kernel Version

1.0.0-1495638678.commit-1e1d6cf

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

unicorn 

### NameTag

Olav#5842

**Comment by olavra** [comment]
Hi @Omlandos 

Thank your for reporting this issue and sorry for the late response. That tutorial step has been changed and no longer causes that problems.

Regards
