### ISSUE TITLE
QUEST help not working (repeated and not rewarding)

### ISSUE THREAD

**Issue by Eattoomuch** [decentraland/issues#133]
### What happened?

1. The Drink of the Gods quest 
Quest completed except for one of the previous tasks, i have completed these 3-4 times and lists i have found 8/10 crystals

2.  Dragon City Quest 
I have completed this quest many times and it has not disappeared in my quests section and has not rewarded me. There has been several attempts and did not show anything.

3. Finding the gears quest
Final thing to do is to talk to Anna, several times speaking to her and did not award me with quest

There seems to be a lag? or glitch with these quests? Please help, spent alot of time trying to get these working.

Thankyou
EG

### Steps to reproduce

Updating these quests with better UI. Similar to OSRS, making quest progress more intuitive 

### Operating System

Windows NT 64

### Wallet

Metamask

### CPU

i9

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 2060

### RAM

32

### Kernel Version

1.0.0-1495638678.commit-1e1d6cf

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

poseidon

### NameTag

Eatoomuch#4af1

**Comment by gtgameprogrammer** [comment]
I had the exact Eattoomuch problem that he described in 2. Dragon City Quest.

Also, I've talked with others guys in the chat with the same problem.
