### ISSUE TITLE
White and Black Grimreapear in the Dragon land

### ISSUE THREAD

**Issue by JimmyHu213** [decentraland/issues#137]
### What happened?

I meet two NPC here, they tell me I am not welcomed and I cant escape.

### Steps to reproduce

1

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.34

### Wallet

Metamask

### CPU

i5 8th

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7212) 512MB

### RAM

12

### Kernel Version

1.0.0-1503886844.commit-b174d3b

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

dg

### NameTag

Jimmy#e5b0

**Comment by olavra** [comment]
This report is considered invalid due to lack of data.
