### ISSUE TITLE
Asian Plaza Floor Bug

### ISSUE THREAD

**Issue by Arctic30** [decentraland/issues#138]
### What happened?

55, -60 coordinate the building where the gong is has a bug.  Nothing crazy, but none the less a bug. You can't walk on it. You just fall through the floor after going up the stairs.

### Steps to reproduce

Walk up the stairs to the gong.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

I9 7980XE

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9676) 512MB

### RAM

64GB

### Kernel Version

1.0.0-1503886844.commit-b174d3b

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

dg

### NameTag

LtArcticShadow#854f

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
