### ISSUE TITLE
On ne me donne pas ma recompense 

### ISSUE THREAD

**Issue by Gabriel2150** [decentraland/issues#139]
### What happened?

Jai terminer la mission mes on menvoye un message derreur jai faite des capture decran 

Merci de maider
![Capturedsfsfvdsf](https://user-images.githubusercontent.com/35935607/143528572-7f88e6c4-03f2-4345-9f2f-22e74e81c09a.PNG)
![dvsdfvsddv](https://user-images.githubusercontent.com/35935607/143528577-2346ea08-1f72-469e-9776-8cdc698bfda3.PNG)

### Steps to reproduce

Juste corriger lerreur je sais pas pourquoi sa arrive cest comme si le systeme a approuver la derniere mission et non l'avant derniere.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Wallet Connect

### CPU

Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz   2.30 GHz

### GPU

ANGLE (Intel, Intel(R) HD Graphics 5500 Direct3D11 vs_5_0 ps_5_0, D3D11-20.19.15.5126) 512MB

### RAM

8,0 Go DDR3

### Kernel Version

1.0.0-1503886844.commit-b174d3b

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

dg

### NameTag

Gabriel2150#3f8b

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
