### ISSUE TITLE
Wondercoin

### ISSUE THREAD

**Issue by PblColet** [decentraland/issues#142]
### What happened?

He hasn't given me the free daily wondercoins for a week

### Steps to reproduce

fix and compensate players

### Operating System

Chrome/96.0.4664.45

### Wallet

Metamask

### CPU

gigabyte i7 7th gen

### GPU

NVIDIA GeForce GTX 1060 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7141) 512MB

### RAM

8

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20666-20211125172528.commit-76bddf6

### Realm

dg

### NameTag

PblColet#c39b

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
