### ISSUE TITLE
Missing poker chips

### ISSUE THREAD

**Issue by Macvanko** [decentraland/issues#146]
### What happened?

Game just bugged , it continiued but didnt count the progress. Chips were on the table but when i left they wasnt count in my daily sum. Also at the same table , the progress wasnt counted. I had 4860 chips and was on same multiplier. When i came back they just disapeared as if i havent played that table.

### Steps to reproduce

Retrace that table and check for the solution

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

AMD ryzer 9 5900x

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5751) 512MB

### RAM

128 gb

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20666-20211125172528.commit-76bddf6

### Realm

hephaestus

### NameTag

Macvanko#8a8c

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
