### ISSUE TITLE
Bug when mining

### ISSUE THREAD

**Issue by iampedroluis** [decentraland/issues#148]
### What happened?

it can be mined in the hole left by the meteorite when it falls

attachment

![Bug Decentraland](https://user-images.githubusercontent.com/83560861/143724243-8515cf90-1fda-4953-90ba-0c48adf96125.jpeg)

### Steps to reproduce

1 - mine the hole from which the meteorite bounces

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

Intel Core i5

### GPU

ANGLE (Intel, Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.100.9864) 512MB

### RAM

64GB

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20666-20211125172528.commit-76bddf6

### Realm

dg

### NameTag

gasmask#6564

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
