### ISSUE TITLE
The drink of the gods - pick cat hairs

### ISSUE THREAD

**Issue by joehunnah** [decentraland/issues#150]
### What happened?

Clicking E to pick cat hair does nothing. There's no indication that picking the cat's hair is successful or not.

### Steps to reproduce

1. Find the cat guy.
2. Get near the cat, Click E

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

Intel i7

### GPU

ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8681) 512MB

### RAM

16 gb

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20666-20211125172528.commit-76bddf6

### Realm

dg

### NameTag

Joehunnah#1db4

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
