### ISSUE TITLE
Invert mouse

### ISSUE THREAD

**Issue by csicky** [decentraland/issues#151]
### What happened?

Where is the invert mouse setting? How am I supposed to try this if I am dizzy all the time?

### Steps to reproduce

Go in the game, move mouse, get dizzy.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0

### Wallet

Metamask

### CPU

Ryzen

### GPU

RX 5700

### RAM

16

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20666-20211125172528.commit-76bddf6

### Realm

dg

### NameTag

Rudy#edee

**Comment by olavra** [comment]
Hi! I'm glad to tell you that we have implemented this feature and is no available in the settings planel. Thanks for your suggestion! :) https://github.com/decentraland/unity-renderer/issues/1899
