### ISSUE TITLE
I can't get my reward!

### ISSUE THREAD

**Issue by ZHONGHUASHI** [decentraland/issues#152]
### What happened?

![image](https://user-images.githubusercontent.com/90999310/143755060-c1b94ab2-b8cd-4b50-acc2-e6da501a2fcd.png)

I finished the event,but I can't get my reward!

### Steps to reproduce

Normal step

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36

### Wallet

Metamask

### CPU

Intel i5 7th

### GPU

ANGLE (Intel, Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8682) 512MB

### RAM

12GB

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20666-20211125172528.commit-76bddf6

### Realm

dg

### NameTag

Linfan#15e9

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
