### ISSUE TITLE
Quest API error

### ISSUE THREAD

**Issue by AdelMW** [decentraland/issues#153]
### What happened?

I just finished doing the SteamPunk quest, but I cannot claim my reward, followed with a message that says "Quest API error".
What is the cause of this? As well as with other quests; the dragon quest does not record the completed tasks I do.

### Steps to reproduce

I believe it is because its not optimized with Mac, although I wasnt the only one facing the same problem.

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36

### Wallet

Metamask

### CPU

Apple Silicon M1

### GPU

Apple M1 512MB

### RAM

8GB

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20666-20211125172528.commit-76bddf6

### Realm

dg

### NameTag

Dulla#4231

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
