### ISSUE TITLE
Steam Punk Quest

### ISSUE THREAD

**Issue by kyawrayzan** [decentraland/issues#154]
### What happened?
Can not get reward after activating the latch and closing the door.
SetQuest Progress State
Unexpected Error[](url)

### Steps to reproduce

After getting second key

### Operating System

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Fortmatic

### CPU

i3

### GPU

nividia

### RAM

4gb

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20666-20211125172528.commit-76bddf6

### Realm

baldr

### NameTag

ray101#4702

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
