### ISSUE TITLE
Quest bug

### ISSUE THREAD

**Issue by ImMickyy** [decentraland/issues#155]
### What happened?

At the end of the quest named "SteamPunk Dappcraft", I need to finally talk to Anna and end the quest, but when I talk to her, the quest doesn't move, it doesn't happen everything.

### Steps to reproduce

At the end of the quest named "SteamPunk Dappcraft", I need to finally talk to Anna and end the quest, but when I talk to her, the quest doesn't move, it doesn't happen everything.

### Operating System

Brave

### Wallet

Metamask

### CPU

ASUS

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671) 512MB

### RAM

1042GB

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20666-20211125172528.commit-76bddf6

### Realm

baldr

### NameTag

Micky#daa9

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
