### ISSUE TITLE
Steampunk quest

### ISSUE THREAD

**Issue by batuhansepetcioglu** [decentraland/issues#156]
### What happened?

I did not receive my reward even though I completed the steampunk quest

### Steps to reproduce

I did not receive my reward even though I completed the steampunk quest

### Operating System

Google Chrome

### Wallet

Metamask

### CPU

İntel İ5 9300H

### GPU

Nvidia GTX 1050Ti

### RAM

16GB

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20666-20211125172528.commit-76bddf6

### Realm

dg

### NameTag

Algan35#9aef

**Comment by batuhansepetcioglu** [comment]
İ have quest API error

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
