### ISSUE TITLE
Quests problem

### ISSUE THREAD

**Issue by shishido-mh** [decentraland/issues#157]
### What happened?

The mission progress does not update

### Steps to reproduce

1. Interact with NPC/Item that is requested for a quest
2. The quest does not update and the player can not finish it or advance on it

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

i3

### GPU

AMD RADEON R7

### RAM

32GB

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20666-20211125172528.commit-76bddf6

### Realm

dg

### NameTag

Tojoski#ba03

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
