### ISSUE TITLE
Dragon City Quest Bug

### ISSUE THREAD

**Issue by perezhua1684** [decentraland/issues#158]
### What happened?

finishing the last part of Dragon city where i speak to the white Grimreaper and get the last piece  but the quest doesnt complete and if i teleport  i lose the last piece of the tangram

### Steps to reproduce

get to the final trial.l

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

intel I7

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9676) 512MB

### RAM

32gb

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20666-20211125172528.commit-76bddf6

### Realm

dg

### NameTag

Angel#9356

**Comment by Gautamdaga** [comment]
Same problem for me as well

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
