### ISSUE TITLE
Error with Quest API

### ISSUE THREAD

**Issue by MANOJEET22** [decentraland/issues#159]
### What happened?

There is some error with Quest API that was not allowed me to complete the final ta
![Uploading Screenshot (4017).png…]()
sk

### Steps to reproduce

I am completing the final step which I to talk with that lady and she said thank you your reward is waiting after that I receive that error with Quest API.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

Intel core i5 8th Generation

### GPU

ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8681) 512MB

### RAM

8GB

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20666-20211125172528.commit-76bddf6

### Realm

SteamPunk DC Quest

### NameTag

Mearth#fca5

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
