### ISSUE TITLE
hi he gave an error quest and he does not give me the prize. i also have the details of the error ......set quest progress state: 717faa62-4116-4402-9658-05e16863308a  http: 500   details :unexpected error

### ISSUE THREAD

**Issue by amin3251** [decentraland/issues#160]
### What happened?

hi he gave an error quest and he does not give me the prize. i also have the details of the error ......set quest progress state: 717faa62-4116-4402-9658-05e16863308a  http: 500   details :unexpected error

### Steps to reproduce

i do know

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

AMD A10

### GPU

ANGLE (AMD, AMD Radeon(TM) R6 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-23.20.15024.2006) 512MB

### RAM

8

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20666-20211125172528.commit-76bddf6

### Realm

baldr

### NameTag

Amin#477b

**Comment by amin3251** [comment]
help me pliz

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
