### ISSUE TITLE
Didn't get reward after finishing SteamPunk by DappCraft

### ISSUE THREAD

**Issue by fseehawer** [decentraland/issues#161]
### What happened?

Didn't get reward after finishing SteamPunk by DappCraft

### Steps to reproduce

Anna says thanks for helping after completing all the steps, but I didn't receive the reward.

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Metamask

### CPU

2,6 GHz 6-Core Intel Core i7

### GPU

AMD Radeon Pro 5300M OpenGL Engine 512MB

### RAM

16GB

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20666-20211125172528.commit-76bddf6

### Realm

dg

### NameTag

Fio#55e4

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
