### ISSUE TITLE
API Unexpected Error

### ISSUE THREAD

**Issue by ailton-fortes** [decentraland/issues#162]
### What happened?

I got API Unexpected Error

### Steps to reproduce

![image](https://user-images.githubusercontent.com/20643037/143875834-2bd61c08-f450-447b-b6f4-94f8952748f2.png)

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

Intel Core i5

### GPU

Intel(R) Iris(TM) Plus Graphics 655 512MB

### RAM

16Gb

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20666-20211125172528.commit-76bddf6

### Realm

dg

### NameTag

ailtonfortes#da93

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
