### ISSUE TITLE
Bug SteamPunk by DappCraft

### ISSUE THREAD

**Issue by betomgarcia** [decentraland/issues#163]
### What happened?

Error in last part (Jump to Anna and talk with her) of Quest "SteamPunk by DappCraft"

### Steps to reproduce

When we try to finish the Quest.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

5800x

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.7005) 512MB

### RAM

32GB

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20666-20211125172528.commit-76bddf6

### Realm

dg

### NameTag

Beto#2610

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
