### ISSUE TITLE
Gems task in drink of the gods 

### ISSUE THREAD

**Issue by Jolgarz** [decentraland/issues#164]
### What happened?

hi, im username Jolgarz, the gems task for the drinks of the gods quest doesn´t get completed, the bar for the gems don´t go up 

### Steps to reproduce

Talk with the bartender after getting the previous quest (the plants)
Go to the gamer plaza and talk to the chaman
After getting the 10 gems the questshould appear complete, you even get the key and the cup, but the bartender doesn´t take it.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

msi 

### GPU

ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8681) 512MB

### RAM

12

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20908-20211129142011.commit-225e066

### Realm

dg

### NameTag

Jolgarz#049e

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
