### ISSUE TITLE
Low FPS/Lag

### ISSUE THREAD

**Issue by ItsLio** [decentraland/issues#165]
### What happened?

when i try to play i can see that my jump lasts longer, i am slower than my friend and in general the game is not smooth. its like i have low FPS. I have only Decentraland running on my PC and i've done all the recommendation steps from here: https://docs.decentraland.org/decentraland/hardware-acceleration/  
Help me please.. Check my PC build below to fix this.. 

### Steps to reproduce

The bug started from the start when i create my account. 

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

AMD Ryzen 5 2600c 6C/12T 3.4ghz 

### GPU

 MSi GeForce GTX 1650 4GB

### RAM

 Kingston 8GB ddr4 2666 MHz

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20908-20211129142011.commit-225e066

### Realm

dg

### NameTag

Lio#d435

**Comment by davidejensen** [comment]
The experience has been improved a lot also on the performance side in the past few months, additionally movements are no longer affected by in game fps, if you still encounter heavy lag or stutter please open a new issue with more detailed information.
