### ISSUE TITLE
can't invert mouse look

### ISSUE THREAD

**Issue by obdnanr** [decentraland/issues#166]
### What happened?

Can't invert mouse look.  

### Steps to reproduce

Go to settings, look at no buttons to invert mouse.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

None, played as guest

### CPU

i7 11 gen

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9676) 512MB

### RAM

32

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20908-20211129142011.commit-225e066

### Realm

dg

### NameTag

RickJames#8c31

**Comment by olavra** [comment]
Hi! I'm glad to tell you that we have implemented this feature and is no available in the settings panel. Thanks for your suggestion! :) https://github.com/decentraland/unity-renderer/issues/1899
