### ISSUE TITLE
Leather Vine missed

### ISSUE THREAD

**Issue by Mwaruwari** [decentraland/issues#167]
### What happened?

Im playing the drink of the gods mission but leather vine tree missed.

### Steps to reproduce

It may be enough to collect 2 lv

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

intel(R) Core(TM) i5-8300H CPU @ 2.30GHz   2.30 GHz

### GPU

ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-23.20.16.5018) 512MB

### RAM

16

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20908-20211129142011.commit-225e066

### Realm

dg

### NameTag

Mwaruwari#c62b

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
