### ISSUE TITLE
quest bug Tangram

### ISSUE THREAD

**Issue by Fredoxygen** [decentraland/issues#168]
### What happened?

I was performing the Tangram Quest, and noticed several bugs. Once each step completed, they were taking a long time to be marked as completed. Very often, I was going to the next steps , but finally it was telling me I had not completed the previous step, eventhough I had already collected the relevant piece of tangram. And then after almost one hour playing and completing the first 4 steps, I gave wine to the old man, collected the piece of Tangram from him, but it didn't marked as completed, and no way to do it. I jumped to the next step, and then all was LOST... That is EXTREMELY FRUSTRATING. I lost my progress, and that quest DISAPPEARED... What can I do now ?

### Steps to reproduce

I was performing the Tangram Quest, and noticed several bugs. Once each step completed, they were taking a long time to be marked as completed. Very often, I was going to the next steps , but finally it was telling me I had not completed the previous step, eventhough I had already collected the relevant piece of tangram. And then after almost one hour playing and completing the first 4 steps, I gave wine to the old man, collected the piece of Tangram from him, but it didn't marked as completed, and no way to do it. I jumped to the next step, and then all was LOST... That is EXTREMELY FRUSTRATING. I lost my progress, and that quest DISAPPEARED... What can I do now ?

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36

### Wallet

Metamask

### CPU

Intel Iris Graphics 6100 1536 MB

### GPU

Intel(R) Iris(TM) Graphics 6100 512MB

### RAM

8

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20908-20211129142011.commit-225e066

### Realm

dg

### NameTag

Alfredo#dbb4

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
