### ISSUE TITLE
Complete Steampunk Quest--get API Issue error and cannot retrieve reward

### ISSUE THREAD

**Issue by cryptokev33** [decentraland/issues#169]
### What happened?

Complete Steampunk Quest--get API Issue error and cannot retrieve reward. Complete all tasks and activate gears. Speak with the figure you have to who thanks you for your help and says your reward is ready. An error message pops up saying something about API error and cannot get reward

### Steps to reproduce

after completing task go and speak with Anna--who is in charge of task

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0

### Wallet

Metamask

### CPU

intel Iris Graphics 550 1536 MB

### GPU

Intel(R) HD Graphics 400 512MB

### RAM

8gb

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20908-20211129142011.commit-225e066

### Realm

loki

### NameTag

CryptoKev#c909

**Comment by cryptokev33** [comment]
Exact error message is "Some Errors with Quests API."

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
