### ISSUE TITLE
SteamPunk by Dappcraft

### ISSUE THREAD

**Issue by perezhua1684** [decentraland/issues#170]
### What happened?

can not complete quest. will  not turn green after speaking with anna

### Steps to reproduce

finish quest up to speaking with anna

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

Intel I7

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9676) 512MB

### RAM

32gb

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20908-20211129142011.commit-225e066

### Realm

dg

### NameTag

Angel#9356

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
