### ISSUE TITLE
Terrible design of a golf course.

### ISSUE THREAD

**Issue by vanackerglenn** [decentraland/issues#171]
### What happened?

I ended up on a part of a golf course where there was no way to get back and finish the course:
![Screenshot_20211130_105829](https://user-images.githubusercontent.com/28847460/144026698-5f73b153-46df-4a18-aad2-f76e56369b5f.png)

### Steps to reproduce

Go to that golf course, to that place, and try to finish the course from there.

### Operating System

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

Ryzen 7

### GPU

ANGLE (NVIDIA Corporation, NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2, OpenGL 4.5.0 NVIDIA 495.44) 512MB

### RAM

16GB

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20908-20211129142011.commit-225e066

### Realm

dg

### NameTag

Gluckez#1f66

**Comment by davidejensen** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
