### ISSUE TITLE
BUG with quest

### ISSUE THREAD

**Issue by daddySANDEX** [decentraland/issues#172]
### What happened?

I can't turn in the quest "steampunk by dappcraft". Specifically, the task is not being executed "jump to Anna". When I approach it, an error appears - some errors with Quests API. Next i am talk with anna. She say me - thanks for help. But the quest doesn't count

### Steps to reproduce

I can't turn in the quest "steampunk by dappcraft". Specifically, the task is not being executed "jump to Anna". When I approach it, an error appears - some errors with Quests API. Next i am talk with anna. She say me - thanks for help. But the quest doesn't count

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

i7-3770

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9613) 512MB

### RAM

8

### Kernel Version

1.0.0-1508086403.commit-b0565d7

### Unity Version

1.0.20908-20211129142011.commit-225e066

### Realm

dg

### NameTag

SANDEX#8cf5

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
