### ISSUE TITLE
Stuck moving left with my avatar

### ISSUE THREAD

**Issue by adampaal** [decentraland/issues#173]
### What happened?

The avatar character always goes left. I can modify the way he goes but if I release all buttons he keeps going left. Cannot even stop from moving.

### Steps to reproduce

It always happen when I am in a place where I can walk freely. It started to do this after I jumped in a event after the very start with the tutorial.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

I5 7500

### GPU

ANGLE (AMD, Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.13033.5003) 512MB

### RAM

16gb

### Kernel Version

1.0.0-1521470514.commit-5478f09

### Unity Version

1.0.20908-20211129142011.commit-225e066

### Realm

dg

### NameTag

Adam#07a1

**Comment by olavra** [comment]
Hi @adampaal 

We have had several problems with the character control system, but they should have been solved with the latest updates.

Please could you confirm that this is still happening to you?

Thanks
