### ISSUE TITLE
Some errors with quests api 

### ISSUE THREAD

**Issue by adjime** [decentraland/issues#174]
### What happened?

Hi, i can't receive my reward after jumping and talking with Anna :
"Some errors with quests api"

### Steps to reproduce

i don't know

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

3770K

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9649) 512MB

### RAM

8

### Kernel Version

1.0.0-1521470514.commit-5478f09

### Unity Version

1.0.20908-20211129142011.commit-225e066

### Realm

dg

### NameTag

adjime#5680

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
