### ISSUE TITLE
Tangram Quest

### ISSUE THREAD

**Issue by iPrsut** [decentraland/issues#175]
### What happened?

I completed the Cube Monster quest and received the tangram, but the quest did not complete.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/95318439/144144693-937b7f59-bff6-4630-9726-ef913b10552a.png)

### Operating System

Chrome is up to date Version 96.0.4664.45 (Official Build) (64-bit)/Edition	Windows 11 Pro Version	21H2 OS build	22000.348

### Wallet

Metamask

### CPU

AMD Ryzen 7 5700G with Radeon Graphics            3.80 GHz

### GPU

NVIDIA GeForce RTX 3060

### RAM

16.0 GB

### Kernel Version

1.0.0-1521470514.commit-5478f09

### Unity Version

1.0.20908-20211129142011.commit-225e066

### Realm

dg

### NameTag

nprsut#6529

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
