### ISSUE TITLE
decentreland is more slow

### ISSUE THREAD

**Issue by mrclaytonetreal** [decentraland/issues#176]
### What happened?

is more slow to play

### Steps to reproduce

slow

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Fortmatic

### CPU

xeon

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GT 630 Direct3D11 vs_5_0 ps_5_0, D3D11-23.21.13.9135) 512MB

### RAM

16 gb

### Kernel Version

1.0.0-1521470514.commit-5478f09

### Unity Version

1.0.20908-20211129142011.commit-225e066

### Realm

dg

### NameTag

SkyTronics#2466

**Comment by olavra** [comment]
Invalidated by a bad formulation of the support request
