### ISSUE TITLE
golf competition

### ISSUE THREAD

**Issue by Tatatatricata** [decentraland/issues#177]
### What happened?

on one of the golf competition levels buttons w/a/d/x are freezing in the beginning (10-20 seconds), also there are other players are appearing on the level, maybe blends with the previous stage or the main menu picture

### Steps to reproduce

please check the golf comp. levels

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36

### Wallet

Metamask

### CPU

Intel i9

### GPU

Apple M1 512MB

### RAM

32Gb

### Kernel Version

1.0.0-1521470514.commit-5478f09

### Unity Version

1.0.20908-20211129142011.commit-225e066

### Realm

dg

### NameTag

Tata#3015

**Comment by davidejensen** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
