### ISSUE TITLE
Some errors with Queste API 

### ISSUE THREAD

**Issue by FirstMana** [decentraland/issues#178]
### What happened?

hello 
in the game when i complete any task , this massage show to me .
"Some errors with Queste API"
HOW can i Fix this ?
i complete several time levels , but for this problem i can not give my reward.
Thank
![1](https://user-images.githubusercontent.com/95347008/144215265-ffc87633-a92b-4ee6-92af-1a42ccd4c258.jpg)
![2](https://user-images.githubusercontent.com/95347008/144215270-6113b873-0661-45e6-8fac-4bf1d7311b9d.jpg)
s

### Steps to reproduce

when i complete any task , this massage show to me

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

i7

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 660M Direct3D11 vs_5_0 ps_5_0, D3D11-21.21.13.7654) 512MB

### RAM

4

### Kernel Version

1.0.0-1521470514.commit-5478f09

### Unity Version

1.0.20908-20211129142011.commit-225e066

### Realm

dg

### NameTag

FirstMANA#8e6f

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
