### ISSUE TITLE
SetQuestProgressState:http://717faa62-4116-4402-9658-05e16863308a.http:500

### ISSUE THREAD

**Issue by MistrzKorman** [decentraland/issues#179]
### What happened?

SetQuestProgressState:http://717faa62-116-4402-9658-05e16863308a.http:500

### Steps to reproduce

SetQuestProgressState:http://717faa62-116-4402-9658-05e16863308a.http:500

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

i7-9700F

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9676) 512MB

### RAM

32

### Kernel Version

1.0.0-1521470514.commit-5478f09

### Unity Version

1.0.20908-20211129142011.commit-225e066

### Realm

dg

### NameTag

Kamil#430a

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
