### ISSUE TITLE
Character running without control.

### ISSUE THREAD

**Issue by Karatroz** [decentraland/issues#180]
### What happened?

My character keeps running backwards with no control. It only stops when I press ESC, but after clicking with the mouse, it go back do running.
It makes impossible to do stuff.

### Steps to reproduce

I just open the Decentraland and the character stars running without control.

### Operating System

Chrome/Windows 7 64 bit.

### Wallet

Metamask

### CPU

Intel i5 3rd Gen. 3.00 GHz

### GPU

AMD, Radeon RX550/550 Serie

### RAM

8GB

### Kernel Version

1.0.0-1521470514.commit-5478f09

### Unity Version

1.0.20908-20211129142011.commit-225e066

### Realm

dg

### NameTag

Karatroz#065a

**Comment by QuentinDvl** [comment]
I've the same issue ..

**Comment by olavra** [comment]
Hello @Karatroz 

We have had several problems with the control system that should be solved by now. Could you let us know if this is still happening to you?

Best regards

**Comment by R4k4210** [comment]
Guys I found a workaround, try it and tell me if works for you too.
Go to metamaks plugin, connected sites, search for decentraland and disconnect all accounts, then go to Decentraland again.

**Comment by davidejensen** [comment]
Hello @Karatroz 
We have recently applied a fix that should resolve this issue in the majority of the cases, could you verify if this is still happening to you?

If it's still happening, could you please verify that you don't have any external devices connected that could alter the input? (i.e. joysticks, steering wheels, graphics tablet, ...)
Could you verify that you also don't have any softwares that could alter the inputs as well? (autoclickers, virtual keyboards, ...)
If your device has touch support could you also try to disable the touch support and try again?
