### ISSUE TITLE
steam punk quest reward bug

### ISSUE THREAD

**Issue by Tatatatricata** [decentraland/issues#181]
### What happened?

after finishing the quest there is an error message instead of the collectibles reward window
![Uploading Снимок экрана 2021-12-01 в 10.36.46 PM.png…]()

### Steps to reproduce

fix the bugm1

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36

### Wallet

Metamask

### CPU

M1

### GPU

Apple M1 512MB

### RAM

8Gb

### Kernel Version

1.0.0-1521470514.commit-5478f09

### Unity Version

1.0.20908-20211129142011.commit-225e066

### Realm

loki

### NameTag

Tata#3015

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
