### ISSUE TITLE
Decentraland graphic problem

### ISSUE THREAD

**Issue by SeferC** [decentraland/issues#182]
### What happened?

![image](https://user-images.githubusercontent.com/95368336/144267992-da8acbda-d8d8-493d-abf5-1d0b94668b5a.png)
deadland -65,-8 avatar is not move... There is bug in the graphics

### Steps to reproduce

it should be intervened to fix the error in the system.

### Operating System

Win 10 Google chrome

### Wallet

Metamask

### CPU

Amd ryzen 1600 AF

### GPU

radeon Rx570

### RAM

8 gb

### Kernel Version

1.0.0-1521470514.commit-5478f09

### Unity Version

1.0.20908-20211129142011.commit-225e066

### Realm

dg deadland

### NameTag

Sefer#bd8c

**Comment by olavra** [comment]
Hi @SeferC 

I dont understand what is the problem here. Could you please extend the information?

Regards

**Comment by D4rWiNSS** [comment]
Closed because the reporter doesn't answer
