### ISSUE TITLE
No quest bar

### ISSUE THREAD

**Issue by DonMezza** [decentraland/issues#183]
### What happened?

Quest bar is just non existent, "SetProgressState:717faa624116-4402-9658-05e16863308a  http:500  details:Unexpected error"

### Steps to reproduce

no clue 

### Operating System

Windows 11

### Wallet

Fortmatic

### CPU

Intel i7 10700k

### GPU

Pallet Nvidia 3070

### RAM

32gb

### Kernel Version

1.0.0-1521470514.commit-5478f09

### Unity Version

1.0.21174-20211201090001.commit-06e8db4

### Realm

baldr

### NameTag

QuantumKush#b444

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
