### ISSUE TITLE
Quest Icon Not Showing Up

### ISSUE THREAD

**Issue by stacystarz** [decentraland/issues#184]
### What happened?

I am in the process of trying to complete the "Drink of the Gods" quest. I found it odd that, when I "collected" each item for the second portion of it (sugar berries, kim kim etc) that nothing showed up in my inventory.

Anyways, I go back anyways and it seems that the items weren't actually collected.

I imagine this has something to do with the rocket quest button being completely gone. I've tried restarting the game, my computer and all that. I'd love to figure this out - I completed the gears quest to but never received the POAP. 

Thank you!

### Steps to reproduce

1) After collecting cat hairs, bring them to the octopus
2) PROBLEM STARTS HERE ---> He gives you three more ingredients to find, however at this point the objectives didn't show up in the quest log like the previous quests did (the Steampunk one). 
3) Unable to troubleshoot further as this morning my quest button is completely gone. I am still in the quest, however seem unable to complete it.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Wallet Connect

### CPU

11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz   2.50 GHz

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7141) 512MB

### RAM

16.0 GB (15.9 GB usable

### Kernel Version

1.0.0-1521470514.commit-5478f09

### Unity Version

1.0.21174-20211201090001.commit-06e8db4

### Realm

dg

### NameTag

stacystarz#46c6

**Comment by viniciustavanoferreira** [comment]
Hey guys, just to complement what was mentioned by @stacystarz , I have exactly the same issue here:
![image](https://user-images.githubusercontent.com/4478387/144338488-9c9f6814-8acb-4399-b08a-2a97aaa902e8.png)

**Comment by arti0090** [comment]
Hey, looks like there is more of us :sob: 
![image](https://user-images.githubusercontent.com/35863747/144393045-fe9249d6-2c2e-49af-8489-79ca26582d65.png)

Also I didn't get the reward for gear quest...

**Comment by stacystarz** [comment]
Still no update or change - I hope it gets fixed soon. Would love to continue questing!

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
