### ISSUE TITLE
steampunk quest

### ISSUE THREAD

**Issue by bartoszekjustin** [decentraland/issues#185]
### What happened?

I completed the quest and then it said "some errors with quest API" and then SetQuestProgressState:717faa62-4116-4402-9658-05e168683308ahhtp:500 details: unexpected error

### Steps to reproduce

Click on the quest master after completing the quest

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

intel

### GPU

ANGLE (AMD, AMD Radeon RX 5700 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.13033.5003) 512MB

### RAM

16gb

### Kernel Version

1.0.0-1521470514.commit-5478f09

### Unity Version

1.0.21174-20211201090001.commit-06e8db4

### Realm

dg

### NameTag

MrJustin#64d8

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
