### ISSUE TITLE
A setting needs to be added to invert mouse controls

### ISSUE THREAD

**Issue by legolego** [decentraland/issues#186]
### What happened?

It's very difficult for lots of people to navigate with a mouse that isn't inverted, this should be a very simple setting to add. Can you please add it?

### Steps to reproduce

Can you please add a setting to invert the mouse for movement?

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

Intel i7

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 with Max-Q Design Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6280) 512MB

### RAM

32

### Kernel Version

1.0.0-1527377120.commit-a94b988

### Unity Version

1.0.21334-20211202053601.commit-3d8e7ad

### Realm

dg

### NameTag

legoleg#21c3

**Comment by olavra** [comment]
Hi @legolego 

Thank you very much for taking the time to make this request. You are not the first to say so, and we keep it in mind at the product table.

Please stay tuned for further updates ;)

I am closing this issue as it is not a support ticket.

Regards

**Comment by olavra** [comment]
Hi! I'm glad to tell you that we have implemented this feature and is no available in the settings panel. Thanks for your suggestion! :) https://github.com/decentraland/unity-renderer/issues/1899
