### ISSUE TITLE
mana disappeard in tominoya casino when try to bet but bet canceled

### ISSUE THREAD

**Issue by amchodler** [decentraland/issues#188]
### What happened?

i had 63 mana when i was in timanoya casino (-120,135) and tried to bet on the roulete and black jack
but the bet was canceled every time about 10 times that i tried bet again and again.
i refreshed the all browser game and when it lunched i had only 1 mana from 63 that i had.
please check it because it wasnt alowed me to bet and canceled my bets immediately while the roulette only started to spin.

### Steps to reproduce

please return my 63 mana that disappeard from the bug problem

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

intel 5 8th gen

### GPU

ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8854) 512MB

### RAM

32

### Kernel Version

1.0.0-1527377120.commit-a94b988

### Unity Version

1.0.21334-20211202053601.commit-3d8e7ad

### Realm

loki

### NameTag

AMChodler#9b9a

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
