### ISSUE TITLE
Bug on property

### ISSUE THREAD

**Issue by mgirift269f** [decentraland/issues#190]
### What happened?

I dont know how its work, its a bug, or not. I can pass through som property
![bug](https://user-images.githubusercontent.com/95527425/144706608-b85f9589-fba0-4646-8266-114c9f386d6e.jpg)

### Steps to reproduce

Update property system please,,

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

Intel

### GPU

ANGLE (AMD, AMD Radeon(TM) R6 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.1034.6) 512MB

### RAM

8

### Kernel Version

1.0.0-1537672436.commit-92098d5

### Unity Version

1.0.21334-20211202053601.commit-3d8e7ad

### Realm

dg

### NameTag

Romy#d868

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
