### ISSUE TITLE
i'am alone 

### ISSUE THREAD

**Issue by sendi404** [decentraland/issues#191]
### What happened?

when i playing there is no player and i'am alone, and then i'am cannot join with my frends. idk why. please helppp

### Steps to reproduce

there is not error

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

i7

### GPU

ANGLE (Intel, Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0, D3D11-20.19.15.5171) 512MB

### RAM

12

### Kernel Version

1.0.0-1537672436.commit-92098d5

### Unity Version

1.0.21334-20211202053601.commit-3d8e7ad

### Realm

dg

### NameTag

SaddamHussein#8d31

**Comment by olavra** [comment]
Hi @sendi404 

We had a few problems with comms and the realms. This should have been solved by now.

Could you please confirm if this is still happening to you?

**Comment by 0xJuancito** [comment]
Closing this issue because of not having a response for two weeks.
