### ISSUE TITLE
Camera Position bug

### ISSUE THREAD

**Issue by aikoiwnl** [decentraland/issues#192]
### What happened?

When in the Wondermine map, climbing up to the shack north of the crafting station/spawn point, climbing to the plank that's behind it the camera gets offset and forced to stay in a certain position and even mouse movement doesn't fix it you need to physically move the character.

### Steps to reproduce

When in the Wondermine map, climbing up to the shack north of the crafting station/spawn point, climbing to the plank that's behind it the camera gets offset and forced to stay in a certain position and even mouse movement doesn't fix it you need to physically move the character.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Fortmatic

### CPU

i7 8700k

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9709) 512MB

### RAM

32GB

### Kernel Version

1.0.0-1537672436.commit-92098d5

### Unity Version

1.0.21334-20211202053601.commit-3d8e7ad

### Realm

dg

### NameTag

a7#5b3f

**Comment by davidejensen** [comment]
This issue has been fixed, if it happens again open a new one
