### ISSUE TITLE
Avatars not appearing

### ISSUE THREAD

**Issue by DCLCurations** [decentraland/issues#193]
### What happened?

For the past week, no avatars have showed up for me in Decentraland. I can play the games, view events, and change wearables no problem - but I cant see or talk to anyone else. I have cleared my cache multiple times as well as rebooted but nothing has worked.  I also checked to make sure my PC is up to date on everything. 

### Steps to reproduce

It happens every time I log in. 

### Operating System

Chrome, windows 10

### Wallet

Metamask

### CPU

AMD Ryzen 7

### GPU

Radeon RX 5700

### RAM

32

### Kernel Version

1.0.0-1537672436.commit-92098d5

### Unity Version

1.0.21334-20211202053601.commit-3d8e7ad

### Realm

dg

### NameTag

DCLCurations

**Comment by olavra** [comment]
Hi @DCLCurations 

We had a few problems with comms and the realms. This should have been solved by now.

Could you please confirm if this is still happening to you?

**Comment by mavimdev** [comment]
This happens with me too. I tried to switch to realms and islands with more people, but I never see anyone.

**Comment by 0xJuancito** [comment]
Can you provide us with more information to debug this issue?

Have you tried with different accounts?
Do you see chat messages or are just avatars missing?
Is there any specific error on the browser console?

**Comment by mavimdev** [comment]
Hello!

Maybe it was something with my computer. Now it's working. I don't know
what the problem was.
I was always alone everywhere.

Thank you.


A terça, 28 de jun de 2022, 15:58, juancito.eth ***@***.***>
escreveu:

**Comment by AjimenezDCL** [comment]
Resolved!
