### ISSUE TITLE
My free 60K coins are missing , 

### ISSUE THREAD

**Issue by Chrisariel** [decentraland/issues#194]
### What happened?

My 60K+ coins are missing, I see a balance of -250 and no matter how long I stay at the casino it still -250 ... When I attempt to join poker table my balance shows to 60K+ but when I try to join the table it switches to -20 balance and I get a message that I don't have enough funds to join. Cannot play blackjack nor roulette.

### Steps to reproduce

you can try to join a poker table. You will see my 60K balance and when you try to join, it will revert back to -250 or so

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36

### Wallet

Metamask

### CPU

Mac (Retina 5K, 27-inch, 2020)

### GPU

AMD Radeon Pro 5300 4 GB

### RAM

8 GB 2667 MHz DDR4

### Kernel Version

1.0.0-1537672436.commit-92098d5

### Unity Version

1.0.21334-20211202053601.commit-3d8e7ad

### Realm

dg

### NameTag

Papiringo#bb0d

**Comment by davidejensen** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
