### ISSUE TITLE
Stuck on Forest Plaza close to East side

### ISSUE THREAD

**Issue by shaikhrabi96** [decentraland/issues#195]
### What happened?

So as the title suggest I am stuck on the Forest Plaza on the east side. There's this small passage way basically on the outskirts of the plaza. And I can not move anywhere outside of that passage way. 

### Steps to reproduce

Don't understand this 

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36

### Wallet

Fortmatic

### CPU

M1 

### GPU

Apple M1 512MB

### RAM

256

### Kernel Version

1.0.0-1537672436.commit-92098d5

### Unity Version

1.0.21334-20211202053601.commit-3d8e7ad

### Realm

dg

### NameTag

Pegava#0c45

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
