### ISSUE TITLE
3LAU HAUS -70,98 BLAU WEARABLES BUG

### ISSUE THREAD

**Issue by marcogriffo** [decentraland/issues#196]
### What happened?

When I try to get the item an unexpected error message appears and does not allow me to get the Wearable. It's been 2 day in a row.

### Steps to reproduce

Go to 3LAU HAUS -70,98, try to get the item.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz   2.50 GHz

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1650 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7219) 512MB

### RAM

16GB

### Kernel Version

1.0.0-1537672436.commit-92098d5

### Unity Version

1.0.21334-20211202053601.commit-3d8e7ad

### Realm

dg

### NameTag

Marco#ee92

**Comment by davidejensen** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
