### ISSUE TITLE
Dragon City Tangram quest

### ISSUE THREAD

**Issue by michaeloconte** [decentraland/issues#197]
### What happened?

1. When completing tasks in this quest, I do not have the menu on the right side updating with my progress
2. I have completed the final quest twice now (followed youtube video as well) and it appears that I receive the last piece, but as soon as I jump to somewhere else on the map, I lose the piece

### Steps to reproduce

Go to 80,-90 with black, red, green, blue, yellow pieces. Complete quest to receive final (white) piece. Jump to somewhere else on the map. Verify that white piece is now missing

### Operating System

Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

### Wallet

Metamask

### CPU

Intel i7

### GPU

ANGLE (Intel, Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0, D3D11-10.18.10.3304) 512MB

### RAM

64Gb

### Kernel Version

1.0.0-1537672436.commit-92098d5

### Unity Version

1.0.21334-20211202053601.commit-3d8e7ad

### Realm

dg

### NameTag

wontonpaisan#f4d8

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
