### ISSUE TITLE
Mission Tab gone

### ISSUE THREAD

**Issue by djtedesco** [decentraland/issues#198]
### What happened?

I cant find my missions tab in the lower right corner.

### Steps to reproduce

It doesn't come back after reloading 

### Operating System

google chrome 

### Wallet

Metamask

### CPU

mac os monterey

### GPU

AMD Radeon Pro 5500M OpenGL Engine 512MB

### RAM

8 gb

### Kernel Version

1.0.0-1537672436.commit-92098d5

### Unity Version

1.0.21334-20211202053601.commit-3d8e7ad

### Realm

dg

### NameTag

deezjayz#d6bb

**Comment by olavra** [comment]
Hi @djtedesco 

Sorry for the late response. We have deactivated the Quests system due its instability. We are working on bringing it back with better features and performance. 

Regards
