### ISSUE TITLE
Mouse and trac pad wont work

### ISSUE THREAD

**Issue by ghost** [decentraland/issues#199]
### What happened?

I was playing in decentraland earlier all was fine but suddenly I'm not able to look around me anymore. Not sure what the issue is but my mouse still works perfectly fine so there must be a bug

### Steps to reproduce

im not sure

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36

### Wallet

Metamask

### CPU

Intel I9 10th generation

### GPU

AMD Radeon Pro 560 OpenGL Engine 512MB

### RAM

32 GB

### Kernel Version

1.0.0-1527377120.commit-a94b988

### Unity Version

1.0.21334-20211202053601.commit-3d8e7ad

### Realm

dg

### NameTag

Alec#a221

**Comment by olavra** [comment]
Hi @slickwilly69 

Sorry for the late response.

We need a bit of extra information here. Is this happening with a regular mouse? or using the laptops mousepad?

Regards

**Comment by moliva** [comment]
Closing this issue because of not having a response for two weeks.
