### ISSUE TITLE
Graphics all Black and White 

### ISSUE THREAD

**Issue by kvande-standingwave** [decentraland/issues#200]
### What happened?

I was running up a sharp incline ramp and the graphics popped and only black and white colors were being rendered.  Shortly before this happened I hit a huge lag spike. Assumed it was my end.  Is there a way to reset/load the level in browser?

### Steps to reproduce

Run up a steep ramp.

### Operating System

Chrome, Win 10

### Wallet

Metamask

### CPU

i7-5820k

### GPU

NVIDIA 

### RAM

64

### Kernel Version

/version

### Unity Version

/version

### Realm

dg

### NameTag

Utora#13d7

**Comment by olavra** [comment]
Hi @kvande-standingwave 

We had several graphic problems a few months ago that has been resolved with the latest patches.

Could you please confirm this is still happening to you?

Thanks

**Comment by D4rWiNSS** [comment]
Closed because the reporter doesn't answer
