### ISSUE TITLE
Midas Park

### ISSUE THREAD

**Issue by wesleibarbato17** [decentraland/issues#201]
### What happened?

after got all keys i can get the car, because there is a bug on crank.
-127,-136

### Steps to reproduce

the crank need to function! 

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36

### Wallet

Metamask

### CPU

intel i9 th generation

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7212) 512MB

### RAM

32gb

### Kernel Version

1.0.0-1527377120.commit-a94b988

### Unity Version

1.0.21334-20211202053601.commit-3d8e7ad

### Realm

midas park

### NameTag

WesleiBarbato#38ca

**Comment by davidejensen** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
