### ISSUE TITLE
I found a bug

### ISSUE THREAD

**Issue by midpoint** [decentraland/issues#202]
### What happened?

I open a box,but it is nothing.It said: There was a problem with our servers.
![bug](https://user-images.githubusercontent.com/832157/145566122-a1c8884b-ebef-4fc7-b33f-0232eec99aa9.jpg)

### Steps to reproduce

I went to Decentraland University,climbe to the top,found a box,when I open the box,but it is nothing.
It said: There was a problem with our servers.

### Operating System

Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36

### Wallet

Fortmatic

### CPU

Intel i9

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GT 720 Direct3D11 vs_5_0 ps_5_0, D3D11-21.21.13.7563) 512MB

### RAM

15GB

### Kernel Version

1.0.0-1527377120.commit-a94b988

### Unity Version

1.0.21784-20211209132347.commit-15ad62b

### Realm

odin

### NameTag

Maidou#662f

**Comment by davidejensen** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
