### ISSUE TITLE
ICE POKER

### ISSUE THREAD

**Issue by rockymarko** [decentraland/issues#203]
### What happened?

Hello my name is rocky I was playing ice poker and i was + 60chips and then dropped down to -460 chips for no reason. If someone could help that would be great . Need those chips back I have a delegator I need to make quota ty for your help!

### Steps to reproduce

possibly find bug as why peoples chips are disappearing.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36

### Wallet

Metamask

### CPU

intel I7

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6677) 512MB

### RAM

16 gb

### Kernel Version

1.0.0-1564535596.commit-f2d5a55

### Unity Version

1.0.21784-20211209132347.commit-15ad62b

### Realm

odin

### NameTag

rocky#b2e7

**Comment by rockymarko** [comment]
![0](https://user-images.githubusercontent.com/95960977/145672196-36be9fc3-9796-45f8-9119-7a57ba962c3d.jpg)
https://mail.google.com/mail/u/0?ui=2&ik=4cd3775999&attid=0.4&permmsgid=msg-a:r-3819938193400191303&th=17da8e4c9182f919&view=att&disp=safe&realattid=17da8e41699a0fa921d3https://mail.google.com/mail/u/0?ui=2&ik=4cd3775999&attid=0.2&permmsgid=msg-a:r-3819938193400191303&th=17da8e4c9182f919&vhttps://mail.google.com/mail/u/0?ui=2&ik=4cd3775999&attid=0.1&permmsgid=msg-a:r-3819938193400191303&th=17da8e4c9182f919&view=att&disp=safe&realattid=17da8e416a9a2cb99be4iew=att&disp=safe&realattid=17da8e4168e70fa82b52

**Comment by rockymarko** [comment]
I got from plus 80 chips down to minus 480 !

**Comment by D4rWiNSS** [comment]
This can't be fixed on our end since this bug is related to the scene. The content creator should fix it. Please contact the content creator in order to have this issue fixed
