### ISSUE TITLE
Dragon city - Tangram

### ISSUE THREAD

**Issue by cubistic-mind** [decentraland/issues#204]
### What happened?

Hi
When I complete the Tangram quest in Dragon city and talk with the white reaper. I take the last piece of Tangram which is white and a congratulation message will pop up. but after teleporting again in dragon city, there isn't any white tangram. it's like I've never done the quest at all! 

### Steps to reproduce

Simply solve the problem. :)

### Operating System

Chrome/96.0.46 (Macintosh; Intel Mac OS X 12_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36

### Wallet

Metamask

### CPU

2.9 GHz Quad-Core Intel Core i7

### GPU

Radeon Pro 560 4 GB

### RAM

16 GB

### Kernel Version

1.0.0-1564535596.commit-f2d5a55

### Unity Version

1.0.21784-20211209132347.commit-15ad62b

### Realm

dg

### NameTag

Hessam#9613

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
