### ISSUE TITLE
King Trippy's Yatch 

### ISSUE THREAD

**Issue by pinarci** [decentraland/issues#205]
### What happened?

![Ekran görüntüsü 2021-12-12 153831](https://user-images.githubusercontent.com/61177851/145712579-9fdcb4df-4897-4995-836c-b61fed146919.png)

### Steps to reproduce

I guess you can fill  bottom of the yatch

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36

### Wallet

None, played as guest

### CPU

ryzen 5 3500x

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7212) 512MB

### RAM

16GB

### Kernel Version

1.0.0-1564535596.commit-f2d5a55

### Unity Version

1.0.21784-20211209132347.commit-15ad62b

### Realm

dg

### NameTag

dasdasd#bcf5

**Comment by D4rWiNSS** [comment]
This can't be fixed on our end since this bug is related to the scene. The content creator should fix it. Please contact the content creator in order to have this issue fixed
