### ISSUE TITLE
cant pickup basket

### ISSUE THREAD

**Issue by tonaccus** [decentraland/issues#206]
### What happened?

was trying to play the fruit catch game and couldnt pick up the basket

### Steps to reproduce

try to play the game

### Operating System

windows 11 chrome both updated

### Wallet

Metamask

### CPU

hp lgdy0013dx

### GPU

unknown

### RAM

16

### Kernel Version

1.0.0-1564535596.commit-f2d5a55

### Unity Version

1.0.21784-20211209132347.commit-15ad62b

### Realm

dg

### NameTag

Tonaccus#595f

**Comment by D4rWiNSS** [comment]
This can't be fixed on our end since this bug is related to the scene. The content creator should fix it. Please contact the content creator in order to have this issue fixed
