### ISSUE TITLE
bag

### ISSUE THREAD

**Issue by merdan24** [decentraland/issues#207]
### What happened?

![2021-12-14_01-21-22](https://user-images.githubusercontent.com/96088627/145899206-307c87bf-b31e-4a54-a4fe-aca92f53b0a5.png)
![2021-12-14_01-20-25](https://user-images.githubusercontent.com/96088627/145899212-26cb13b0-17cb-4423-9664-f7527e76ae8e.png)

### Steps to reproduce

error

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36

### Wallet

Metamask

### CPU

i5

### GPU

ANGLE (Intel, Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.9565) 512MB

### RAM

16

### Kernel Version

1.0.0-1574334367.commit-5676f8e

### Unity Version

1.0.21784-20211209132347.commit-15ad62b

### Realm

dg

### NameTag

Merdan#271a

**Comment by olavra** [comment]
Invalid due to lack of information to reproduce the incident.
