### ISSUE TITLE
No invert Y Axis..

### ISSUE THREAD

**Issue by djpseudonym** [decentraland/issues#208]
### What happened?

Not a bug but this is the only place I can find to report an issue.

I need Invert Y Axis for mouse adding to the game. 

I am not alone in needing this. I push up for down and down for up on a mouse like a lot of old school gamer,s do.
It makes it so difficult to play and almost impossible if you are playing a skill game.

If you are unsure how difficult it is.. Just goto any other FPV game you have, goto the settings and set Invert Y axis to the opposite of your usual setting. Now try to play.

See what I mean.

Please add Invert Y Axis.. Thousands of people play this way.

Thanks 
James

### Steps to reproduce

Try Invert Y Axis in any FPV game. This is what trying to  play Decent is like for us without having that options.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36

### Wallet

Metamask

### CPU

Intel 5

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9709) 512MB

### RAM

16

### Kernel Version

1.0.0-1574334367.commit-5676f8e

### Unity Version

1.0.21784-20211209132347.commit-15ad62b

### Realm

dg

### NameTag

DjPseudonym#4440

**Comment by djpseudonym** [comment]
A lot of people who invert the Y axis do so because the games they started playing had that control set-up as the default option. This is especially true of older gamers – in the 1980s and early 1990s, flight sims were a hugely popular genre, and of course, the controls would be inverted to match an aircraft yoke or joystick. The chances are, if you grew up with Microsoft Flight Sim or the LucasArts X-Wing and Tie-Fighter games, you have become used to pulling back on the controls to move upwards. This is also the case with some highly influential first-person shooters, including TimeSplitters 2, GoldenEye and Turok, all of which encouraged an inverted Y axis as the correct way to play.

**Comment by olavra** [comment]
hi @djpseudonym 

Thank you for taking the time to formulate this proposal. It is something that we have raised on sevearl occasions but it is not prioritized in the backlog, but it certainly helps to give it more importance. We will take it to the product table.

I am closing this ticket as it is not a support ticket.

**Comment by olavra** [comment]
Hi! I'm glad to tell you that we have implemented this feature and is no available in the settings planel. Thanks for your suggestion! :) https://github.com/decentraland/unity-renderer/issues/1899

**Comment by djpseudonym** [comment]
Brilliant..thank you 😊

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
