### ISSUE TITLE
Login in Chrome

### ISSUE THREAD

**Issue by JOHNNYinside** [decentraland/issues#209]
### What happened?

I am trying to login, using Google Chrome, and the button that links to the Wallet keeps spinning forever.

I tried reloading the page, deleting all sort of cookies and nothing happened.

I tried the anonymous option and it worked.

But, another funny issue came across. I could turn on the mic for a chat but it now kept on endlessly.

### Steps to reproduce

Just open Chrome, go to play.decentraland.org and mouseover the left card to login. The button will start spinning and never show the QR code to link the game to TrustWallet.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Wallet

Wallet Connect

### CPU

Intel i7

### GPU

ANGLE (Intel, Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0, D3D11-20.19.15.5058) 512MB

### RAM

16GB

### Kernel Version

1.0.0-1574334367.commit-5676f8e

### Unity Version

1.0.21784-20211209132347.commit-15ad62b

### Realm

dg

### NameTag

JOHNNYinside#2f3d

**Comment by olavra** [comment]
Hi @JOHNNYinside,

Sorry for the late response. We completely changed the behavior of the sign up page to cover this kind of corner cases.

Can you please confirm this is still happening to you?

**Comment by JOHNNYinside** [comment]
[image: oops.jpg]
Hi! Shamefully, I don't know what's wrong here. I cannot log into the PLAY
subdomain, but I can login to BUILDER, MARKETPLACE, etc.

The PLAY login is in a loop. Could it be related to a database issue? Maybe
my user location? From time to time I use a VPN. But, I've tested other
options and they work well, anyhow.

**Comment by D4rWiNSS** [comment]
Can you please delete the cache of the browser, and try again¿

**Comment by fzavalia** [comment]
There have been changes to the connection system. Is this issue still happening?

**Comment by AjimenezDCL** [comment]
Closing this issue because of not having a response for two weeks.
