### ISSUE TITLE
gltich or something

### ISSUE THREAD

**Issue by Domi155** [decentraland/issues#210]
### What happened?

my character keeps moving back(holding S) even though i am not holding it on my keyboard

### Steps to reproduce

please fix it its anoying that my character constantly moves

### Operating System

chrome, windows 10

### Wallet

Metamask

### CPU

ryzen 5 3600

### GPU

ANGLE (AMD, Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.13025.5005) 512MB

### RAM

16GB

### Kernel Version

1.0.0-1574334367.commit-5676f8e

### Unity Version

1.0.21784-20211209132347.commit-15ad62b

### Realm

dg

### NameTag

Domi#0084

**Comment by davidejensen** [comment]
Hello @Domi155 
We have recently applied a fix that should resolve this issue in the majority of the cases, could you verify if this is still happening to you?

If it's still happening, could you please verify that you don't have any external devices connected that could alter the input? (i.e. joysticks, steering wheels, graphics tablet, ...)
Could you verify that you also don't have any softwares that could alter the inputs as well? (autoclickers, virtual keyboards, ...)
