### ISSUE TITLE
Wonderzone Zeroed Out on Me

### ISSUE THREAD

**Issue by Preisolauphenonputenic** [decentraland/issues#211]
### What happened?

I've been in Wonderzone for quite a while - several weeks.  When I logged on today, all my earnings from the meteor mining are gone.

### Steps to reproduce

Play for days on end.  Log in one day and all your hard work is gone.

![20211215 DecentraLand Meteor Error](https://user-images.githubusercontent.com/80160391/146226939-cbcbbeec-67d3-4d0f-a196-b65e04e9be16.jpg)

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36

### Wallet

Metamask

### CPU

2.6 GHz 6-Core Intel Core i7

### GPU

AMD Radeon Pro 5500M OpenGL Engine 512MB

### RAM

16 GB 2667 MHz DDR4

### Kernel Version

1.0.0-1574334367.commit-5676f8e

### Unity Version

1.0.21784-20211209132347.commit-15ad62b

### Realm

dg

### NameTag

Preisolauphenon#fd26

**Comment by D4rWiNSS** [comment]
This must be fixed by the scene creator
