### ISSUE TITLE
buttun F in ice poker

### ISSUE THREAD

**Issue by amindecentra** [decentraland/issues#213]
### What happened?

hello, when im enter the ice poker , says press f to play and im press but not works, Im playing fluently, no lag, but sometimes f or e not work in my game.

### Steps to reproduce

i dont know

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0

### Wallet

Metamask

### CPU

intel i5 3th generation

### GPU

Radeon HD 7570m 1024mb

### RAM

6gb

### Kernel Version

1.0.0-1592770279.commit-473692f

### Unity Version

1.0.22656-20211217163527.commit-f7c808f

### Realm

artemis

### NameTag

Amin#8a91

**Comment by D4rWiNSS** [comment]
This can't be fixed on our end since this bug is related to the scene. The content creator should fix it. Please contact the content creator in order to have this issue fixed
