### ISSUE TITLE
Broken MAP Competition 1-220

### ISSUE THREAD

**Issue by Keravl** [decentraland/issues#216]
### What happened?

The hole is broken. When you put the ball in the hole it does not end the game. Because hole and finishing UI in different places.

### Steps to reproduce

Fix it
![image](https://user-images.githubusercontent.com/96367937/146666914-f15f87d0-fdd7-4fa9-a785-d3ed6eb81642.png)

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 OPR/81.0.4196.61

### Wallet

Fortmatic

### CPU

i8750

### GPU

ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-23.20.16.4974) 512MB

### RAM

8

### Kernel Version

1.0.0-1592770279.commit-473692f

### Unity Version

1.0.22656-20211217163527.commit-f7c808f

### Realm

dg

### NameTag

Keravi#9481

**Comment by D4rWiNSS** [comment]
This can't be fixed on our end since this bug is related to the scene. The content creator should fix it. Please contact the content creator in order to have this issue fixed
