### ISSUE TITLE
MAP point of interest Bug

### ISSUE THREAD

**Issue by Accusedbold** [decentraland/issues#217]
### What happened?

When you hover over the point of interest star for Chateau Satoshi Casino [-78, 75] You get a popup for an empty parcel.

### Steps to reproduce

Bring up the map and hover over the Golden Stay Labeled Chateau Satoshi.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36

### Wallet

Metamask

### CPU

Intel i7-8750H CPU @ 2.20 GHz (12 CPUs), ~2.2GHz

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6089) 512MB

### RAM

16 GB

### Kernel Version

1.0.0-1592770279.commit-473692f

### Unity Version

1.0.22656-20211217163527.commit-f7c808f

### Realm

dg

### NameTag

Accusedbold#fe2a

**Comment by olavra** [comment]
Hi @Accusedbold 

The scene of the Chateau Satoshi Casino is -77,76. We will double check the position of the POI.

**Comment by moliva** [comment]
Hello again, @Accusedbold.
Checking the map and the world, Chateau Satoshi Casino is marked on -78,76 and parcels around it. Parcel -78,75 is marking The Theatre scene placed there.
Please open a new issue if you find any issues with the map and scenes marked there currently.
Thank you!
