### ISSUE TITLE
problem with music

### ISSUE THREAD

**Issue by aircrypto69** [decentraland/issues#218]
### What happened?

hi music dont mute or decrese when i pot cursor on zero

### Steps to reproduce

...

### Operating System

brave

### Wallet

Metamask

### CPU

17 6 mg cacht

### GPU

ANGLE (Intel, Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0, D3D11-10.18.10.5100) 512MB

### RAM

4

### Kernel Version

1.0.0-1592770279.commit-473692f

### Unity Version

1.0.22656-20211217163527.commit-f7c808f

### Realm

dg

### NameTag

ChappePool#1712

**Comment by olavra** [comment]
Hi @aircrypto69 

We had a problem with the sound mixer a few months ago. This should be resolved by now. 
Please consider the music played by the scenes are not controlled by that setting slider, but the world slider.

Could you please confirm this is still happening to you?

**Comment by D4rWiNSS** [comment]
Closed because the reporter doesn't answer
