### ISSUE TITLE
Bug in Bug Reporting 

### ISSUE THREAD

**Issue by Accusedbold** [decentraland/issues#219]
### What happened?

When submitting a bug, I got a bunch of emails about a slack message not being able to be sent. People reporting bugs should not be receiving Error messages to their email.

### Steps to reproduce

Submit a bug and include your email.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36

### Wallet

Metamask

### CPU

Intel i7-8750H CPU @ 2.20 GHz (12 CPUs), ~2.2GHz

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6089) 512MB

### RAM

16 GB

### Kernel Version

1.0.0-1592770279.commit-473692f

### Unity Version

1.0.22734-20211220134033.commit-f5ece3c

### Realm

dg

### NameTag

Accusedbold#fe2a

**Comment by olavra** [comment]
Hi @Accusedbold 

Sorry for the late response. We have removed the slack notifications on this repository. Thanks for reporting this.
