### ISSUE TITLE
Christmas Quest

### ISSUE THREAD

**Issue by zMrSok** [decentraland/issues#220]
### What happened?

Completed and still 80% saying UNEXPECTED ERROR. If change location crash and delete every progress on completed mission.
![Screenshot (183)](https://user-images.githubusercontent.com/63802597/147009795-85b7ea2c-2249-4b1c-a36c-3b0cc9934b47.png)

### Steps to reproduce

Deliver last missing body part / key

### Operating System

Chrome

### Wallet

Metamask

### CPU

intel i7

### GPU

GTX 230

### RAM

16GB

### Kernel Version

1.0.0-1607309071.commit-3c59e2e

### Unity Version

1.0.22974-20211221165939.commit-3a1b261

### Realm

marvel

### NameTag

MrVertual#350d

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
