### ISSUE TITLE
Not able to add a friend through name or wallet

### ISSUE THREAD

**Issue by dmtzs** [decentraland/issues#221]
### What happened?

Im trying to add a friend using their wallet address or name but its not working

### Steps to reproduce

Just to try to add a friend in the normal way

### Operating System

Edge/96.0.1054.62 (Windows 10.0; Win64; x64)

### Wallet

Metamask

### CPU

AMD ryzen threadripper 1920x

### GPU

NVIDIA GeForce RTX 2080 SUPER

### RAM

48GB

### Kernel Version

1.0.0-1607309071.commit-3c59e2e

### Unity Version

1.0.22974-20211221165939.commit-3a1b261

### Realm

hephaestus

### NameTag

Dmtzs#06da

**Comment by 0xJuancito** [comment]
This issue has been solved. Please reopen a ticket if you experience this issue again
