### ISSUE TITLE
Holiday Party - Playboy not being able to redeem rewards

### ISSUE THREAD

**Issue by wedob13** [decentraland/issues#222]
### What happened?

I am having a hard luck (and i lost the poap ;) ) the last 2 days with the Playboy event. For some reason people keep getting errors and they cant collect the rewards from various events around DCL. Obviously this is not the only one but ill just go through them in different bug reports.

Location: Playboy holiday Party (102,80)

### Steps to reproduce

1.Go under the mistletoe and try to blow a kiss. Blew a kiss, got the pop up message and never had the reward delivered.

2. Make it to the end of the jumping puzzle (parkour challenge) -> Did it, make it to the end, "Collected" the reward , its not appearing anywhere.

3. Fish the POAP -> Did it, but in the end it threw an error

( i have videos + screenshots i can provide - can't upload them to github ofc but if someone needs them they can contact me, thank you :) )

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Wallet

Metamask

### CPU

Ryzen 5600X

### GPU

ANGLE (AMD, AMD Radeon RX 5700 XT Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.13033.5003) 512MB

### RAM

32GB

### Kernel Version

1.0.0-1607309071.commit-3c59e2e

### Unity Version

1.0.22974-20211221165939.commit-3a1b261

### Realm

dg

### NameTag

dev13nt#df98

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
