### ISSUE TITLE
Dragon Rush - Leaderboard not getting updated properly

### ISSUE THREAD

**Issue by wedob13** [decentraland/issues#223]
### What happened?

Hello all, i would like to report an incosistency with the dragon rush game. There is no way to contact the creators so i thought about dropping it here in case someone sees it.

I have a high score of over 55k points and i should be on top #1 of the leader board , but i am not.

For some reason the leaderboard is not getting updated properly

### Steps to reproduce

1. Play Dragon Rush
2. Validate that the points are getting reflected always

(As always i have video footage + screenshots with the high score that is still not on the leaderboard)

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Wallet

Metamask

### CPU

Ryzen 5600X

### GPU

ANGLE (AMD, AMD Radeon RX 5700 XT Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.13033.5003) 512MB

### RAM

32GB

### Kernel Version

1.0.0-1607309071.commit-3c59e2e

### Unity Version

1.0.22974-20211221165939.commit-3a1b261

### Realm

dg

### NameTag

dev13nt#df98

**Comment by D4rWiNSS** [comment]
We can't fix this on our side. This needs to be fixed by the content creators, there is nothing we can do

**Comment by wedob13** [comment]
Took you guys a bit to reply
