### ISSUE TITLE
Sound gone

### ISSUE THREAD

**Issue by nit-network** [decentraland/issues#224]
### What happened?

Sound goes off after several minutes of gameplay.

### Steps to reproduce

https://play.decentraland.org/?island=I3kd&position=-27%2C56&realm=odin

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Wallet

Metamask

### CPU

2,9 GHz Quad-Core Intel Core i7

### GPU

Radeon Pro 560 4 GB Intel HD Graphics 630 1536 MB

### RAM

16

### Kernel Version

1.0.0-1611794749.commit-aa12e6f

### Unity Version

1.0.23155-20211222192146.commit-63835fd

### Realm

odin

### NameTag

web3nit#b418

**Comment by olavra** [comment]
Hi @nit-network 

Sorry for the late response. We had some instability with the sound mixer a few months ago. This should have been resolved with the latest updates.

Can you please confirm this is still happening to you?

**Comment by D4rWiNSS** [comment]
Closed because the reporter doesn't answer
