### ISSUE TITLE
xmas quest

### ISSUE THREAD

**Issue by Slyoo1** [decentraland/issues#225]
### What happened?

I finished the xmas quest in dcl and open the present for the glasses and did not receive them. I ended up doing the quest twice and finished it and still did not receive the reward.

### Steps to reproduce

I dont know.

### Operating System

Chrome/96.0.4664.110

### Wallet

Metamask

### CPU

samsung intel core i7

### GPU

ANGLE (NVIDIA, NVIDIA GeForce 940MX Direct3D11 vs_5_0 ps_5_0, D3D11-24.21.13.9907) 512MB

### RAM

64gb

### Kernel Version

1.0.0-1611794749.commit-aa12e6f

### Unity Version

1.0.23155-20211222192146.commit-63835fd

### Realm

dg

### NameTag

Sly#77be

**Comment by skoblenick** [comment]
i have seen the issue on other realms and tried different wallets with the same result. I have attempted to complete the quest multiple times (on the same wallet) with no change in the result. the glasses never show up in the backpack > collectables.

**Comment by D4rWiNSS** [comment]
Quest is not active at the momment
