### ISSUE TITLE
xmas quest

### ISSUE THREAD

**Issue by Slyoo1** [decentraland/issues#226]
### What happened?

completed the quest and did not receive reward.

### Steps to reproduce

finish the quest

### Operating System

Chrome/96.0.4664.110

### Wallet

Metamask

### CPU

samsung intel core i7

### GPU

ANGLE (NVIDIA, NVIDIA GeForce 940MX Direct3D11 vs_5_0 ps_5_0, D3D11-24.21.13.9907) 512MB

### RAM

32gb

### Kernel Version

1.0.0-1611794749.commit-aa12e6f

### Unity Version

1.0.23155-20211222192146.commit-63835fd

### Realm

dg

### NameTag

Sly#77be

**Comment by D4rWiNSS** [comment]
Quest is not active at the momment
