### ISSUE TITLE
error when i send item to sell on decentraland game

### ISSUE THREAD

**Issue by aircrypto69** [decentraland/issues#227]
### What happened?

on during the game decentraland when i want to send Xmas-ray-vision that i got from game , i put sell bottom and page wrote: 

" sorry,that page is missing.do you want to check if a saved version is available on the saveback machine ? "

and when i put "check for saved version"  u wrote " sorry thre is no saved version"  .....  so how  players can sell items that colect from gameeee????????

### Steps to reproduce

when i wnat to send Xmas-ray-vision that i got from game , i put sell bottom and page wrote: 

" sorry,that page is missing.do you want to check if a saved version is available on the saveback machine ? "

and when i put "check for saved version"  u wrote " sorry thre is no saved version"  .....  so how  players can sell items that colect from gameeee????????

### Operating System

brave

### Wallet

Metamask

### CPU

17 6 mg cacht

### GPU

NVIDIA GeForce GT 635M Direct3D11

### RAM

4

### Kernel Version

1.0.0-1615749195.commit-a4079d2

### Unity Version

1.0.23155-20211222192146.commit-63835fd

### Realm

fenrir

### NameTag

ChappePool#1712

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
