### ISSUE TITLE
Playboy mistletoe

### ISSUE THREAD

**Issue by perezhua1684** [decentraland/issues#228]
### What happened?

mistletoe challenge will not work. press kiss number 7 under the mistletoe but wont receive achievement.

### Steps to reproduce

go under mistletoe press 7 nothing happen.

### Operating System

5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Wallet

Metamask

### CPU

intel I7

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9676) 512MB

### RAM

32gb

### Kernel Version

1.0.0-1615749195.commit-a4079d2

### Unity Version

1.0.23155-20211222192146.commit-63835fd

### Realm

dg

### NameTag

Angel#9356

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
