### ISSUE TITLE
error doing playboy parkour

### ISSUE THREAD

**Issue by perezhua1684** [decentraland/issues#229]
### What happened?

finished parkour map and was given "error error" when clicking on  claim prize playboy

### Steps to reproduce

finish playboy parkour and click on ice playboy at the end

### Operating System

Chrome

### Wallet

Metamask

### CPU

i7

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9676) 512MB

### RAM

32gb

### Kernel Version

1.0.0-1615749195.commit-a4079d2

### Unity Version

1.0.23155-20211222192146.commit-63835fd

### Realm

dg

### NameTag

Angel#9356

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
