### ISSUE TITLE
No reward Crismass

### ISSUE THREAD

**Issue by killten** [decentraland/issues#230]
### What happened?

complete All Quest xmax but No reward recvivied Please check

### Steps to reproduce

complete All Quest xmax but No reward recvivied Please check

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Wallet

Metamask

### CPU

i5

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7196) 512MB

### RAM

8

### Kernel Version

1.0.0-1615749195.commit-a4079d2

### Unity Version

1.0.23155-20211222192146.commit-63835fd

### Realm

dg

### NameTag

Sezar89#f330

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
