### ISSUE TITLE
Cant change realm and name change on its own 

### ISSUE THREAD

**Issue by Rypatterso** [decentraland/issues#231]
### What happened?

Hello, I have encountered an issue where I am stuck on the fenrir realm. I have tried resetting my browser cache, unlinking my wallet, resetting my pc and also resetting my modem. None of it seems to work and the chat box replies with a message that says unable to fid the realm that I am trying to switch to, for instance "unable to find dg" I also had something happen a little over a week ago where my in game name pson#83d8 was changed to something else like claple#83d8 when I logged on the next day. Not sure if that was also a bug but I figured I should mention it because it stood out to me. Any help with this would be greatly appreciated! I want to partake in the holiday festivities! :) 

### Steps to reproduce

![Screenshot 2021-12-24 181931](https://user-images.githubusercontent.com/94562244/147374175-f78526f4-e4f4-4852-a476-8e2581f2f54a.png)

### Operating System

Chrome, Windows 10 

### Wallet

Metamask

### CPU

Ryzen 5 

### GPU

ANGLE (AMD, AMD Radeon(TM) Vega 8 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.11028.10001) 512MB

### RAM

8

### Kernel Version

1.0.0-1615749195.commit-a4079d2

### Unity Version

1.0.23155-20211222192146.commit-63835fd

### Realm

fenrir

### NameTag

Pson#83d8

**Comment by olavra** [comment]
Hi @Rypatterso 

Sorry for the inconvenience. Servers are managed by the community and sometimes they may be unstable.
This problem should be resolved by now. Remember that you can use the realm switcher in the Start menu now.

**Comment by D4rWiNSS** [comment]
This is fixedd now
