### ISSUE TITLE
missing reward

### ISSUE THREAD

**Issue by Valcanos** [decentraland/issues#232]
### What happened?

Finished X-mas quest, got the reward, but i cant see it in my backpack. Did the quest over again, same results. (i did refresh etc)

### Steps to reproduce

I guess to give me my reward? or at least to fix my account so i can be able to receive my gift

### Operating System

google chrome

### Wallet

Metamask

### CPU

intel core i7 7th gen

### GPU

GTX 1050Ti

### RAM

16

### Kernel Version

1.0.0-1615749195.commit-a4079d2

### Unity Version

1.0.23155-20211222192146.commit-63835fd

### Realm

dg

### NameTag

Demis#db27

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
