### ISSUE TITLE
unable to load friends & messages

### ISSUE THREAD

**Issue by 9buyexpert** [decentraland/issues#236]
### What happened?

there was a message showing up "unable to load friends & messages" during login. 

### Steps to reproduce

just login

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Wallet

Metamask

### CPU

intel i7

### GPU

NVIDIA GeForce

### RAM

64gb

### Kernel Version

1.0.0-1615749195.commit-a4079d2

### Unity Version

1.0.23155-20211222192146.commit-63835fd

### Realm

dg

### NameTag

9buyexpert#833e

**Comment by ImClev** [comment]
I'm having the same issue. It's been happening for about a week now.

**Comment by 0xJuancito** [comment]
This issue has been solved. Please reopen a ticket if you experience this issue again
