### ISSUE TITLE
Server error?

### ISSUE THREAD

**Issue by EthanClapp** [decentraland/issues#237]
### What happened?

While attempting to complete the christmas quests at Christmas Plaza, the server encounters an error and reloads the page, with all quests reset to the beginning, and as such i have been unable to complete them and receive a POAP.

### Steps to reproduce

Go to Christmas Plaza and attempt to complete the quests. This error doesn't happen for my partner though, so is an intermittent issue.

### Operating System

Chrome 96.0.4664.110 , Windows 10 64bit 19043.1415

### Wallet

Metamask

### CPU

11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz   3.60 GHz

### GPU

NVIDIA GeForce RTX 3070

### RAM

32GB

### Kernel Version

1.0.0-1615749195.commit-a4079d2

### Unity Version

1.0.23155-20211222192146.commit-63835fd

### Realm

any, has occurred in DG, Thor and Fenrir

### NameTag

Clueless1#98b4

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
