### ISSUE TITLE
Problem with the chests

### ISSUE THREAD

**Issue by GonzaloNa** [decentraland/issues#238]
### What happened?

The system returns an error message to me every time I try to open a chest. "Sorry, There was a problem with our server, please try again later."

### Steps to reproduce

Go to de Afterr flood - Teasury (-46,61) try to open the chest.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Wallet

Metamask

### CPU

AMD FX(tm)-8350 Eight-Core Processor 4.00 GHz

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GT 730 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671) 512MB

### RAM

16GB

### Kernel Version

1.0.0-1637382899.commit-5416ee7

### Unity Version

1.0.23155-20211222192146.commit-63835fd

### Realm

dg

### NameTag

Gonzalo#7899

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
