### ISSUE TITLE
Unable to redeem X-Mas Ray Glasses in Xmas Plaza Christmas Event

### ISSUE THREAD

**Issue by itsjaylin** [decentraland/issues#239]
### What happened?

Unable to redeem X-Mas Ray Glasses in Xmas Plaza Christmas Event. I did all of the tasks, opened the red gift box and saw the glasses, but was unable to locate the glasses in my backpack (checked all accessories and collectibles section.

### Steps to reproduce

Complete Christmas event in Xmas Plaza.
Talk to elf.
Open the red gift box containing glasses
Click Yes to receive them (clicking learn more reveals nothing available on last try)
Check inventory.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Wallet

Metamask

### CPU

Processor	Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz, 3000 Mhz, 8 Core(s), 8 Logical Processor(s)

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5785) 512MB

### RAM

16GB

### Kernel Version

1.0.0-1637382899.commit-5416ee7

### Unity Version

1.0.23155-20211222192146.commit-63835fd

### Realm

dg

### NameTag

itsjaylin#40d2

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
