### ISSUE TITLE
HUD stuck in center of screen

### ISSUE THREAD

**Issue by abinge05** [decentraland/issues#240]
### What happened?

HUD moved to center of screen after changing graphics from medium to ultra. Resetting settings hasn't fixed the issue.

### Steps to reproduce

See above.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62

### Wallet

Metamask

### CPU

3600X

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9613) 512MB

### RAM

16GM

### Kernel Version

1.0.0-1637382899.commit-5416ee7

### Unity Version

1.0.23155-20211222192146.commit-63835fd

### Realm

dg

### NameTag

abinge05#0fe0

**Comment by olavra** [comment]
Hi @abinge05 

We have released a patch that fixes this issue. Could you please confirm this has been resolved for you?

**Comment by D4rWiNSS** [comment]
Closed because the reporter doesn't answer
