### ISSUE TITLE
Walking backwards upon logging in.

### ISSUE THREAD

**Issue by Mechman2001** [decentraland/issues#241]
### What happened?

Character is stuck walking backwards and will not stop.

### Steps to reproduce

Log in.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Wallet

Metamask

### CPU

ryzen 5

### GPU

ANGLE (AMD, AMD Radeon RX 5700 XT Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14011.3017) 512MB

### RAM

15 gb

### Kernel Version

1.0.0-1637382899.commit-5416ee7

### Unity Version

1.0.23155-20211222192146.commit-63835fd

### Realm

dg

### NameTag

KiGee#c143

**Comment by olavra** [comment]
Hi @Mechman2001 

Sorry for the late response.

Are you using any tablet, mouse pad or non-traditional input system?

Regards

**Comment by olavra** [comment]
Could it be related to this other issue?
https://github.com/decentraland/issues/issues/253

**Comment by moliva** [comment]
Closing this issue because of not having a response for two weeks.
