### ISSUE TITLE
Wonder Mine

### ISSUE THREAD

**Issue by 1THEOMEN** [decentraland/issues#242]
### What happened?

I am not getting each day 100 wonder coin 

### Steps to reproduce

not getting 100 wonder coin each day

### Operating System

Chrome/96.0.4664.110 

### Wallet

Fortmatic

### CPU

intel i7 10th generation

### GPU

 (NVIDIA, NVIDIA GeForce RTX 2060 

### RAM

16

### Kernel Version

1.0.0-1637382899.commit-5416ee7

### Unity Version

1.0.23155-20211222192146.commit-63835fd

### Realm

Wonder mine

### NameTag

OMEN#8b0c

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
