### ISSUE TITLE
crash chrome

### ISSUE THREAD

**Issue by bobodj1988** [decentraland/issues#243]
### What happened?

abort("Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 2147090432, (2) compile with -s ALLOW_MEMORY_GROWTH=1 which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with -s ABORTING_MALLOC=0 ") at Error at jsStackTrace (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.framework.js.br?v=1.0.23155-20211222192146.commit-63835fd:408:16319) at stackTrace (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.framework.js.br?v=1.0.23155-20211222192146.commit-63835fd:408:16490) at abort (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.framework.js.br?v=1.0.23155-20211222192146.commit-63835fd:408:703) at abortOnCannotGrowMemory (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.framework.js.br?v=1.0.23155-20211222192146.commit-63835fd:408:17570) at _sbrk (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[105616]:0x1b57e97) at _GC_unix_sbrk_get_mem (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[104423]:0x1b28f68) at _GC_unix_get_mem (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[104422]:0x1b28f1b) at _GC_expand_hp_inner (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[104448]:0x1b2a2f5) at _GC_collect_or_expand (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[104445]:0x1b29fbc) at _GC_alloc_large (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[104442]:0x1b29c43) at _GC_generic_malloc (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[104594]:0x1b2fc68) at _GC_malloc_kind (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[104593]:0x1b2fc04) at _GC_malloc_atomic (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[104596]:0x1b2fcd5) at __ZN6il2cpp2vm6Object15AllocatePtrFreeEmP11Il2CppClass (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[103026]:0x1aff160) at __ZN6il2cpp2vm5Array11NewSpecificEP11Il2CppClassm (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[103023]:0x1aff0b6) at __ZN6il2cpp2vm5Array3NewEP11Il2CppClassm (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[103020]:0x1aff01c) at _il2cpp_array_new (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[101714]:0x1ad90fe) at __Z19scripting_array_new17ScriptingClassPtrmm (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[7226]:0x2e57cb) at __Z30Mesh_CUSTOM_GetBoneWeightsImplP12Il2CppObject (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[16904]:0x69c3ce) at _Mesh_GetBoneWeightsImpl_m98A8F5011434EB2373D3BCEAD5CFB8BD7D5B1170 (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[64354]:0x12d95ca) at _Mesh_get_boneWeights_mD1DD5B905C2BA8FFAB355DFBE6692792F0393126 (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[64466]:0x12db1ff) at _GPUSkinningUtils_EncodeBindPosesIntoMesh_m2AAB2A46F96B426CB2BD75DEC834F24783D3AD57 (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[100492]:0x1aa1175) at _AvatarMeshCombinerHelper_CombineInternal_m25BBAAF84C95387306080F37F419C7C8FD884E81 (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[96055]:0x19f9908) at _AvatarMeshCombinerHelper_Combine_m9D38910195F76C46B46C6A00D771578090030AD7 (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[96054]:0x19f95d9) at _AvatarRenderer_MergeAvatar_m3A075ED3C62FEAD3048F261FDB4A31CBBF13AF13 (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[73400]:0x147da36) at dynCall_iiii (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[105723]:0x1b58915) at Object.dynCall_iiii (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.framework.js.br?v=1.0.23155-20211222192146.commit-63835fd:408:512844) at invoke_iiii (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.framework.js.br?v=1.0.23155-20211222192146.commit-63835fd:408:356070) at _U3CLoadAvatarU3Ed__56_MoveNext_m8B542B1ECA99EEBB4268FBC691B7F52517401CC0 (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[73511]:0x14855ac) at __ZN21InterfaceFuncInvoker0IP12Il2CppObjectE6InvokeEtP11Il2CppClassS1_ (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[33528]:0xd675c8) at _SetupCoroutine_InvokeMoveNext_m036E6EE8C2A4D2DAA957D5702F1A3CA51313F2C7 (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[59965]:0x11fab43) at __Z164RuntimeInvoker_FalseVoid_t700C6383A2A510C2CF4DD86DABD5CA9FF70ADAC5_VoidU2A_tC7FFEB695C165BD92A8656A0260E9CBC93892D9A_Int32_tFDE5F8CD43D10453F6A2E0C77FE48C6CC7009046PFvvEPK10MethodInfoPvPS4_ (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[32532]:0xd47702) at dynCall_iiiii (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[105734]:0x1b58a6d) at Object.dynCall_iiiii (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.framework.js.br?v=1.0.23155-20211222192146.commit-63835fd:408:514231) at invoke_iiiii (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.framework.js.br?v=1.0.23155-20211222192146.commit-63835fd:408:358686) at __ZN6il2cpp2vm7Runtime6InvokeEPK10MethodInfoPvPS5_PP15Il2CppException (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[103047]:0x1aff850) at _il2cpp_runtime_invoke (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[101786]:0x1ad9440) at __Z23scripting_method_invoke18ScriptingMethodPtr18ScriptingObjectPtrR18ScriptingArgumentsP21ScriptingExceptionPtrb (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[5473]:0x24e29b) at __ZN19ScriptingInvocation6InvokeEP21ScriptingExceptionPtrb (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[5471]:0x24df87) at __ZN9Coroutine14InvokeMoveNextEP21ScriptingExceptionPtr (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[9746]:0x3ad1fb) at __ZN9Coroutine3RunEPb (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[9743]:0x3aced0) at __ZN9Coroutine3RunEPb (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[9743]:0x3acf6a) at __ZN9Coroutine17ContinueCoroutineEP6ObjectPv (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[9749]:0x3ad421) at __ZN18DelayedCallManager6UpdateEi (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[10004]:0x3c64ee) at __ZZ23InitPlayerLoopCallbacksvEN49UpdateScriptRunDelayedDynamicFrameRateRegistrator7ForwardEv (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[12599]:0x4b23a4) at __Z17ExecutePlayerLoopP22NativePlayerLoopSystem (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[12214]:0x48cb80) at __Z17ExecutePlayerLoopP22NativePlayerLoopSystem (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[12214]:0x48cb95) at __Z10PlayerLoopv (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[12202]:0x48c6d2) at __ZL8MainLoopv (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[12190]:0x48a9b5) at dynCall_v (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[105818]:0x1b59458) ... file: - lineno: 0

### Steps to reproduce

abort("Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 2147090432, (2) compile with -s ALLOW_MEMORY_GROWTH=1 which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with -s ABORTING_MALLOC=0 ") at Error at jsStackTrace (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.framework.js.br?v=1.0.23155-20211222192146.commit-63835fd:408:16319) at stackTrace (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.framework.js.br?v=1.0.23155-20211222192146.commit-63835fd:408:16490) at abort (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.framework.js.br?v=1.0.23155-20211222192146.commit-63835fd:408:703) at abortOnCannotGrowMemory (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.framework.js.br?v=1.0.23155-20211222192146.commit-63835fd:408:17570) at _sbrk (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[105616]:0x1b57e97) at _GC_unix_sbrk_get_mem (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[104423]:0x1b28f68) at _GC_unix_get_mem (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[104422]:0x1b28f1b) at _GC_expand_hp_inner (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[104448]:0x1b2a2f5) at _GC_collect_or_expand (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[104445]:0x1b29fbc) at _GC_alloc_large (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[104442]:0x1b29c43) at _GC_generic_malloc (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[104594]:0x1b2fc68) at _GC_malloc_kind (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[104593]:0x1b2fc04) at _GC_malloc_atomic (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[104596]:0x1b2fcd5) at __ZN6il2cpp2vm6Object15AllocatePtrFreeEmP11Il2CppClass (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[103026]:0x1aff160) at __ZN6il2cpp2vm5Array11NewSpecificEP11Il2CppClassm (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[103023]:0x1aff0b6) at __ZN6il2cpp2vm5Array3NewEP11Il2CppClassm (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[103020]:0x1aff01c) at _il2cpp_array_new (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[101714]:0x1ad90fe) at __Z19scripting_array_new17ScriptingClassPtrmm (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[7226]:0x2e57cb) at __Z30Mesh_CUSTOM_GetBoneWeightsImplP12Il2CppObject (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[16904]:0x69c3ce) at _Mesh_GetBoneWeightsImpl_m98A8F5011434EB2373D3BCEAD5CFB8BD7D5B1170 (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[64354]:0x12d95ca) at _Mesh_get_boneWeights_mD1DD5B905C2BA8FFAB355DFBE6692792F0393126 (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[64466]:0x12db1ff) at _GPUSkinningUtils_EncodeBindPosesIntoMesh_m2AAB2A46F96B426CB2BD75DEC834F24783D3AD57 (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[100492]:0x1aa1175) at _AvatarMeshCombinerHelper_CombineInternal_m25BBAAF84C95387306080F37F419C7C8FD884E81 (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[96055]:0x19f9908) at _AvatarMeshCombinerHelper_Combine_m9D38910195F76C46B46C6A00D771578090030AD7 (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[96054]:0x19f95d9) at _AvatarRenderer_MergeAvatar_m3A075ED3C62FEAD3048F261FDB4A31CBBF13AF13 (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[73400]:0x147da36) at dynCall_iiii (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[105723]:0x1b58915) at Object.dynCall_iiii (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.framework.js.br?v=1.0.23155-20211222192146.commit-63835fd:408:512844) at invoke_iiii (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.framework.js.br?v=1.0.23155-20211222192146.commit-63835fd:408:356070) at _U3CLoadAvatarU3Ed__56_MoveNext_m8B542B1ECA99EEBB4268FBC691B7F52517401CC0 (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[73511]:0x14855ac) at __ZN21InterfaceFuncInvoker0IP12Il2CppObjectE6InvokeEtP11Il2CppClassS1_ (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[33528]:0xd675c8) at _SetupCoroutine_InvokeMoveNext_m036E6EE8C2A4D2DAA957D5702F1A3CA51313F2C7 (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[59965]:0x11fab43) at __Z164RuntimeInvoker_FalseVoid_t700C6383A2A510C2CF4DD86DABD5CA9FF70ADAC5_VoidU2A_tC7FFEB695C165BD92A8656A0260E9CBC93892D9A_Int32_tFDE5F8CD43D10453F6A2E0C77FE48C6CC7009046PFvvEPK10MethodInfoPvPS4_ (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[32532]:0xd47702) at dynCall_iiiii (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[105734]:0x1b58a6d) at Object.dynCall_iiiii (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.framework.js.br?v=1.0.23155-20211222192146.commit-63835fd:408:514231) at invoke_iiiii (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.framework.js.br?v=1.0.23155-20211222192146.commit-63835fd:408:358686) at __ZN6il2cpp2vm7Runtime6InvokeEPK10MethodInfoPvPS5_PP15Il2CppException (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[103047]:0x1aff850) at _il2cpp_runtime_invoke (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[101786]:0x1ad9440) at __Z23scripting_method_invoke18ScriptingMethodPtr18ScriptingObjectPtrR18ScriptingArgumentsP21ScriptingExceptionPtrb (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[5473]:0x24e29b) at __ZN19ScriptingInvocation6InvokeEP21ScriptingExceptionPtrb (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[5471]:0x24df87) at __ZN9Coroutine14InvokeMoveNextEP21ScriptingExceptionPtr (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[9746]:0x3ad1fb) at __ZN9Coroutine3RunEPb (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[9743]:0x3aced0) at __ZN9Coroutine3RunEPb (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[9743]:0x3acf6a) at __ZN9Coroutine17ContinueCoroutineEP6ObjectPv (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[9749]:0x3ad421) at __ZN18DelayedCallManager6UpdateEi (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[10004]:0x3c64ee) at __ZZ23InitPlayerLoopCallbacksvEN49UpdateScriptRunDelayedDynamicFrameRateRegistrator7ForwardEv (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[12599]:0x4b23a4) at __Z17ExecutePlayerLoopP22NativePlayerLoopSystem (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[12214]:0x48cb80) at __Z17ExecutePlayerLoopP22NativePlayerLoopSystem (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[12214]:0x48cb95) at __Z10PlayerLoopv (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[12202]:0x48c6d2) at __ZL8MainLoopv (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[12190]:0x48a9b5) at dynCall_v (https://cdn.decentraland.org/@dcl/unity-renderer/1.0.23155-20211222192146.commit-63835fd/unity.wasm.br?v=1.0.23155-20211222192146.commit-63835fd:wasm-function[105818]:0x1b59458) ... file: - lineno: 0

### Operating System

Chrome/96.0.4664.110

### Wallet

Metamask

### CPU

i5

### GPU

ANGLE (AMD, AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.20903.8001) 512MB

### RAM

16

### Kernel Version

1.0.0-1637382899.commit-5416ee7

### Unity Version

1.0.23155-20211222192146.commit-63835fd

### Realm

dg

### NameTag

bobo1988#223b

**Comment by olavra** [comment]
Hi @bobodj1988 

Thank you for reporting this issue. We had some memory issues that were mitigated with the latest updates. Can you confirm this is still happening to you?

**Comment by D4rWiNSS** [comment]
Close because there is no answer from the reporter
