### ISSUE TITLE
Locked on map

### ISSUE THREAD

**Issue by GutemX** [decentraland/issues#244]
### What happened?

While walking through the Wonder World area, Test 1 Space -17 -21, I tried to climb a wooden structure. But it fell to the side and I got stuck.

### Steps to reproduce

Climb up the wooden frame ramp and drop down beside the second column.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Wallet

Metamask

### CPU

Intel Core i3

### GPU

ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8853) 512MB

### RAM

16

### Kernel Version

1.0.0-1637382899.commit-5416ee7

### Unity Version

1.0.23155-20211222192146.commit-63835fd

### Realm

thor

### NameTag

Papilum#974e

**Comment by D4rWiNSS** [comment]
This can't be fixed on our end since this bug is related to the scene. The content creator should fix it
