### ISSUE TITLE
Slow gas issue

### ISSUE THREAD

**Issue by Blittz88** [decentraland/issues#247]
### What happened?

Hello,

I am writing to inform you of missing tokens whilst playing Roulette. The wheel will either keep spinning or will take a rather longer than usual time to stop. I understand if the gas fees are high there may be some delay, but however, when it doesn't stop spinning and requires me to reload the game and my tokens that I had on the table are then gone. Now I believe this is unfair as I don't get to see what the results are. This has not happened once or twice but many times, and I am getting quite fed up with it. I actually have the issue still going in the background whilst reporting this issue now.

### Steps to reproduce

Could start by reimbursing.

### Operating System

Chrome 96.0.4664.110 (Official Build) (64-bit) / Windows 10 Home 64Bit

### Wallet

Metamask

### CPU

AMD Ryzen 7 5800H with Radeon Graphics 3.20 GHz

### GPU

Nvidia GeForce RTX 3060

### RAM

16GB

### Kernel Version

1.0.0-1655291241.commit-703e3b8

### Unity Version

1.0.23767-20220104173406.commit-c6926e1

### Realm

heimdallr

### NameTag

Blittz88#bf90

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
