### ISSUE TITLE
Cant login to golfcraft

### ISSUE THREAD

**Issue by Awakeneddave** [decentraland/issues#248]
### What happened?

Enter decentraland, go to golf craft and click login. My phone prompts me to approve sign in (using crypto.com defi wallet) and I am receiving a message saying 'something went wrong, please try again later'. I have rebooted all my devices and cleared cookies and retried several times over a few days with the same results. I cannot log in. 

### Steps to reproduce

Login to dectraland using walletconnect and crypto.com defi wallet. Then jumpin to golfcraft. click login and I get the error
![Screenshot_20220105-173239](https://user-images.githubusercontent.com/97197175/148292740-8cfcdf83-79ed-43cb-8c69-d4369e919f40.jpg)
![Screenshot_20220105-173247](https://user-images.githubusercontent.com/97197175/148292755-dbfebe3a-08ed-4fdf-9d36-9bf519ed4510.jpg)

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Wallet

Wallet Connect

### CPU

Intel core i7-7700HQ

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9649) 512MB

### RAM

32GB

### Kernel Version

1.0.0-1659135064.commit-8e1d1f7

### Unity Version

1.0.23767-20220104173406.commit-c6926e1

### Realm

loki

### NameTag

Awakeneddave#c79f

**Comment by pabloes** [comment]
While this is fixed:
Only metamask is supported for now in Golfcraft (browser extension or mobile)

**Comment by AjimenezDCL** [comment]
Is this still happening? Now Decentraland is compatible with Wallet Connect.

**Comment by pabloes** [comment]
It's fixed now

**Comment by pravusjif** [comment]
Closing issue as it's been fixed.
