### ISSUE TITLE
Shows"error" when claiming badge

### ISSUE THREAD

**Issue by DGLIU0816** [decentraland/issues#249]
### What happened?

as title

### Steps to reproduce

help

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Wallet

Metamask

### CPU

intel i7

### GPU

no

### RAM

16GB

### Kernel Version

1.0.0-1663107759.commit-44ce947

### Unity Version

1.0.23767-20220104173406.commit-c6926e1

### Realm

marvel

### NameTag

DGLIU#77ad

**Comment by olavra** [comment]
Closed due to invalid formation of support request
