### ISSUE TITLE
Bug in tominoya casino

### ISSUE THREAD

**Issue by Elli44** [decentraland/issues#250]
### What happened?

Hi ! i were playing in tominoya casino and the roulette was lock on rolling mode. So it was impossible to reset. 
Since this moment, when i want to play, i have this message on my screen " You can't play ice poker in multiple tabs please close all other tabs to continue". But first i want to play roulette and no poker and second i have all my tabs closed.

Thank you for help ! 

Elliot 

### Steps to reproduce

Maybe look at the script to see if there is a problem.

### Operating System

 Chrome/96.0.4664.110 

### Wallet

Metamask

### CPU

Intel core i5

### GPU

Nvidia GEFORCE GTX

### RAM

8

### Kernel Version

1.0.0-1663107759.commit-44ce947

### Unity Version

1.0.23767-20220104173406.commit-c6926e1

### Realm

dg

### NameTag

Elliot#7d89

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
