### ISSUE TITLE
The character is always on the move.

### ISSUE THREAD

**Issue by kyurtseven7** [decentraland/issues#251]
### What happened?

Because the character is constantly running, I am unable to engage with anything.

### Steps to reproduce

Fix it.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Wallet

Metamask

### CPU

AMD Ryzen 7 3800x

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9729) 512MB

### RAM

16GB

### Kernel Version

1.0.0-1663107759.commit-44ce947

### Unity Version

1.0.23767-20220104173406.commit-c6926e1

### Realm

marvel

### NameTag

kyurtseven7#8501

**Comment by olavra** [comment]
Hi @kyurtseven7 

Sorry for the late response. Is this still happening to you?

Are you using any tablet / mouse pad or any unusual input hardware?

**Comment by davidejensen** [comment]
Hello @kyurtseven7 
We have recently applied a fix that should resolve this issue in the majority of the cases, could you verify if this is still happening to you?

If it's still happening, could you please verify that you don't have any external devices connected that could alter the input? (i.e. joysticks, steering wheels, graphics tablet, ...) 
Could you verify that you also don't have any softwares that could alter the inputs as well? (autoclickers, virtual keyboards, ...)
