### ISSUE TITLE
ERROR CLAIM BADGE SAMSUNG

### ISSUE THREAD

**Issue by skoumpis1** [decentraland/issues#252]
### What happened?

I try to claim badge in samsung hall but get ERROR 

### Steps to reproduce

I wanna claim badge u know

### Operating System

Google Chrome, Windows 10 OS 64 bit 

### Wallet

Metamask

### CPU

AMD

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9729) 512MB

### RAM

16

### Kernel Version

1.0.0-1663107759.commit-44ce947

### Unity Version

1.0.23767-20220104173406.commit-c6926e1

### Realm

fenrir

### NameTag

karenbrat#173f

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
