### ISSUE TITLE
Pilar in purplr door cant interact

### ISSUE THREAD

**Issue by U1TR4man** [decentraland/issues#254]
### What happened?

Pilar in purplr door cant interact

### Steps to reproduce

Pilar in purplr door cant interact

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Wallet

Metamask

### CPU

MacAir

### GPU

Apple M1 512MB

### RAM

32GB

### Kernel Version

1.0.0-1663107759.commit-44ce947

### Unity Version

1.0.23767-20220104173406.commit-c6926e1

### Realm

dg

### NameTag

0x8u88le#dcae

**Comment by olavra** [comment]
Hi @U1TR4man 

Could you please provide more information?

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
