### ISSUE TITLE
Shows "error" when claiming badge

### ISSUE THREAD

**Issue by DGLIU0816** [decentraland/issues#255]
### What happened?

Shows "error" when claiming badge

### Steps to reproduce

1. enter the yellow area
2. click the central yellow ball
3. through the 3 points
4. claim the badge

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Wallet

Metamask

### CPU

intel i7

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1650 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6230) 512MB

### RAM

16GB

### Kernel Version

1.0.0-1663107759.commit-44ce947

### Unity Version

1.0.23767-20220104173406.commit-c6926e1

### Realm

marvel

### NameTag

DGLIU#77ad

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client
