### ISSUE TITLE
Error while claiming Samsung 837x event

### ISSUE THREAD

**Issue by ImmortalxTiger** [decentraland/issues#256]
### What happened?

I got an error while claiming my last badge in Samsung 837x event

### Steps to reproduce

![image](https://user-images.githubusercontent.com/85162133/148548889-0b53c681-b87c-4d34-8eb2-dce01cf84542.png)

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Wallet

Metamask

### CPU

AMD Ryzen 5 3600X 6-Core Processor 3.80 GHz

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1650 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6647) 512MB

### RAM

16gb

### Kernel Version

1.0.0-1663107759.commit-44ce947

### Unity Version

1.0.23767-20220104173406.commit-c6926e1

### Realm

dg

### NameTag

ImmortalxTiger#aba7

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client
