### ISSUE TITLE
bug blocked

### ISSUE THREAD

**Issue by MaGuMa666** [decentraland/issues#257]
### What happened?

I was looking for tokens in the samsung conference room, I managed to go through the screen thinking I had found a token and I am blocked now, I wanted to let you know, thanks to you for the development meta!

### Steps to reproduce

texture change presentation screen, right mouse movement and w / jump

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Wallet

Metamask

### CPU

i3 8350k

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 3GB Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9729) 512MB

### RAM

8

### Kernel Version

1.0.0-1663107759.commit-44ce947

### Unity Version

1.0.23767-20220104173406.commit-c6926e1

### Realm

dg

### NameTag

MaGuMa#b00c

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client
