### ISSUE TITLE
Customization stage can't get badge

### ISSUE THREAD

**Issue by andrew-jr** [decentraland/issues#258]
### What happened?

Cannot retrieve final Samsung 837x badge from the Customization Stage 

### Steps to reproduce

Attempt to interact with the central pillar in the Customization Stage area, nothing happens when trying to interact. I have been told the option to "Control Lights" should appear but it does not and the badge does not appear anywhere to collect.

### Operating System

Chrome, Windows 10

### Wallet

Metamask

### CPU

AMD Ryzen 5700x

### GPU

NVIDIA EVGA Geforce GTX 1080 

### RAM

16GB

### Kernel Version

1.0.0-1663107759.commit-44ce947

### Unity Version

1.0.23767-20220104173406.commit-c6926e1

### Realm

dg

### NameTag

HoraceBellemy#4487

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
