### ISSUE TITLE
Multi-tab open Ice Poker error

### ISSUE THREAD

**Issue by Edgrateful** [decentraland/issues#259]
### What happened?

After a server update yesterday. When I switched to a different serve I am stopped from play poker by a Multi-tab open error
<img width="1677" alt="Screen Shot 2022-01-07 at 6 48 47 PM" src="https://user-images.githubusercontent.com/97354103/148652121-1dba3406-0a33-48f1-be76-3019ddb0c595.png">
.

### Steps to reproduce

On any server with my account go to any of the ice poker casinos and when it loads you will be stopped by the same erro
<img width="1677" alt="Screen Shot 2022-01-07 at 6 48 47 PM" src="https://user-images.githubusercontent.com/97354103/148652231-85825019-389c-447b-af90-fcbac1ded54d.png">
r

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

### Wallet

Metamask

### CPU

2.6 GHz Intel Core i7

### GPU

Intel HD Graphics 530 1536 MB

### RAM

16 GB 2133 MHz LPDDR3

### Kernel Version

1.0.0-1663107759.commit-44ce947

### Unity Version

1.0.23767-20220104173406.commit-c6926e1

### Realm

dg

### NameTag

ObiwanCannoli#7cfd

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client
