### ISSUE TITLE
Where´s my NFT????

### ISSUE THREAD

**Issue by PblColet** [decentraland/issues#260]
### What happened?

I crafted a hat because it no longer indicates in the description that the transaction has to be paid and after 2 days I do not have my NFT

### Steps to reproduce

Give me my NFT ??

### Operating System

Chrome/97.0.4692.71

### Wallet

Metamask

### CPU

gigabyte i7 7th gen

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7141) 512MB

### RAM

8

### Kernel Version

1.0.0-1663107759.commit-44ce947

### Unity Version

1.0.23767-20220104173406.commit-c6926e1

### Realm

España

### NameTag

PblColet#c39b

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client
