### ISSUE TITLE
我的名字ID不断自动变化，POAP无法进入钱包

### ISSUE THREAD

**Issue by JCZDUBS** [decentraland/issues#262]
### What happened?

我的名字ID不断自动变化，POAP显示处理中，但无法成功进入钱包。  -120，-15
![微信图片_20220113115448](https://user-images.githubusercontent.com/95859279/149263388-7d23c06b-8ba8-4a51-9065-ab5ceff84d8d.jpg)

https://user-images.githubusercontent.com/95859279/149263393-ac1bfe21-5f08-420f-a79c-82370f45eca5.mp4

0

### Steps to reproduce

恢复我的原始名字，JIA#185d   

恢复我顺利领取POAP到钱包的功能

### Operating System

Mozilla/5.0 (Windows NT 6.1; Win64; x64) 

### Wallet

Metamask

### CPU

I9

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 660 Direct3D11 vs_5_0 ps_5_0, D3D11-24.21.13.9882) 512MB

### RAM

32GB

### Kernel Version

1.0.0-1682491587.commit-afd06bd

### Unity Version

1.0.24303-20220111173830.commit-edbd3c9

### Realm

dg

### NameTag

jia#185d

**Comment by olavra** [comment]
Closed due to invalid formation of support request.
