### ISSUE TITLE
Cant see other players

### ISSUE THREAD

**Issue by HedrickCode** [decentraland/issues#263]
### What happened?

I have been playing for 3 weeks and i have yet to see another character model. I made a new account and i see them. Im lost please help.

### Steps to reproduce

Not a clue

### Operating System

 Chrome/97.0.4692.71 windows 10

### Wallet

Metamask

### CPU

i9 9900k

### GPU

 NVIDIA GeForce RTX 2080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9649) 512MB

### RAM

32gb

### Kernel Version

1.0.0-1694472438.commit-f32569e

### Unity Version

1.0.24406-20220112194022.commit-cad874d

### Realm

dg

### NameTag

Zackpack#38e4

**Comment by olavra** [comment]
Hi @HedrickCode,

Sorry for the late response. Is this still happening to you?

**Comment by kuruk-mm** [comment]
Closing this issue because of not having a response for two weeks.
