### ISSUE TITLE
NFT's Not Loading

### ISSUE THREAD

**Issue by Fzk-Arts** [decentraland/issues#265]
### What happened?

Good Day

I recently made a Wonderland purchase and it is yet to show in my inventory even after waiting for more than a day. This also happened with an Item I collected at an Elon Mask event around New Years. Am I no longer able to get wearables.  

### Steps to reproduce

just try making a wearable in Wonderland or getting a wearable at a POA station.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

### Wallet

Metamask

### CPU

AMD Ryzen 5 3500 6-Core Processor

### GPU

Radeon RX550/550 Series

### RAM

16GB

### Kernel Version

1.0.0-1694472438.commit-f32569e

### Unity Version

1.0.24406-20220112194022.commit-cad874d

### Realm

baldr

### NameTag

FzkArts#d8d6

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client
