### ISSUE TITLE
Although I collect all 10 rackets no POAP appears in wallet

### ISSUE THREAD

**Issue by nebulascloud** [decentraland/issues#266]
### What happened?

Although I collect all 10 rackets no POAP appears in wallet. I visit poap.xyz, connect with metamask and it is empty. Also nothing in my profile wallet.

### Steps to reproduce

Although I collect all 10 rackets no POAP appears in wallet. I visit poap.xyz, connect with metamask and it is empty. Also nothing in my profile wallet.

### Operating System

Microsoft Edge/ M1X MAX Mac OS Montery 12.0.1

### Wallet

Metamask

### CPU

Apple M1 Max

### GPU

Apple M1 Max 32 Core

### RAM

64GB

### Kernel Version

1.0.0-1694472438.commit-f32569e

### Unity Version

1.0.24406-20220112194022.commit-cad874d

### Realm

unicorn

### NameTag

ArgusHarkyn#ca99

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client
