### ISSUE TITLE
the score of dragon rush was not updated with my score

### ISSUE THREAD

**Issue by saviopagano** [decentraland/issues#267]
### What happened?

Dear Decentraland crew,
the score of dragon rush was not updated with my score. I make 55200 (wisep#a42c)

https://youtu.be/61CF1EiVcUY

I got screenshots and video if you need! 
my email is saviopagano@gmail.com

cheers

### Steps to reproduce

fix the bug with the score

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36

### Wallet

Fortmatic

### CPU

11th Gen Intel(R) Core(TM) i5-1135G7

### GPU

ANGLE (Intel, Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.9168) 512MB

### RAM

8

### Kernel Version

1.0.0-1728675769.commit-4a4b94d

### Unity Version

1.0.25106-20220119154020.commit-97a92e0

### Realm

dg

### NameTag

Wisep#a42c

**Comment by saviopagano** [comment]
again -___- for the second time

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client
