### ISSUE TITLE
Stuck on running

### ISSUE THREAD

**Issue by NiaAtreides** [decentraland/issues#268]
### What happened?

My avatar can only run, not walk. I'm on a iMac, btw

### Steps to reproduce

Try to walk

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

### Wallet

None, played as guest

### CPU

Quad-Core Intel Core i7

### GPU

AMD Radeon Pro 580 OpenGL Engine 512MB

### RAM

16gb

### Kernel Version

1.0.0-1729947058.commit-aa13346

### Unity Version

1.0.25397-20220121122726.commit-deb1f07

### Realm

dg

### NameTag

NiaAtreides#7385

**Comment by olavra** [comment]
Hi @NiaAtreides,
Is this still happening to you?
Have you tried in a different browser?
Can you make sure your Shift key is not pressed somehow?

**Comment by moliva** [comment]
Closing this issue because of not having a response for two weeks.
