### ISSUE TITLE
MISSING ETHERUM AGAIN

### ISSUE THREAD

**Issue by Blittz88** [decentraland/issues#269]
### What happened?

Same thing has happened again! Ethereum being taken out of my account for unknown reason, Gas fees were high so I went AFK, and I've come back to realise around .4 ethereum is were being taken out of my account. WHAT THE HELL IS GOING ON? Has this also been taking out funds whilst I am on playing???
![4](https://user-images.githubusercontent.com/97134831/150637745-b1530407-bade-4967-8d8f-339703375107.jpg)
![5](https://user-images.githubusercontent.com/97134831/150637747-098cb565-e931-488d-b209-faf31156e67c.jpg)
![6](https://user-images.githubusercontent.com/97134831/150637748-aa8a3ab5-69a7-4470-a764-0423ab03b798.jpg)
![7](https://user-images.githubusercontent.com/97134831/150637750-30e91716-ebe0-456c-8257-585af176bac2.jpg)
 

### Steps to reproduce

Tell me why it is taking funds out of my account whilst AFK, 

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36

### Wallet

Metamask

### CPU

AMD Ryzen 7 5800H with Radeon Graphics            3.20 GHz

### GPU

Nvidia GeForce RTX 3060

### RAM

16

### Kernel Version

1.0.0-1729947058.commit-aa13346

### Unity Version

1.0.25467-20220121232645.commit-3974cfb

### Realm

dg

### NameTag

Blittz88#bf90

**Comment by menduz** [comment]
Hello, there is no way Decentraland can make transactions on your behalf, if that would be the case, you must approve it manually for each individual transaction. 

Please make sure your wallet seed phrase is not compromised.

Check who sent the transactions that moved your funds, if that is your own address, then it is likely to be compromised. If the sender is a third party address check your allowances to the specific contract.

**Comment by Blittz88** [comment]
Hi Menduz

The contracts seem normal and looks as though I was approving them. Check the screenshots I’ve attached, it was still happening while I was getting screenshots for proof. These shots were taken within minutes of each other, my Avatar has not moved, in the same spot at the entrance of the Aquarium, Ethereum amount dropped from 0.327 – 0.135 and though DG mined is still the same at 0.0157 and surely that would had increased had I approved anything and I know for a fact that I myself did not placed down a bet at 0.070 eth or higher tonight so I don’t know how 0.14eth came to be, and I didn’t do anything with my wallet outside of Decentraland as that likely would had used MATIC to which you can is still the same amount in the other 2 shots.

AS I mentioned this incident also happened on the 21st Jan, where 0.26 Eth also went missing. Which I reported through the google DG Bug Report Form, but am still yet to get a response for that. So that makes it at least 0.65Eth gone, and that’s from just these 2 moments. I have noticed smaller amounts in the past so I started screen recording more often, and have a few screen recordings of that and other times I seemed to be ‘short’ on Ethereum all of a sudden. The file is too big for the email, is there a way I can upload to you?

Its seems to only happen within the casinos after a period of time and so far only with Eth.

You may also check the contract addresses if you like as you would likely have a better understanding to me.
https://polygonscan.com/address/0xa330F041b4e74294DbD8E08fd4ac3Fd4EDD2bF90#tokentxns

Blittz88#bF90


Get Outlook for Android<https://aka.ms/AAb9ysg>

**Comment by Blittz88** [comment]
Hello

Are you someone that can actually help?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
