### ISSUE TITLE
Issue with fruit catcher

### ISSUE THREAD

**Issue by whatismana** [decentraland/issues#270]
### What happened?

Rules state get over 1000 points to unlock chest. I scored 1390 and have not gotten a chest. 

### Steps to reproduce

Play game get over 1000 points and get no chest. 

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

### Wallet

Metamask

### CPU

Intel i7-6700k

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0, D3D11-26.21.14.3200) 512MB

### RAM

32GB

### Kernel Version

1.0.0-1729947058.commit-aa13346

### Unity Version

1.0.25467-20220121232645.commit-3974cfb

### Realm

hera

### NameTag

Quazy#93fd

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
