### ISSUE TITLE
problem with tab open in different window

### ISSUE THREAD

**Issue by Red555Rose** [decentraland/issues#271]
### What happened?

I am unable to use ice wearable and login to decentral.games/account/item.
please assist. thank you
![Screenshot 2022-01-23 000740](https://user-images.githubusercontent.com/98248464/150665804-00d82479-491c-4165-8dde-150c1adbd519.png)
.

### Steps to reproduce

Just stepping into the Ice Poker Stronghold and I will get this window of "You can't play ICE Poker in Multiple Tabs."

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0

### Wallet

Metamask

### CPU

ThinkBook 15 G3 ACL

### GPU

ANGLE (Radeon HD 3200 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.14036.8) 512MB

### RAM

24gb

### Kernel Version

1.0.0-1729947058.commit-aa13346

### Unity Version

1.0.25467-20220121232645.commit-3974cfb

### Realm

artemis

### NameTag

Sorithy2012#0841

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
