### ISSUE TITLE
DECENTRALAND GOLF CLUB BUG

### ISSUE THREAD

**Issue by DIRTYPIXELL** [decentraland/issues#272]
### What happened?

Hello, after making the league to Decentraland golf club game, when you enter the tutorial section, the ready text appears, then the internet browser gives an error because there is a problem and a white screen appears. Or if you stop at the golf club after logging in, the same error occurs, so I can't open the golf club.

### Steps to reproduce

Hello, after making the league to Decentraland golf club game, when you enter the tutorial section, the ready text appears, then the internet browser gives an error because there is a problem and a white screen appears. Or if you stop at the golf club after logging in, the same error occurs, so I can't open the golf club.

### Operating System

Chrome 97.0.4692.99

### Wallet

Metamask

### CPU

AMD Ryzen 5 3600X 6-Core Processor 

### GPU

ANGLE (AMD, AMD Radeon RX 5700 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.13033.1000) 512MB

### RAM

16

### Kernel Version

1.0.0-1729947058.commit-aa13346

### Unity Version

1.0.25467-20220121232645.commit-3974cfb

### Realm

Decentraland

### NameTag

DIRTYPIXEL#d251

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
