### ISSUE TITLE
Couldn't activate the garage at Midas Car Park 

### ISSUE THREAD

**Issue by TheOGDY-eth** [decentraland/issues#274]
### What happened?

After winning the contest and obtaining the keys, the garage could not be opened 
![image](https://user-images.githubusercontent.com/98342904/150831279-095f19d4-2c03-4736-bcfa-c2746f0d519f.png)

### Steps to reproduce

collect all the keys within 3.5 minutes. 

### Operating System

(Windows NT 10.0; Win64; x64)  Chrome

### Wallet

None, played as guest

### CPU

AMD Ryzen 5 

### GPU

NVIDIA GeForce RTX 3060 

### RAM

16

### Kernel Version

1.0.0-1739996552.commit-d48b4e5

### Unity Version

1.0.25467-20220121232645.commit-3974cfb

### Realm

dg

### NameTag

Guest#7ac3

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
