### ISSUE TITLE
If you Spin the Reel on your Slot Machine at the 5.00 accrual mark, you get a free bet. 

### ISSUE THREAD

**Issue by mgarner2** [decentraland/issues#275]
### What happened?

Spin the wheel at the same time the accrual switches from 4.83 to 5.00 and your bet is free. This is the case for 10,20,50,100.

### Steps to reproduce

Spin the wheel at the same time the accrual switches from 4.83 to 5.00 and your bet is free. This is the case for 10,20,50,100.

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Wallet

Metamask

### CPU

Mac Mini m1 2020

### GPU

Apple M1 512MB

### RAM

16GB

### Kernel Version

1.0.0-1739996552.commit-d48b4e5

### Unity Version

1.0.25467-20220121232645.commit-3974cfb

### Realm

dg

### NameTag

Mark#a276

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
