### ISSUE TITLE
Chest open with ERRoR every Time

### ISSUE THREAD

**Issue by Elgoron** [decentraland/issues#281]
### What happened?

Chest open with ERRoR every Time

at -44,57

### Steps to reproduce

start working on this fuckinggggg bugs

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36

### Wallet

Metamask

### CPU

i9

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9709) 512MB

### RAM

64

### Kernel Version

1.0.0-1752637577.commit-039d162

### Unity Version

1.0.25906-20220126232321.commit-1edbff3

### Realm

dg

### NameTag

Elgoron#9a3d

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
