### ISSUE TITLE
Running as if pressing W and A

### ISSUE THREAD

**Issue by LupusMechanicus** [decentraland/issues#282]
### What happened?

First time trying decentraland, character is running without any input. It's as if I am pressing w and a

### Steps to reproduce

log in with new character. 

### Operating System

Brave is up to date Version 1.34.81 Chromium: 97.0.4692.99 (Official Build) (64-bit)

### Wallet

Metamask

### CPU

i7 11th gen 11700k 

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7212) 512MB

### RAM

128gb

### Kernel Version

1.0.0-1752637577.commit-039d162

### Unity Version

1.0.25906-20220126232321.commit-1edbff3

### Realm

dg

### NameTag

Maschiach#e3b4

**Comment by olavra** [comment]
Hi @LupusMechanicus 

Thank you for reporting this issue.

Please could you tell us if this still happens when you close the browser and reopen it?

Could you tell us what kind of keyboard you have and if you have done something specific to activate this?

Best regards

**Comment by davidejensen** [comment]
We have applied a fix that should resolve this issue in the majority of the cases, could you verify if this is still happening to you?
If it's still happening, could you please verify that you don't have any external devices connected that could alter the input? (i.e. joysticks, steering wheels, graphics tablet, ...) 
Could you verify that you also don't have any softwares that could alter the inputs as well? (autoclickers, virtual keyboards, ...)
