### ISSUE TITLE
Staircase bug

### ISSUE THREAD

**Issue by daevif1** [decentraland/issues#284]
### What happened?

Coordinates 71, 63, there's a bug where avatars cannot go up the staircase . There's no smooth motion, and the only way to go up is to jump while moving forward.

### Steps to reproduce

Make avatars go smoothly up the stairs, in a fluent manner. 

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36

### Wallet

Metamask

### CPU

Intel i7-1185G7 11th Gen

### GPU

ANGLE (Intel, Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.9749) 512MB

### RAM

16

### Kernel Version

1.0.0-1772786810.commit-feaf312

### Unity Version

1.0.26288-20220131182725.commit-b2c586c

### Realm

dg

### NameTag

daevif#7e42

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
