### ISSUE TITLE
Bug in golfcraft game

### ISSUE THREAD

**Issue by ExpoNut1** [decentraland/issues#285]
### What happened?

After exchanging tickets for wearable ZG-10-1 AP Full body the tickets has disappeared, but no wearable added to my backpack. it happenet nearly 11:20 07/02/2022

### Steps to reproduce

I don`t know, return me the wearabe or tickets

### Operating System

Chrome/97.0.4692.99 (Windows NT 10.0; Win64; x64) 

### Wallet

Fortmatic

### CPU

ntel(R) Pentium(R) Gold G5600F CPU @ 3.90GHz   3.91 GHz

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GT 730 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671) 512MB

### RAM

8GB

### Kernel Version

1.0.0-1772786810.commit-feaf312

### Unity Version

1.0.26288-20220131182725.commit-b2c586c

### Realm

dg

### NameTag

ExpoNut#75a0

**Comment by pabloes** [comment]
You can come to Golfcraft discord to claim your FT or wearable: https://discord.com/invite/2tshKm6UzJ

This issue has been slighty improved already

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
