### ISSUE TITLE
Bug Empty Wallet 0.09 ETH

### ISSUE THREAD

**Issue by baronecampanino** [decentraland/issues#286]
### What happened?

Hi there,
in Decentraland I had uploaded an amount of Eth to play at the Taminoya casino. When I logged out in the evening I had 0.09 ETH, in the morning I reconnect and find only 0.002 ETH in my wallet. Who can help me?

### Steps to reproduce

I don't know what data I can share except all the blockchain transactions that prove the truthfulness of my words

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36

### Wallet

Metamask

### CPU

Apple M1 Pro 

### GPU

Apple M1 Pro 512MB

### RAM

16

### Kernel Version

1.0.0-1772786810.commit-feaf312

### Unity Version

1.0.26288-20220131182725.commit-b2c586c

### Realm

dg

### NameTag

Siddharta#1454

**Comment by AjimenezDCL** [comment]
You can check the transaction history in etherscan. Anyway, this not a Decentraland Client issue.
