### ISSUE TITLE
Avatar keeps moving without player input

### ISSUE THREAD

**Issue by Lootchips** [decentraland/issues#287]
### What happened?

With out using my keyboard with a new battery, after relogging in my character just keeps running! It is very hard to navigate and I cannot stand in place

### Steps to reproduce

I will send my account details and maybe you can try the to walk around as me.
![DecentralandRunError](https://user-images.githubusercontent.com/99280167/153042116-4b00b52f-766a-4e2d-90c5-7216016d51f0.png)

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36

### Wallet

Metamask

### CPU

Gigabyte 1080i

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7284) 512MB

### RAM

32

### Kernel Version

1.0.0-1772786810.commit-feaf312

### Unity Version

1.0.26878-20220204193605.commit-3bfcca9

### Realm

dg

### NameTag

Lootchips#3d18

**Comment by olavra** [comment]
Hi @Lootchips 

Thank you for reporting this issue.

Please could you tell us if this still happens when you close the browser and reopen it?

Could you tell us what kind of keyboard you have and if you have done something specific to activate this?

Best regards

**Comment by Lootchips** [comment]
I have already tried this. This still does not work

**Comment by ghost** [comment]
I have same issue.  I tried unplugging all my controllers with no luck.   When I launch in it is standing still, then I click the mouse just once and it starts running and nothing I do can stop it.   Movement keys can affect direction, same with mouse.  That is all. I just started the game and cannot play at all.

**Comment by ghost** [comment]
I am in Windows 11 with Google Chrome.

**Comment by ghost** [comment]
I was using metamask, but when I switch to guest the same thing happened.

**Comment by davidejensen** [comment]
We have recently applied a fix that should resolve this issue in the majority of the cases, could you verify if this is still happening to you?
@sunsetbrew could you verify that you don't have any sotwares that could generate any type of input as well? Like autoclickers or virtual keyboards
