### ISSUE TITLE
I have been constantly kicked out of tables with my bets inside losing more than 1k in coins

### ISSUE THREAD

**Issue by ANDRESALV1304** [decentraland/issues#288]
### What happened?

It happened a couple a times, during a call or raise or bet. It just kicked me out of the table minus my bet and money. Last one I won with two pairs and it just kicked me like I folded last second.

### Steps to reproduce

It happened a couple a times, during a call or raise or bet. It just kicked me out of the table minus my bet and money. Last one I won with two pairs and it just kicked me like I folded last second.

### Operating System

Windows 11

### Wallet

Metamask

### CPU

rayzen 7

### GPU

AMD Radeon

### RAM

16

### Kernel Version

1.0.0-1814221959.commit-9d3539b

### Unity Version

1.0.26878-20220204193605.commit-3bfcca9

### Realm

hephaestus

### NameTag

Andres#814c

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
