### ISSUE TITLE
Restarting servers koncked me out of 2 games which I was about to win

### ISSUE THREAD

**Issue by ANDRESALV1304** [decentraland/issues#289]
### What happened?

A notice of servers to restart appeared in my screen and all of the sudden the game was over, than entered again with K and 8 and knocked me out of the game for the second game. Everyone else was able to play. Next it automatically called in the 3 rd game for 100 chips that I didn't even click on.

### Steps to reproduce

A notice of servers to restart appeared in my screen and all of the sudden the game was over, than entered again with K and 8 and knocked me out of the game for the second game. Everyone else was able to play. Next it automatically called in the 3 rd game for 100 chips that I didn't even click on.

### Operating System

Edge

### Wallet

Metamask

### CPU

rayzen 7

### GPU

 AMD Radeon(TM) 

### RAM

16

### Kernel Version

1.0.0-1814221959.commit-9d3539b

### Unity Version

1.0.26878-20220204193605.commit-3bfcca9

### Realm

hephaestus

### NameTag

Andres#814c

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
