### ISSUE TITLE
Multiple tabs bug

### ISSUE THREAD

**Issue by lucasf407** [decentraland/issues#291]
### What happened?

It won't let me play because it tells me I have another tab open when I don't. please fix it

### Steps to reproduce

It won't let me play because it tells me I have another tab open when I don't. please fix it

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36

### Wallet

Metamask

### CPU

intel i5

### GPU

ANGLE (Intel, Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0, D3D11-20.19.15.4963) 512MB

### RAM

32gb

### Kernel Version

1.0.0-1814221959.commit-9d3539b

### Unity Version

1.0.27113-20220209083208.commit-f3e3c54

### Realm

dg

### NameTag

Lucas#f5fe

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
