### ISSUE TITLE
Samsung Event NFT doesn't appearing in OpenSea account

### ISSUE THREAD

**Issue by maslov1986** [decentraland/issues#292]
### What happened?

i collected all boxes according to samsung event and didn't get any NFT twice

### Steps to reproduce

1. Go to samsung location
2. Get the quest to collect boxes
3. Collect 10 boxes
4. Come back to the quest point
5. get the message with congratulation
6. in opened window type the bot code and click ok
7. get the message that you had NFT

AR
There are no NFT on opensea account

ER
You have NFT in your account

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36

### Wallet

Metamask

### CPU

Intel i7 10 gen

### GPU

ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.100.9864) 512MB

### RAM

32

### Kernel Version

1.0.0-1814221959.commit-9d3539b

### Unity Version

1.0.27113-20220209083208.commit-f3e3c54

### Realm

dg

### NameTag

NRH#4cca

**Comment by maslov1986** [comment]
The same issue was when i collected 5 boxes. NFT doesn't appearing in OpenSea

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
