### ISSUE TITLE
ice poker

### ISSUE THREAD

**Issue by carlitosg91** [decentraland/issues#293]
### What happened?

Hello, I bet allin on the flop with AA and the rival paid me but on the turn he made another bet in which I could not pay him because I had no chips, he offered me the button to raise call or fold .. the question is that I I fold the cards

### Steps to reproduce

Steps to reproduce
Describe the necessary steps we can take in order to reproduce this error.

### Operating System

google chrome  windows 10 home

### Wallet

Metamask

### CPU

intel i7 pth gen

### GPU

Geforce gtx 1650

### RAM

16gb

### Kernel Version

1.0.0-1814221959.commit-9d3539b

### Unity Version

1.0.27113-20220209083208.commit-f3e3c54

### Realm

ice game poker

### NameTag

wositoo#c339

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
