### ISSUE TITLE
samsung event bug

### ISSUE THREAD

**Issue by erfanpan** [decentraland/issues#294]
### What happened?

when i click on the tree to claim skin nothing will be happened but the item on tree disappeared please help me
![Uploading Screenshot (3943).png…]()
![Screenshot (3944)](https://user-images.githubusercontent.com/99647752/153839996-87e2e379-44e5-4154-bf33-f44bc5cd437e.png)
 

### Steps to reproduce

![Screenshot (3943)](https://user-images.githubusercontent.com/99647752/153839746-af9e1139-46d1-4827-a30c-bb4b883857f7.png)

### Operating System

chrome/i7 7700k/16g/gtx 1050ti

### Wallet

Metamask

### CPU

i7 7700k

### GPU

gtx 1050 ti

### RAM

16

### Kernel Version

1.0.0-1837492817.commit-a39eb15

### Unity Version

1.0.27113-20220209083208.commit-f3e3c54

### Realm

dg

### NameTag

erfanpan#b2a9

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
