### ISSUE TITLE
bug in game and cant claim my reward

### ISSUE THREAD

**Issue by zooze35** [decentraland/issues#295]
### What happened?

when i want to complete Samsung task (find the boxes - at least 5) i found it and the robot (central avatar gave me a spa)
i plant it in forest land (green land) near the river.
a little plant grown . and robot tell me that come back at 14 feb (valentines day)

- after exiting the game and come back a few hourse later . a first come welcome message happend in sumsung land!!! and again the robot said find at least 5 box (that look like nothing saved) but after i found 5 boxes again the robot said you planted the spa . come back 14 feb.
- and today in 14 feb when i was came back robot said go to your plant and give that love (or heart) but there is no plant on green land near the river. and there is no reward also

### Steps to reproduce

said at up

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.87 Safari/537.36

### Wallet

Metamask

### CPU

amd ryzen 9 3950x 16-core 

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6677) 512MB

### RAM

64 GB

### Kernel Version

1.0.0-1837492817.commit-a39eb15

### Unity Version

1.0.27113-20220209083208.commit-f3e3c54

### Realm

athena

### NameTag

Milad#6409

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
