### ISSUE TITLE
Decentraland Golf Map Buggggggggggg

### ISSUE THREAD

**Issue by LeviWins95** [decentraland/issues#296]
### What happened?

Golf Map from Decentraland is not working again .............. Fix it or bannnn the map.... I cant connect my walet to the map and is allways have some maps tath you can go to the top of the stage becaouse of the bugggg....

### Steps to reproduce

Bannnnn or make those who make the map owners to solve those bugsssssssss

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36

### Wallet

Metamask

### CPU

intel i9 10 th

### GPU

ANGLE (AMD, Radeon RX 5500 XT Direct3D11 vs_5_0 ps_5_0, D3D11-26.20.15029.27017) 512MB

### RAM

32

### Kernel Version

1.0.0-1837492817.commit-a39eb15

### Unity Version

1.0.27113-20220209083208.commit-f3e3c54

### Realm

dg

### NameTag

LeVIwINS#d73b

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
