### ISSUE TITLE
Builders Bug?  can not open Collectibles/ Asset pack

### ISSUE THREAD

**Issue by a0324** [decentraland/issues#297]
### What happened?

I have been unable to open Collectibles/ Asset pack  in my builder for about a month. When I try to open it, it just shows a loading circle.

Cookie refresh but not improved.

Sign in by different account but not improved.

Using different PC widndows and Mac , but not improved 

### Steps to reproduce

I want to display my NFTs in the Builder / Asset / Collectibles folder and place them in the scene.

### Operating System

chome, windows 11 (and OS 10)

### Wallet

Metamask

### CPU

11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz

### GPU

 GeForce RTX 3060 6GB

### RAM

16.0 GB

### Kernel Version

latest

### Unity Version

latest

### Realm

DG

### NameTag

ATeaMaster

**Comment by olavra** [comment]
Hi @a0324 

Which version of builder are you using? 
Web builder builder.decentraland.org?
or in-world builder.

Regards

**Comment by a0324** [comment]
Hi @olavra,
　
Using builder.decentraland.org.

Basicaly it is difficult to enter builder in world.  Frequent errors and inability to start.

Regards

**Comment by a0324** [comment]
@olavra 
Thanks It was improved.
Today I could see.
