### ISSUE TITLE
I created my NFT but it doesn't show up in my backpack.

### ISSUE THREAD

**Issue by faturamentoconecta** [decentraland/issues#298]
### What happened?

I created my NFT but it doesn't show up in my backpack. I created a WonderZone cap and it doesn't show up in my backpack, I don't know where it went. When I created the cap, a yellow star appeared and after that the nft did not appear

### Steps to reproduce

Create a wonderzone cap and receive a yellow star, after which the nft does not enter the backpack

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz   2.90 GHz

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1650 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7141) 512MB

### RAM

16,0 GB

### Kernel Version

1.0.0-1876297332.commit-9804de6

### Unity Version

1.0.28189-20220218145015.commit-b289f57

### Realm

unicorn

### NameTag

ConstanSix#75cf

**Comment by Bleujj1** [comment]
You will need to synchronize your wallet first and then you debug it

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
