### ISSUE TITLE
Can't change keyboard input

### ISSUE THREAD

**Issue by vincent-dp** [decentraland/issues#299]
### What happened?

Can't find anywhere to go azerty. No option nowhere

### Steps to reproduce

ingame nothing to do to reproduce

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36

### Wallet

Metamask

### CPU

i7

### GPU

ANGLE (NVIDIA, NVIDIA Quadro P2000 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6231) 512MB

### RAM

64gb

### Kernel Version

1.0.0-1876297332.commit-9804de6

### Unity Version

1.0.28189-20220218145015.commit-b289f57

### Realm

dg

### NameTag

vincentdeco#ec76

**Comment by AjimenezDCL** [comment]
This feature is in our backlog already, thanks for suggesting!

https://github.com/decentraland/unity-renderer/issues/72
