### ISSUE TITLE
Ban the cheaters

### ISSUE THREAD

**Issue by adamslavo** [decentraland/issues#300]
### What happened?

Hello dear developers.
Please do something with cheaters/bug abusers. I can't technically explain how they do/work  that, but i have enough game experience to understand unusual game play. 
So please pay attention to user nickname: juancho#5222
Thank you in advance.
Best regards.
Ayaz Ismayilov
email: ayaz.ismaylov91@gmail.com

### Steps to reproduce

I'm not a game developer. But i can't get any other place to report cheating

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz  

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6242) 512MB

### RAM

16gb

### Kernel Version

1.0.0-1876297332.commit-9804de6

### Unity Version

1.0.28189-20220218145015.commit-b289f57

### Realm

dg

### NameTag

yolgezer3#af79

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
