### ISSUE TITLE
ICE POKER

### ISSUE THREAD

**Issue by YuyiCS** [decentraland/issues#301]
### What happened?

I have problems to enter the game since yesterday because it tells me that it is open in multiple windows
![image](https://user-images.githubusercontent.com/100299572/155352976-54196e59-c280-46f4-a1c7-72c24da54b11.png)

### Steps to reproduce

I cleared cache, I reset the modem, I entered in another browser, I restarted the computer and it took more than 12 hours without being able to enter

### Operating System

Chrome and Brave windows 11

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-10500T CPU @ 2.30GHz   2.30 GH

### GPU

ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.9565) 512MB

### RAM

8.00 GB (7.78 GB utilizable)

### Kernel Version

1.0.0-1876297332.commit-9804de6

### Unity Version

1.0.28189-20220218145015.commit-b289f57

### Realm

marvel

### NameTag

YuyiCS#db1d

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
