### ISSUE TITLE
I was stuck here

### ISSUE THREAD

**Issue by ggsimon** [decentraland/issues#302]
### What happened?

when I was going to upstair, I don't know what happened and I was stucked here. 
![图片](https://user-images.githubusercontent.com/15527379/155519141-bf102ea4-0302-4e65-8fd4-81be0355de97.png)

### Steps to reproduce

![图片](https://user-images.githubusercontent.com/15527379/155519123-93a19962-15e7-46fb-bfb8-9e969c5193a7.png)

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0

### Wallet

Metamask

### CPU

Inter i9 10 generation

### GPU

ANGLE (Intel(R) HD Graphics 400 Direct3D11 vs_5_0 ps_5_0, D3D11-25.20.100.6472) 512MB

### RAM

32GB

### Kernel Version

1.0.0-1876297332.commit-9804de6

### Unity Version

1.0.28189-20220218145015.commit-b289f57

### Realm

dg

### NameTag

gg#2d4d

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
