### ISSUE TITLE
ICE Poker Chips refund

### ISSUE THREAD

**Issue by brooklynzoo22** [decentraland/issues#304]
[###]() What happened?

Luckily have the screenshot of start of the round, had AQ on my hand POT on flop was 740chips, on the TURN I raised 370 chips 1/2pot and other player folded. Cards dissapeared and I never had my chips. This happened at 02:56 (GMT +4) 26.01.2022.
![274578308_681846599730996_2762994430341273619_n](https://user-images.githubusercontent.com/100449943/155817119-cc7c12d6-c691-4c88-a8e9-cfe22d1e2134.jpg)

### Steps to reproduce

Please refund lost 1110 chips or equal Ices for next day. Thank you in advance.

### Operating System

Chrome/98.0.4758.102

### Wallet

Metamask

### CPU

Intel i5 CORE

### GPU

ANGLE (Intel, Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0, D3D11-20.19.15.5126) 512MB

### RAM

8GB

### Kernel Version

1.0.0-1876297332.commit-9804de6

### Unity Version

1.0.28189-20220218145015.commit-b289f57

### Realm

marvel

### NameTag

brooklynzoo#c4ec

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
