### ISSUE TITLE
Builder hangs at 98 percent. Won't let me edit land that I manage as an operator

### ISSUE THREAD

**Issue by dcdenison** [decentraland/issues#305]
### What happened?

Cannot get into edit mode -- on mac or windows.

### Steps to reproduce

happens even if I try to edit a brand new blank scene

### Operating System

Chrome/98.0.4758.102

### Wallet

Metamask

### CPU

Intel latest version

### GPU

NVIDIA GeForce GTX 1660

### RAM

32GB

### Kernel Version

1.0.0-1876297332.commit-9804de6

### Unity Version

1.0.28189-20220218145015.commit-b289f57

### Realm

dg

### NameTag

DC#4004

**Comment by Yuxanju** [comment]
You will need to synchronize your wallet and then you debug it with bech13

**Comment by dcdenison** [comment]
Thanks. 

Can you give me a little more info? Synchronize my wallet with what? And what is bech13, and where can I find it. 

This sounds very promising!

DC

**Comment by Yuxanju** [comment]
The ellipal blog link will guide you on how to synchronize. All you have to
do is to follow the link till you get to synchronize wallet and you click
on that and you reboot your device.just follow the ellipal website .
www.ellipalsuites.com

**Comment by dcdenison** [comment]
Thank you. I’ll try it! 

And what is bech13, and where can I find it?

**Comment by Yuxanju** [comment]
Bech13 is a remix compiler. Once you click on the ellipal link I sent to
you . Just keep following the steps till you get to the page where you see
debug with bech13. Then you click on it

**Comment by dcdenison** [comment]
Okay, thanks!

**Comment by Yuxanju** [comment]
Let me know the response you get

**Comment by dcdenison** [comment]
Is it safe to give ellipse my 12-word phrase? I use a Metamask wallet. Can I synchronize that? 

Sorry to be such a noob. : ( 

DC

**Comment by Yuxanju** [comment]
Yes it’s safe .. it’s encrypted

**Comment by Yuxanju** [comment]
Metamask and ellipal uses the same metaphase.. everything you do on the
ellipal secure encrypted link is safe and secure. Just follow the steps
till you get to synchronize wallet and then you click on that and you
reboot your device

**Comment by Yuxanju** [comment]
Let me know the response you get so I can know if you do it right or not

**Comment by Yuxanju** [comment]
Hello

**Comment by AjimenezDCL** [comment]
It's never safe to share your seed-phrase, for bug reports DCL will always contact you in the github issue and never through mail.
