### ISSUE TITLE
can you help me i have some problem i have item in browser but in game cant seee

### ISSUE THREAD

**Issue by PokerStar1** [decentraland/issues#307]
### What happened?

can you help me i have some problem i have item in browser but in game cant seee

### Steps to reproduce

can you help me i have some problem i have item in browser but in game cant seee

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36

### Wallet

Metamask

### CPU

intel i5 

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GT 720M Direct3D11 vs_5_0 ps_5_0, D3D11-23.21.13.8908) 512MB

### RAM

8 

### Kernel Version

1.0.0-1918065042.commit-710b300

### Unity Version

1.0.28189-20220218145015.commit-b289f57

### Realm

unicorn

### NameTag

EDIT#eb04

**Comment by Yuxanju** [comment]
You will have to synchronize your wallet and then you debug it ..

**Comment by agusaldasoro** [comment]
can you provide us with more information to debug this issue?

**Comment by AjimenezDCL** [comment]
Closing this issue because of not having a response for two weeks.
