### ISSUE TITLE
extra chips on chekin

### ISSUE THREAD

**Issue by gendze** [decentraland/issues#309]
### What happened?

hello i checked in and i have 5.5k chips instead of 3000. check it please and inform me what to do i want to start playing but i dont want extra chips i prefer to play fairy 

### Steps to reproduce

i dont know

### Operating System

microsoft edge

### Wallet

Metamask

### CPU

lenovo thinkpad

### GPU

ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.15026.5002) 512MB

### RAM

32gb

### Kernel Version

1.0.0-1928584197.commit-b86632b

### Unity Version

1.0.28189-20220218145015.commit-b289f57

### Realm

artemis

### NameTag

venom#2ce8

**Comment by agusaldasoro** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
