### ISSUE TITLE
Ice Poker glitch

### ISSUE THREAD

**Issue by heartache9999** [decentraland/issues#310]
### What happened?

There is a big glitch on my Ice Poker History for March 5.  It shows impossibly huge amount of chips lost but in the gameplay breakdown for March 5, I ended in the Top 40%.  Because of this glitch, when I enter any poker room I see an error message that says "You have reached the maximum amount of chips lost" and I can't check in when delegated.  Also, the 208 ICE which was my rewards for March 5 was never placed in my account for me to claim.  Please look into this and see if this can fixed.  Thank you. 
![ice poker - 3-5-2022 - gameplay history](https://user-images.githubusercontent.com/15687067/157381546-bc6a15a7-0fde-4659-8388-0c4bf9c401d0.jpg)
![ice poker - 3-5-2022 - gameplay breakdown](https://user-images.githubusercontent.com/15687067/157381598-5c42b8fe-eebd-40f4-94ea-5021abe557d6.jpg)
 

### Steps to reproduce

Screenshots of gameplay history and gameplay breakdown and screenshots from actual poker rooms for March 5.
Time of day in the poker rooms screenshots are EST.  
I was up to Top 10% and was trying for Top 5% but in the last hour or so I slipped to Top 40% but it's impossible that I could have lost the huge numbers show in the gameplay history. 
Error Message was first seen the next day on March 6.

![ice poker - 3-5-2022 - gameplay history](https://user-images.githubusercontent.com/15687067/157381647-49b65dcb-3861-402d-999c-8ab4d2fc66f3.jpg)
![ice poker - 3-5-2022 - gameplay breakdown](https://user-images.githubusercontent.com/15687067/157381661-cea8305c-fba5-4438-bc38-c872d57aeb73.jpg)
![ice poker - 3-5-2022 - play 1](https://user-images.githubusercontent.com/15687067/157384435-a9bb9828-46e7-4d5b-b655-c5e87476c711.jpg)
![ice poker - 3-5-2022 - play 2](https://user-images.githubusercontent.com/15687067/157384444-c65b1d97-a19e-4336-8c19-eb97d2ccd1b0.jpg)

![ice poker - 3-6-2022 - play 3](https://user-images.githubusercontent.com/15687067/157387814-e92171dc-d520-410f-9003-45516a64ba1a.jpg)

### Operating System

Chrome, Windows 11

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz   3.19 GHz

### GPU

NVIDIA GeForce GTX 1060 6GB

### RAM

16.0 GB (15.8 GB usable)

### Kernel Version

1.0.0-1945586917.commit-f8e2ae5

### Unity Version

1.0.29096-20220308082410.commit-3e064b2

### Realm

loki - later on in baldr

### NameTag

heartache#517c

**Comment by agusaldasoro** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
