### ISSUE TITLE
always error

### ISSUE THREAD

**Issue by pichst** [decentraland/issues#311]
### What happened?

i dont know my acc always respond . i just play only me why always repond...? how to change password in decentraland 

### Steps to reproduce

i dont know my acc always respond . i just play only me why always repond...? how to change password in decentraland 

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36

### Wallet

Metamask

### CPU

Intel I9

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6089) 512MB

### RAM

32

### Kernel Version

1.0.0-1959721167.commit-e8e7260

### Unity Version

1.0.29096-20220308082410.commit-3e064b2

### Realm

dg

### NameTag

PichST#de1c

**Comment by agusaldasoro** [comment]
can you provide us with more information to debug this issue?

**Comment by AjimenezDCL** [comment]
Closing this issue because of not having a response for two weeks.
