### ISSUE TITLE
missing chips despite winning a hand

### ISSUE THREAD

**Issue by MAXKAZ8** [decentraland/issues#312]
### What happened?

Hey! I got a bug. I won the hand and my chips were debited. Can something be done about this? My account is MAXKAZ#711b 
![Снимок экрана 2022-03-12 092941](https://user-images.githubusercontent.com/101450986/158010511-0b5b0ba9-403e-47be-a00a-0dcb426821ec.png)

### Steps to reproduce

I want my chips back. Better and win too

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36

### Wallet

Metamask

### CPU

AMD RYZEN 5000 

### GPU

ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.13014.4003) 512MB

### RAM

20GB

### Kernel Version

1.0.0-1970282103.commit-16f79be

### Unity Version

1.0.29457-20220310165850.commit-c416ce4

### Realm

dg

### NameTag

MAXKAZ#711b

**Comment by agusaldasoro** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
