### ISSUE TITLE
no reward no me dieron el premio canjEADO 

### ISSUE THREAD

**Issue by juanc8532** [decentraland/issues#313]
### What happened?

buenas estaba en wondermine juntando materiales para canjear por un producto de la maquina .los junte los 3 wcoins fui a la maquina a canjearlo y cuando porngo para craftear el gorro rosa ., me saca los coins y no me da el gorro y ensima se resta de la cantidad que habia en el lote de rewards nesecito una solucion o reposicion del dicha prenda gracias 

### Steps to reproduce

buenas estaba en wondermine juntando materiales para canjear por un producto de la maquina .los junte los 3 wcoins fui a la maquina a canjearlo y cuando porngo para craftear el gorro rosa ., me saca los coins y no me da el gorro y ensima se resta de la cantidad que habia en el lote de rewards nesecito una solucion o reposicion del dicha prenda gracias 

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36

### Wallet

Metamask

### CPU

ryzen5

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GT 710 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7298) 512MB

### RAM

8

### Kernel Version

1.0.0-1970282103.commit-16f79be

### Unity Version

1.0.29457-20220310165850.commit-c416ce4

### Realm

dg

### NameTag

juanc#4766

**Comment by tupungatog** [comment]
Hola consulta lo reclamaste por esta pagina? https://wondermine.wonderzone.io/ , entra con tu billetera metamask en la red de poligon y luego de reclamado lo veras en tu mochila o inventario, a mi me paso igual que a ti.

**Comment by agusaldasoro** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
