### ISSUE TITLE
glitch

### ISSUE THREAD

**Issue by JDS007** [decentraland/issues#314]
### What happened?

my name titles keep changing

### Steps to reproduce

why does my name title say 3/15 ? 15 different names keep appearing as my name..

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36

### Wallet

Metamask

### CPU

intel i9 10th generation

### GPU

ANGLE (NVIDIA, NVIDIA Quadro P620 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5148) 512MB

### RAM

32GB

### Kernel Version

1.0.0-1970282103.commit-16f79be

### Unity Version

1.0.29457-20220310165850.commit-c416ce4

### Realm

unicorn

### NameTag

Snake#4843

**Comment by agusaldasoro** [comment]
can you provide us with more information to debug this issue?

**Comment by AjimenezDCL** [comment]
Closing this issue because of not having a response for two weeks
