### ISSUE TITLE
Could play all day long, could finish any game nor challenge due to lag and repetitive dropouts

### ISSUE THREAD

**Issue by ANDRESALV1304** [decentraland/issues#315]
### What happened?

Could play all day long, could finish any game nor challenge due to lag and repetitive dropouts

### Steps to reproduce

Could play all day long, could finish any game nor challenge due to lag and repetitive dropouts

### Operating System

Windows 11

### Wallet

Metamask

### CPU

rayzen 7

### GPU

ANGLE (AMD, AMD Radeon(TM) 

### RAM

16

### Kernel Version

1.0.0-1970282103.commit-16f79be

### Unity Version

1.0.29457-20220310165850.commit-c416ce4

### Realm

dg

### NameTag

Andres#814c

**Comment by agusaldasoro** [comment]
can you provide us with more information to debug this issue?

**Comment by AjimenezDCL** [comment]
Closing this issue because of not having a response for two weeks.
