### ISSUE TITLE
injustice

### ISSUE THREAD

**Issue by Mauyuyal** [decentraland/issues#316]
### What happened?

I just bet on an all-in of 400 chips and I go all-in of 1600 chips, I win the hand with a straight, and the player who lost walks away from the table and there they gave me the hand as lost and it became negative not only the 400 of him but the remaining 1200 of mine. two days ago 3200 chips disappeared in the same way please!!!!!!!!!!
What can I do where I complain?

### Steps to reproduce

I just bet on an all-in of 400 chips and I go all-in of 1600 chips, I win the hand with a straight, and the player who lost walks away from the table and there they gave me the hand as lost and it became negative not only the 400 of him but the remaining 1200 of mine. two days ago 3200 chips disappeared in the same way please!!!!!!!!!!

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36

### Wallet

Metamask

### CPU

Dell

### GPU

ANGLE (Intel, Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.9664) 512MB

### RAM

8GB

### Kernel Version

1.0.0-1990570041.commit-c77c4c3

### Unity Version

1.0.29457-20220310165850.commit-c416ce4

### Realm

hela

### NameTag

Mauyuyal#cb32

**Comment by agusaldasoro** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
