### ISSUE TITLE
cant see chips

### ISSUE THREAD

**Issue by vallanzasca** [decentraland/issues#317]
### What happened?

hello,i was playing and there appeared window (unauthorized client error,reach out support) help me if u can

### Steps to reproduce

hello,i was playing and there appeared window (unauthorized client error,reach out support) help me if u can

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36

### Wallet

Metamask

### CPU

i5 9400f

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671) 512MB

### RAM

16

### Kernel Version

1.0.0-1990570041.commit-c77c4c3

### Unity Version

1.0.29457-20220310165850.commit-c416ce4

### Realm

unicorn

### NameTag

medgradanalshi#2088

**Comment by agusaldasoro** [comment]
can you provide us with more information to debug this issue?

**Comment by AjimenezDCL** [comment]
Closing this issue because of not having a response for two weeks.
