### ISSUE TITLE
chip count displayed incorrectly

### ISSUE THREAD

**Issue by MAXKAZ8** [decentraland/issues#318]
### What happened?

not yet sat down at the table but already a negative score

### Steps to reproduce

![Снимок экрана 2022-03-20 114900](https://user-images.githubusercontent.com/101450986/159158852-429c5990-dd2c-439e-a769-ce8fb4bf10cb.png)

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36

### Wallet

Metamask

### CPU

AMD RYZEN 5000 

### GPU

ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.13014.10001) 512MB

### RAM

20GB

### Kernel Version

1.0.0-2004224613.commit-89c15c2

### Unity Version

1.0.29457-20220310165850.commit-c416ce4

### Realm

dg

### NameTag

MAXKAZ#711b

**Comment by agusaldasoro** [comment]
https://github.com/decentraland/issues/issues/321
