### ISSUE TITLE
Chips, Wearable, Multiplier and Selecting Realm not showing.

### ISSUE THREAD

**Issue by ajayxmagtoto** [decentraland/issues#319]
### What happened?

I just refreshed my browser then the bug happens.

### Steps to reproduce

Tried to clear cache and cookies, did try to create a new account without wearable and tried using another browser but issue not being fixed.

### Operating System

Google Chrome

### Wallet

Metamask

### CPU

intel core i5

### GPU

N/A

### RAM

64GB

### Kernel Version

1.0.0-2036429826.commit-e96a984

### Unity Version

1.0.31222-20220325162755.commit-e197ab1

### Realm

dg

### NameTag

Waw#9477

**Comment by pravusjif** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
