### ISSUE TITLE
Quest does not complete

### ISSUE THREAD

**Issue by jffuriscal** [decentraland/issues#32]
### What happened?

Quest in ethermon does not complete. it only shows 7/8, 9/10, 9/10 for killing slime, digging and planting respectively

### Steps to reproduce

1. Kill 8 or more slimes, check if quest is completed
2. Dig 10 or more times, check if quest is completed
3. Plant 10 or more, check if quest is completed

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36

### Wallet

Metamask

### CPU

intel i7

### GPU

Intel Iris OpenGL Engine 512MB

### RAM

16GB

### Kernel Version

1.0.0-1255409905.commit-20a69d2

### Unity Version

1.0.14045-20210921135352.commit-cce13a0

### Realm

unicorn

### NameTag

Joe#8967

**Comment by moliva** [comment]
Hi @jffuriscal !
Sorry for the delay. This feature is currently disabled in the platform.
Thanks for reporting!
