### ISSUE TITLE
Error en bonus de minado

### ISSUE THREAD

**Issue by tupungatog** [decentraland/issues#321]
### What happened?

Hola, no me sube el bonus de minado con el suéter de invierno y la gorra, antes si subía si me lo colocaba, ahora no sube el 2% de cada uno he probado de todo.

### Steps to reproduce

colocarse el suéter de invierno o gorra actualizar con F5 y tiene que subir el bonus de minado el cual no me sube, antes si subía ahora no.

### Operating System

crome Versión 99.0.4844.82 (Build oficial) (64 bits)     

### Wallet

Metamask

### CPU

(AMD Ryzen 7 3700X 8-Core Processor  3.59 GHz)

### GPU

ANGLE (AMD, Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.13023.4001) 512MB

### RAM

16,0 GB

### Kernel Version

1.0.0-2052512970.commit-016ce7c

### Unity Version

1.0.31286-20220326153912.commit-55b9e15

### Realm

dg

### NameTag

Gustavo#0d9e

**Comment by agusaldasoro** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
