### ISSUE TITLE
Decentraland

### ISSUE THREAD

**Issue by alishmoz** [decentraland/issues#322]
### What happened?

Hi,I'm Alishmoz
when I play in dragon rush my dragon fly in to a mountain and i can't fly and play with dragon to get score.

![Screenshot (276)](https://user-images.githubusercontent.com/102727384/161019054-bc8f4fdf-8c86-48c8-86df-9d37aaa6da57.png)

### Steps to reproduce

I think decentraland should make an app and fix the Metaverse with new programmer and new graphic to get better.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36

### Wallet

Metamask

### CPU

intel i7

### GPU

ANGLE (Intel, Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

8

### Kernel Version

1.0.0-2060496377.commit-e84fd6b

### Unity Version

1.0.31286-20220326153912.commit-55b9e15

### Realm

unicorn

### NameTag

khoda#c241

**Comment by agusaldasoro** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
