### ISSUE TITLE
Hard to find a table

### ISSUE THREAD

**Issue by Puchiepuchiechu** [decentraland/issues#323]
### What happened?

Everytime i go to a server, it takes forever to find a table in Poker. Then once a table is available, it has only 1 person waiting. Also there's a glitch wherein, i would confirm to buy in, but it routes me back to "table 1". My friends are also experiencing the same. I've been 24 hours awake now, and i cant play poker still. I also have noticed, there's a lot of free tables with only 3 playing, but the automatic seating would not route me there, instead it finds an empty table and routes me there to sit. And i have no choice but to wait, and there would be no opponent or other player after an hour. :( 👎 

Please have this removed or at least fix it so that we all can play. 

### Steps to reproduce

Please fix the automatic seating. You can also remove it. Please 

i wanna play poker. 

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36

### Wallet

Metamask

### CPU

i5

### GPU

ANGLE (AMD, AMD Radeon(TM) Vega 11 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

8

### Kernel Version

1.0.0-2060496377.commit-e84fd6b

### Unity Version

1.0.31286-20220326153912.commit-55b9e15

### Realm

dg

### NameTag

Patwisa#4927

**Comment by agusaldasoro** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
