### ISSUE TITLE
Playing on Multiple Tabs false alert

### ISSUE THREAD

**Issue by OGBrownMan** [decentraland/issues#324]
### What happened?

I keep getting denied from playing because it states im playing on multiple devices while im only playing on one. Any way to fix this? Ive made sure all my tabs are closed except for this one; I've restarted my computer and the problem still occurs. 

### Steps to reproduce

Not let this alert pop up when i only have one tab open

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36

### Wallet

Metamask

### CPU

Intel i7

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9649) 512MB

### RAM

16GB

### Kernel Version

1.0.0-2071407489.commit-9b51f8e

### Unity Version

1.0.31900-20220331144233.commit-708fd3d

### Realm

artemis

### NameTag

OGBrownMan#6573

**Comment by agusaldasoro** [comment]
Duplicated of https://github.com/decentraland/sdk/issues/343
