### ISSUE TITLE
"You can't play ICE Poker in multiple tabs" error 

### ISSUE THREAD

**Issue by paulcicio** [decentraland/issues#325]
### What happened?

I randomly got an "You can't play ICE Poker in multiple tabs" error, even though I didn't had multiple tabs. I tried several workarounds (opening a second tab with the same URL and then close one of them, log out and relogin, restart, shutdown, even playing on another laptop), nothing seems to do the trick. 
 

### Steps to reproduce

No clear steps to reproduce, I was playing ICE Poker, took a short break and when I returned, I saw the "You can't play ICE Poker in multiple tabs" error message, then I wasn't able to play anymore

### Operating System

Google Chrome Version 99.0.4844.84 (Official Build) (64-bit)

### Wallet

Metamask

### CPU

Intel Core i5 vPro

### GPU

ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.9168) 512MB

### RAM

32 Gb

### Kernel Version

1.0.0-2071407489.commit-9b51f8e

### Unity Version

1.0.31900-20220331144233.commit-708fd3d

### Realm

unicorn

### NameTag

PaulC#783a

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client
