### ISSUE TITLE
Minning bonus is fake?

### ISSUE THREAD

**Issue by srdrBABA** [decentraland/issues#326]
### What happened?

i made wearable nft. bonuses are wrong it should be 53, but now 49.   ( i am turk player ) english bad sorry :)

46 bonusum vardı, 3 adet nft yaptım ve 53 olması lazımken 49 gösteriyor. lütfen yardımcı olur musunuz

### Steps to reproduce

Biraz takip etmeniz gerekiyor. follow game please

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36

### Wallet

Metamask

### CPU

ryze 5 2600

### GPU

ANGLE (AMD, Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14029.5006) 512MB

### RAM

8

### Kernel Version

1.0.0-2098154396.commit-22a0cf9

### Unity Version

1.0.31900-20220331144233.commit-708fd3d

### Realm

dg

### NameTag

Mandril#570d

**Comment by LautaroPetaccio** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
