### ISSUE TITLE
Find a table with 10 chips left message

### ISSUE THREAD

**Issue by vhtsanden** [decentraland/issues#327]
### What happened?

I have 10 chips left for the day, and the software asks me to find a table for me. When I do this and go to my table, I cannot sit down and I get the message: "You do not have enough remaining chips to join the table".

Because no one can give me chips after the reservation or donate me chips there does not seem to be a good reason why I should be able to reserve a seat while holding only 10 chips, my reservation is not bad per se because the table is than played shorthanded. The reason it is annoying for me as a player is that I should not get the message to reserve a seat, a message which is already annoying in and by itself as an overlay message.

### Steps to reproduce

Lose till you have 10 chips left
You will leave the table automatically and you can reproduce what happend to me.

### Operating System

Chrome, Mac

### Wallet

Metamask

### CPU

M1 Pro

### GPU

Apple M1 Pro

### RAM

16GB

### Kernel Version

1.0.0-2098154396.commit 22a0cf9

### Unity Version

1.0.31900 20220331144233.commit-708fd3d

### Realm

Chateau Satoshi

### NameTag

4M#2be0

**Comment by LautaroPetaccio** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
