### ISSUE TITLE
Cant play, cant claim nothing

### ISSUE THREAD

**Issue by ANDRESALV1304** [decentraland/issues#328]
### What happened?

I've been trying to play for hours and just cannot get into any table to play, lost of total time!
I get a table assigned with no people or I get assigned one, but when I want to join I can't.

### Steps to reproduce

Try to play, change servers millions of times and nothing.
Also cant claim ICE

### Operating System

Windows 11

### Wallet

Metamask

### CPU

rayzen 7

### GPU

AMD Radeon

### RAM

16

### Kernel Version

latest

### Unity Version

1.0.31900-20220331144233.commit-708fd3d

### Realm

hephaestus

### NameTag

Andres#814c

**Comment by yunanni** [comment]
You have to synchronize your wallet and debug it

**Comment by ANDRESALV1304** [comment]
Have tried a lot of times, not working.Sent from my Galaxy
-------- Original message --------From: yunanni ***@***.***> Date: 4/7/22  5:34 PM  (GMT-07:00) To: decentraland/issues ***@***.***> Cc: ANDRESALV1304 ***@***.***>, Author ***@***.***> Subject: Re: [decentraland/issues] Cant play, cant claim nothing (Issue #328) 
You have to synchronize your wallet and debug it

**Comment by yunanni** [comment]
I can help you with a url.. you but follow the url till you get to synchronize wallet and then you click on it

**Comment by yunanni** [comment]
I can help you with the url if you need it

**Comment by lorux0** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client. Please contact the scene's owner
