### ISSUE TITLE
3 times this week I lost over 400 ICE at least me and my delegator

### ISSUE THREAD

**Issue by ANDRESALV1304** [decentraland/issues#329]
### What happened?

Due to all the bugs that have been going on, 3 times this week I haven't been able to play. Nor finish the daily challenges.
I asked for help, but nothing really worked. It is not fair at this point I have been very patient, but I am so done now, this is just a headache for me at this point, and also a lot of fights with the person who is delegating to me.

### Steps to reproduce

I don't know, there are a lot of bugs, from trying to get a table, changing servers. Not able to play because of another apparent session on. Not been able to claim rewards. Black screen, kicked out a table. It is just a lot.

### Operating System

Windows 11

### Wallet

Metamask

### CPU

rayzen 7

### GPU

AMD Radeon

### RAM

16

### Kernel Version

1.0.0-2141827118.commit-450c363

### Unity Version

1.0.31900-20220331144233.commit-708fd3d

### Realm

loki

### NameTag

Andres#814c

**Comment by LautaroPetaccio** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
