### ISSUE TITLE
New Quest available popup shows for not reason

### ISSUE THREAD

**Issue by olavra** [decentraland/issues#33]
### What happened?

As you walk, teleport or basically do nothing, the "New quest available" pop-up appears. This popup should only appear when the players finds a new quest.

### Steps to reproduce

Randomly teleport to different locations, it will eventually happen

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.54 Safari/537.36

### Wallet

Metamask

### CPU

Intel i7

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7141) 512MB

### RAM

32GB

### Kernel Version

1.0.0-1263611010.commit-3a42e8e

### Unity Version

1.0.14134-20210921210431.commit-a9209b8

### Realm

loki

### NameTag

olavra

**Comment by moliva** [comment]
Closing as this feature is no longer enabled in the platform.
