### ISSUE TITLE
Avartar Wont stop Running

### ISSUE THREAD

**Issue by NoiiNoii** [decentraland/issues#330]
### What happened?

My avatar will randomly start to run and won't stop. Even if I close the system and come back a few days later. Sometimes he is fine and other time it will start again. My shift key is not stuck down either. 

### Steps to reproduce

Click any mouse button.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36 Edg/100.0.1185.36

### Wallet

Metamask

### CPU

Intel i9 10th generation

### GPU

ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

32GB

### Kernel Version

1.0.0-2149292527.commit-b323b2d

### Unity Version

1.0.31900-20220331144233.commit-708fd3d

### Realm

odin

### NameTag

NoiiNoii#8e80

**Comment by JorgeDecentraland** [comment]
Hello @NoiiNoii, can you confirm if this is still happening, please? If it does, are you using any external peripherals that could be bringing an input signal, like gamepads or tablets?

**Comment by endiverse** [comment]
I have this same problem.  I don't know of what perpiheral could be causing this..
It does the same thing in Unity.  If I start a unity game it goes hard left, wont stop....  If I stop the game and start it again,  The second time I start the game it all works fine!!  I decentraland, everytime i start it, my avatar is just running..  it wont stop.

**Comment by lorux0** [comment]
this is a duplicated report from [#2600](https://github.com/decentraland/unity-renderer/issues/2600)
