### ISSUE TITLE
Chips not taken into account for multiplier

### ISSUE THREAD

**Issue by paulcicio** [decentraland/issues#332]
### What happened?

I've won the last hand, just before the 2:00 AM deadline, a hand with 3 players all-in, I got the confirmation that I won the 3078 chips for the respective hand, but my balance was not updated and the chips were not taken into account for the multiplier

### Steps to reproduce

Win the last hand before the deadline
Chips balance was not updated accordingly, multiplier was not modified

### Operating System

Google Chrome Version 99.0.4844.84 (Official Build) (64-bit)

### Wallet

Metamask

### CPU

Intel Core i5 vPro

### GPU

Nvidia 980 TI

### RAM

32 Gb

### Kernel Version

latest

### Unity Version

latest

### Realm

fenrir

### NameTag

PaulC#783a

**Comment by LautaroPetaccio** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client. Please contact the scene owner to resolve this issue.
