### ISSUE TITLE
location -26-67

### ISSUE THREAD

**Issue by sepehrnb** [decentraland/issues#334]
### What happened?

My character is stuck behind the scenes

### Steps to reproduce

This is the second time this has happened in different places

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36

### Wallet

Wallet Connect

### CPU

ore(TM) i7-4720HQ CPU

### GPU

ANGLE (Intel, Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

16gb

### Kernel Version

1.0.0-2189800740.commit-1ab8e83

### Unity Version

1.0.32838-20220415090933.commit-43530d2

### Realm

baldr

### NameTag

amoo3pehr#e467

**Comment by LautaroPetaccio** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
