### ISSUE TITLE
Chips not acrediting after winning 

### ISSUE THREAD

**Issue by dregli14** [decentraland/issues#336]
### What happened?

This has happened 2 times now. I go all in, win the hand, then no chips gets accredited. So frustrating I completed the google form, talked to DG support. I lost wereable delegator because of it. Please help me here this software is killing me 
![Other player](https://user-images.githubusercontent.com/38593071/164996611-8d46ab2e-f685-448c-a52d-f239b7a0d7db.jpg)
![Poker table](https://user-images.githubusercontent.com/38593071/164996614-c41a4702-1a79-4a63-bffe-bd5dbaa02f41.jpg)
![Hand history bug](https://user-images.githubusercontent.com/38593071/164996624-c4157cd0-f31c-4527-b12f-3113ed406700.jpg)
This one is just from now
![image](https://user-images.githubusercontent.com/38593071/164996628-c178cf36-d57f-41ba-8c28-e88b34d25bc6.png)

### Steps to reproduce

I don't know im not a programer. Just compensate my ICE loses from an average of my daily performance and admit the error to my delegator I let down 

### Operating System

Chrome Windows 11

### Wallet

Metamask

### CPU

I7

### GPU

I dont know 

### RAM

16

### Kernel Version

1.0.0-2189800740.commit-1ab8e83

### Unity Version

1.0.32838-20220415090933.commit-43530d2

### Realm

hela

### NameTag

ILOVECARECA#85f2

**Comment by jmoguilevsky** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
