### ISSUE TITLE
Land not loading

### ISSUE THREAD

**Issue by ryaine** [decentraland/issues#337]
### What happened?

I have uninstall and reinstall many times and the graphics and map of the game is not loading 

### Steps to reproduce

i have no idea

### Operating System

Windows 10  (10.0.19042) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 5500U with Radeon Graphics 

### GPU

AMD Radeon(TM) Graphics 3002MB

### RAM

6005MB

### Kernel Version

1.0.0-2189800740.commit-1ab8e83

### Unity Version

desktop-main.commit-7b08a86

### Realm

dg

### NameTag

ryaine#d8b1

**Comment by lorux0** [comment]
could you specify what are the things you cannot see? can you see 3d world objects?
is this issue still happening to you?

**Comment by AjimenezDCL** [comment]
Closing this issue because of not having a response for two weeks.
