### ISSUE TITLE
Poligonal coin hunt quest bug

### ISSUE THREAD

**Issue by ghost** [decentraland/issues#34]
### What happened?

I have done quest poligonal coin hunt, but then i entered again the game this quest have not done, i need jump to it again and after all automatic marks as done, but after i exit and again in the all happen again

### Steps to reproduce

1. Enter the metamask
2. Enter the game
3.  Choose Poligon coin hunt, then press - Jump in
4. After pess logout
5. Enter again

### Operating System

Version 94.0.4606.54 (Official Build) (64-bit) Win64; x64)

### Wallet

Metamask

### CPU

Intel Xeon Gold 6132 26 Ghz

### GPU

ANGLE (NVIDIA, NVIDIA GRID GTX P40-6 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7111) 512MB

### RAM

28

### Kernel Version

1.0.0-1270687252.commit-ac7d7a7

### Unity Version

1.0.14532-20210924152610.commit-2aac923

### Realm

loki

### NameTag

Nyar#71fe

**Comment by moliva** [comment]
Hi @yar41ik !
Sorry for the delay. This feature is currently disabled in the platform.
Thanks for reporting!
