### ISSUE TITLE
Tab Issue

### ISSUE THREAD

**Issue by Cliveybhoy37** [decentraland/issues#344]
### What happened?

Can't play ice poker in multipile tabs open, though i only have one tab open
![TabIssue](https://user-images.githubusercontent.com/87447940/165596222-6866c526-ab8c-4722-9d6b-58d3ca1b0acf.png)
 

### Steps to reproduce

Login into DCL,
Click Places Tab,
click tominoya,
Loads then shows issue to close Tab,

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36

### Wallet

Metamask

### CPU

3.2 GHz Quad-Core Intel Core i5

### GPU

NVIDIA GeForce GT 755M OpenGL Engine 512MB

### RAM

1TB

### Kernel Version

1.0.0-2227136955.commit-c4944ec

### Unity Version

1.0.32838-20220415090933.commit-43530d2

### Realm

dg

### NameTag

prep#3ed3

**Comment by jmoguilevsky** [comment]
Duplicate: https://github.com/decentraland/sdk/issues/343
