### ISSUE TITLE
MULTIPLE TABS OPEN

### ISSUE THREAD

**Issue by dregli14** [decentraland/issues#345]
### What happened?

IT KICKS ME SAYING I HAVE MULTIPLE TABS WICH IS NOT TRUE I LOST A HAND BC OF THAT IM SICK AND TIRED OF THIS FUCKING ASS MADE SOFTWARE YOU MAKE MILLONS CAN'T MAKE A DECENT PLAY EXPERIENCE

### Steps to reproduce

WTF DO I KNOW

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36

### Wallet

Metamask

### CPU

I7

### GPU

ANGLE (Intel, Intel(R) Iris(R) Plus Graphics Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

16

### Kernel Version

1.0.0-2227136955.commit-c4944ec

### Unity Version

1.0.32838-20220415090933.commit-43530d2

### Realm

hela

### NameTag

ILOVESRINGES#ee1d

**Comment by jmoguilevsky** [comment]
Duplicate: https://github.com/decentraland/sdk/issues/343
