### ISSUE TITLE
ventanas multiples

### ISSUE THREAD

**Issue by jcarlosgiil** [decentraland/issues#347]
### What happened?

no puedo inciar el juego por ventanas multiples

### Steps to reproduce

quitar el bug de las ventas multiples

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36

### Wallet

Metamask

### CPU

hp windows

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GT 710 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

6

### Kernel Version

1.0.0-2227136955.commit-c4944ec

### Unity Version

1.0.32838-20220415090933.commit-43530d2

### Realm

hela

### NameTag

Heisenberg#3270

**Comment by jmoguilevsky** [comment]
Duplicado: https://github.com/decentraland/sdk/issues/343
