### ISSUE TITLE
You can't play ICE Poker in multiple tables error message

### ISSUE THREAD

**Issue by paulcicio** [decentraland/issues#348]
### What happened?

I've played ICE Poker for around 2 hours, then took a break for some while and then I tried to reload and play again, when I got this error message. 

### Steps to reproduce

Play ICE Poker for some time, then take a break
Try to reload the tab, in order to restart playing

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36

### Wallet

Metamask

### CPU

Intel Core i5 vPro

### GPU

ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

32 Gb

### Kernel Version

1.0.0-2227136955.commit-c4944ec

### Unity Version

1.0.32838-20220415090933.commit-43530d2

### Realm

hela

### NameTag

PaulC#783a

**Comment by pravusjif** [comment]
Is this still happening to you? We'd need more info to debug this.

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
