### ISSUE TITLE
Can't change wearable

### ISSUE THREAD

**Issue by kenji08** [decentraland/issues#349]
### What happened?

When I try to change my wearables, they revert back to their original state and I can't change them.

### Steps to reproduce

Open backpack to change wearables

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36

### Wallet

Metamask

### CPU

Intel i5

### GPU

Intel(R) HD Graphics 6000 512MB

### RAM

8

### Kernel Version

1.0.0-2227136955.commit-c4944ec

### Unity Version

1.0.32838-20220415090933.commit-43530d2

### Realm

loki

### NameTag

KENJI

**Comment by pravusjif** [comment]
Is this still happening to you?

**Comment by AjimenezDCL** [comment]
Closing this issue because of not having a response for two weeks
