### ISSUE TITLE
See Green Triangle, but no cards to click on to start game

### ISSUE THREAD

**Issue by CaptureMotion** [decentraland/issues#351]
### What happened?

Trying to enter an ICE game and I get a green triangle to go and sit at that table. But no cards to click on to buy in.

### Steps to reproduce

I just logged into Ice Poker Stronghold, nothing fancy.

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

### GPU

NVIDIA GeForce GTX 1660 5991MB

### RAM

32699MB

### Kernel Version

1.0.0-2258376128.commit-f035f09

### Unity Version

desktop-main.commit-bd7b560

### Realm

athena

### NameTag

CaptureMotion#05bc

**Comment by jmoguilevsky** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
