### ISSUE TITLE
Opensea NFTs are not displaying well 

### ISSUE THREAD

**Issue by xyzlb** [decentraland/issues#38]
### What happened?

Hi! can you pls help ? here is teh link to my plot in DCL 
Not sure why the NFTs are not displaying ... 

Also first time I logged in there was a transparent wall preventing me from getting in , second time I logged in, it was gone
https://play.decentraland.org/?position=68,29
Thanks!
<img width="1392" alt="Screen Shot 2021-10-12 at 12 56 56 AM" src="https://user-images.githubusercontent.com/69472591/136860642-71ccb8fb-9ea5-4158-97be-886359737983.png">
The ones on the side too !

### Steps to reproduce

visit https://play.decentraland.org/?position=68,29

### Operating System

MAC OS Cataline 10.15.7

### Wallet

Metamask

### CPU

2.9 GHz Quad-Core Intel Core i7

### GPU

Radeon Pro 460 4 GB Intel HD Graphics 530 1536 MB

### RAM

16 GB 2133 MHz LPDDR3

### Kernel Version

1.0.0-1329611301.commit-0d474aa

### Unity Version

i entered /version in chat it said this command doesn't exist

### Realm

hephaestus

### NameTag

test#0570

**Comment by olavra** [comment]
Hi @xyzlb, we released a fix that solves this problem. Could you please check if this is still happening?

**Comment by xyzlb** [comment]
Thank you olavra! I need to vent my frustration , i am frankly quite frustrated , taking a break from DCL  , my scenes r having constantly issues, last one is landing spot of visitor was inside my neighbour’s spot! I COULDN’t get help anywhere. How can this happen ? I never use sdk just the builder,  and to my knowledge builder doesn’t have the ability to change it.  Thanks again .
