### ISSUE TITLE
ice poker

### ISSUE THREAD

**Issue by canduyz** [decentraland/issues#381]
### What happened?

it just kicked me out of the game.. i have 3 of a kind and then suddenly kicked me out,.. please fix the fucking game.. the developer of the game is an idiot how many times i reported a bug but theres no action.. so stupid..

### Steps to reproduce

the developer and the IT of this games is so stupid they cant resolved the bug of the game.. 

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz

### GPU

NVIDIA Quadro 2000 979MB

### RAM

8079MB

### Kernel Version

1.0.0-2258376128.commit-f035f09

### Unity Version

desktop-main.commit-bd7b560

### Realm

dg

### NameTag

Candi#7e69

**Comment by jmoguilevsky** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
