### ISSUE TITLE
0 stuf

### ISSUE THREAD

**Issue by tntdad121** [decentraland/issues#384]
### What happened?

the game made me level 1 and 0 stuf ai had a lot of stuf

### Steps to reproduce

i was playing last night and then i was sleppy so i closed my laptop and went to sleep till 11:00 in the pm my stuf was turned to 0

### Operating System

Windows 10  (10.0.18363) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz

### GPU

Intel(R) HD Graphics Family 2048MB

### RAM

8073MB

### Kernel Version

1.0.0-2277899092.commit-8ac5c17

### Unity Version

desktop-main.commit-eec0526

### Realm

gd

### NameTag

Wisdom#87a4

**Comment by jmoguilevsky** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
