### ISSUE TITLE
Ice says I am in playing in Multi Tabs

### ISSUE THREAD

**Issue by CaptureMotion** [decentraland/issues#385]
### What happened?

I have an error that says I am playing in multiple tabs and I am not playing at all.

### Steps to reproduce

I am not sure

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

### GPU

NVIDIA GeForce GTX 1660 5991MB

### RAM

32699MB

### Kernel Version

1.0.0-2277899092.commit-8ac5c17

### Unity Version

desktop-main.commit-eec0526

### Realm

dg

### NameTag

CaptureMotion#05bc

**Comment by starleaf2017** [comment]
Did you fix this issue yet

**Comment by starleaf2017** [comment]
Im having the same one and i can't figure anything out

**Comment by CaptureMotion** [comment]
Have not had the issue surface again....I think this is the multitab issue

**Comment by jmoguilevsky** [comment]
Duplicate: https://github.com/decentraland/issues/issues/423
