### ISSUE TITLE
In the middle of hand of ice poker and crash.

### ISSUE THREAD

**Issue by CaptureMotion** [decentraland/issues#387]
### What happened?

Was playing ice poker with bets on table, and was disconnected with a good hand mind you.

### Steps to reproduce

I have no idea.

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

### GPU

NVIDIA GeForce GTX 1660 5991MB

### RAM

32699MB

### Kernel Version

1.0.0-2283707362.commit-ec0c888

### Unity Version

desktop-main.commit-b960319

### Realm

artemis

### NameTag

CaptureMotion#05bc

**Comment by pbosio** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
