### ISSUE TITLE
jumping out of game

### ISSUE THREAD

**Issue by daltonjjj** [decentraland/issues#388]
### What happened?

jumping out of game

### Steps to reproduce

jumping out of game

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7 CPU 960 @ 3.20GHz

### GPU

NVIDIA GeForce GTX 1050 Ti 4018MB

### RAM

16375MB

### Kernel Version

1.0.0-2283707362.commit-ec0c888

### Unity Version

desktop-main.commit-b960319

### Realm

dg

### NameTag

dali#cd74

**Comment by pbosio** [comment]
can you provide us with more information to debug this issue?

**Comment by AjimenezDCL** [comment]
Closing this issue because of not having a response for two weeks
