### ISSUE TITLE
i made a full house and didn't win the hand

### ISSUE THREAD

**Issue by ganja4i20** [decentraland/issues#389]
### What happened?

i made a full house and didn't win the hand, then they pulled me off the table and I ran out of my chips

### Steps to reproduce

I have Q7 in my hand , the flop hit 22Q gave a raise and the other player paid , Turn appeared a 3 , the two players asked table and River Q .. i made a full house lost my chips and took me off the table.

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz

### GPU

NVIDIA GeForce RTX 3050 8070MB

### RAM

16225MB

### Kernel Version

1.0.0-2283707362.commit-ec0c888

### Unity Version

desktop-main.commit-b960319

### Realm

dg

### NameTag

Ganja4i20#2fac

**Comment by pbosio** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
