### ISSUE TITLE
Steampunk by Dappcraft Bug

### ISSUE THREAD

**Issue by pseudezub** [decentraland/issues#39]
### What happened?

Whenever I try to finish the Steampunk challenge by talking to Anna it wont go through and will not mark my challenge as complete..

### Steps to reproduce

mark my last step as complete to gain the POAP, Anna says ÿour poap is waiting for you" but never gives it to me

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36

### Wallet

Metamask

### CPU

Intel Core i5

### GPU

Intel(R) Iris(TM) Plus Graphics 645 512MB

### RAM

32GB

### Kernel Version

1.0.0-1329611301.commit-0d474aa

### Unity Version

1.0.16082-20211011151203.commit-adc3e3b

### Realm

fenrir

### NameTag

sadezub#7ee3

**Comment by nearnshaw** [comment]
Hi!

The issue with this quest has now been resolved, thanks for reporting

If you enter the scene with the same account you originally used, you should now be able to talk to the NPC to complete the final step, and this time you'll receive the reward for completing the quest.

https://play.decentraland.org/?position=38%2C12
