### ISSUE TITLE
Table 2 at the Chateau Satoshi

### ISSUE THREAD

**Issue by CaptureMotion** [decentraland/issues#390]
### What happened?

Table 2 has been broke for about 2 days. 

### Steps to reproduce

Just walk over to table

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

### GPU

NVIDIA GeForce GTX 1660 5991MB

### RAM

32699MB

### Kernel Version

1.0.0-2283707362.commit-ec0c888

### Unity Version

desktop-main.commit-b960319

### Realm

artemis

### NameTag

CaptureMotion#05bc

**Comment by pbosio** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
