### ISSUE TITLE
clicked instead of counting on the Layer Mined Cubes

### ISSUE THREAD

**Issue by yakov007** [decentraland/issues#391]
### What happened?

I clicked instead of counting on the Layer Mined Cubes, the count got stuck at the number 10051

### Steps to reproduce

I click and it doesn't count

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 3400G with Radeon Vega Graphics 

### GPU

AMD Radeon(TM) RX Vega 11 Graphics 15321MB

### RAM

30642MB

### Kernel Version

1.0.0-2283707362.commit-ec0c888

### Unity Version

desktop-main.commit-b960319

### Realm

athena

### NameTag

Baqiorana#a9ba

**Comment by pbosio** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
