### ISSUE TITLE
When you choose option to bet half pot

### ISSUE THREAD

**Issue by CaptureMotion** [decentraland/issues#392]
### What happened?

When you choose option to bet half pot the system adds $5 chips to it.

### Steps to reproduce

Go to any table and bet half pot.

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

### GPU

NVIDIA GeForce GTX 1660 5991MB

### RAM

32699MB

### Kernel Version

1.0.0-2283707362.commit-ec0c888

### Unity Version

desktop-main.commit-b960319

### Realm

dg

### NameTag

CaptureMotion#05bc

**Comment by pbosio** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
