### ISSUE TITLE
Flying mode intermittent

### ISSUE THREAD

**Issue by kermy069** [decentraland/issues#393]
### What happened?

when i logged back into megacube,  i could not fly i have been flying fine for the last 6 hrs and im aware you can only fly in certain places,   some times i can fly for about 5 or six people high and i fall straigt out of the sky on to the ground. and other times i can not fly at all

### Steps to reproduce

log in after a short break

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

AMD Phenom(tm) 9950 Quad-Core Processor

### GPU

NVIDIA GeForce 9600 GT 480MB

### RAM

8191MB

### Kernel Version

1.0.0-2283707362.commit-ec0c888

### Unity Version

desktop-main.commit-b960319

### Realm

dg

### NameTag

Kermy#4d5b

**Comment by menduz** [comment]
Hello, fly mode only works in the scenes that implement it, like the Megacube. It is not currently a feature that is available in the rest of the world.

**Comment by kermy069** [comment]
> Hello, fly mode only works in the scenes that implement it, like the Megacube. It is not currently a feature that is available in the rest of the world.

Yes i am aware of that and im refereeing to when i was competing in the mega cube event
