### ISSUE TITLE
Metamask unvailible for Decentraland PC

### ISSUE THREAD

**Issue by BigBaston** [decentraland/issues#395]
### What happened?

Hello,

It's impossible for me to send token or cryptocurrency of decentraland game to another wallet (megtamask or infinitywallet).

Please check the problem and keep me informed.

Cordially.

### Steps to reproduce

White page in decentraland game. The wallet was not recognized.

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Wallet Connect

### CPU

Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz

### GPU

NVIDIA GeForce 840M 2010MB

### RAM

8124MB

### Kernel Version

1.0.0-2301104289.commit-e2ad175

### Unity Version

desktop-1.0.318-20220507010707.commit-b960319

### Realm

athena

### NameTag

BigBaston#3783

**Comment by pbosio** [comment]
- https://github.com/decentraland/issues/issues/396

**Comment by pbosio** [comment]
can you provide us with more information to debug this issue?

**Comment by fzavalia** [comment]
No response from the reporter
