### ISSUE TITLE
Game of Ice Poker Folded on me!

### ISSUE THREAD

**Issue by CaptureMotion** [decentraland/issues#396]
### What happened?

I was in a hand in Ice poker, I was waiting for a player to make their decision. And the system folded my hand. 

### Steps to reproduce

I have no idea.

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

### GPU

NVIDIA GeForce GTX 1660 5991MB

### RAM

32699MB

### Kernel Version

1.0.0-2302764182.commit-cf8d532

### Unity Version

desktop-1.0.318-20220507010707.commit-b960319

### Realm

unicorn

### NameTag

CaptureMotion#05bc

**Comment by pbosio** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
