### ISSUE TITLE
Big Blind is not posting

### ISSUE THREAD

**Issue by CaptureMotion** [decentraland/issues#399]
### What happened?

Big blind is not posting, it just says waiting. 

### Steps to reproduce

I don't know.

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

### GPU

NVIDIA GeForce GTX 1660 5991MB

### RAM

32699MB

### Kernel Version

1.0.0-2302764182.commit-cf8d532

### Unity Version

desktop-1.0.318-20220507010707.commit-b960319

### Realm

dg

### NameTag

CaptureMotion#05bc

**Comment by pbosio** [comment]
can you provide us with more information to debug this issue?

**Comment by fzavalia** [comment]
No response from the reporter
