### ISSUE TITLE
SteamPunk by DappCraft Quest

### ISSUE THREAD

**Issue by nagle-analytics** [decentraland/issues#40]
### What happened?

39,12 
4/5
Talk to Anna to complete.
Anna says "Thanks for your help. Hope you enjoyed."

But quest never ends, Reward is never received.

### Steps to reproduce

Click jump in on the last step of the question and talk with Anna.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36

### Wallet

Metamask

### CPU

Intel i9 10 generation

### GPU

ANGLE (NVIDIA, NVIDIA Quadro P1000 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6155) 512MB

### RAM

24

### Kernel Version

1.0.0-1329611301.commit-0d474aa

### Unity Version

1.0.16426-20211013185142.commit-8d95de7

### Realm

fenrir

### NameTag

Jeff#5c52

**Comment by nearnshaw** [comment]
Hi!

The issue with this quest has now been resolved, thanks for reporting

If you enter the scene with the same account you originally used, you should now be able to talk to the NPC to complete the final step, and this time you'll receive the reward for completing the quest.

https://play.decentraland.org/?position=38%2C12
