### ISSUE TITLE
Server Error 

### ISSUE THREAD

**Issue by Megsy13** [decentraland/issues#400]
### What happened?

Went outside the gingerbread house and opened the chest to the left of the house and encountered a server error. I had pressed the button and not much else outside the house
![image](https://user-images.githubusercontent.com/105487001/168248989-182bd424-ffb0-4bf9-a6cf-8fe4a13b6b8c.png)

### Steps to reproduce

Went outside the gingerbread house and opened the chest to the left of the house and encountered a server error. I had pressed the button and not much else outside the house
![image](https://user-images.githubusercontent.com/105487001/168248675-be43ede0-3d7a-4fef-916e-daba1a8f0327.png)

### Operating System

Windows 10  (10.0.22000) 64bit

### Wallet

None, played as guest

### CPU

11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

### GPU

Intel(R) Iris(R) Xe Graphics 8091MB

### RAM

16183MB

### Kernel Version

1.0.0-2316068501.commit-7c28adc

### Unity Version

desktop-1.0.318-20220507010707.commit-b960319

### Realm

dg

### NameTag

Worm#af02

**Comment by fzavalia** [comment]
This seems to be a problem with the scene. The creators of that scene should be notified about the issue.
