### ISSUE TITLE
GolfCraft Game - The golf ball stays on air at the same place while the lever platform moves

### ISSUE THREAD

**Issue by arif-aygun** [decentraland/issues#401]
### What happened?

Hi,

I was playing in training sessions. There was a level that I needed to locate the ball upper platform with a tiny ramp. The ball dropped on the lever platform which was moving up and down continuously. But, the golf ball went down with the lever and stayed on air like there is another platform underneath. When lever come across to the ball, the ball stays and pass through the lever platform. To shoot, i had to wait the lever platform to be at the same level with the ball, otherwise the ball would go directly to outside of the path and reset.

![Screenshot_2](https://user-images.githubusercontent.com/30390865/168421590-9119fdae-aaa8-4e04-9642-882567dfdf47.png)
![Screenshot_4](https://user-images.githubusercontent.com/30390865/168421591-c47951b6-a554-44fe-99f6-53c03b1def43.png)
![Screenshot_5](https://user-images.githubusercontent.com/30390865/168421592-2931df3e-14b7-4c96-9172-4880ddc8d094.png)
 

### Steps to reproduce

Maybe the ball can be vulnerable to the lever platform or the lever platform can be vulnerable to the ball.

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz

### GPU

Intel(R) UHD Graphics 3938MB

### RAM

7877MB

### Kernel Version

1.0.0-2322196163.commit-bfb06e9

### Unity Version

desktop-1.0.318-20220507010707.commit-b960319

### Realm

dg

### NameTag

arif#b005

**Comment by pbosio** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
