### ISSUE TITLE
Multiple Tab prob.

### ISSUE THREAD

**Issue by gnininvi** [decentraland/issues#402]
### What happened?

Can#t play icepoker. I have to close all tabs but i play with the client and i dont have tabs open. Pls help

### Steps to reproduce

Close Tabs

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 1600 Six-Core Processor 

### GPU

NVIDIA GeForce GTX 1650 3962MB

### RAM

16315MB

### Kernel Version

1.0.0-2322196163.commit-bfb06e9

### Unity Version

desktop-1.0.318-20220507010707.commit-b960319

### Realm

dg

### NameTag

Blackmuller#12a2

**Comment by pbosio** [comment]
duplicated https://github.com/decentraland/sdk/issues/343
