### ISSUE TITLE
multitab

### ISSUE THREAD

**Issue by xtractop** [decentraland/issues#404]
### What happened?

showing multi tabs error even though the wallet is just connected to one application

### Steps to reproduce

![image](https://user-images.githubusercontent.com/103028295/168486537-48ee1e91-b029-4666-ad6f-88bc97960cad.png)

showing this error repeatedly even though i have the wallet connected to the desktop application

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz

### GPU

Intel(R) UHD Graphics 6068MB

### RAM

12137MB

### Kernel Version

1.0.0-2322196163.commit-bfb06e9

### Unity Version

desktop-1.0.318-20220507010707.commit-b960319

### Realm

dg

### NameTag

PhishcallinGG#6902

**Comment by pbosio** [comment]
duplicated https://github.com/decentraland/sdk/issues/343
