### ISSUE TITLE
Music is not working

### ISSUE THREAD

**Issue by React2github** [decentraland/issues#406]
### What happened?

Everytime I go to an event where there is music. I lose audio after a few seconds. 
The character is dancing but I can't hear any music. 

### Steps to reproduce

Go to any event/place with music. 

### Operating System

Windows 10  (10.0.22000) 64bit

### Wallet

None, played as guest

### CPU

Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz

### GPU

NVIDIA GeForce GTX 1060 3GB 2988MB

### RAM

16271MB

### Kernel Version

1.0.0-2339190888.commit-8fb7f19

### Unity Version

desktop-1.0.318-20220507010707.commit-b960319

### Realm

dg

### NameTag

CodeWorld#e4b7

**Comment by fzavalia** [comment]
Would you be so kind as to provide a picture of your audio settings?
Could you tell us on which particular scene (coordinates) that happens?
Keep in mind that if the event is over, there is a chance that music will not be playing.

**Comment by AjimenezDCL** [comment]
Closing this issue because of not having a response for two weeks
