### ISSUE TITLE
Ice Poker -  game tables not showing up

### ISSUE THREAD

**Issue by ghost** [decentraland/issues#407]
### What happened?

I play not in the browser, but from Windows. When I show up at the "Ice Poker" location, people show up but not the game tables. This happens on any location "Ice Poker". I tried restarting my computer and clearing the cache, but that didn't help.

### Steps to reproduce

I play not in the browser, but from Windows. When I show up at the "Ice Poker" location, people show up but not the game tables. 
![BUG](https://user-images.githubusercontent.com/98421773/168938603-dc1b6cad-5dd3-4646-92fa-f728fba0c8a8.png)

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz

### GPU

NVIDIA GeForce GTX 1060 3GB 2988MB

### RAM

32686MB

### Kernel Version

1.0.0-2339190888.commit-8fb7f19

### Unity Version

desktop-1.0.318-20220507010707.commit-b960319

### Realm

dg

### NameTag

Animadverte#3d7b

**Comment by fzavalia** [comment]
Have you tried connecting to a different realm? 
Are you still experiencing this issue?

**Comment by Rodriasd** [comment]
THE SAME HAPPENS TO ME, ALMOST 5 DAYS AGO THEY DON'T KNOW WHAT TO TELL ME AND I CAN'T PLAY

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
