### ISSUE TITLE
Multi Tab error please help

### ISSUE THREAD

**Issue by buboiii** [decentraland/issues#409]
### What happened?

![image](https://user-images.githubusercontent.com/105955712/169629131-2cc7a7e7-f7d8-4bc6-b9b6-0ab441c9536f.png)

I've been experiencing Multi Tab since last 48hrs up until this day :(

### Steps to reproduce

![image](https://user-images.githubusercontent.com/105955712/169629156-d1a3ff6f-b626-4bc3-921a-eed9be839ad3.png)

### Operating System

windows 11

### Wallet

Metamask

### CPU

Ryzen 7

### GPU

(NVIDIA, NVIDIA GeForce GTX 1650 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

32GB

### Kernel Version

1.0.0-2353976899.commit-60c9fb6 

### Unity Version

1.0.36640-20220519145238.commit-952bfe9 

### Realm

baldr 

### NameTag

RiiniBee#aad5

**Comment by pbosio** [comment]
duplicated https://github.com/decentraland/sdk/issues/343
