### ISSUE TITLE
Spontaneous change of username and wearables and appearance of decentraland character

### ISSUE THREAD

**Issue by payamal** [decentraland/issues#410]
### What happened?

I realized something that was very surprising to me and I was very shocked and lost my sense of security, my account is in trouble, I had already chosen another name for my character in decentraland, but I realized that the Doing it myself has changed, and even the wearables I chose for my character (hairstyle, T-shirt, shoes) have changed.
   We set the username and style as before, but again I noticed that it has changed
I even wiped the browser cache and reset the metamask wallet but it was useless and the problem persists

### Steps to reproduce

I want my account back to normal

### Operating System

chrome, windows 7

### Wallet

Metamask

### CPU

intel core i5-3470

### GPU

gt610 2gb 64bit

### RAM

8 gigabyte

### Kernel Version

1.0.0-2353976899.commit-60c9fb6

### Unity Version

1.0.36640-20220519145238.commit-952bfe9

### Realm

dg

### NameTag

Salamander#e7e6

**Comment by davidejensen** [comment]
Could you please check if this issue is still happening? If yes could you give us more clear instructions to reproduce it?

**Comment by AjimenezDCL** [comment]
Closing this issue because of not having a response for two weeks.
