### ISSUE TITLE
got banned without any reason

### ISSUE THREAD

**Issue by xtractop** [decentraland/issues#411]
### What happened?

i got banned without any reason, I did not to do anything , got banned for no reason

### Steps to reproduce

![image](https://user-images.githubusercontent.com/103028295/169701861-b375eaf9-7551-479d-9045-fc176892ec8a.png)

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz

### GPU

Intel(R) UHD Graphics 6068MB

### RAM

12137MB

### Kernel Version

1.0.0-2353976899.commit-60c9fb6

### Unity Version

desktop-1.0.339-20220520162118.commit-ccddcf0

### Realm

dg

### NameTag

PhishcallinGG#6902

**Comment by pbosio** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
