### ISSUE TITLE
wonderzone

### ISSUE THREAD

**Issue by sepehrnb** [decentraland/issues#412]
### What happened?

Hi 
I cant connect my wallet to wonderzone.wondermine.io
my wallet is infinity wallet
I have 2 wearable item in there

### Steps to reproduce

how can I connect my infinity wallet to wonderzone.wondermine.io?

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36

### Wallet

Wallet Connect

### CPU

ore(TM) i7-4720HQ CPU

### GPU

ANGLE (Intel, Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

16gb

### Kernel Version

1.0.0-2353976899.commit-60c9fb6

### Unity Version

1.0.36640-20220519145238.commit-952bfe9

### Realm

heimdallr

### NameTag

amoo3pehr#e467

**Comment by davidejensen** [comment]
This issue is not related to Decentraland but with Wonderzone, you can get in touch with them at https://discord.com/channels/460537434061668362/822221488392372254
