### ISSUE TITLE
cant see people even after changing realms also online friends not working

### ISSUE THREAD

**Issue by CHIPDEALERS** [decentraland/issues#413]
### What happened?

cant see people even after changing realms also online friends not working

### Steps to reproduce

cant see people even after changing realms also online friends not working

### Operating System

Windows 10  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz

### GPU

NVIDIA GeForce GTX 1660 Ti 5991MB

### RAM

16295MB

### Kernel Version

1.0.0-2353976899.commit-60c9fb6

### Unity Version

desktop-1.0.339-20220520162118.commit-ccddcf0

### Realm

dg

### NameTag

247#bf8b

**Comment by davidejensen** [comment]
We recently fixed this issue, if the problem persists please open a new issue
