### ISSUE TITLE
Multiple Tabs

### ISSUE THREAD

**Issue by Despo96** [decentraland/issues#414]
### What happened?

I have downloaded the Decentralland app. I was playing poker when I was kicked off the table. Write in a few seconds, "You Can't Play ICE Poker In Multiple Tabs, But I didn't had extra tab because i was played in Decentraland application version.

### Steps to reproduce

please fix it.

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz

### GPU

NVIDIA GeForce RTX 3060 Ti 8050MB

### RAM

32704MB

### Kernel Version

1.0.0-2353976899.commit-60c9fb6

### Unity Version

desktop-1.0.339-20220520162118.commit-ccddcf0

### Realm

artemis

### NameTag

Cat#85f6

**Comment by pbosio** [comment]
duplicated https://github.com/decentraland/sdk/issues/343
