### ISSUE TITLE
heve bug

### ISSUE THREAD

**Issue by SHIMI212** [decentraland/issues#415]
### What happened?

The player gets stuck and the bug cannot be moved

### Steps to reproduce

Reset the user

### Operating System

Windows 10  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

### GPU

NVIDIA GeForce GTX 1060 6052MB

### RAM

16234MB

### Kernel Version

1.0.0-2353976899.commit-60c9fb6

### Unity Version

desktop-1.0.339-20220520162118.commit-ccddcf0

### Realm

dg

### NameTag

Kroloupe#ef62

**Comment by davidejensen** [comment]
Can you provide us with more information to debug this issue?
