### ISSUE TITLE
I can't import my scenes

### ISSUE THREAD

**Issue by juroguim** [decentraland/issues#416]
### What happened?

I can't import my scenes.

The + button and the "New asset pack" button don't appear for me

### Steps to reproduce

I entered the Builder
I created a new project
and I searched for the buttons to import

### Operating System

Windows 10  (10.0.22000) 64bit

### Wallet

Fortmatic

### CPU

11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz

### GPU

Intel(R) Iris(R) Xe Graphics 3965MB

### RAM

7930MB

### Kernel Version

1.0.0-2385043759.commit-1934759

### Unity Version

desktop-1.0.339-20220520162118.commit-ccddcf0

### Realm

dg

### NameTag

Juroguim#fda6

**Comment by kuruk-mm** [comment]
Can you provide us with more information to debug this issue?

Can you provide a screenshot of the UI?

Are you using builder.decentraland.org or the builder inside the Decentraland Desktop Client?
