### ISSUE TITLE
Issue with SteamPunk quest

### ISSUE THREAD

**Issue by DmitriZhurba** [decentraland/issues#42]
### What happened?

all jobs done, the quest is almost passed, the only thing can;t be done - I should "talk to Anna to complete". I do but nothing happens
![SteamPunk quest issue with Anna](https://user-images.githubusercontent.com/92916922/138244076-fcec27c9-66ff-47b8-acf6-aa2ae3702a4f.jpg)
. 

### Steps to reproduce

please check and repair the bug to let the quest be completed

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz   2.11 GHz

### GPU

ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.9171) 512MB

### RAM

16GB

### Kernel Version

1.0.0-1363890249.commit-64dd58e

### Unity Version

1.0.16782-20211018202845.commit-11e6f6a

### Realm

fenrir

### NameTag

zhurbik#4eb2

**Comment by nearnshaw** [comment]
Hi!

The issue with this quest has now been resolved, thanks for reporting

If you enter the scene with the same account you originally used, you should now be able to talk to the NPC to complete the final step, and this time you'll receive the reward for completing the quest.

https://play.decentraland.org/?position=38%2C12

**Comment by DmitriZhurba** [comment]
Hi,
when I login again using your provided link with my Metamask wallet (as
always) I get to the quest location and see the message about (quest API
error). When I try to talk to the NPC she offers me to pass the quest from
the start.

BR
Dmitri
>
>

вт, 9 нояб. 2021 г. в 00:05, Nicolas Earnshaw ***@***.***>:

**Comment by DmitriZhurba** [comment]
Hi,
please find attached some evidencing pictures taken from the quest in
Decentraland.

BR
Dmitri

вт, 9 нояб. 2021 г. в 10:05, Dmitri Zhurba ***@***.***>:
