### ISSUE TITLE
banned account

### ISSUE THREAD

**Issue by krizelism30** [decentraland/issues#420]
### What happened?

im actively playing and automatic kicked from table then ot banned when i try to find table agai
![x2vrjFzl](https://user-images.githubusercontent.com/106356310/170604288-546374f6-eb7d-45c6-a1a5-a61769288a51.jpg)
n

### Steps to reproduce

N/A

### Operating System

windows10/googlechrome

### Wallet

Metamask

### CPU

intel i511th gen

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GT 1030 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

8GB

### Kernel Version

1.0.0-2392404250.commit-1b886c4

### Unity Version

1.0.37205-20220525141805.commit-8ee0cf3

### Realm

osiris

### NameTag

KRIZEL#ec57

**Comment by kuruk-mm** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.

Decentraland doesn't have a way of banning wallets or accounts. Contact the scene creator to handle this problem.
