### ISSUE TITLE
Metaball. PvC mode

### ISSUE THREAD

**Issue by Beerforthewin** [decentraland/issues#422]
### What happened?

During a game in a PvC mode after my turn I got an extra turn for no reason instead of passing on to MetaBaller. During my extra turn I can't interact with a game, adjuct direction and power, can't shoot

### Steps to reproduce

No idea, everything was smooth

### Operating System

Windows 10  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 4500U with Radeon Graphics 

### GPU

AMD Radeon(TM) Graphics 3774MB

### RAM

7549MB

### Kernel Version

1.0.0-2392404250.commit-1b886c4

### Unity Version

desktop-1.0.339-20220520162118.commit-ccddcf0

### Realm

artemis

### NameTag

Beerftw#a1b1

**Comment by kuruk-mm** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
