### ISSUE TITLE
ME APARECE MULTIPLE TABS DESDE EL DIA DE AYER

### ISSUE THREAD

**Issue by jcarlosgiil** [decentraland/issues#424]
### What happened?

NO PUEDO ENTRAR A JUGAR POR MULTIPLE TABS ME BANEARON. SIN RAZON , SIN MOTIVO.

### Steps to reproduce

QUITAR MULTIPLE TABS

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36

### Wallet

Metamask

### CPU

HP

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GT 710 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

8 GB

### Kernel Version

1.0.0-2392404250.commit-1b886c4

### Unity Version

1.0.37358-20220526153817.commit-40bae14

### Realm

artemis

### NameTag

SINAZUCAR#6e5a

**Comment by jcarlosgiil** [comment]
???????????????????

**Comment by kuruk-mm** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.

Decentraland doesn't have a way of banning wallets or accounts. Contact the scene creator to handle this problem.
