### ISSUE TITLE
How to exit decentraland app?

### ISSUE THREAD

**Issue by uxpstudio** [decentraland/issues#425]
### What happened?

I don't think it's exactly a bug. It's more of an usability issue, I guess.
I can't find exit/close button for the app, other than alt-F4(the default window closing shortcut).

### Steps to reproduce

A very easy-to-use metaverse exit convention, such as, "esc > L(leave) > return key" might help user feel secure about the exit procedure. 

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

### GPU

NVIDIA GeForce GTX 1080 8079MB

### RAM

16286MB

### Kernel Version

1.0.0-2392404250.commit-1b886c4

### Unity Version

desktop-1.0.361-20220527144557.commit-e48ddbc

### Realm

odin

### NameTag

Moonrider#1065

**Comment by uxpstudio** [comment]
Oh, I found the exit button under the setting. It's not very intuitive, but still exists. 
Cheers,

**Comment by tapple** [comment]
I can't find it under settings either

**Comment by kuruk-mm** [comment]
You can exit the game from `Menu > Profile > Exit`.

> Oh, I found the exit button under the setting. It's not very intuitive, but still exists. Cheers,

Thank you for the feedback. Will be taken into account.
