### ISSUE TITLE
Music is not working in TRU Band room

### ISSUE THREAD

**Issue by kermy069** [decentraland/issues#427]
### What happened?

No music!  i can see video of dj playing, But no music sound, only audio of people moving around no music, audio settings turned up in volume settings window for master,ui sfx,voice chat,music,avatar sfx and world sfx 

### Steps to reproduce

walk into tru band room walk all around room on stages objects and all platforms start dancing but no dj sound

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

AMD Phenom(tm) 9950 Quad-Core Processor

### GPU

NVIDIA GeForce 9600 GT 480MB

### RAM

8191MB

### Kernel Version

1.0.0-2392404250.commit-1b886c4

### Unity Version

desktop-1.0.361-20220527144557.commit-e48ddbc

### Realm

artemis

### NameTag

Kermy#4d5b

**Comment by kuruk-mm** [comment]
Can you provide us with more information to debug this issue?

Can you provide the positions where it's happening?
