### ISSUE TITLE
Craft-O-Matic does not response of showing any thing for me to craft 

### ISSUE THREAD

**Issue by KahanaCAguy** [decentraland/issues#428]
### What happened?

The Craft-O-Matic in Wondermine does not response or allows me to craft anytihng

### Steps to reproduce

When I click on the Craft-O-Matic arrows, it just changes my view and nothing really shows up to be able to select and craft. 

### Operating System

Window 11

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz   2.30 GHz

### GPU

NVIDIA

### RAM

16

### Kernel Version

1.0.0-2392404250.commit-1b886c4

### Unity Version

Desktop 1.0.361-20220527144557.commit-e48ddbc

### NameTag

kahanaCAguy

**Comment by kuruk-mm** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
