### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by enzifiri** [decentraland/issues#429]
### What happened?

![image](https://user-images.githubusercontent.com/76253089/171202647-26afa73d-d921-413a-b711-75d194d7258b.png)
Hello. I found an annoying visual bug. Can you fix this? COORDİNATES -44,52 Dragon Rush Walls

### Steps to reproduce

You can fill in the gap

### Operating System

Windows 10  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz

### GPU

NVIDIA GeForce GTX 1050 Ti 4019MB

### RAM

20369MB

### Kernel Version

1.0.0-2392404250.commit-1b886c4

### Unity Version

desktop-1.0.361-20220527144557.commit-e48ddbc

### Realm

dg Dragon Rush

### NameTag

enzifiri#258f

**Comment by kuruk-mm** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
