### ISSUE TITLE
I see nobody 

### ISSUE THREAD

**Issue by SIKU84** [decentraland/issues#43]
### What happened?

Hello , i don't know if it really a bug , but i'm in the festival in Decentraland , everything works well , i can see the stage , my player can move , i hear the music , but nobody's here , i see nobody

### Steps to reproduce

<img width="1220" alt="Capture d’écran 2021-10-22 à 00 50 16" src="https://user-images.githubusercontent.com/92945009/138328045-e1090e0a-6d9b-4352-a952-e2c7fdf2e0f5.png">

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:93.0) Gecko/20100101 Firefox/93.0

### Wallet

Metamask

### CPU

3.1 Ghz Intel I5

### GPU

Intel(R) HD Graphics 400 512MB

### RAM

16GB

### Kernel Version

1.0.0-1363890249.commit-64dd58e

### Unity Version

1.0.17195-20211021144557.commit-c5b54bb

### Realm

odin

### NameTag

PengSIKU#359b

**Comment by 0xJuancito** [comment]
Can you provide us with more information to debug this issue?

Does this happen in every scene? Does it happen on the Genesis Plaza when you log in?

**Comment by pravusjif** [comment]
Closing this issue because of not having a response for two weeks.
