### ISSUE TITLE
Wrong full house was displayed as winning hand.

### ISSUE THREAD

**Issue by Rikki-Tavi** [decentraland/issues#430]
### What happened?

I lost the below hand (which was accurate). My opponent had pocket sixes, which means he had Jacks over 6's while I only had Jacks over 3's (all in the river). But when the showdown switched to showing the winning hand, it reported it as Jacks over 3's (which had me wondering why I didn't tie. It flashed so quickly, I missed the fact that he had pocket 6's. I didn't figure it out until I consulted my session history later.) 
![image](https://user-images.githubusercontent.com/18092994/171316405-2d76a748-6432-453d-85c5-afd9fa2b6ed0.png)

### Steps to reproduce

- I presume the river has to contain a full house with a lesser pair than a pocket pair of one of the players. 
- fwiw, In the showdown, I bet 80, he raised to 160, and I called.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

### Wallet

Metamask

### CPU

Intel i9 10th gen

### GPU

ANGLE (NVIDIA, NVIDIA Quadro T2000 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

32GB

### Kernel Version

1.0.0-2392404250.commit-1b886c4

### Unity Version

1.0.37358-20220526153817.commit-40bae14

### Realm

dg

### NameTag

ISpacedOut#9f86

**Comment by kuruk-mm** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
