### ISSUE TITLE
I got banned for no reason

### ISSUE THREAD

**Issue by ganja4i20** [decentraland/issues#431]
### What happened?

 message appears saying that I can't play because I was banned... for what reason?

### Steps to reproduce

I just want to play again..because I didn't do anything to get banned

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz

### GPU

NVIDIA GeForce RTX 3050 8070MB

### RAM

16225MB

### Kernel Version

1.0.0-2392404250.commit-1b886c4

### Unity Version

desktop-main.commit-32f01fd

### Realm

artemis

### NameTag

Ganja4i20#2fac

**Comment by kuruk-mm** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.

Decentraland doesn't have a way of banning users or wallets.
