### ISSUE TITLE
No music

### ISSUE THREAD

**Issue by Corellianjedi2** [decentraland/issues#432]
### What happened?

I can hear all the SFX but not the music playing. Tried resetting and messing with settings.

### Steps to reproduce

Not sure

### Operating System

Windows 10  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz

### GPU

NVIDIA GeForce GTX 1660 5992MB

### RAM

16257MB

### Kernel Version

1.0.0-2423216443.commit-f63496e

### Unity Version

desktop-1.0.361-20220527144557.commit-e48ddbc

### Realm

artemis

### NameTag

Corellianjedi2#f784

**Comment by RusseII** [comment]
same issue

**Comment by kuruk-mm** [comment]
can you provide us with more information to debug this issue?

for example, the position where it happens

**Comment by davidejensen** [comment]
duplicate #427
