### ISSUE TITLE
Unable to go fullscreen

### ISSUE THREAD

**Issue by GodMannn** [decentraland/issues#435]
### What happened?

I can go windowless but not true fullscreen. I don't have a problem with fullscreen in the browser. The desktop app blows out the resolution and makes it look terrible.  Also unable to see second column of settings options in menu on desktop. It's not just a square screen. It's actually cut off. 

### Steps to reproduce

Shouldn't be hard. I'm using windows 10. 

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz

### GPU

NVIDIA GeForce RTX 2060 SUPER 8031MB

### RAM

32683MB

### Kernel Version

1.0.0-2435235498.commit-ec6b32d

### Unity Version

desktop-1.0.361-20220527144557.commit-e48ddbc

### Realm

dg

**Comment by kuruk-mm** [comment]
Duplicate from https://github.com/decentraland/explorer-desktop/issues/232
