### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by MadMaxx76** [decentraland/issues#436]
### What happened?

unable to change wearables. 

### Steps to reproduce

unknown

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36

### Wallet

Metamask

### CPU

intel i9 10th generation

### GPU

ANGLE (AMD, AMD Radeon(TM) Vega 6 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

150

### Kernel Version

1.0.0-2450204627.commit-f9c6a13

### Unity Version

1.0.38571-20220606193958.commit-e41f33f

### Realm

dg

### NameTag

MadMax#081e

**Comment by kuruk-mm** [comment]
can you provide us with more information to debug this issue?
