### ISSUE TITLE
My assigned table is already full

### ISSUE THREAD

**Issue by Rikki-Tavi** [decentraland/issues#438]
### What happened?

I was assigned a table, I got there within a few seconds, but there is no hand available. Happened twice tonight already.

### Steps to reproduce

1. Click Find Table
2. Reach table and find that it is already full.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

### Wallet

Metamask

### CPU

Intel i9 10th gen

### GPU

ANGLE (NVIDIA, NVIDIA Quadro T2000 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

32GB

### Kernel Version

1.0.0-2450204627.commit-f9c6a13

### Unity Version

1.0.38571-20220606193958.commit-e41f33f

### Realm

hephaestus

### NameTag

ISpacedOut#9f86

**Comment by kuruk-mm** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
