### ISSUE TITLE
I lost my chips 2 times in an all win

### ISSUE THREAD

**Issue by ganja4i20** [decentraland/issues#439]
### What happened?

was in a hand of all win, as the photo below, I ended up losing the hand! soon after I tried to make Rebuyin more the game i lock and and lost my chips without playing!

> 
![1](https://user-images.githubusercontent.com/105138270/172916433-6bdf5bde-5207-41f3-9e4e-5e49d0b624b8.png)

### Steps to reproduce

i just lost my chips without playing

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz

### GPU

NVIDIA GeForce RTX 3050 8070MB

### RAM

16225MB

### Kernel Version

1.0.0-2469359484.commit-a5610ca

### Unity Version

desktop-1.0.379-20220608191335.commit-d7ee49c

### Realm

dg

### NameTag

Ganja4i20#2fac

**Comment by pravusjif** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
