### ISSUE TITLE
unable to claim wearables

### ISSUE THREAD

**Issue by nicholasostman** [decentraland/issues#44]
### What happened?

I was unable to claim DODO wearables last week, thought maybe they had run out. Now that I'm in the festival (metaverse festival) I've seen 4 boxes airdrop so far and each one gives me the following and then disappears
![fuckDCL](https://user-images.githubusercontent.com/31261631/138541123-709dfd6d-82ab-4ec9-b41a-176184f2a106.png)
 

### Steps to reproduce

simply copy my user data and wait for an airdrop I guess or try to redeem a wearable of any kind. 

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36

### Wallet

Metamask

### CPU

i7 4700k

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7212) 512MB

### RAM

16 GB

### Kernel Version

1.0.0-1363890249.commit-64dd58e

### Unity Version

1.0.17424-20211022234430.commit-3483ea2

### Realm

fenrir

### NameTag

LunarFox#c8c3

**Comment by moliva** [comment]
Hey @nicholasostman .
We are sorry about the delay in responding this!
This event and scene are no longer active, please open a new issue if this happens again in the future.
Thank you for reporting!

**Comment by nicholasostman** [comment]
LMAO yeah I'll be sure to do that so I can get another email MONTHS later
