### ISSUE TITLE
lose my account

### ISSUE THREAD

**Issue by daltonjjj** [decentraland/issues#441]
### What happened?

lose my account

### Steps to reproduce

1

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7 CPU 960 @ 3.20GHz

### GPU

NVIDIA GeForce GTX 1050 Ti 4018MB

### RAM

16375MB

### Kernel Version

1.0.0-2475769352.commit-8a2d7a3

### Unity Version

desktop-1.0.379-20220608191335.commit-d7ee49c

### Realm

dg

### NameTag

dali#cd74

**Comment by pravusjif** [comment]
can you provide us with more information to debug this issue?

**Comment by D4rWiNSS** [comment]
Close because there is no answer from the reporter
