### ISSUE TITLE
Mr.

### ISSUE THREAD

**Issue by ANDREIBAIS** [decentraland/issues#442]
### What happened?

I've been banned for thrice without a reason. I mean I'm playing fair then the Decentraland banned me. i hope I can retrieve my Ice, please help. I need it badly because thats for my son needs.
![report](https://user-images.githubusercontent.com/107445606/173469903-8f1dee3a-90bf-4c3b-a35c-d316b8885a88.png)

### Steps to reproduce

Just help me to retrieve my Ice. 

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36

### Wallet

Metamask

### CPU

AMD Ryzen 5 PRO 4650G with Radeon Graphics   3.70 GHz

### GPU

No GPU

### RAM

8.00 GB

### Kernel Version

1.0.0-2475769352.commit-8a2d7a3

### Unity Version

1.0.39035-20220609154533.commit-2f3b34d

### Realm

athena

### NameTag

SURAIDA#8cc9

**Comment by pravusjif** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
