### ISSUE TITLE
Captchas are broken

### ISSUE THREAD

**Issue by kubalaml** [decentraland/issues#443]
### What happened?

At different points in the Angel's Envy Meta Distillery tour, I was asked to fill in a captcha, but after many many attempts, it just kept prompting me for more captchas. After many attempts it just went to a Contacting Server screen and I had to exit out. 

### Steps to reproduce

1. Go on Angel's Distillery Tour
2. After completing the appropriate steps, get asked to fill out a captcha to receive a wearable
3. At this point the captcha will fail over and over again

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz

### GPU

NVIDIA GeForce GTX 1080 Ti 11128MB

### RAM

16348MB

### Kernel Version

1.0.0-2503059035.commit-0dd1ae6

### Unity Version

desktop-1.0.387-20220615161653.commit-3df2ab6

### Realm

baldr

### NameTag

Swan#56b5

**Comment by kuruk-mm** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
