### ISSUE TITLE
ICE Poker chips only 576 today

### ISSUE THREAD

**Issue by asdfghjkl10653** [decentraland/issues#445]
### What happened?

I was playing ICE poker when i realized i had only lost 400 and only had 166 avail. The wearable i wear usually has 3,000. I will provide screenshots

### Steps to reproduce

I am not really sure, fix it so i can play? 

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz

### GPU

NVIDIA GeForce 920M 2020MB

### RAM

8109MB

### Kernel Version

1.0.0-2503059035.commit-0dd1ae6

### Unity Version

desktop-1.0.387-20220615161653.commit-3df2ab6

### Realm

unicorn

### NameTag

asdfghjkl#015b

**Comment by asdfghjkl10653** [comment]
![Screenshot (78)](https://user-images.githubusercontent.com/107749248/174430473-62861aa6-ff63-4c2e-81e9-e6439edacc32.png)
![Screenshot (76)](https://user-images.githubusercontent.com/107749248/174430486-3afe3ac3-e4a5-4455-8a53-8df6330212f5.png)

**Comment by asdfghjkl10653** [comment]
I logged out and logged back in multiple times.

**Comment by kuruk-mm** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
