### ISSUE TITLE
problem in load information wonder mine

### ISSUE THREAD

**Issue by omiddir** [decentraland/issues#446]
### What happened?

hi
my account got problem with restore my information in wonder mine and every time I hop in wonder mine  everthing start with zero

my meta mask account
0x8D4986261fd3391afE4767a2fA942ac30c190d34

also
HeartBitPlayer#0d34

### Steps to reproduce

try out in another computer
log in with different trial account
try with an explorer
and so on

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz

### GPU

AMD Radeon HD 6670 1008MB

### RAM

8150MB

### Kernel Version

1.0.0-2503059035.commit-0dd1ae6

### Unity Version

desktop-1.0.387-20220615161653.commit-3df2ab6

### Realm

dg

### NameTag

HeartBitPlayer#0d34

**Comment by kuruk-mm** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
