### ISSUE TITLE
The In world builder is no longer available. 

### ISSUE THREAD

**Issue by tonsosons** [decentraland/issues#447]
### What happened?

No option to access the In world builder. 

### Steps to reproduce

While in world, click on your avatar on the top right. Across the top " Builder" was available now it is not there. I can still access the old web builder at builder.decentraland.org but the newer In world builder is gone. 

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz

### GPU

Intel(R) UHD Graphics 4013MB

### RAM

8026MB

### Kernel Version

1.0.0-2503059035.commit-0dd1ae6

### Unity Version

desktop-1.0.387-20220615161653.commit-3df2ab6

### Realm

hela

### NameTag

Tonsosons#f830

**Comment by fzavalia** [comment]
The builder in-world has been discontinued. There is a pending announcement for that but you should use the one at builder.decentraland.org
