### ISSUE TITLE
WALLET SUPPORT

### ISSUE THREAD

**Issue by alienne8** [decentraland/issues#45]
### What happened?

It says I DO NOT have not enough mana but I DO

### Steps to reproduce

LET ME BUY WHAT I WANT TO BUY WITH THE MANA I HAVE

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36

### Wallet

Metamask

### CPU

MAC

### GPU

AMD Radeon R9 M380 OpenGL Engine 512MB

### RAM

32G

### Kernel Version

1.0.0-1363890249.commit-64dd58e

### Unity Version

1.0.17452-20211023222002.commit-9f3fd74

### Realm

fenrir

### NameTag

Alienne#cdac

**Comment by olavra** [comment]
Hi @alienne8!
We need a bit more context about the MANA that you hold and what you are trying to buy. You need to consider that MANA can be now in 2 different Networks, Ethereum and Polygon. If you are trying to buy a wearable, most probably need to check if it belongs to the Polygon network and migrate some of your MANA to that network using account.decentraland.org. Hope this helps.

**Comment by davidejensen** [comment]
Closing this issue because of not having a response for more than two weeks.
