### ISSUE TITLE
Table Not loading

### ISSUE THREAD

**Issue by AkhriPastaaa** [decentraland/issues#450]
### What happened?

Suddenly from today my tables arent loading, and cant even claim my my chips to play everything else is loading. please help me with this bug? How do i claim the chips to start playing and the tables to load
![Prod Screenshot 2022 06 21 - 20 48 18 44](https://user-images.githubusercontent.com/104498084/174836595-84641afa-b3be-489e-be05-757c38362624.png)
?

### Steps to reproduce

Table Bugs A lot these days a fix would be great.

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 2600 Six-Core Processor 

### GPU

NVIDIA GeForce GTX 1660 5992MB

### RAM

15834MB

### Kernel Version

1.0.0-2529763428.commit-f5a0321

### Unity Version

desktop-1.0.393-20220620162122.commit-88e3597

### Realm

dg

### NameTag

AkhriPastaaa#f53b

**Comment by kuruk-mm** [comment]
Can you provide us with more information to debug this issue?

How much time did you wait?

Can you reproduce it constantly?

**Comment by AkhriPastaaa** [comment]
I tried everything the whole day , been more than 16hrs and i tried every
possible ways like browser changing my lan wire and what not. But it
doesn't seems to work. Please help me out with this bug. It would be of
great help.

**Comment by AkhriPastaaa** [comment]
i tried today again its the same issue, now more than 24hrs. My tables still dont load up and i cant event checkin to claim the chips. I have tried multiple times and all possible ways, but nothing works plz help me with this issue. how do i join the tables?
![Prod Screenshot 2022 06 22 - 13 06 24 80](https://user-images.githubusercontent.com/104498084/174971772-dcd3be81-b079-46fe-85f9-88f9d7392675.png)

**Comment by davidejensen** [comment]
Could you please try to use the web version to check if the issue persists there? Could you also try to change realm?

**Comment by Rodriasd** [comment]
BRO, I haven't been able to play for days, the same thing happens to me as you, I already reinstalled the chrome, the opera and the desktop, and nothing, I formatted the pc and neither !!!
IT IS THEIR PROBLEM, OR THEY BLOCK IP BELIEVING THAT WE ARE CHEATING, OR I DON'T KNOW THE TRUTH., I HAVE NOT BEEN ABLE TO PLAY FOR 7 DAYS, I HAVE THE ITEM FOR NOTHING

**Comment by lorux0** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client. Please contact the scene's owner.
