### ISSUE TITLE
Mastercard info cube screen

### ISSUE THREAD

**Issue by sipsavorslay** [decentraland/issues#451]
### What happened?

Once activated, screen cannot be closed.

### Steps to reproduce

Jump to experience
Click on "i" (info) cube
Message pops up X to close does not work

### Operating System

Windows 11  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz

### GPU

NVIDIA GeForce RTX 3080 Laptop GPU 8042MB

### RAM

32429MB

### Kernel Version

1.0.0-2548884389.commit-1a1bc66

### Unity Version

desktop-1.0.416-20220623144956.commit-c9134b0

### Realm

artemis

### NameTag

sipsavorslay

**Comment by davidejensen** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
