### ISSUE TITLE
DOES NOT LOAD THE SCENE

### ISSUE THREAD

**Issue by Rodriasd** [decentraland/issues#454]
### What happened?

I haven't been able to play for days, the same thing happens to me as you, I already reinstalled the chrome, the opera and the desktop, and nothing, I formatted the pc and neither !!!
IT IS THEIR PROBLEM, OR THEY BLOCK IP BELIEVING THAT WE ARE CHEATING, OR I DON'T KNOW THE TRUTH., I HAVE NOT BEEN ABLE TO PLAY FOR 7 DAYS, I HAVE THE ITEM FOR NOTHING
![image](https://user-images.githubusercontent.com/108191327/176246733-ede6339f-4391-4a4a-89a0-162670fc9c28.png)

### Steps to reproduce

I DON'T KNOW WHAT ELSE TO DO

### Operating System

chrome, windonws 11

### Wallet

Metamask

### CPU

ryzen 7 1700x

### GPU

2070

### RAM

16 ram 

### Kernel Version

1.0.0-2548884389.commit-1a1bc66

### Unity Version

1.0.40765-20220622131414.commit-3603482

### Realm

everybody

### NameTag

Rodri#3326

**Comment by lorux0** [comment]
hello, is this issue still happening to you?

**Comment by AjimenezDCL** [comment]
Can you provide us with more information to debug this issue?

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
