### ISSUE TITLE
i cant see my chips on poker decentraland .

### ISSUE THREAD

**Issue by MumuHugs** [decentraland/issues#457]
### What happened?

Im done with my quest in poker . then i played again. my chips are gone . in a good shot i screen shot my stuff before it happens because im a beginner in here im asking my friend and talk her about this game. then suddenly it comes the issue

### Steps to reproduce

![333](https://user-images.githubusercontent.com/108460125/176642960-bcac149c-ce26-4dff-b143-f15d47341e78.png)
![1234](https://user-images.githubusercontent.com/108460125/176642971-f8629cd8-11a9-4a35-9663-09b8e9ea35ea.png)

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 2600 Six-Core Processor 

### GPU

Radeon RX 580 Series 4074MB

### RAM

16320MB

### Kernel Version

1.0.0-2570291833.commit-c09e849

### Unity Version

desktop-1.0.416-20220623144956.commit-c9134b0

### Realm

dg

### NameTag

Slaqeoriman#8ee0

**Comment by lorux0** [comment]
please contact the scene's creator
