### ISSUE TITLE
my money is gone

### ISSUE THREAD

**Issue by Rozzy16** [decentraland/issues#459]
### What happened?

I had MANA and dentragames currency in my decentragames wallet but now its gone

### Steps to reproduce

I dont know

### Operating System

Windows 11  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz

### GPU

NVIDIA GeForce RTX 3060 Ti 8050MB

### RAM

16253MB

### Kernel Version

1.0.0-2590481394.commit-4b16c90

### Unity Version

desktop-1.0.416-20220623144956.commit-c9134b0

### Realm

marvel

### NameTag

Ozzie#5895

**Comment by lorux0** [comment]
Hello, can you please check if the MANA is displayed in your personal wallet correctly? Can you specify where you are seeing the MANA indicator with zero value?

**Comment by AjimenezDCL** [comment]
Can you provide us with more information to debug this issue?

**Comment by pravusjif** [comment]
Closing this issue because of not having a response for two weeks.
