### ISSUE TITLE
POAP and GLOWING CRATE

### ISSUE THREAD

**Issue by AngelaStGrace** [decentraland/issues#46]
### What happened?

During the Paris Hilton concert. I was able to get to the stage to claim a POAP. Only to get a yellow error message.

Later I opened a glowing create with a metaverse hat inside and now it isn't in my wallet.

### Steps to reproduce

.,..

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36

### Wallet

Metamask

### CPU

mac laptop

### GPU

AMD Radeon Pro 555X OpenGL Engine 512MB

### RAM

32gb

### Kernel Version

1.0.0-1363890249.commit-64dd58e

### Unity Version

1.0.17495-20211024193803.commit-19683dc

### Realm

loki

### NameTag

LadyC

**Comment by moliva** [comment]
Hey @AngelaStGrace .
We are sorry about the delay in responding this!
This event and scene are no longer active, please open a new issue if this happens again in the future.
Thank you for reporting!
