### ISSUE TITLE
Weareble delegated but not ingame

### ISSUE THREAD

**Issue by lakenetti** [decentraland/issues#460]
### What happened?

As the title says the wearable is delegated but cant use it ingame. its not shown

### Steps to reproduce

As the title says the wearable is delegated but cant use it ingame. its not shown

i did restart and everything

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

AMD FX(tm)-6300 Six-Core Processor 

### GPU

NVIDIA GeForce RTX 2060 5968MB

### RAM

16348MB

### Kernel Version

1.0.0-2590481394.commit-4b16c90

### Unity Version

desktop-1.0.416-20220623144956.commit-c9134b0

### Realm

odin

### NameTag

Budriel#d81f

**Comment by lorux0** [comment]
hello, thanks for reporting. Could you specify a little bit more about what do you mean with delegated wearable?

**Comment by AjimenezDCL** [comment]
Can you provide us with more information to debug this issue?

**Comment by pravusjif** [comment]
This is an issue with DG's own services.

Closing this issue because of not having a response for two weeks.
