### ISSUE TITLE
Im banned but why?

### ISSUE THREAD

**Issue by lakenetti** [decentraland/issues#461]
### What happened?

I played fine a couple of hands. Then there where not enough players. so i triede to get to a table. somehow ive been banned now.
Reaseo: more chips exploid

I have done nothing. i just want to play. 

This is so buggy. yesetrday i made a ticket with some other stuff. 

Im losing the fun of playing here. 

### Steps to reproduce

Read above

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

AMD FX(tm)-6300 Six-Core Processor 

### GPU

NVIDIA GeForce RTX 2060 5968MB

### RAM

16348MB

### Kernel Version

1.0.0-2590481394.commit-4b16c90

### Unity Version

desktop-1.0.416-20220623144956.commit-c9134b0

### Realm

baldr

### NameTag

Budriel#d81f

**Comment by lorux0** [comment]
please contact the creators of the scene
