### ISSUE TITLE
Getting kicked out from table

### ISSUE THREAD

**Issue by Puchiepuchiechu** [decentraland/issues#468]
### What happened?

In the middle of a game, i'm randomly getting kicked out from table, resulting, my chips that i bet will be split up by the remaining active hand players. 

what's annoying is that, when i have the winning hand, and i had all in already, and im just waiting for the round to be over, in the middle of the time where my opponents are thinking, i'll get kicked out. Resulting to a loss, then my chips will not be returned. PLEASE FIX THIS! THIS IS UNFAIR! ALMOST HAPPENING TO ME EVERYDAY!! AND IT'S ANNOYING ALREADY!!!

### Steps to reproduce

Put all chips and wait. 

### Operating System

Chrome, Windows 10

### Wallet

Metamask

### CPU

AMD Ryzen 5 PRO 3400G

### GPU

Radeon Vega Graphics   3.70 GHz

### RAM

8.00 GB

### Kernel Version

Latest

### Unity Version

Latest

### Realm

Hela, but happened almost in any realm

### NameTag

Nicole#74fb

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
