### ISSUE TITLE
can not see other people when using VPN

### ISSUE THREAD

**Issue by qpoisson** [decentraland/issues#47]
### What happened?

when accessing the website with VPN, can not see other player. It is fine after turning off VPN.

### Steps to reproduce

1 turn on VPN
2 log into decenteraland
3 jump into any land
4 cannot see other people in the same land

### Operating System

chrome, mac os 11.6

### Wallet

Metamask

### CPU

m1

### GPU

m1

### RAM

16G

### Kernel Version

latest

### Unity Version

latest

### Realm

any

### NameTag

test#5820

**Comment by olavra** [comment]
Hi @qpoisson! Thanks for your report! 
Some VPNs are not compatible with WebRTC, which is the protocol that we are using for our communications. We do not support VPNs for now. Sorry for the inconveniences.
