### ISSUE TITLE
UI wont hide

### ISSUE THREAD

**Issue by ghost** [decentraland/issues#473]
### What happened?

Most of the time When I log in to the client, the full UI wont hide when pressing "U",  the avatar icon top right corner and chat/friends/mic icons at bottom left corner doesnt hide. I've tried toggling various setting in the menu on and off, of cause including the "hide UI" switch, skybox, resolutions, different realms and locations.

Only once did I get it to hide the full UI, without any logical reasoning behind why it worked at that time.
its pretty frustrating when trying to do screenshots and videos.

Happens w wallet connect and with "guest mode"

### Steps to reproduce

login with wallet connect or guest mode, click "U" > only hides parts of the UI > no option to hide the full U

Hiden UI "U"
<img width="1444" alt="Hide UI" src="https://user-images.githubusercontent.com/48699098/178482002-dc90f846-c1de-4e0f-8967-ac2fe4b24d6a.png">

Normal visible UI mode
<img width="1452" alt="Normal full UI" src="https://user-images.githubusercontent.com/48699098/178482013-2be9b247-c714-47e4-9a24-5b312f2d0319.png">
I

### Operating System

Mac OS X 12.3.1

### Wallet

Wallet Connect

### CPU

Apple M1 Max

### GPU

Apple M1 Max 49152MB

### RAM

65536MB

### Kernel Version

1.0.0-2638443584.commit-696a74b

### Unity Version

desktop-1.0.455-20220707134647.commit-e3e69ac

### Realm

hela

### NameTag

Slywest

-----------

I have found a weird temporary fix.

- click on voice chat in the bottom left corner
- click join 
- click leave
- exit voice chat
- Click "U"
it will now hide the full UI

apparently rn you're required to join the voice chat once, every time you log in, for the full "hide ui" to work.

though this step should def not be required to use "hide ui"

**Comment by AjimenezDCL** [comment]
Thanks for reporting, this has been fixed here: https://github.com/decentraland/unity-renderer/issues/2621

In our next release it should be in production already.
