### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by beccapana** [decentraland/issues#475]
### What happened?

If you will fail your mission on golfcraft and start a new mission, map willn't load
video: youtu.be/drgcny9bKks

### Steps to reproduce

go to golfcraft
start a new mission
fail it
start a new mission again
bug

### Operating System

Windows 10

### Wallet

Metamask

### CPU

AMD Ryzen 7 3700X 8-Core

### GPU

NVIDIA RTX2060

### RAM

16

### Kernel Version

1.0.0-2658915233

### Unity Version

1.0.455-20220707134647

### Realm

unicorn

### NameTag

beccapana#8ee2

**Comment by AjimenezDCL** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.
