### ISSUE TITLE
VIP Password prompt doesn't go away when you leave

### ISSUE THREAD

**Issue by Battsie** [decentraland/issues#476]
### What happened?

![Decentral bug](https://user-images.githubusercontent.com/64389108/179047963-0f535b02-0493-4875-8ab5-40d277111b05.PNG)
Even when not in VIP area, if you don't enter password, this stays on the screen

### Steps to reproduce

Go to VIP area, don't enter password, and leave.

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

None, played as guest

### CPU

Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

### GPU

NVIDIA GeForce RTX 3080 Ti 12108MB

### RAM

65487MB

### Kernel Version

1.0.0-2658915233.commit-9209529

### Unity Version

desktop-1.0.479-20220714165132.commit-becdc13

### Realm

hela

### NameTag

Cat#2fc4

**Comment by pravusjif** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client. You could try contacting the scene creator to fix the issue.
