### ISSUE TITLE
reward missing

### ISSUE THREAD

**Issue by BTCFab** [decentraland/issues#479]
### What happened?

Hi, in Wondermine, moving to level 16, popup says there is a 20 gold reward ... But never been added to my bagpack ... 
Have a nice day ^^

### Steps to reproduce

nothing to say about this bug more than what i already said

### Operating System

Windows 7  (6.1.0) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz

### GPU

Intel(R) HD Graphics 4000 1632MB

### RAM

7888MB

### Kernel Version

1.0.0-2673696742.commit-535b3fa

### Unity Version

desktop-1.0.481-20220714181434.commit-d37208d

### Realm

dg

### NameTag

Player1#9abd

**Comment by pravusjif** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client. You could try contacting the scene creator to fix the issue.
