### ISSUE TITLE
Dragon City Quest Tangram

### ISSUE THREAD

**Issue by Preisolauphenonputenic** [decentraland/issues#48]
### What happened?

I was in the middle of the forest maze part of the quest w/ the black and white grim reapers.  I had found the black grim reaper, and it took me to the next part of the quest.  I had to refresh my page, and it took me back to the start of that part of the quest, and now the black grim reaper won't send me back to the next part of the quest, so I'm stuck.

### Steps to reproduce

1.  Begin the Dragon City Quest Tangram.  2.  Proceed through the steps until you get to the Forest maze w/ the Black & White Grim Reapers.  3.  Find the Black Grim Reaper and go through the discussion with him where he gives you the next tangram and sends you to the 'Welcome to the Jungle' screen.  4.  Refresh your screen.  5.  This refresh should take you back to the start of the Forest maze where the you can only find the Black Grim Reaper in the maze, and all he'll tell you is 'Come On Warriors'.

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36

### Wallet

Metamask

### CPU

2.6 GHz 6-Core Intel Core i7

### GPU

AMD Radeon Pro 5500M OpenGL Engine 512MB

### RAM

16 GB 2667 MHz DDR4

### Kernel Version

1.0.0-1363890249.commit-64dd58e

### Unity Version

1.0.17531-20211025074527.commit-1ea0025

### Realm

loki

### NameTag

Preisolauphenon#fd26

**Comment by yore-trash** [comment]
Leave the maze and return through the Jump to link... You should return to the Welcome to the Jungle part.

**Comment by moliva** [comment]
Hi @Preisolauphenonputenic  !
Sorry for the delay. This feature is currently disabled in the platform.
Thanks for reporting!
