### ISSUE TITLE
coin drops in Wondermine

### ISSUE THREAD

**Issue by johnluke11a** [decentraland/issues#481]
### What happened?

The number of coins I have just keeps dropping I went from 2000 coin to 50 in an hour 

### Steps to reproduce

Refund my coins and stop this issue

### Operating System

Windows 11  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx 

### GPU

AMD Radeon(TM) Vega 8 Graphics 3045MB

### RAM

6091MB

### Kernel Version

1.0.0-2673696742.commit-535b3fa

### Unity Version

desktop-1.0.481-20220714181434.commit-d37208d

### Realm

dg

### NameTag

Fire11#2c78

**Comment by pravusjif** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client. You could try contacting the scene creator to fix the issue.
