### ISSUE TITLE
me quitaron los ice sin motivo

### ISSUE THREAD

**Issue by jcarlosgiil** [decentraland/issues#482]
### What happened?

me quitaron los ice y me marca error no puedo jugar 

### Steps to reproduce

devolverme los ice 

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

### Wallet

Metamask

### CPU

hp 

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GT 710 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

8 ram

### Kernel Version

1.0.0-2673696742.commit-535b3fa

### Unity Version

1.0.44188-20220714171940.commit-6146b15

### Realm

marvel

### NameTag

walterwhite#6e5a

**Comment by pravusjif** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client. You could try contacting the scene creator to fix the issue.
