### ISSUE TITLE
Lost progress in a game

### ISSUE THREAD

**Issue by Salamontes** [decentraland/issues#485]
### What happened?

Hi, I am visiting the event in Decentraland Battle-to-Earn RPG and I've already mined lots of coins and now, a day after I come back and all the progress  is lost. Also the game crashes on mac os sometimes, even with low resolution settings. In web browser it's not possible to play at all. 
Photos of my game progress one day ago and today. All progress lost.
![Screenshot 2022-07-15 at 22 32 55](https://user-images.githubusercontent.com/109667790/179973005-ba151d3f-a6fd-4394-b3d1-4a7700604149.png)
![Screenshot 2022-07-20 at 14 39 59](https://user-images.githubusercontent.com/109667790/179973159-01397415-50ef-46e3-a1d3-0eb8fe44a435.png)

### Steps to reproduce

Just quit the game completely and logged back in. Twice lost all the progress.

### Operating System

Mac OS X 12.4.0

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz

### GPU

Intel(R) Iris(TM) Plus Graphics 655 1536MB

### RAM

8192MB

### Kernel Version

1.0.0-2698790060.commit-1ccbd20

### Unity Version

desktop-1.0.481-20220714181434.commit-d37208d

### Realm

hephaestus

### NameTag

Kliyarac#ebe4

**Comment by pravusjif** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client.

You could try contacting the scene creator to fix the issue.
