### ISSUE TITLE
Woodstone Mansion in Decentraland - NFT's codes not showing

### ISSUE THREAD

**Issue by TheWaveFlows** [decentraland/issues#487]
### What happened?

Been trying to gather all NFTs from [Woodstone Mansion in Decentraland](https://play.decentraland.org/?NETWORK=mainnet&position=-16,146) but, sometimes, when I reach one of the characters, it dowesnt show the window to click to receive the NFT.
Already did this more than 10 times, and always fails in 1 at least. So far, I'm still missing the last one from Jay Arondekar.

### Steps to reproduce

Just doing things normal. Its ramdom when it doesnt trigger the raclaim NFT window.

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz

### GPU

NVIDIA GeForce RTX 2070 Super 8012MB

### RAM

32600MB

### Kernel Version

1.0.0-2714369718.commit-2f5adfb

### Unity Version

desktop-1.0.487-20220722140000.commit-e528a92

### Realm

dg

### NameTag

AverageJoe#9e4c

**Comment by sandrade-dcl** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client. You could try contacting the scene creator to fix the issue.
