### ISSUE TITLE
Bug: Not working last sub quest at Steam Punk by DappCraft

### ISSUE THREAD

**Issue by chagasrodrigo** [decentraland/issues#49]
### What happened?

I can not complete the quest Steam Punk by DappCraft. I've tried to talk with Anna to complete, but my user account doesnt work and I can not finnish the quest.

### Steps to reproduce

I can not complete the quest Steam Punk by DappCraft. I've tried to talk with Anna to complete, but my user account doesnt work and I can not finnish the quest.

As you can see at the position with my user
https://play.decentraland.org/?island=Ik8u6&position=38%2C12&realm=loki

Screenshot
https://prnt.sc/1xidcp4

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36

### Wallet

Metamask

### CPU

Intel i7

### GPU

ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8935) 512MB

### RAM

16gb

### Kernel Version

1.0.0-1363890249.commit-64dd58e

### Unity Version

1.0.17713-20211026202347.commit-c3b8f3d

### Realm

loki

### NameTag

mr4cha#857b

**Comment by nearnshaw** [comment]
Hi!

The issue with this quest has now been resolved, thanks for reporting

If you enter the scene with the same account you originally used, you should now be able to talk to the NPC to complete the final step, and this time you'll receive the reward for completing the quest.

https://play.decentraland.org/?position=38%2C12

**Comment by chagasrodrigo** [comment]
Other errors
[image: error-1.jpg][image: error-2.jpg]

Em seg., 8 de nov. de 2021 às 18:05, Nicolas Earnshaw <
***@***.***> escreveu:
