### ISSUE TITLE
DCL Wonder Mine:  WonderZone caps 

### ISSUE THREAD

**Issue by PeterAp57** [decentraland/issues#491]
### What happened?

The craft machine under WonderZone caps  shows availability of 9, but does not allow you to craft.

### Steps to reproduce

just go to the crafting cart and select WonderZone cap

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

AMD Athlon(tm) X4 860K Quad Core Processor 

### GPU

NVIDIA GeForce RTX 3060 Ti 8050MB

### RAM

8139MB

### Kernel Version

1.0.0-2714369718.commit-2f5adfb

### Unity Version

desktop-1.0.487-20220722140000.commit-e528a92

### Realm

dg

### NameTag

5sata#0a77

**Comment by Kinerius** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client. You could try contacting the scene creator to fix the issue.
