### ISSUE TITLE
Unable to exit game with sign out or exit option

### ISSUE THREAD

**Issue by dUBSP** [decentraland/issues#492]
### What happened?

Hello guys, I was unable to exit the game. I tried pressing the exit and the sign out option. Neither would allow me to shut down game. I had to report a bug in order to get the window to minimize, which allowed me to exit the game. Now I am worried if all the work I put in, connecting my wallet and creating my avatar will have to be done over. 

### Steps to reproduce

1. Sign in with coinbase
2. Get taken to create a character 
3. Create avatar and get ported to DG server
4. Observe a few things, attempt to interact with a player by trying to view their info with the left mouse click, unable to do that.
5. interact with games and events kiosk
6. walk to center portal but choose to turn and jump out of portal
7. Attempt to exit game
8. Travel to another area on map
9. Attempt to exit game by sign out and exit
10. Travel to Marvel server
11. Walk around a bit then attempt to exit game

### Operating System

Windows 11  (10.0.22000) 64bit

### Wallet

Wallet Connect

### CPU

11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz

### GPU

NVIDIA GeForce RTX 3050 Ti Laptop GPU 3990MB

### RAM

24318MB

### Kernel Version

1.0.0-2714369718.commit-2f5adfb

### Unity Version

desktop-1.0.487-20220722140000.commit-e528a92

### Realm

marvel

### NameTag

Unnealasan#fec2

**Comment by Kinerius** [comment]
This was fixed on the latest release, thank you for reporting!
