### ISSUE TITLE
Decentraland CLient Sign out bug

### ISSUE THREAD

**Issue by AkhriPastaaa** [decentraland/issues#493]
### What happened?

i cannot sign out or exit my account from the client. please help me with this issue how to log out?

### Steps to reproduce

what should i do to fix this problem

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 2600 Six-Core Processor 

### GPU

NVIDIA GeForce GTX 1660 5992MB

### RAM

15834MB

### Kernel Version

1.0.0-2714369718.commit-2f5adfb

### Unity Version

desktop-1.0.487-20220722140000.commit-e528a92

### Realm

dg

### NameTag

AkhriPastaaa#f53b

**Comment by Kinerius** [comment]
This was fixed on the latest release, thank you for reporting!
