### ISSUE TITLE
Music and Video not working

### ISSUE THREAD

**Issue by grafkaal** [decentraland/issues#494]
### What happened?

In a lot of locations that have music and video, there is no sound or video feed.
You can still hear all the other in-game audio.
One location that this happen a lot is 132, -2 The Inn and also  111, -23 Meta Zoo Int Boat House.

### Steps to reproduce

Just visit the locations, could be Mac specif as no PC to test it.

### Operating System

Mac OS X 10.13.6

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz

### GPU

NVIDIA GeForce GTX 780M 4096MB

### RAM

24576MB

### Kernel Version

1.0.0-2784032865.commit-a2fe442

### Unity Version

desktop-1.0.501-20220729181828.commit-0a5320a

### Realm

dg

### NameTag

Grafkaal

**Comment by Kinerius** [comment]
Thank you for reporting! We already are tracking this issue, so I'm going to close this one.
