### ISSUE TITLE
Terrible performance

### ISSUE THREAD

**Issue by ktimam** [decentraland/issues#495]
### What happened?

Performance is terrible using the desktop app on windows.

### Steps to reproduce

Performance is terrible using the desktop app on windows.

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

11th Gen Intel(R) Core(TM) i7-1160G7 @ 1.20GHz

### GPU

Intel(R) Iris(R) Xe Graphics 8063MB

### RAM

16126MB

### Kernel Version

1.0.0-2785459950.commit-fc527e7

### Unity Version

desktop-1.0.508-20220803173003.commit-fa5b53d

### Realm

artemis

### NameTag

Kiko

**Comment by Kinerius** [comment]
Can you provide us with more information to debug this issue? Especially the coordinates of the unperformant scene.

**Comment by davidejensen** [comment]
Closing this issue because of not having a response for two weeks.
