### ISSUE TITLE
Voice chat doesn't work in Firefox

### ISSUE THREAD

**Issue by tsume-san** [decentraland/issues#499]
### What happened?

I use firefox to voice chat, but my friend can't hear me.
By the way, Voice chat worked fine for me in Chrome.

### Steps to reproduce

I have installed the latest version of Firefox.
I allowed to use the microphone.
And I tested my mic with Firefox on the mic test site.

### Operating System

Firefox 103.0.1 (64bit), Windows 10

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz 3.40 GHz

### GPU

NVIDIA GeForce GT 320

### RAM

8GB

### Kernel Version

1.0.0-2803737193.commit-ef753b1

### Unity Version

1.0.47078-20220803165043.commit-08eab36

### Realm

gd

### NameTag

Tsume#838f

**Comment by lorux0** [comment]
this issue is duplicated to [#400](https://github.com/decentraland/sdk/issues/400)
