### ISSUE TITLE
Can't finish SteamPunk DC Quest

### ISSUE THREAD

**Issue by joolztheviking** [decentraland/issues#50]
### What happened?

Hello there!

I can't finish the SteamPunk DC Quest.

The last thing to do in this quest is to talk to Anna.
When I do she replies: "Your reward is waiting for you" "Hope you enjoyed"
But I don't get my reward and I'm still at 4/5 of the quest...

Can you help?

Thanks a lot :-)
joolztheviking

### Steps to reproduce

Please just let me finish the quest :-)

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Metamask

### CPU

i9

### GPU

Apple M1 512MB

### RAM

32GB

### Kernel Version

1.0.0-1391805960.commit-bbcb4e2

### Unity Version

1.0.17961-20211028102204.commit-e983535

### Realm

loki odin doesn't matter

### NameTag

joolztheviking#f040

**Comment by nearnshaw** [comment]
Hi!

The issue with this quest has now been resolved, thanks for reporting

If you enter the scene with the same account you originally used, you should now be able to talk to the NPC to complete the final step, and this time you'll receive the reward for completing the quest.

https://play.decentraland.org/?position=38%2C12
