### ISSUE TITLE
Tominoya 122,134

### ISSUE THREAD

**Issue by OnixInferno** [decentraland/issues#501]
### What happened?

One of the slot machines took my money and never stopped spinning 

### Steps to reproduce

Just bet on the slot machines 

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz

### GPU

NVIDIA GeForce RTX 3060 Ti 8050MB

### RAM

16266MB

### Kernel Version

1.0.0-2803737193.commit-ef753b1

### Unity Version

desktop-1.0.508-20220803173003.commit-fa5b53d

### Realm

marvel

### NameTag

Onix#b3da

**Comment by lorux0** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client. You could try contacting the scene creator to fix the issue.
