### ISSUE TITLE
Level sumiu.

### ISSUE THREAD

**Issue by Dtrezeofc** [decentraland/issues#502]
### What happened?

Comecei a pouco tempo conhecer o decentraland. Comecei a usar a wondermine. Conseguir chegar até o level 5. Porém agora acabei de entrar na plataforma. E tudo que Eu havia conquistado. Sumiu!

Desde já. Gratidão

### Steps to reproduce

![image](https://user-images.githubusercontent.com/89828250/184121355-f60e012e-8efa-406a-9031-d3bff4a685ae.png)

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Wallet Connect

### CPU

Intel(R) Core(TM) i5-4460S CPU @ 2.90GHz

### GPU

Intel(R) HD Graphics 4600 2048MB

### RAM

7644MB

### Kernel Version

1.0.0-2835179067.commit-bcebdbc

### Unity Version

desktop-1.0.516-20220810181531.commit-3692e47

### Realm

hephaestus

### NameTag

BobGren#7c1d

**Comment by lorux0** [comment]
please contact the scene's creator issue
