### ISSUE TITLE
UI-TABLES NOT LOADING

### ISSUE THREAD

**Issue by manterax** [decentraland/issues#504]
### What happened?

My job want us to use work VPN after i install it to my computer my poker is no longer working, tables and ui is not showing.

![image](https://user-images.githubusercontent.com/111542650/185510520-523a3a67-fe9e-41ba-a9ac-d8d70b6d8733.png)

### Steps to reproduce

I tried to uninstall that VPN - CLEAR EVERYTHING ON CHROME - RESET SETTINGS ON THE GAME - CHANGING MY DNS TO 8.8.8.8 8.8.4.4 (MIGHT HELP IDK) but still nothing is happening. for 2 days 

### Operating System

Chrome/104.0.5112.102

### Wallet

Metamask

### CPU

ryzen 5 2600

### GPU

ANGLE (AMD, Radeon RX 570 Series Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

16gb

### Kernel Version

1.0.0-2877189490.commit-01c0714

### Unity Version

1.0.49704-20220817150556.commit-9c13d73

### Realm

hephaestus

### NameTag

COLEEN#40f7

**Comment by davidejensen** [comment]
This issue is related either to the VPN or the scene implementation.

Previously other people encountered this problem and as a workaround managed to make everything load with a different browser.
