### ISSUE TITLE
Cant repair my axe

### ISSUE THREAD

**Issue by kovacbranko** [decentraland/issues#506]
### What happened?

I can't restore my axe, even when I press
lever to restore the axe, the wonder coins are used up
the ax is made but there is still 0 in the bag
I tried to repeat it a couple of times but always the same,
can you help me solve this situation

### Steps to reproduce

try to upgrade your ax when it breaks

### Operating System

win 11

### Wallet

Metamask

### CPU

AMD Ryzen 5 5600X

### GPU

Nvidia GTX 1650

### RAM

32gb

### Kernel Version

1.0.0-2891534524.commit-bd0f189

### Unity Version

1.0.49990-20220819104049.commit-6783408

### Realm

dg

### NameTag

kovacbranko#7f13

**Comment by kwspgoliasz** [comment]
Hi, thank you for reporting this issue to us. If possible, could you provide us with more information to debug this issue?
The specific coordinates for the location and a screenshot or a short video clip would be especially helpful.

**Comment by kwspgoliasz** [comment]
Hi, we'll be closing this issue as there was no response for two weeks. If the issue still occurs for you, please don't hesitate to contact us by reopening this issue.
