### ISSUE TITLE
Black patch on the screen in the decenterland

### ISSUE THREAD

**Issue by jarnahom** [decentraland/issues#508]
### What happened?

Black patch on the screen in the decenterland

### Steps to reproduce

.

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz

### GPU

Intel(R) Iris(R) Xe Graphics 8032MB

### RAM

16064MB

### Kernel Version

1.0.0-2929857607.commit-cfda590

### Unity Version

desktop-1.0.541-20220825233913.commit-050c3d5

### Realm

artemis

### NameTag

Mohanraj#716f

**Comment by kwssbocian** [comment]
Can you provide us with more information to debug this issue? We'd appreciate if you could describe what were you doing at the time of the issue and also provide the coordinates of the location you have experienced the issue at. Additionally a screenshot would be most helpful.

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
