### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Fackyoibutch** [decentraland/issues#509]
### What happened?

impossile to finish the quest to grab a poker pants in the box in the maze

### Steps to reproduce

impossile to finish the quest to grab a poker pants in the box in the maze

### Operating System

Windows 11  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz

### GPU

NVIDIA GeForce RTX 3050 Ti Laptop GPU 3990MB

### RAM

16085MB

### Kernel Version

1.0.0-2949092612.commit-101f737

### Unity Version

desktop-1.0.541-20220825233913.commit-050c3d5

### Realm

heimdallr

### NameTag

Fackyoibutch#17fb

**Comment by kwspgoliasz** [comment]
Hello, thank you for contacting us. If possible, we'd like to request some additional information in order to properly deal with this issue. Could you provide us with the coordinates of the scene and an additional screenshot (or a video) showing the issue?

**Comment by kwspgoliasz** [comment]
Due to lack of response for two weeks, the ticket will be closed. If the issue still occurs, please do not hesitate to contact us again by reopening the ticket.
