### ISSUE TITLE
SteamPunk by DappCraft Quest

### ISSUE THREAD

**Issue by Preisolauphenonputenic** [decentraland/issues#51]
### What happened?

The quest won't let me complete it.  The last thing I have to do is speak w/ Anna again, and every time I do, she tells me my reward is waiting for me, but the quest won't show 'complete', and I don't get the badge.  The first time I spoke w/ her after completing the quest and activating the lever, she said some stuff that clued me in that the quest was complete, but it appears the quest is glitching out and not giving me my reward.

### Steps to reproduce

Run through the Quest, activate the switch, and speak w/ Anna the 2nd time.  In my case, she'll tell you great job, thank you, and go through the dialogue telling you you received your reward.

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36

### Wallet

Metamask

### CPU

2.6 GHz 6-Core Intel Core i7

### GPU

AMD Radeon Pro 5500M OpenGL Engine 512MB

### RAM

16 GB 2667 MHz DDR4

### Kernel Version

1.0.0-1399471884.commit-6aa8480

### Unity Version

1.0.18126-20211029133620.commit-42454bc

### Realm

artemis

### NameTag

Preisolauphenon#fd26

**Comment by nearnshaw** [comment]
Hi!

The issue with this quest has now been resolved, thanks for reporting

If you enter the scene with the same account you originally used, you should now be able to talk to the NPC to complete the final step, and this time you'll receive the reward for completing the quest.

https://play.decentraland.org/?position=38%2C12
