### ISSUE TITLE
Cant join in table, cards not clickable

### ISSUE THREAD

**Issue by Alcyd** [decentraland/issues#511]
### What happened?

Cant join in table, cards not clickable

### Steps to reproduce

Cant join in table, cards not clickable

### Operating System

Windows 10  (10.0.19042) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 2400G with Radeon Vega Graphics 

### GPU

NVIDIA GeForce GTX 1050 Ti 4018MB

### RAM

16331MB

### Kernel Version

1.0.0-2962066080.commit-0d7454e

### Unity Version

desktop-1.0.554-20220831145848.commit-56c8ecc

### Realm

dg

### NameTag

Alcyd#8ff8

**Comment by Alcyd** [comment]
Any update on this.

**Comment by kwspgoliasz** [comment]
Hello, thank you for reporting this issue to us. The latest update should have fixed the issue with the interactions. Please try to check if the issue still occurs in the latest version of the app. In case of any further issues do not hesitate to contact us again.
