### ISSUE TITLE
Problems with the marketplace

### ISSUE THREAD

**Issue by rubernumerus** [decentraland/issues#513]
### What happened?

Search filters on Decentraland Marketplace do not work.

### Steps to reproduce

Please repair product search filters, they do not respond to clicks

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Wallet Connect

### CPU

11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz

### GPU

NVIDIA GeForce MX350 1979MB

### RAM

7884MB

### Kernel Version

1.0.0-2714369718.commit-2f5adfb

### Unity Version

desktop-1.0.487-20220722140000.commit-e528a92

### Realm

decentraland marketplace

### NameTag

rubernumerus#dc48

**Comment by kwssbocian** [comment]
Hi, thank you for reporting this issue. Can you please provide us with additional information such as which exact filters were not working for you and possibly a screenshot/video of the issue? Also could you please try whether the issue also occurs for you on a different browser and after clearing your browser's cookies/cache?

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
