### ISSUE TITLE
trapped in castle

### ISSUE THREAD

**Issue by ckjkumar** [decentraland/issues#514]
### What happened?

I went to complete castle quest and got stuck after completing the quest I did not got any rewards, so I jumped outside and  went back for the quest and reward now I am stuck in armory.

### Steps to reproduce

completely check the quest again
![Screenshot 2022-09-04 001813](https://user-images.githubusercontent.com/62317613/188284265-e40ba639-dd56-4d2f-8a48-fe5d93aa0c92.png)

### Operating System

Windows 11  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

12th Gen Intel(R) Core(TM) i7-12650H

### GPU

NVIDIA GeForce RTX 3050 Laptop GPU 3991MB

### RAM

24244MB

### Kernel Version

1.0.0-2962066080.commit-0d7454e

### Unity Version

desktop-1.0.572-20220902135606.commit-6c11e72

### Realm

hela

### NameTag

CKJ#c3ed

**Comment by kwssbocian** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client. Please try contacting the scene creator in order to fix the issue.
