### ISSUE TITLE
9/8/2022 - Some avatars are not appearing 

### ISSUE THREAD

**Issue by acrosscoder** [decentraland/issues#518]
### What happened?

Issues:
*some avatars are not showing (depending on users)
* on other user's end few avatars appear
* avatars don't appear even when changing realms
* avatar loading

### Steps to reproduce

by loading in decentraland any locations

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 3 2200G with Radeon Vega Graphics 

### GPU

NVIDIA GeForce GT 730 2007MB

### RAM

8140MB

### Kernel Version

1.0.0-3008254642.commit-f7c1434

### Unity Version

desktop-1.0.572-20220902135606.commit-6c11e72

### Realm

dg

### NameTag

JimSedric

**Comment by kwspgoliasz** [comment]
Hi, thank you for reporting this to us. The issues with avatars were fixed in the latest version of Decentraland, so updating the platform should fix these problems.
If the issues will persist after the update, please contacts us again by reopening this ticket.
