### ISSUE TITLE
Toki Land

### ISSUE THREAD

**Issue by macJames976** [decentraland/issues#519]
### What happened?

After push snow man is impossible take key

### Steps to reproduce

push snowman and take to take a key

### Operating System

Windows 11  (10.0.22000) 64bit

### Wallet

None, played as guest

### CPU

11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz

### GPU

Intel(R) Iris(R) Xe Graphics 8055MB

### RAM

16110MB

### Kernel Version

1.0.0-3010216043.commit-0abe595

### Unity Version

desktop-1.0.572-20220902135606.commit-6c11e72

### Realm

hela

### NameTag

macjames#b69f

**Comment by kwssbocian** [comment]
Thank you for reporting this issue. Can you provide us with more information such as the location (coordinates) and a screenshot/video of the issue occurring?

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
