### ISSUE TITLE
Crafting item didn't appear

### ISSUE THREAD

**Issue by Koko65** [decentraland/issues#520]
### What happened?

Hello!
While playing the WonderMine crafting game, I created a WonderZone Logo Cap and that clothes didn't appear in my inventory. It's been a few days since I made it. Resources were taken for it (2 wearables tokens and others), but the cap was not credited, please correct this unfortunate misunderstanding! Thank you
-29, 55

### Steps to reproduce

Add this item

### Operating System

Windows 10  (10.0.14393) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz

### GPU

NVIDIA GeForce GTX 960 2007MB

### RAM

8128MB

### Kernel Version

1.0.0-3046078665.commit-09675ea

### Unity Version

desktop-1.0.580-20220912223148.commit-52c962e

### Realm

dg

### NameTag

Alligator#5b94

**Comment by kwspgoliasz** [comment]
Hi, thank you for reaching out to us. The issue you mentioned is a problem with the scene SDK implementation, not with Decentraland's client. Please try contacting the scene creator in order to fix this issue.
