### ISSUE TITLE
error en golf craft

### ISSUE THREAD

**Issue by faloup** [decentraland/issues#528]
### What happened?

error en golf craft uno de los entrenamientos no funciona y se queda trabado como que se termino el tiempo. el del hoyo en uno.

### Steps to reproduce

inciciar el entrenamiento de golf craft (48,-44) hasta que les toque hacer ese entrenamiento.

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Wallet Connect

### CPU

Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

### GPU

NVIDIA GeForce GTX 1050 4019MB

### RAM

12171MB

### Kernel Version

1.0.0-3106729404.commit-4698e1d

### Unity Version

desktop-1.0.614-20220923172652.commit-85e7e67

### Realm

hephaestus

### NameTag

imel#1b7b

**Comment by kwspgoliasz** [comment]
Hi, thank you for reaching out to us. This is a problem with the scene SDK implementation, not with Decentraland's client. You could try contacting the scene creator in order to fix this issue.
