### ISSUE TITLE
SteamPunk by DappCraft

### ISSUE THREAD

**Issue by metaverser** [decentraland/issues#53]
### What happened?

There is a clock quest that says to collect all 5 gears and insert them all. I found them all and insert them all but Anna who is Quest NPC doesn't complete quest and doesn't give rewards. I talk with people nobody gets it.

### Steps to reproduce

Fix error

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36

### Wallet

Metamask

### CPU

Inter i7 7th

### GPU

ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8681) 512MB

### RAM

16

### Kernel Version

1.0.0-1399994176.commit-9bd8e36

### Unity Version

1.0.18126-20211029133620.commit-42454bc

### Realm

loki

### NameTag

Fatih#5c44

**Comment by nearnshaw** [comment]
Hi!

The issue with this quest has now been resolved, thanks for reporting

If you enter the scene with the same account you originally used, you should now be able to talk to the NPC to complete the final step, and this time you'll receive the reward for completing the quest.

https://play.decentraland.org/?position=38%2C12
