### ISSUE TITLE
Waiting fir shot

### ISSUE THREAD

**Issue by moiper15** [decentraland/issues#534]
### What happened?

cuando trato de disparar la pelota se queda en esa acción

### Steps to reproduce

Playing glof craft

### Operating System

Windows 11  (10.0.22621) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz

### GPU

NVIDIA GeForce GTX 1650 3962MB

### RAM

8029MB

### Kernel Version

1.0.0-3221083740.commit-8485118

### Unity Version

desktop-1.0.641-20221006152813.commit-5f8ac22

### Realm

baldr

### NameTag

MOIPER#1701

**Comment by kwssbocian** [comment]
Hi, thank you for reporting this with us. Could you please provide us with some more information so that we could debug this issue? We'd need the coordinates for the scene and we'd also be grateful for a screenshot or a video of the issue.

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
