### ISSUE TITLE
Avatars are not showing/loading in

### ISSUE THREAD

**Issue by acrosscoder** [decentraland/issues#536]
### What happened?

I tried visiting other places....then the avatars are not showing or loading at all
the realm shows visitor's quantity but doesn't show the avatar visitors

### Steps to reproduce

try teleporting to some of the top places

what I tried so far
* changing realms
* reloading the page
* clearing the cache

still same result ...the avatars arent showing

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

### Wallet

Metamask

### CPU

Ryzen 7 CPU

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GT 710 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

32GB

### Kernel Version

1.0.0-3251602826.commit-d234e63

### Unity Version

1.0.57934-20221013161320.commit-72f1dfe

### Realm

baldr

### NameTag

JimSedric

**Comment by renkcub** [comment]
I had the same issue here, answered the devs, and was ignored and marked closed. 

https://github.com/decentraland/issues/issues/261

**Comment by kwspgoliasz** [comment]
Hi, sorry to have kept you waiting. Unfortunately we were not able to reproduce the issue on our side. Do you still experience the issue? If you do, please try reinstalling the browser and then trying to log in once again. If it won't help, could you please provide us with a video (preferably starting from the point of logging into Decentraland) showing the issue.

**Comment by renkcub** [comment]
I will provide a video. Note that this only happens on Chrome. I've noticed others having issues on Chrome in various ways.

**Comment by renkcub** [comment]
https://vimeo.com/773348731 - Chrome video. Note other players don't load. Attempted several scenes, server changes, page reload, and displayed settings.
https://vimeo.com/773349131 - Desktop client video. Other players load fine, but load times are about twice as long consistently for some reason (separate issue)?

**Comment by renkcub** [comment]
> Hi, sorry to have kept you waiting. Unfortunately we were not able to reproduce the issue on our side. Do you still experience the issue? If you do, please try reinstalling the browser and then trying to log in once again. If it won't help, could you please provide us with a video (preferably starting from the point of logging into Decentraland) showing the issue.

https://vimeo.com/773348731 - Chrome video. Note other players don't load. Attempted several scenes, server changes, page reload, and displayed settings.
https://vimeo.com/773349131 - Desktop client video. Other players load fine, but load times are about twice as long consistently for some reason (separate issue)?

**Comment by kwspgoliasz** [comment]
Thank you for the provided information. Sorry for the trouble but we'd like for you to confirm two additional things.
When accessing the browser version on chrome, is the platform launched on any other browser or the desktop client as well? Some irregularities may occur when two clients are opened simultaneously.
Additionally, could you please provide us with the log from a session on which the issue had occurred? The log should be obtained from the browser console (console can be accessed by pressing F12).

**Comment by renkcub** [comment]
> Collaborator

No - and I had this issue before I ever installed the desktop client. However, I ONLY have this issue when logged into my main Chrome profile which has other add-ons. I'm guessing that is the issue? I just tried opening up on a new Chrome profile and it fixed the issue.

**Comment by kwspgoliasz** [comment]
If changing the Chrome profile fixed the issue, then it is possible that an add-on might be the cause. If you don't mind, could you let us know what add-ons are installed on the mentioned profile, so we can investigate it more thoroughly?

**Comment by renkcub** [comment]
I have too many add-ons to list. If I am able to pin down which is causing the issue I will let you know. Thanks for the support.

**Comment by kwspgoliasz** [comment]
Thank you for the provided information. We're glad to have been of some help. In case of any further questions, please don't hesitate to contact us again.
