### ISSUE TITLE
Avatars appearing online but not visible

### ISSUE THREAD

**Issue by acrosscoder** [decentraland/issues#538]
### What happened?

when a place is loaded the other avatars take a long time to load
* some avatars load and are visible, some are not showing but appears to be online

### Steps to reproduce

Try visiting a place or any coordinates with a populated area
then wait for things to load

Realm:
 * any realm and place

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

### Wallet

Metamask

### CPU

Ryzen 5

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GT 730 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

32GB

### Kernel Version

1.0.0-3281395375.commit-29238aa

### Unity Version

1.0.57934-20221013161320.commit-72f1dfe

### Realm

baldr

### NameTag

JimSedric

**Comment by kwspgoliasz** [comment]
Hi, sorry for the late response. As this issue was already reported by you in another ticket, this one will be closed. Please refer to ticket [#536](https://github.com/decentraland/issues/issues/536) for further updates.
