### ISSUE TITLE
SteamPunk by Dapp Craft

### ISSUE THREAD

**Issue by mgpawoo** [decentraland/issues#54]
### What happened?

Could not complete the quest
![error](https://user-images.githubusercontent.com/19990541/139556105-af0dc25d-0dc4-45af-8fa9-67203fe782a0.jpg)
.

### Steps to reproduce

pass through the quest steps and then in the end you can't complete the quest and no reward will be given.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Metamask

### CPU

intel core i7-8700

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9649) 512MB

### RAM

32gb

### Kernel Version

1.0.0-1399994176.commit-9bd8e36

### Unity Version

1.0.18188-20211030153253.commit-2d4df83

### Realm

heimdallr

### NameTag

EzJOE#7984

**Comment by nearnshaw** [comment]
Hi!

The issue with this quest has now been resolved, thanks for reporting

If you enter the scene with the same account you originally used, you should now be able to talk to the NPC to complete the final step, and this time you'll receive the reward for completing the quest.

https://play.decentraland.org/?position=38%2C12
