### ISSUE TITLE
I cannot find the decentraland university, is it still in construction?

### ISSUE THREAD

**Issue by EmaCivaz** [decentraland/issues#540]
### What happened?

I read about decentraland university all over the web and I'd like to learn 3d modeling for decentraland but I cannot find the education district. is it still in construction?

### Steps to reproduce

I cannot find it in Genesis plaza by exploring with my avatar, nor in the map

### Operating System

Windows 11 Pro

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   1.99 GHz

### GPU

Sistema operativo a 64 bit, processore basato su x64

### RAM

16,0 GB (15,8 GB utilizzabile)

### Kernel Version

22H2

### Unity Version

ff

**Comment by kwspgoliasz** [comment]
Hi, sorry to have kept you waiting. The educational district is located at coordinates **-11,100**.
Unfortunately, as the area was not created by Decentraland, we are unable to provide any detailed information regarding the courses or the area's management.
Please contact the scene owner directly if you'd like to receive more detailed information.
