### ISSUE TITLE
Unexpected Realm switching issue

### ISSUE THREAD

**Issue by acrosscoder** [decentraland/issues#542]
### What happened?

Avatars on a specific realm get automatically and uncontrollably loaded into another realm
for example one of the avatars loaded in Baldr but suddenly gets loaded on the unicorn realm.

some related issues: 
 * sometimes when the user manually switches realms, it can't go to the desired realm
 * followed by a crash

### Steps to reproduce

load avatar on a specific realm like Baldr for example... then for a few minutes the realm switches into a different one

when it happens:
* randomly

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

### Wallet

Metamask

### CPU

Ryzen 7 CPU

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GT 710 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

16GB

### Kernel Version

1.0.0-3324480046.commit-3d365d8

### Unity Version

1.0.59618-20221025153231.commit-d676472

### Realm

baldr

### NameTag

JimSedric

**Comment by kwspgoliasz** [comment]
Hi, thank you for bringing this issue to our attention. Unfortunately, we were unable to reproduce it on our side. If you're still able to reproduce the issue, could you provide us with a video showing the realm switch?

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for over two weeks.
