### ISSUE TITLE
10/27/2022 - Avatars are loading as default avatars

### ISSUE THREAD

**Issue by acrosscoder** [decentraland/issues#543]
### What happened?

When entering today at DCL 
Issues
* avatars connected to Metamask are loading as default avatars with default wearables
* avatars are seen by others as default avatars even though they already changed wearable
* delays in wearable changing

### Steps to reproduce

try loading DCL avatar on any place with crowded populations on any realm (dg,baldr, etch)

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

### Wallet

Metamask

### CPU

Ryzen 7 CPU

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GT 710 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

32GB

### Kernel Version

1.0.0-3333920782.commit-4162db4

### Unity Version

1.0.59618-20221025153231.commit-d676472

### Realm

dg

### NameTag

JimSedric

**Comment by kwssbocian** [comment]
Hello, recently some updates have been made to the client which should have fixed this issue. Could you please update the client verify if it is still occurring for you? Thank you

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
