### ISSUE TITLE
Halloween Graveyard Menu Pops Up In Butterfly Prawn Game

### ISSUE THREAD

**Issue by ImageComposer** [decentraland/issues#545]
### What happened?

120, -11 Coordinates  -- Graveyard Halloween Game Menu appears in Butterfly Prawn Game
![10-29-2022 bug](https://user-images.githubusercontent.com/116951138/198827517-4592f06f-ceac-4745-8c81-9bb293c95551.JPG)

### Steps to reproduce

Walk around in Butterfly Prawn Game

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

### Wallet

Metamask

### CPU

Intel 19 10th Generation

### GPU

ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

32 GB

### Kernel Version

1.0.0-3346881156.commit-d4588f4

### Unity Version

1.0.60189-20221028142813.commit-7e54658

### Realm

baldr

### NameTag

Petunia#a039

**Comment by kwssbocian** [comment]
Hello and thank you for bringing this issue to our attention. This is a problem with the scene SDK implementation, not with Decentraland's client itself. Please try contacting the scene creator in order to fix the issue.
