### ISSUE TITLE
You Can Walk Into the Vending Cart Sign - Butterfly Prawn Game

### ISSUE THREAD

**Issue by ImageComposer** [decentraland/issues#546]
![10-29-2022 bug#2](https://user-images.githubusercontent.com/116951138/198828120-4e09ec76-87f9-4870-86f6-f4756a584047.JPG)

**Comment by kwssbocian** [comment]
Hello and thank you for bringing this issue to our attention. This is a problem with the scene SDK implementation, not with Decentraland's client itself. Please try contacting the scene creator in order to fix the issue.
