### ISSUE TITLE
toki land

### ISSUE THREAD

**Issue by chadsun** [decentraland/issues#549]
### What happened?

1. I opened the house of toki but when im about to open the safe inside it restard back again.
![toki hous](https://user-images.githubusercontent.com/113761199/198875610-c2ab6fde-20e2-4890-b8fa-08b17963eb3c.png)

2. another one is when passing the first barrier i just pass thru the side not acuiring the pass.

3. the vault at the edge of the garden where you put the number is not opening. even i have the code. 

### Steps to reproduce

At first I was able to enter by jumping at the back of the toki land and did not press the button at the side of the gate to open it.
the edge is so spacious you can just go to the side and enter.

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz

### GPU

Intel(R) HD Graphics 630 3941MB

### RAM

7883MB

### Kernel Version

1.0.0-3346881156.commit-d4588f4

### Unity Version

desktop-1.0.723-20221028151427.commit-dc27759

### Realm

baldr

### NameTag

chadprosun#6244

**Comment by kwssbocian** [comment]
Hello and thanks for bringing this issue to our attention. However this appears to be a problem with the scene SDK implementation, not with Decentraland's client itself. Please try contacting the scene creator in order to have the issue fixed.
