### ISSUE TITLE
Glass Pavillion 

### ISSUE THREAD

**Issue by queenAnn17** [decentraland/issues#552]
### What happened?

Im already done with the task but whenever i press claim the price it was unexpected error occurred, how can I claim the price without error? please help

### Steps to reproduce

please help me how can i claim the price?

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Wallet Connect

### CPU

AMD Ryzen 5 3600 6-Core Processor 

### GPU

NVIDIA GeForce RTX 2060 SUPER 8031MB

### RAM

16332MB

### Kernel Version

1.0.0-3346881156.commit-d4588f4

### Unity Version

desktop-1.0.723-20221028151427.commit-dc27759

### Realm

baldr

### NameTag

queenAnn#b247

**Comment by kwssbocian** [comment]
Hi and thank you for bringing this issue to our attention. Would you be able to provide us with more information to debug this issue? We'd need the scene coordinates and we'd also be grateful for a screenshot, or a video showing the problem.

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
