### ISSUE TITLE
Setting the interface dimensions

### ISSUE THREAD

**Issue by luger95** [decentraland/issues#555]
### What happened?

The size of the interface comes out of my screen. I can't figure out how to adjust it.

### Steps to reproduce

Launch the interface for the first time.

### Operating System

Windows 10  (10.0.19045) 64bit

### Wallet

Wallet Connect

### CPU

AMD Ryzen 3 2300X Quad-Core Processor 

### GPU

Radeon RX 570 Series 8170MB

### RAM

16296MB

### Kernel Version

1.0.0-3387732730.commit-bc98547

### Unity Version

desktop-1.0.741-20221103155459.commit-478d41e

### Realm

marvel

### NameTag

Luger95#55f0

**Comment by kwssbocian** [comment]
Hello, thank you for bringing this issue to our attention. Would you be able to provide us with more information to debug this issue? We'd be especially grateful for a screenshot, or a video showing the problem.

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
