### ISSUE TITLE
Error Spawn

### ISSUE THREAD

**Issue by GMmarcos** [decentraland/issues#556]
### What happened?

error spawn en Ghang Gang Rovi Grind Spot Power. Mi personaje se encuentra bug, en una ezquina y sin poder moverme atrapado entres los laterales y un muro. 

### Steps to reproduce

cambiar puntos de spawn.
![Sin título](https://user-images.githubusercontent.com/28172125/200101793-ff70fffb-6e4a-4db3-ad42-16bb6af348ca.png)

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz

### GPU

NVIDIA GeForce GTX 1650 3949MB

### RAM

16326MB

### Kernel Version

1.0.0-3387732730.commit-bc98547

### Unity Version

desktop-1.0.741-20221103155459.commit-478d41e

### Realm

marvel

### NameTag

Tucutin#0467

**Comment by kwspgoliasz** [comment]
Hi, thank you for your patience. We've investigated the scene, however, we were unable to reproduce the issue. Could you try to clear your Decentraland app cache/data and then check if the issue still occurs? If it does, we'd be grateful if you would provide us with a video clip.

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
