### ISSUE TITLE
Another Session Error

### ISSUE THREAD

**Issue by Tudamoon** [decentraland/issues#558]
### What happened?

The client keeps closing my session randomly while I am on Festival Road. Then it says I have it open on another session. I don't have another session open- the client is the only session I have open. It's probably happened 10 times today for me.

### Steps to reproduce

Unknown.

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz

### GPU

NVIDIA GeForce RTX 3090 24340MB

### RAM

65424MB

### Kernel Version

1.0.0-3439624905.commit-8755449

### Unity Version

desktop-1.0.766-20221110104109.commit-746c0b8

### Realm

baldr

### NameTag

TudaMoon

**Comment by kwspgoliasz** [comment]
Hello, thank you for bringing this issue to our attention. Unfortunately, we were unable to reproduce it on our side.
Could you try to reinstall the desktop client and then try to log in once more? Additionally, if you ever used the account with the website, please try to access and log out from the web client before attempting to access the desktop client.
If the issue still occurs after the trying the aforementioned methods, please contact us again. Additionally, we'd be very grateful if you could provide us with some screenshot, or video of the issue.

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
