### ISSUE TITLE
i cant see the dealer tables on the casinos

### ISSUE THREAD

**Issue by amchodler** [decentraland/issues#559]
### What happened?

i cant see the dealer tables on the casinos
i tried wait long time for apearing tables, nothing happens

### Steps to reproduce

show me the tables in the casinos please

### Operating System

Windows 10  (10.0.19043) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz

### GPU

Radeon (TM) 520 2039MB

### RAM

8057MB

### Kernel Version

1.0.0-3447314206.commit-3cd6272

### Unity Version

desktop-1.0.768-20221111011819.commit-45e707d

### Realm

dg

### NameTag

AMChodler#9b9a

**Comment by kwssbocian** [comment]
Hello, thank you for bringing this issue to our attention. If possible, could you check if the issue still occurs after relogging with your wallet and then logging into the platform with it again? A reinstall of the app could also potentially be of help.
If the problem will persist, please provide us with a screenshot, or a video showing the issue.
Additionally, the Ice Poker may sometimes by blocked if the platform is being accessed via a VPN. If possible, please let us know if one was used when the issue occurred.

**Comment by amchodler** [comment]
hi
i reinstalled it and it's the same problem that i cant enter the tables in
the casinos

I also cant see the wallet in the side of the game that shows how much mana
i have and all the game infobut if i connect as a guest so its upload the
side info.
i tried with 3 difrent computers connect in guest mode but its not giving
me to enter to the tables

Maybe the game not support gamble in israel?

‫בתאריך יום ג׳, 15 בנוב׳ 2022 ב-14:00 מאת ‪kwssbocian‬‏ <‪
***@***.***‬‏>:‬

**Comment by kwssbocian** [comment]
Thank you for the reply. Could you please also try updating drivers on your PC and after that trying logging in with a wallet and checking if it's still the same after that? If yes then we'd be grateful for some screenshots or a video of the issue so that we could see how it looks like on your end. Thanks!

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for over two weeks.
