### ISSUE TITLE
some error with quest API after completing task

### ISSUE THREAD

**Issue by lozhi** [decentraland/issues#56]
### What happened?

https://user-images.githubusercontent.com/93481689/139590106-2b724413-16cb-4bf5-aa09-f1fd226cf0ad.png

### Steps to reproduce

(https://user-images.githubusercontent.com/93481689/139590106-2b724413-16cb-4bf5-aa09-f1fd226cf0ad.png)

### Operating System

CHrome windows 10

### Wallet

Fortmatic

### CPU

Intel core I5 8250U

### GPU

NVIDIA 980T

### RAM

32GB

### Kernel Version

latest

### Unity Version

latest

### Realm

Steampunk DC Quest

### NameTag

Lydia#7477

**Comment by nearnshaw** [comment]
Hi!

The issue with this quest has now been resolved, thanks for reporting

If you enter the scene with the same account you originally used, you should now be able to talk to the NPC to complete the final step, and this time you'll receive the reward for completing the quest.

https://play.decentraland.org/?position=38%2C12
