### ISSUE TITLE
I can't even open my client.

### ISSUE THREAD

**Issue by 0xVapo** [decentraland/issues#562]
### What happened?

Ever since the MVMF22 started I've been unable to even load my Decentraland client. It just crashes for no reason. Got plenty of videos recorded.

### Steps to reproduce

Step 1: Open DCL Client
Step 2: ?????
Step 3: Crash

### Operating System

Windows 11 Pro

### Wallet

Metamask

### CPU

AMD Ryzen 5 3500X 6-Core Processor                3.95 GHz

### GPU

NVIDIA GeForce RTX3050

### RAM

32GB

### Kernel Version

latest i believe. can't even type

### Unity Version

latest i believe. can't even type

### Realm

default, idk

### NameTag

Vapo

**Comment by 0xVapo** [comment]
The error message is:

Something went wrong
Renderer unexpected exit: Exit code cfffffff, error message: Command failed: C:\Users\User\AppData\Roaming\explorer-desktop-launcher\renderer\prod\unity-renderer-windows.exe --browser false --port 7666

**Comment by kwspgoliasz** [comment]
Hello, thank you for bringing this issue to our attention. In order to investigate the case more thoroughly, could we ask you to provide us with logs from the session and a video of the issue? If the logs will be generated, you should be able to find them in the AppData\Roaming\explorer-desktop-launcher folder.
Additionally, we're currently experiencing some issues when launching the client on Windows 11, which might be related to your problem. You can find the details in the ticket [#81](https://github.com/decentraland/explorer-desktop-launcher/issues/81)

**Comment by 0xVapo** [comment]
> Hello, thank you for bringing this issue to our attention. In order to investigate the case more thoroughly, could we ask you to provide us with logs from the session and a video of the issue? If the logs will be generated, you should be able to find them in the AppData\Roaming\explorer-desktop-launcher folder. Additionally, we're currently experiencing some issues when launching the client on Windows 11, which might be related to your problem. You can find the details in the ticket [#81](https://github.com/decentraland/explorer-desktop-launcher/issues/81)

https://youtu.be/hWFcvjUPfkQ
https://youtu.be/LGEoxAlumgc

I'm looking at the explorer-desktop-launcher folder but no idea where are the logs tho. Thanks for the quick response.

**Comment by kwspgoliasz** [comment]
I'm sorry, it was a mistake on my side. You should be able to find the Player Log at the following location AppData\LocalLow\Decentraland.

**Comment by 0xVapo** [comment]
> I'm sorry, it was a mistake on my side. You should be able to find the Player Log at the following location AppData\LocalLow\Decentraland.

No worries, found it! https://easyupload.io/m/jk22bn

**Comment by kwspgoliasz** [comment]
Thank you, we'll look into it and get back to you as soon as we get some updates.

**Comment by kwspgoliasz** [comment]
Hi, the relevant team is still looking into the crash but they mentioned that the issue might be related to outdated drivers. Could you try to install all of the latest drivers for your hardware and afterwards reinstall the Decentraland client?
If these methods won't fix the issue, please contact us again.

**Comment by 0xVapo** [comment]
> Hi, the relevant team is still looking into the crash but they mentioned that the issue might be related to outdated drivers. Could you try to install all of the latest drivers for your hardware and afterwards reinstall the Decentraland client? If these methods won't fix the issue, please contact us again.

Hmmm that's interesting, I downloaded Device Doctor and it pointed 9 outdated drivers. I'll update them, reinstall the client and report back, thanks!

**Comment by 0xVapo** [comment]
I'm still crashing on larger scenes like the GamiMall (146,60) or Holy Temple

**Comment by kwspgoliasz** [comment]
Is the crash on the larger scenes the same one as the one you had right after logging in? If possible, could you provide us with the log for this crash as well? It should be in the same location as last time.

**Comment by 0xVapo** [comment]
> Is the crash on the larger scenes the same one as the one you had right after logging in? If possible, could you provide us with the log for this crash as well? It should be in the same location as last time.

Something went wrong
Renderer unexpected exit: Exit code c0000005, error message: Command failed: C:\Users\User\AppData\Roaming\explorer-desktop-launcher\renderer\prod\unity-renderer-windows.exe --browser false --port 7666

https://www.youtube.com/watch?v=OE_SVkzpY7E

https://easyupload.io/m/xlq977

**Comment by popuz** [comment]
hi @0xVapo, can you also attach a crash report from the `C:/Users/LUCASB~1/AppData/Local/Temp/Decentraland/Decentraland/Crashes` folder?

**Comment by 0xVapo** [comment]
> hi @0xVapo, can you also attach a crash report from the `C:/Users/LUCASB~1/AppData/Local/Temp/Decentraland/Decentraland/Crashes` folder?

Of course! I zipped the folders inside the Crashes folder: https://easyupload.io/ij1t6p

**Comment by kwspgoliasz** [comment]
Hi, thank you for your patience. We'd like to confirm one more thing. Does the platform crash for you at any scene, or only for locations where videos/clips are played?

**Comment by 0xVapo** [comment]
> Hi, thank you for your patience. We'd like to confirm one more thing. Does the platform crash for you at any scene, or only for locations where videos/clips are played?

I just visited Soul Magic (-29,80) and it crashed as well. [It has a billboard in the scene with a picture](https://i.ibb.co/8KBztSM/sdds.png), not sure if that counts as video/clip.

https://youtu.be/c6wraAmUCKo

I was wondering, what's currently the most stable windows version to use the Decentraland Client?

**Comment by kwspgoliasz** [comment]
Thank you for your response. The investigation team concluded that your crash matches the one from ticket [#3665](https://github.com/decentraland/unity-renderer/issues/3665).
The team is doing their best to deal with this issue as soon as possible. An update with a potential fix should be available soon. 
We're really thankful for all of your cooperation in investigating this issue.

Regarding the general stability of the platform, the desktop client seems to be the better option.

As all of the updates are going to be listed in the aforementioned ticket, this one will be closed. Please don't hesitate to contact us in case further questions.
