### ISSUE TITLE
Merch place at metafestival

### ISSUE THREAD

**Issue by Racanlicious** [decentraland/issues#563]
### What happened?

When you enter to this area one square put into the middle of the screen and doesnt let play in a good way

### Steps to reproduce

just enter in this area at the metafest

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz

### GPU

NVIDIA GeForce GTX 970 4043MB

### RAM

16245MB

### Kernel Version

1.0.0-3447314206.commit-3cd6272

### Unity Version

desktop-1.0.768-20221111011819.commit-45e707d

### Realm

artemis

### NameTag

Racan#4e03

**Comment by kwspgoliasz** [comment]
Hello, thank you for reaching out to us. We'd like to ask you for some additional details in order to thoroughly investigate the issue. If possible, could you provide us with coordinates for the merch shop, as well as a screenshot, or video of the issue?

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
