### ISSUE TITLE
Mine dropped, hit the ground and was already cracked open

### ISSUE THREAD

**Issue by kevinstotz** [decentraland/issues#564]
### What happened?

The mine fell from the sky, when the mine hit the ground it cracked open. I walked to the mine and clicked "mine", the mine then closed up and mined like normal. When the mine completed, the mine cracked open again like normal.

only happened one time

### Steps to reproduce

wait for a mine to fall and see if it hits the ground and cracks open

### Operating System

Windows 10

### Wallet

Metamask

### CPU

i8

### GPU

NVIDIA

### RAM

32GB

### Kernel Version

desktop- 1.0.768-202211111011819

### Unity Version

1.0.0-3447314206

### Realm

unsure

### NameTag

skins#f5e0

**Comment by kwssbocian** [comment]
Hello and thank you for bringing this issue to our attention. However this is a problem with the scene SDK implementation, not with Decentraland's client itself. Please try contacting the scene creator in order to fix the issue.
