### ISSUE TITLE
11 empty poaps from the metaversemusicfestival and 2 from quests

### ISSUE THREAD

**Issue by Makeanft** [decentraland/issues#57]
### What happened?

Afternoon Decentraland issues crew. I am having an issue with 11 NFTs in my wallet from Decentraland. (or poaps) I can see them in my wallet through the cargo.build app. I have others in my wallet through decentraland but there are 11 listed but empty. I tried to go through there support and it seems a few scams suggesting to go to walletconnect.com and another site and the site asks for your private keys I (did not do this). attached is a screen shot of the situation. of the missing nfts and a screen shot from the website that I believe is a scam on telegram and discord you may want to alert others to. 

best,
<img width="1850" alt="Screen Shot 2021-10-31 at 11 56 43 AM" src="https://user-images.githubusercontent.com/88350544/139600689-b6de01fb-8152-4e07-be8f-7247adf0d859.png">

<img width="1850" alt="Screen Shot 2021-10-31 at 12 39 17 PM" src="https://user-images.githubusercontent.com/88350544/139600694-aaf3d44d-7d66-4801-a4ac-a402f43dde8f.png">

### Steps to reproduce

would love to know what to do to get these poaps reconnected. also for the good people of decendraland I would get some sort of a team of support on Discord and reddit. Had at lest two people pretending to be support from there.

### Operating System

Brave browser (Macintosh; Intel Mac OS X 10_15_7) 

### Wallet

Metamask

### CPU

Imac pro

### GPU

AMD Radeon Pro Vega 56 OpenGL Engine 512MB

### RAM

32 GB

### Kernel Version

1.0.0-1399994176.commit-9bd8e36

### Unity Version

1.0.18188-20211030153253.commit-2d4df83

### Realm

heimdallr

### NameTag

Jgriff120#fc2f

**Comment by olavra** [comment]
Hi @Makeanft! Thanks for your report! Could you please provide your address so we can look into it?
Regards

**Comment by olavra** [comment]
Hi @Makeanft! Thank you for reporting this issue! You can go to https://app.poap.xyz/ to check your POAPs. 
Related to support, we are aware of the scammers and we are trying to get rid of them asap. Sorry for the inconveniences.
Please let me know if I can help you any further.

**Comment by Makeanft** [comment]
Hey Alvaro,
I caught up with someone from poap on discord, seems the 11 poaps are did not fully generate, and while I can see them through cargo.build they don’t come up on poap or open seas. But thanks for checking  in.
Best
Joshua 


Sent from Yahoo Mail for iPhone


On Tuesday, November 9, 2021, 10:57 AM, Alvaro Luque ***@***.***> wrote:




Hi @Makeanft! Thank you for reporting this issue! You can go to https://app.poap.xyz/ to check your POAPs.
Related to support, we are aware of the scammers and we are trying to get rid of them asap. Sorry for the inconveniences.
Please let me know if I can help you any further.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
