### ISSUE TITLE
No Hatchet from Hopper

### ISSUE THREAD

**Issue by Sucram1975** [decentraland/issues#570]
### What happened?

hopper won't give me an hatchet

### Steps to reproduce

Talk to Hopper

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 5600X 6-Core Processor 

### GPU

AMD Radeon RX 6700 XT 12243MB

### RAM

32680MB

### Kernel Version

2.0.0-3524549503.commit-af41d22

### Unity Version

desktop-1.0.805-20221116144427.commit-ad3486c

### Realm

dg

### NameTag

Bhozar#ff10

**Comment by kwssbocian** [comment]
Hello and thanks for bringing this issue to our attention. However this appears to be a problem with the scene SDK implementation, not with Decentraland's client itself. Please try contacting the scene creator in order to have the issue fixed.
