### ISSUE TITLE
Can not get my avatar

### ISSUE THREAD

**Issue by tarikmsr** [decentraland/issues#571]
### What happened?

Every time I entry to decentraland game (https://play.decentraland.org) , I find new random avatar.

when I check my avatar using api :
https://peer.decentral.io/lambdas//profiles/0x983d62d8a3d3502f40ec3102e8fa68006307c217

I get this empty message
{"avatars":[],"timestamp":0}

### Steps to reproduce

check api to get avatars:
https://peer.decentral.io/lambdas//profiles/0x983d62d8a3d3502f40ec3102e8fa68006307c217

### WHAT DID I TRY
1- I tried to clear cache.
2- to change my browser.
3- to create another account. 
but same issue !

### Operating System
Win 10 64x , Chrom/107.0.5304.122

### Wallet
Metamask

### CPU
intel i5 5th g

### RAM
16

### NameTag

TarikK#c217

**Comment by popuz** [comment]
Hi @tarikmsr. When I checked your link, it leads to the `{"avatars":[],"timestamp":0}`. This is the response you get when there is no account for the address. Are you sure that this is the right address?

**Comment by tarikmsr** [comment]
Hi @popuz , 
yeah same response I got , while I already have an account! 
and I'm sure that is the same address.

## the account info in decentraland game
![image](https://user-images.githubusercontent.com/64175026/205665091-73aa2997-0aef-460d-b470-23895ecb3801.png)


##  the account info in decentraland account / market pages
while in decentraland account page with the same address, I found that I'm connecting just as a guest
 
![image](https://user-images.githubusercontent.com/64175026/205669386-882a941c-171f-4dc6-be24-9e20b1d76528.png)

**Comment by davidejensen** [comment]
Hey @tarikmsr I'm not finding a way to reproduce this issue, I'd like to suggest a couple of things to see if we can get closer to the root problem.
1) Could you try changing the name/description from the account.decentraland.org page?
2) When logging in decentraland, could you verify if there are any critical errors in the browser console?
3) Have you tried using the desktop version? If yes does the same issue appear there?

**Comment by tarikmsr** [comment]
Hi @davidejensen, thanks for your response.

1- I couldn't change description or name , because I even didn't get my profile info (cz the api return empty data)
2- I don't get any error in console.
3- In decentraland game (https://play.decentraland.org/) ,
 I can find my userName, my NFTs , but my  main avatar comes randomly every time ,while I changed it and save it.


## this image show the api that get my profile +avatar info , 
![image](https://user-images.githubusercontent.com/64175026/205889642-9d416b8d-3d07-449b-a21f-e50c293c2464.png)


### Remark
in ( market.decentraland.org ) , I can NOT find my profile info , but I can find my NFTS !

![image](https://user-images.githubusercontent.com/64175026/205890629-30bf25b1-2c90-40e2-8e31-665b787dadd3.png)

**Comment by davidejensen** [comment]
Yes I understand it returns an empty profile, but if you try to press edit avatar, does it allow you to change name/description? And if yes and you save, what happens? Does it still return an empty api request?

**Comment by tarikmsr** [comment]
yes, like I mentioned , it redirect me to the play.decentraland page , and I can change my name  + my description 
but my avatar comes randomly, even if i press save , next time I find another avatar not mine.


## Note 

the api comes empty, while I can see my old name !  // just in case :  play.decentraland page.

I tried with new address , same issue.

**Comment by davidejensen** [comment]
Two additional things you can try:
1) Try re-installing metamask
2) Try by logging in the desktop application, you can find the download link on the decentraland website

**Comment by tarikmsr** [comment]
@davidejensen 

I did both, still same issue.

**Comment by davidejensen** [comment]
The fact that the api returns an empty avatar might mean that there was an issue on the avatar deployment, have you tried changing wearables and saving the profile? 
could you also attach here the browser logs generated when you save a profile with the different wearables?

**Comment by kwspgoliasz** [comment]
Closing this issue due to lack of response for two weeks. Don't hesitate to contact us again in case of any other questions.
