### ISSUE TITLE
Character Stuck

### ISSUE THREAD

**Issue by Dragonfyr** [decentraland/issues#572]
### What happened?

Walked into 'Jammin'Land', walked into a corner (looking at the front entrance, to the right side where there's a mirror, there), can't unstuck my character. 

### Steps to reproduce

As above. Although you can jump out of it. 

### Operating System

Windows 10  (10.0.19045) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 9 3900X 12-Core Processor 

### GPU

NVIDIA GeForce RTX 2080 Ti 11049MB

### RAM

32681MB

### Kernel Version

2.0.0-3605137484.commit-bbe0daf

### Unity Version

desktop-1.0.866-20221202211207.commit-cd84718

### Realm

dg

### NameTag

Dragonfyr#b2fd

**Comment by kwspgoliasz** [comment]
Hello, thank you for reaching out to us. This is a problem with the scene SDK implementation, not with Decentraland's client. You could try contacting the scene creator in order to fix the issue.
