### ISSUE TITLE
Genesis plaza building failed loading, user spawned on floor with green loading indicators

### ISSUE THREAD

**Issue by eordano** [decentraland/issues#574]
### What happened?

With a recently downloaded client in a new machine, a user experienced the main building being missing after creating their avatar.

### Steps to reproduce

1. Download the Windows Desktop client
2. Spend a few minutes customizing the avatar
3. Enter the world

### Operating System

Windows 10, Native

### Wallet

None, played as guest

### CPU

Intel i5 7th Gen

### GPU

None (Intel Iris)

### RAM

8GB

### Kernel Version

(It wasn't my machine -- Play test was on Saturday)

### Unity Version

(It wasn't my machine -- Play test was on Saturday)

**Comment by kwssbocian** [comment]
Issue already known and tracked under [#3714](https://github.com/decentraland/unity-renderer/issues/3714)
