### ISSUE TITLE
i keep getting disconnected from just the POKER TABLE 

### ISSUE THREAD

**Issue by jabaahigh** [decentraland/issues#576]
### What happened?

im like close to winning a game sometimes and then boom i get it all just taken away from me and then on top of that i have to wait to play as if it was my fault i left ...

### Steps to reproduce

just playing, with possibly delegated gear all lvl 5, and if you want to come see me randomly get kicked off a table, my username is jabaah #b723

### Operating System

Windows 11  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

12th Gen Intel(R) Core(TM) i7-12700

### GPU

NVIDIA GeForce RTX 3060 Ti 8038MB

### RAM

32509MB

### Kernel Version

2.0.0-3651197935.commit-57cea9a

### Unity Version

desktop-1.0.901-20221207200957.commit-0265e67

### Realm

dg

### NameTag

jabaah#b723

**Comment by kwspgoliasz** [comment]
Thank you for reaching out to us. This is a problem with the scene SDK implementation, not with Decentraland's client. You should try contacting the scene creator in order to fix this issue.

**Comment by jabaahigh** [comment]
Hello, contacting you to let you know that its still an ongoing problem,
and I don't know how to directly contact SDK team, I know decentraland also
had a part in the creation of Ice Poker, and if there's anything you guys
can do, please let me know  because I really feel like this is a server
issue, where decentrland just randomly keeps refreshing my game and
spawning me at the spawn point of ice poker.....

**Comment by kwspgoliasz** [comment]
Thank you for the response. In that case, we'll forward this ticket to the relevant team. They should be able to help you in troubleshooting the issue.

**Comment by kwspgoliasz** [comment]
Hi, the relevant team investigated the issue, however, it seems that it is related to SDK implementation and needs to be addressed by the scene owner. 
You can try contacting Decentral Games in the following discord channel: https://discord.com/invite/decentralgames.
In case of any other issues, please don't hesitate to contact us again.
