### ISSUE TITLE
bug na entrada do wondermine

### ISSUE THREAD

**Issue by jefferamaxx** [decentraland/issues#579]
### What happened?

A bag não aparece o avatar fica batendo em barreiras verdes e andando em circulo os metoros não caem  e muita demora no carregamento.

### Steps to reproduce

Deixa-lo mais leve e rápido.

### Operating System

Windows 11  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz

### GPU

Intel(R) HD Graphics 3000 512MB

### RAM

7653MB

### Kernel Version

2.0.0-3706422264.commit-09c79d4

### Unity Version

desktop-1.0.954-20221215145051.commit-bd41e54

### Realm

baldr

### NameTag

jefferamaxx#4b74

**Comment by kwspgoliasz** [comment]
Hello, thank you for reaching out to us. The relevant team is already aware of the issue with prolonged loading times on desktop client and is planning to improve it in the future. Unfortunately, at this moment we have no eta for the fix that we can provide.

As a workaround, you could try accessing the client from the web browser and check if the platform runs more smoothly for you there. Additionally, we'd like to request for the future communication to be held in English.
