### ISSUE TITLE
Steam Punk DC Quest API Error

### ISSUE THREAD

**Issue by pawy** [decentraland/issues#58]
### What happened?

Reward receiving fails with an error

### Steps to reproduce

Complete quest and talk to ann
![Unbenannt](https://user-images.githubusercontent.com/5357398/139651824-ba1a74e3-b9d2-494d-9941-bb445e6cc5ac.PNG)
![Unbenannt3](https://user-images.githubusercontent.com/5357398/139651828-32b14a16-fe2a-4f61-9a68-777d3f409518.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/5357398/139651829-05287533-c3f5-4bca-95c5-518ba820dd7c.PNG)
a

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36

### Wallet

Metamask

### CPU

i7

### GPU

ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.9749) 512MB

### RAM

64GB

### Kernel Version

1.0.0-1399994176.commit-9bd8e36

### Unity Version

1.0.18188-20211030153253.commit-2d4df83

### Realm

loki

### NameTag

Pivot#4546

**Comment by nearnshaw** [comment]
Hi!

The issue with this quest has now been resolved, thanks for reporting

If you enter the scene with the same account you originally used, you should now be able to talk to the NPC to complete the final step, and this time you'll receive the reward for completing the quest.

https://play.decentraland.org/?position=38%2C12
