### ISSUE TITLE
Unable to take  shot in training

### ISSUE THREAD

**Issue by TheBoardy99** [decentraland/issues#581]
### What happened?

My ball went quite close to the edge and now im not able to take a shot

### Steps to reproduce

![image](https://user-images.githubusercontent.com/82479285/208242169-92beec4b-deea-41b1-8476-31b047ccdc7f.png)

### Operating System

Windows 11  (10.0.22621) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz

### GPU

NVIDIA Quadro K2200 4051MB

### RAM

32547MB

### Kernel Version

2.0.0-3713708490.commit-d4ba5f8

### Unity Version

desktop-1.0.954-20221215145051.commit-bd41e54

### Realm

dg

### NameTag

TheBoardy99#59ae

**Comment by kwspgoliasz** [comment]
Hi, thank you for reaching out to us. This is a problem with the scene SDK implementation, not with Decentraland's client. You should try contacting the scene creator in order to fix this issue.
