### ISSUE TITLE
I can mine the mine before it hits the ground

### ISSUE THREAD

**Issue by kevinstotz** [decentraland/issues#582]
### What happened?

There is a blue cone shape that precedes the mine falling to the ground. If you happen to be in the correct spot on the ground, the popup will show that says "Mine", but the mine has not fallen to the ground yet. Nevertheless, click mine and the axe starts mining. the mine then shows up and the axe is mining the mine that finally filled in the space

### Steps to reproduce

be in the correct spot on the screen where hte mine is to fall. Click mine

### Operating System

Windows 11  (10.0.22621) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz

### GPU

Intel(R) UHD Graphics 20355MB

### RAM

40711MB

### Kernel Version

2.0.0-3782178443.commit-4daf479

### Unity Version

desktop-1.0.969-20221221204312.commit-e29e47d

### Realm

marvel

### NameTag

Skinz#f5e0

**Comment by kwssbocian** [comment]
Hello and thanks for bringing this issue to our attention. However this appears to be a problem with the scene SDK implementation, not with Decentraland's client itself. Please try contacting the scene creator in order to have the issue fixed.
