### ISSUE TITLE
Im not able to play game 

### ISSUE THREAD

**Issue by BillionaireDA** [decentraland/issues#583]
### What happened?

I don't know why today morning Im playing game but immediately the game pushed me out of cycle game. Im try to rejoin again and again but as results ware unless. Game says Unauthorized client error. Reach out to support.   
![Uploading Capture.PNG…]()

### Steps to reproduce

let me play as usual...!! 

### Operating System

Windows 10  (10.0.19045) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz

### GPU

NVIDIA GeForce GTX 1050 1977MB

### RAM

8MB

### Kernel Version

2.0.0-3838467139.commit-bdbc933

### Unity Version

desktop-1.0.1045-20230104223520.commit-f7ff2ae

### Realm

athena

### NameTag

KingPoker#c784

**Comment by kwssbocian** [comment]
Hello, thank you for bringing this issue to our attention. Unfortunately, we were unable to reproduce it on our side.
If possible, could you check if the issue still occurs after logging out of your wallet and then logging into the platform with it again?
If the problem will persist, please provide us with a screenshot, or a video showing the issue.

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
