### ISSUE TITLE
Wondermine Bug

### ISSUE THREAD

**Issue by ibrahimsofu** [decentraland/issues#584]
### What happened?

Hello. Although my character is level 65 in Wondermine, it appears as level 1 in the game. This problem has been going on for a week. Also, the in-game Craftmatik doesn't work either.

![Wondermine](https://user-images.githubusercontent.com/121691910/211122799-25b25d59-bbe7-493a-8394-bb2bad5c98c1.jpg)

![Wondermine karakter](https://user-images.githubusercontent.com/121691910/211122821-a11ecabf-fde4-4f7e-839d-98c35f400cce.jpg)

### Steps to reproduce

When I come to the Wondermine playground.

### Operating System

Windows0.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz

### GPU

NVIDIA GeForce 930M 2010MB

### RAM

16272MB

### Kernel Version

2.0.0-3857021076.commit-a295dd4

### Unity Version

desktop-1.0.1045-20230104223520.commit-f7ff2ae

### Realm

hephaestus

### NameTag

Kimbilirkim#2375

**Comment by kwssbocian** [comment]
Hello and thank you for bringing this issue to our attention. However this is a problem with the scene SDK implementation, not with Decentraland's client itself. Please try contacting the scene creator in order to fix the issue.
