### ISSUE TITLE
нет русского языка

### ISSUE THREAD

**Issue by sergio5656463** [decentraland/issues#586]
### What happened?

очень сложно изучать метавселенную незная языка

### Steps to reproduce

вы наверное врядли поймете что я хотел сказать

### Operating System

Windows 10  (10.0.19045) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 1500X Quad-Core Processor 

### GPU

AMD Radeon RX 580 2048SP 8170MB

### RAM

16309MB

### Kernel Version

2.0.0-3877361219.commit-077d5a2

### Unity Version

desktop-1.0.1045-20230104223520.commit-f7ff2ae

### Realm

athena

### NameTag

sergiovrn#9b56

**Comment by kwssbocian** [comment]
Hello, thank you for your interest as well as patience regarding this report. Unfortunately at the moment there are no concrete plans in the near future for introducing any other language support into the client. When such decision will be made it will definitely be announced through official channels of communication
