### ISSUE TITLE
Meshes not loading

### ISSUE THREAD

**Issue by mina-skunk** [decentraland/issues#587]
### What happened?

Meshes not loading

![image](https://user-images.githubusercontent.com/8146733/211721071-7dfe6ec9-807d-44ec-a1ce-1a1f00160e38.png)

### Steps to reproduce

Not sure, I came from the east.

### Operating System

Windows 11  (10.0.22622) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

### GPU

NVIDIA GeForce GT 1030 1982MB

### RAM

32475MB

### Kernel Version

2.0.0-3886326247.commit-03066cf

### Unity Version

desktop-1.0.1045-20230104223520.commit-f7ff2ae

### Realm

dg

### NameTag

splat2#513d

**Comment by kwssbocian** [comment]
Hello, thank you for bringing this issue to our attention. If possible, could you check if the issue still occurs after relogging with your wallet and then logging in with it again? A reinstall of the app (or clearing your browser cache, depending on the platform that you're using) could also potentially be of help. After doing that please let us know if it has fixed the issue.

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
