### ISSUE TITLE
Conncet

### ISSUE THREAD

**Issue by joshfisidi** [decentraland/issues#588]
### What happened?

Downloaded .dmg
Installed it in /Applications
Connected to the server via WalletConnect (MetaMask)

Stuck in a reconnection loop
The world resets every few seconds

### Steps to reproduce

![load it up](https://user-images.githubusercontent.com/76191290/211772710-8a9a18b0-c0b1-468b-a1a9-6ac80a868f7b.gif)

### Operating System

Mac OS X 12.6.2

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz

### GPU

AMD Radeon Pro 5500 XT 8176MB

### RAM

40960MB

### Kernel Version

2.0.0-3886326247.commit-03066cf

### Unity Version

desktop-1.0.1045-20230104223520.commit-f7ff2ae

### Realm

dg

### NameTag

jOsh#32c3

**Comment by kwssbocian** [comment]
Hello, thank you for bringing this issue to our attention. Unfortunately, we were unable to reproduce it on our side.
If possible, could you check if the issue still occurs after exiting your wallet and then logging into the platform with it again? If that doesn't help could you please try and remove the `explorer-desktop-launcher` folder inside of `Library/Application Support` and then let us know how it went?
Also could you also make sure that you are not logged in to Decentraland on another device/browser at the same time while using the same wallet?

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
