### ISSUE TITLE
UI does not load after selecting image

### ISSUE THREAD

**Issue by Othello16** [decentraland/issues#589]
### What happened?

Tried viewing what i believe to be an NFT but after the UI popped up, it was stuck at the loading screen. 

### Steps to reproduce

Go into the pool above the stage and select any of the images that will bring up the UI. 

### Operating System

Windows 11  (10.0.22621) 64bit

### Wallet

Metamask

### CPU

11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz

### GPU

NVIDIA GeForce RTX 3050 Ti Laptop GPU 3993MB

### RAM

16103MB

### Kernel Version

2.0.0-3892832104.commit-3e55cd0

### Unity Version

desktop-1.0.1084-20230111185309.commit-5b326ca

### Realm

hephaestus

### NameTag

RisingJupiter

**Comment by kwssbocian** [comment]
Hello, thank you for bringing this issue to our attention. Would you be able to provide us with more information to debug this issue? We'd be especially grateful for a screenshot, or a video showing the problem.

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
