### ISSUE TITLE
SteamPunk quest error

### ISSUE THREAD

**Issue by edvardasast** [decentraland/issues#59]
### What happened?

After complete quest I am getting quest API error
![image](https://user-images.githubusercontent.com/12156283/139653732-6cf18d07-f04b-452f-9c5f-685eb6132227.png)

### Steps to reproduce

Finish SteamPunk quest

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz   3.60 GHz

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 2080 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7155) 512MB

### RAM

16

### Kernel Version

1.0.0-1399994176.commit-9bd8e36

### Unity Version

1.0.18188-20211030153253.commit-2d4df83

### Realm

loki

### NameTag

xEAx#7501

**Comment by nearnshaw** [comment]
Hi!

The issue with this quest has now been resolved, thanks for reporting

If you enter the scene with the same account you originally used, you should now be able to talk to the NPC to complete the final step, and this time you'll receive the reward for completing the quest.

https://play.decentraland.org/?position=38%2C12
