### ISSUE TITLE
no account found in ethermon

### ISSUE THREAD

**Issue by CHIPDEALERS** [decentraland/issues#590]
### What happened?

no account found in ethermon

### Steps to reproduce

no account found in ethermon

### Operating System

Windows 10  (10.0.19041) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz

### GPU

NVIDIA GeForce GTX 1660 Ti 5979MB

### RAM

16295MB

### Kernel Version

2.0.0-3939205064.commit-d917703

### Unity Version

desktop-1.0.1097-20230112142442.commit-cc60c57

### Realm

hephaestus

### NameTag

247#bf8b

**Comment by kwssbocian** [comment]
Hello, thank you for bringing this issue to our attention. If possible, could you check if the issue still occurs after relogging with your wallet and then logging into the platform with it again? A reinstall of the app could also potentially be of help.
If the problem will persist, please provide us with a screenshot, or a video showing the issue.

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
