### ISSUE TITLE
Level went down from 60 to 55

### ISSUE THREAD

**Issue by BigEisen** [decentraland/issues#595]
### What happened?

Since yesterday I lost my level
![Bildschirmfoto 2023-01-30 um 15 23 09](https://user-images.githubusercontent.com/123964875/215508134-b4c52789-097d-4e6d-9013-93d90cb90270.png)

An right now I can't find any enemies and animals. Antron is empty

### Steps to reproduce

nA

### Operating System

Mac OS X 12.1.0

### Wallet

Metamask

### CPU

Apple M1 Max

### GPU

Apple M1 Max 43690MB

### RAM

65536MB

### Kernel Version

2.0.0-4018732630.commit-d22f1d3

### Unity Version

desktop-1.0.1172-20230125164145.commit-9dfba38

### Realm

marvel

### NameTag

BigEisen#6f4f

**Comment by BigEisen** [comment]
After leaving Antrom and rejoin stats are back

**Comment by kwssbocian** [comment]
Hello and thank you for bringing this issue to our attention. However this is a problem with the scene SDK implementation, not with Decentraland's client itself. Please try contacting the scene creator in order to fix the issue.
