### ISSUE TITLE
Wearables not recognized

### ISSUE THREAD

**Issue by BigEisen** [decentraland/issues#596]
### What happened?

Hi Team,

my Frost Monarch Wearables aren't recognized.
![Bildschirmfoto 2023-01-31 um 20 33 44](https://user-images.githubusercontent.com/123964875/215863974-b3a0bec6-e915-4b04-ac83-d71ece97d769.png)
![Bildschirmfoto 2023-01-31 um 20 33 49](https://user-images.githubusercontent.com/123964875/215863987-1973b7fd-151e-4808-a0f0-d28b440d3536.png)

### Steps to reproduce

nA

### Operating System

Mac OS X 12.1.0

### Wallet

Metamask

### CPU

Apple M1 Max

### GPU

Apple M1 Max 43690MB

### RAM

65536MB

### Kernel Version

2.0.0-4018732630.commit-d22f1d3

### Unity Version

desktop-1.0.1172-20230125164145.commit-9dfba38

### Realm

heimdallr

### NameTag

BigEisen#6f4f

**Comment by kwssbocian** [comment]
Hello and thank you for bringing this issue to our attention. However this appears to be a problem with the scene SDK implementation, not with Decentraland's client itself. Please try contacting the scene creator in order to fix the issue.
