### ISSUE TITLE
I'm stuck and I can't move.

### ISSUE THREAD

**Issue by HSuke** [decentraland/issues#599]
### What happened?

I walked into an elevator, and the door closed on me.

Also, these LaLiga missions are the WORST. They keep resetting progress whenever you exit. All the rabbits keep going invisible, and the NPC often disappear and go invisible.

### Steps to reproduce

Walk into an elevator

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 7 5800H with Radeon Graphics 

### GPU

NVIDIA GeForce RTX 3070 Laptop GPU 8033MB

### RAM

32116MB

### Kernel Version

1.0.76936-20230203192114.commit-3d5e351

### Unity Version

1.0.76936-20230203192114.commit-3d5e351

### Realm

heimdallr

### NameTag

MPTest#8f5c

**Comment by kwssbocian** [comment]
Hello and thank you for bringing this issue to our attention. However this is a problem with the scene SDK implementation, not with Decentraland's client itself. Please try contacting the scene creator in order to fix the issue.
