### ISSUE TITLE
reward claim quest steampunk

### ISSUE THREAD

**Issue by BabyMoHere** [decentraland/issues#60]
### What happened?

complete steampunk quest , try to claim the rewar
![Screenshot_2](https://user-images.githubusercontent.com/63315396/139675710-283a0eea-e960-4458-aae5-d8976bffd4fa.png)
![Screenshot_1](https://user-images.githubusercontent.com/63315396/139675727-890e6891-9606-45bf-900c-fcaad8dbc94b.png)

d

### Steps to reproduce

complete steampunk quest , try to claim the rewar

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Metamask

### CPU

intel i7

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1650 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6230) 512MB

### RAM

32gb

### Kernel Version

1.0.0-1399994176.commit-9bd8e36

### Unity Version

1.0.18188-20211030153253.commit-2d4df83

### Realm

dg

### NameTag

Juckieyou#7409

**Comment by nearnshaw** [comment]
Hi!

The issue with this quest has now been resolved, thanks for reporting

If you enter the scene with the same account you originally used, you should now be able to talk to the NPC to complete the final step, and this time you'll receive the reward for completing the quest.

https://play.decentraland.org/?position=38%2C12
