### ISSUE TITLE
Play Verse Scenario bug

### ISSUE THREAD

**Issue by moiper15** [decentraland/issues#600]
### What happened?

There are a problem with the textures in Play verse scenario 

### Steps to reproduce

In the Decentraland app appears this problem, in the browser versión works good.

### Operating System

Windows 10  (10.0.19045) 64bit

### Wallet

Wallet Connect

### CPU

Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz

### GPU

NVIDIA GeForce GTX 1650 3962MB

### RAM

14709MB

### Kernel Version

1.0.76936-20230203192114.commit-3d5e351

### Unity Version

1.0.76936-20230203192114.commit-3d5e351

### Realm

heimdallr

### NameTag

MOIPER#888f

**Comment by kwssbocian** [comment]
Hello, thank you for bringing this issue to our attention. Could you please provide us with a screenshot, or a video showing the issue?

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
