### ISSUE TITLE
the bus has disappeared

### ISSUE THREAD

**Issue by miningnome** [decentraland/issues#601]
### What happened?

The bus has disappeared and now appears like in purple "ghost" skin, can catch it.

### Steps to reproduce

Just go inside several times, at the 6th/7th time it will happen.

![image](https://user-images.githubusercontent.com/39877798/217094433-efd05ce2-6a4c-47c4-9fea-4f3f3adf2c44.png)

### Operating System

Windows 11  (10.0.22621) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 9 3950X 16-Core Processor 

### GPU

AMD Radeon RX 6800 XT 16337MB

### RAM

32690MB

### Kernel Version

1.0.76936-20230203192114.commit-3d5e351

### Unity Version

1.0.76936-20230203192114.commit-3d5e351

### Realm

heimdallr

### NameTag

Sakeador#d9ad

**Comment by kwssbocian** [comment]
Hello and thanks for bringing the issue to our attention. However it is already known and being tracked here [#3284](https://github.com/decentraland/unity-renderer/issues/3284).
