### ISSUE TITLE
" Can't Find me a table"

### ISSUE THREAD

**Issue by DonPabloEscobarr** [decentraland/issues#602]
### What happened?

I cant find a table the time I check in my wearables. " find me a table " is not showing up to find me table.

### Steps to reproduce

what should I do ? 

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.78

### Wallet

Metamask

### CPU

Ryzen 3300X

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1650 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

16GB

### Kernel Version

1.0.76936-20230203192114.commit-3d5e351

### Unity Version

1.0.76936-20230203192114.commit-3d5e351

### Realm

heimdallr

### NameTag

awdawd#c7fb

**Comment by kwssbocian** [comment]
Hello and thank you for bringing this issue to our attention. However this is a problem with the scene SDK implementation, not with Decentraland's client itself. Please try contacting the scene creator in order to fix the issue.
