### ISSUE TITLE
Moving player in the world

### ISSUE THREAD

**Issue by marquies** [decentraland/issues#605]
### What happened?

After entering the world, when moving the avatar, the avatar movement is randomly set back to the start point. It makes moving very hard. Also after jumping to a place in Decentraland, the avatar still bugs around. Not playable at all. 

### Steps to reproduce

1. Start Mac Client
2. Move around.

### Operating System

Mac OS X 13.1.0

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

### GPU

AMD Radeon Pro 5500M 4080MB

### RAM

32768MB

### Kernel Version

desktop-1.0.82987-20230216163357.commit-86cbefe

### Unity Version

desktop-1.0.82987-20230216163357.commit-86cbefe

### Realm

heimdallr

### NameTag

marquies#7682

**Comment by kwssbocian** [comment]
Hello and thank you for your patience regarding this issue. We've recently introduced some changes which should have resolved this. Can you please try and remove the `explorer-desktop-launcher` directory inside of Application Support then try again? If it's still going to be the same can you please provide a video showing the issue? Thank you

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
