### ISSUE TITLE
DCL App locking up on teleport to new destination

### ISSUE THREAD

**Issue by grafkaal** [decentraland/issues#606]
### What happened?

Whenever I jump to any area on the map or jump using /goto x,x the screen locks and the app has to be quit.
The jump works as I can hear myself jumping or walking at the destination.
The app has been working amazingly up until I think the latest version 0.1.46
Attached is the screen I get whenever I jump. 
![Screen_Shot_2023-02-17_at_20 16 33](https://user-images.githubusercontent.com/26093826/219908135-2a1d3882-d389-47aa-b419-fa9052decf42.png)

### Steps to reproduce

Load App, jump to any destination.

### Operating System

Mac OS X 10.13.6

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz

### GPU

NVIDIA GeForce GTX 780M 4096MB

### RAM

24576MB

### Kernel Version

desktop-1.0.82987-20230216163357.commit-86cbefe

### Unity Version

desktop-1.0.82987-20230216163357.commit-86cbefe

### Realm

heimdallr

### NameTag

Grafkaal

**Comment by kwssbocian** [comment]
Hello, we've recently introduced some changes which could have fixed this issue. Can you please try and delete the `explorer-desktop-launcher` directory inside of Application Support then log in again to Decentraland and let us know if it has changed anything on your end?

**Comment by grafkaal** [comment]
I've found, in my case, just deleting the GPUCache folder in the explorer-desktop-launcher works pretty well with the stuck loading at 0% and if I turn the "scenes load radius" to 1 it doesn't lock/crash as much!
