### ISSUE TITLE
quiz

### ISSUE THREAD

**Issue by lordgugo** [decentraland/issues#607]
### What happened?

the quiz not appear 
i cannot do nothing because i cante finish the courses

### Steps to reproduce

fix

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Wallet Connect

### CPU

AMD Ryzen 7 3700X 8-Core Processor 

### GPU

NVIDIA GeForce RTX 3060 12143MB

### RAM

32691MB

### Kernel Version

desktop-1.0.82987-20230216163357.commit-86cbefe

### Unity Version

desktop-1.0.82987-20230216163357.commit-86cbefe

### Realm

heimdallr

### NameTag

LordGugo#95d0

**Comment by kwssbocian** [comment]
Hi, can you please provide us with a screenshot/video of the issue and the coordinates in the world where this occurs? Thank you

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
