### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by zaryatka007** [decentraland/issues#608]
### What happened?

After the latest updates I cant jump in any parcels. I spawn at home point and can do something alone. To fix this, I have to re-log in several times to get a small chance to jump in another parcel.
![image](https://user-images.githubusercontent.com/87534129/220858030-30cac378-5b5c-4ab4-9afd-2e882aed33be.png)
If i open nearby chat i can see just this (see image). I can write something but cant send it. 
![image](https://user-images.githubusercontent.com/87534129/220858122-0909871b-b21f-46d8-af52-eb7a65a02643.png)
Also, my inventory cant loading.
![image](https://user-images.githubusercontent.com/87534129/220860594-ff0f72e3-098e-4d48-a5f1-53755e7b9ba1.png)
![image](https://user-images.githubusercontent.com/87534129/220860951-18f7ff2a-568f-4af8-981c-5fc87f79493a.png)

### Steps to reproduce

Launch the DCL with metamask wallet.

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

AMD Athlon(tm) II X4 620 Processor

### GPU

NVIDIA GeForce GTX 650 984MB

### RAM

8190MB

### Kernel Version

desktop-1.0.82987-20230216163357.commit-86cbefe

### Unity Version

desktop-1.0.82987-20230216163357.commit-86cbefe

### Realm

heimdallr

### NameTag

zaryat#61b1

**Comment by kwssbocian** [comment]
Hi, we've recently introduced some changes which should have fixed this issue. Could you please try and clear your local files by deleting the `explorer-desktop-launcher` folder inside %appdata% then try logging into Decentraland again?

**Comment by zaryatka007** [comment]
Hey! Yes, it helped, thank you very much!
