### ISSUE TITLE
i can get out of an info image on Butterfly Prawn Farming Game

### ISSUE THREAD

**Issue by abicastre** [decentraland/issues#609]
### What happened?

i can get out of an info image on Butterfly Prawn Farming Game

### Steps to reproduce

i can get out of an info image on Butterfly Prawn Farming Game

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 9 3900X 12-Core Processor 

### GPU

NVIDIA GeForce RTX 3060 12129MB

### RAM

32711MB

### Kernel Version

desktop-1.0.82987-20230216163357.commit-86cbefe

### Unity Version

desktop-1.0.82987-20230216163357.commit-86cbefe

### Realm

heimdallr

### NameTag

abicastre

**Comment by kwssbocian** [comment]
Hi. Could you please provide us with a screenshot, or a video showing the issue?

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
