### ISSUE TITLE
Livestream audio stops

### ISSUE THREAD

**Issue by chiaroscurosity** [decentraland/issues#610]
### What happened?

When moving from fullscreen to windowed, the audio from a livestream stops. The game sounds are still present though. To regain livestream audio, the DCL app must be quit and restarted.

### Steps to reproduce

Go to any stage with a livestream. When in fullscreen, change to windowed. The livestream audio will stop. Video will still be available.

### Operating System

Mac OS X 13.2.1

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i9-10910 CPU @ 3.60GHz

### GPU

AMD Radeon Pro 5500 XT 8176MB

### RAM

32768MB

### Kernel Version

desktop-1.0.82987-20230216163357.commit-86cbefe

### Unity Version

desktop-1.0.82987-20230216163357.commit-86cbefe

### Realm

heimdallr

### NameTag

Moto#dd92

**Comment by kwssbocian** [comment]
Hello and thank you for you patience. Would you be able to clear the contents of your `Local Storage` directory inside of `Library/Application Support/explorer-desktop-launcher` and then check if the issue still occurs? If it does then could you please provide us with more information such as scene coordinates or a video showing the problem? Thank you

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
