### ISSUE TITLE
Video don't play

### ISSUE THREAD

**Issue by TakaParade** [decentraland/issues#611]
### What happened?

Video player doesn't play video.
Browser does.

### Steps to reproduce

none.

### Operating System

Mac OS X 13.2.1

### Wallet

Metamask

### CPU

Apple M2 Pro

### GPU

Apple M2 Pro 10922MB

### RAM

16384MB

### Kernel Version

desktop-1.0.84207-20230227202521.commit-bc9219c

### Unity Version

desktop-1.0.84207-20230227202521.commit-bc9219c

### Realm

heimdallr

### NameTag

TakaSuzuki#20ea

**Comment by kwssbocian** [comment]
Hello, thank you for bringing this issue to our attention. Would you be able to provide us with more information to debug this issue? We'd be especially grateful for scene coordinates a video showing the problem.

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
