### ISSUE TITLE
kick me out from table

### ISSUE THREAD

**Issue by fanatikosa** [decentraland/issues#613]
### What happened?

hello, I won 5000 or 6000 chips to 5 people at the same time and the system kicked me out of the table so that I have minus 2000 chips, so I sat on the table

### Steps to reproduce

I don't know how to fix this problem, you are the experts

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

### Wallet

Metamask

### CPU

i5

### GPU

ANGLE (AMD, Radeon RX 570 Series Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

16 gb

### Kernel Version

1.0.84559-20230228134447.commit-2546d79

### Unity Version

1.0.84559-20230228134447.commit-2546d79

### Realm

baldr

### NameTag

MrRed#d414

**Comment by kwssbocian** [comment]
Hello and thank you for bringing this issue to our attention. However this is a problem with the scene SDK implementation, not with Decentraland's client itself. Please try contacting the scene creator in order to fix the issue.
