### ISSUE TITLE
FPS Limit keeps switching back to MAX

### ISSUE THREAD

**Issue by HSuke** [decentraland/issues#615]
### What happened?

I set the FPS limit to 30 FPS every time. And then when I restart the app, it goes back to MAX

### Steps to reproduce

I set the FPS limit to 30 FPS every time. And then when I restart the app, it goes back to MAX

### Operating System

Windows 10  (10.0.19045) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 7 5800H with Radeon Graphics 

### GPU

NVIDIA GeForce RTX 3070 Laptop GPU 8033MB

### RAM

32116MB

### Kernel Version

desktop-1.0.85163-20230301160332.commit-8b4f139

### Unity Version

desktop-1.0.85163-20230301160332.commit-8b4f139

### Realm

unicorn

### NameTag

MPlankton#8f5c

**Comment by kwssbocian** [comment]
Hello and thanks for your report. This issue is already being tracked at [#3567](https://github.com/decentraland/unity-renderer/issues/3567).
