### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by LiuShugao** [decentraland/issues#616]
### What happened?

![image](https://user-images.githubusercontent.com/49239975/224288477-3d2092c1-8d4f-48be-ac31-cd787e05ea86.png)

### Steps to reproduce

。。。

### Operating System

Windows 11  (10.0.22621) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz

### GPU

Intel(R) UHD Graphics 620 4018MB

### RAM

8037MB

### Kernel Version

desktop-1.0.87869-20230307211632.commit-2418067

### Unity Version

desktop-1.0.87869-20230307211632.commit-2418067

### Realm

baldr

### NameTag

mary#f861

**Comment by kwssbocian** [comment]
Hello and thank you for reporting this issue. Can you please remove the contents of your `explorer-desktop-launcher` directory inside of %appdata% then try again and let us know if it has fixed the issue for you?

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
