### ISSUE TITLE
Temple

### ISSUE THREAD

**Issue by titrou91** [decentraland/issues#617]
### What happened?

I cant see the first radish the girl planted in temple so i cant start the game...

### Steps to reproduce

give a seed for new players 

### Operating System

Windows 11  (10.0.22621) 64bit

### Wallet

Metamask

### CPU

11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz

### GPU

NVIDIA GeForce RTX 3060 12129MB

### RAM

32548MB

### Kernel Version

desktop-1.0.87869-20230307211632.commit-2418067

### Unity Version

desktop-1.0.87869-20230307211632.commit-2418067

### Realm

baldr

### NameTag

titrou#c904

**Comment by kwssbocian** [comment]
Hi, can you please provide the coordinates of the location this occurred at and also a screenshot/video showing the issue?

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
