### ISSUE TITLE
walls are not active. task unavailable

### ISSUE THREAD

**Issue by truials** [decentraland/issues#618]
### What happened?

walls are not active. task unavailable

### Steps to reproduce

walls are not active. task unavailable

### Operating System

Windows 11  (10.0.22624) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz

### GPU

NVIDIA GeForce GTX 1650 3949MB

### RAM

16264MB

### Kernel Version

desktop-1.0.90919-20230315154144.commit-30d0e51

### Unity Version

desktop-1.0.90919-20230315154144.commit-30d0e51

### Realm

hera

### NameTag

kamatu#6cf5

**Comment by kwssbocian** [comment]
Hello, can you please provide us with more details regarding this issue? We'd need coordinates and a screenshot/video of the issue occurring

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
