### ISSUE TITLE
slotgame cleapatra (Oasis Arcade)

### ISSUE THREAD

**Issue by Mkalanawi23** [decentraland/issues#619]
### What happened?

i cant play the cleopatra slotgame

### Steps to reproduce

i don't do anything when i click ?

### Operating System

Windows 11  (10.0.22621) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz

### GPU

NVIDIA GeForce GTX 1650 Ti 3962MB

### RAM

16292MB

### Kernel Version

desktop-1.0.91848-20230316193823.commit-3058d4d

### Unity Version

desktop-1.0.91848-20230316193823.commit-3058d4d

### Realm

baldr

### NameTag

Paymefirst#7426

**Comment by kwssbocian** [comment]
Hello and thank you for bringing this issue to our attention. However this is a problem with the scene SDK implementation, not with Decentraland's client itself. Please try contacting the scene creator in order to fix the issue.
