### ISSUE TITLE
SteamPunk DC Quest - Decentraland

### ISSUE THREAD

**Issue by MrLuke2** [decentraland/issues#62]
### What happened?

I completed all task for the Steampunks DC Quest but am not able to receive my reward. I have left the world and attempted to return thinking it may have been fixed, but it did not and now has been this way for 2 days. I attempted to contact support through Discord, but the Discord Invitation is currently invalid. Please advise, I have also attempted to reset the quest through the reset lamp on the tree in front of the clock with no success. Each time I load the area all the quest is complete except talking to the lady and receiving my reward. Once I talk to the lady she says thanks then I get the error message (Attached)
![SteamPunks DC Quest - Error](https://user-images.githubusercontent.com/93392796/139697359-d42eb87c-0cfb-40d5-abf2-792bb17f1e7c.png)

### Steps to reproduce

The error occurs when I speak to the lady in SteamPunks DC to receive my reward. She says thanks then gives me a big error!

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-6200U

### GPU

ANGLE (Intel, Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0, D3D11-26.20.100.7812) 512MB

### RAM

16

### Kernel Version

1.0.0-1399994176.commit-9bd8e36

### Unity Version

1.0.18188-20211030153253.commit-2d4df83

### Realm

baldr

### NameTag

uncleluke#1f35

**Comment by nearnshaw** [comment]
Hi!

The issue with this quest has now been resolved, thanks for reporting

If you enter the scene with the same account you originally used, you should now be able to talk to the NPC to complete the final step, and this time you'll receive the reward for completing the quest.

https://play.decentraland.org/?position=38%2C12
