### ISSUE TITLE
Whole stack disappeared while in a hand

### ISSUE THREAD

**Issue by SnakeeyesOne** [decentraland/issues#620]
### What happened?

I was sat at table 5, playing with 81xx chips. Went all in with AK and got called. He had much less than me. Mid-hand I get kicked off table and achips were lost. Even if I lost the hand, I would have still have had 5000 left to finish my daily quests with. Now I am half way through, and I think this sucks. Your poker mechanics are not up to par, and this really pisses me off.

### Steps to reproduce

Fix the problem and give me my chips back

### Operating System

Windows 11  (10.0.22621) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz

### GPU

NVIDIA GeForce GTX 1660 Ti with Max-Q Design 5982MB

### RAM

32353MB

### Kernel Version

desktop-1.0.93180-20230321152015.commit-92ce8d2

### Unity Version

desktop-1.0.93180-20230321152015.commit-92ce8d2

### Realm

dg

### NameTag

Snakeeyes#1b8a

**Comment by SnakeeyesOne** [comment]
I was booted from the table when the flop was being laid. Suddenly all cards dissapeared and I was without a spot at the table, noe chips and nothing.

**Comment by kwssbocian** [comment]
Hello and thanks for raising this report. However this appears to be a problem with the scene SDK implementation, not with Decentraland's client itself. Please try contacting the scene creator in order to have the issue fixed. Thank you
