### ISSUE TITLE
The video is displayed in the browser, but not in the application

### ISSUE THREAD

**Issue by esisl** [decentraland/issues#621]
### What happened?

The video is displayed in the browser, but not in the application

I display the video using new VideoTexture("https://my_url ")

Everything works in the builder
In the published scene, when viewed in the browser - too

But when I enter the scene with a desktop application, the Planescape is visible, but the videos are not played.

### Steps to reproduce

Go to coordinates 39, 72 there is a three-storey building on the walls inside the screens. Here in the application they are empty, and in the browser they play videos

### Operating System

Windows 10  (10.0.19045) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz

### GPU

NVIDIA GeForce GT 710 2007MB

### RAM

16254MB

### Kernel Version

desktop-1.0.97016-20230329154250.commit-bbdf85a

### Unity Version

desktop-1.0.97016-20230329154250.commit-bbdf85a

### Realm

baldr

### NameTag

esisl#a344

**Comment by kwssbocian** [comment]
Hello, thank you for bringing this issue to our attention. Unfortunately we've been unable to reproduce it on our side. Could you please clear the contents of your `Local Storage` directory inside of `%appdata%/explorer-desktop-launcher` and then check if the issue still occurs? If it does then could you please provide us with a video showing the problem? Thank you

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
