### ISSUE TITLE
no elevator on the shop

### ISSUE THREAD

**Issue by lordgugo** [decentraland/issues#623]
### What happened?

cant finish the 20 missions because the shop dont have elevator

### Steps to reproduce

go to the shop

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 7 3700X 8-Core Processor 

### GPU

NVIDIA GeForce RTX 3060 12143MB

### RAM

32691MB

### Kernel Version

desktop-1.0.97316-20230329194509.commit-78a8265

### Unity Version

desktop-1.0.97316-20230329194509.commit-78a8265

### Realm

dg

### NameTag

LordGugo#95d0

**Comment by kwssbocian** [comment]
Hello, thank you for bringing this issue to our attention. Would you be able to provide us with more information to debug this issue? We'd be especially grateful for scene coordinates and a video showing the problem. Thank you

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
