### ISSUE TITLE
Unable to click popoup of T&C

### ISSUE THREAD

**Issue by AN8991** [decentraland/issues#624]
### What happened?

There is a static pop up open when you visit this coordinates (-16,150) which you should agree to before visiting this place.  The pop up isn't clickable on the Desktop Application.
![Screenshot of the T C](https://user-images.githubusercontent.com/26569849/230072155-5b821b82-be48-4e20-8b90-6c567342abf4.png)

### Steps to reproduce

1. Goto coordiantes  (-16,150)
2. See Pop-Up appear. Wont be able to click. Issue reproduced.

### Operating System

Windows 11  (10.0.22621) 64bit

### Wallet

Metamask

### CPU

12th Gen Intel(R) Core(TM) i7-12700K

### GPU

NVIDIA GeForce RTX 4080 16064MB

### RAM

65321MB

### Kernel Version

desktop-1.0.98935-20230404132958.commit-590c4ec

### Unity Version

desktop-1.0.98935-20230404132958.commit-590c4ec

### Realm

baldr

### NameTag

Bharat#28c1

**Comment by kwssbocian** [comment]
Hello, thank you for bringing this issue to our attention. We've since introduced updates which should have fixed the issue. Could you please clear the contents of your `Local Storage` directory inside of `%appdata%/explorer-desktop-launcher` and then check if the issue still occurs? Thank you

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
