### ISSUE TITLE
Carrera Stand - Interact with video failed

### ISSUE THREAD

**Issue by Diggio95** [decentraland/issues#625]
### What happened?

I am in the "Carrera Stand" (-5,49) and i pressed "interact" on the video screen on the left of the Carrera's shirt. That video doesn't start.

### Steps to reproduce

1. Into the Carrera Stand;
2. Coordinates (-5, 49);
3. I've done a left click on the screen on the left of Carrera's shirt when my cursor said "Interact";
4. Video doesn't start.

### Operating System

Windows 10  (10.0.19045) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx 

### GPU

AMD Radeon(TM) Vega 3 Mobile Graphics 3558MB

### RAM

7117MB

### Kernel Version

desktop-1.0.98935-20230404132958.commit-590c4ec

### Unity Version

desktop-1.0.98935-20230404132958.commit-590c4ec

### Realm

baldr

### NameTag

Diggio#f39c

**Comment by kwssbocian** [comment]
Hello, thank you for bringing this issue to our attention. Unfortunately we've been unable to reproduce it on our side. Could you please clear the contents of your `Local Storage` directory inside of `%appdata%/explorer-desktop-launcher` and then check if the issue still occurs? If it does then could you please provide us with a video showing the problem? Thank you

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
