### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Hibakhamis89** [decentraland/issues#626]
### Steps to reproduce

hello guys 

### Operating System

Windows 11  (10.0.22621) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz

### GPU

Intel(R) UHD Graphics 620 6065MB

### RAM

12130MB

### Kernel Version

desktop-1.0.98935-20230404132958.commit-590c4ec

### Unity Version

desktop-1.0.98935-20230404132958.commit-590c4ec

### Realm

hiboz

### NameTag

hiboz1989

**Comment by Hibakhamis89** [comment]
Hi

**Comment by kwsskulinski** [comment]
Hello, could you please describe the issue you are having?

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
