### ISSUE TITLE
Absolut Land Dance Battle Not Working

### ISSUE THREAD

**Issue by blackcoyote89** [decentraland/issues#627]
### What happened?

It started after arriving at the new Absolut Land in Decentraland, I was exploring the place after finishing the verifying my age and I was eager to want to do the dance battle feature.

However after the countdown for the dance battle thing reach zero I waited and waited but nothing happen. there was no notification or any changes what so ever.

And when I decided to head out and head back in the timer resets and the same thing happened again after the timer reach zero.

Something is wrong with the Absolut Land Dance Battle feature and I want to know why isn't it working for me even though I have a good internet connection.

please and thank you
blackcoyote89
![Decentraland 4_14_2023 5_02_53 PM](https://user-images.githubusercontent.com/130799683/232156962-4d3dabfd-c014-44ef-ba0f-4234152cdd16.png)

### Steps to reproduce

Well when I first arrived I verify my age from the promter and review the house rules

after that I wander around the Absolut Land place for each floor and than I waited in front of the large Wild Berry character until the timer each zero.

after that nothing happens after waiting and when leaving and coming back the timer resets.

### Operating System

Windows 10  (10.0.19045) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

### GPU

NVIDIA GeForce GTX 1070 8081MB

### RAM

32670MB

### Kernel Version

desktop-1.0.102687-20230413193410.commit-e600ca0

### Unity Version

desktop-1.0.102687-20230413193410.commit-e600ca0

### Realm

dg

### NameTag

blackcoyote89#7dad

**Comment by kwssbocian** [comment]
Hello and thank you for bringing this issue to our attention. However this is a problem with the scene SDK implementation, not with Decentraland's client itself. Please try contacting the scene creator in order to fix the issue.
