### ISSUE TITLE
too slow

### ISSUE THREAD

**Issue by HoneyTv** [decentraland/issues#628]
### What happened?

its taking sooooooo long to load the loby for a event i have to go to

<img width="950" alt="Screenshot 2023-04-16 200305" src="https://user-images.githubusercontent.com/112003412/232335783-08ea7b79-a29a-4ce0-9ca2-9b4a2e69668a.png">

been sat on here for 10 mins now

### Steps to reproduce

i dont know

### Operating System

Windows 11  (10.0.22621) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 4500U with Radeon Graphics 

### GPU

AMD Radeon(TM) Graphics 3774MB

### RAM

7549MB

### Kernel Version

desktop-1.0.102687-20230413193410.commit-e600ca0

### Unity Version

desktop-1.0.102687-20230413193410.commit-e600ca0

### Realm

dg

### NameTag

HoneyNia#372b

**Comment by kwsskulinski** [comment]
Hello and thank you for bringing this issue to our attention. However this is a problem with the scene SDK implementation, not with Decentraland's client itself. Please try contacting the scene creator in order to fix the issue.
