### ISSUE TITLE
Error claiming wearable

### ISSUE THREAD

**Issue by vickorkumar** [decentraland/issues#629]
### What happened?

After completing a task in Dominos store, i clicked on the wearable and also on waiter. It asked me to enter the captcha and after entering captcha and click/entered on submit i got the error.

### Steps to reproduce

1.Click on the waiter
2.enter the captcha asked
3.click on submit/ click enter
4.it shows the error 

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx 

### GPU

AMD Radeon(TM) Vega 8 Graphics 3029MB

### RAM

6058MB

### Kernel Version

desktop-1.0.103960-20230418125811.commit-3ee87bc

### Unity Version

desktop-1.0.103960-20230418125811.commit-3ee87bc

### Realm

unicorn

### NameTag

Vicktor#1f86

**Comment by kwsskulinski** [comment]
Hello and thank you for bringing this issue to our attention. In order to get this issue resolved please contact the issuers of the NFT collection directly. Thank you.
