### ISSUE TITLE
Got stuck

### ISSUE THREAD

**Issue by MyemiOficial** [decentraland/issues#63]
### What happened?

When you jump near to the table you get stuck and cant move

### Steps to reproduce

Check how to move somethin

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36

### Wallet

Metamask

### CPU

Intel i7 10th genetation

### GPU

ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8729) 512MB

### RAM

16

### Kernel Version

1.0.0-1399994176.commit-9bd8e36

### Unity Version

1.0.18188-20211030153253.commit-2d4df83

### Realm

dg

### NameTag

MyEmiofficial#66d8

**Comment by olavra** [comment]
Hi @MyemiOficial! Thank you for reporting this issue. The scenes, their geometry and colliders are completely generated by the community and the owners of the Lands, so they are out of our control over their content. However, we will try to get in touch with their owners to report this issue if you provide us with the coordinates of the land you got stuck.
Thank you very much for your time! I hope you have a great experience in Decentraland.
