### ISSUE TITLE
La touche Z pour avancer ne fonctionne pas !

### ISSUE THREAD

**Issue by Thomasecdo** [decentraland/issues#630]
### What happened?

Bonjour,

La touche Z pour avancer ne fonctionne pas

Cordialement

### Steps to reproduce

il faut remettre la fonction pour se déplacer

### Operating System

Windows 11  (10.0.22621) 64bit

### Wallet

Metamask

### CPU

12th Gen Intel(R) Core(TM) i7-12700H

### GPU

NVIDIA GeForce RTX 3070 Ti Laptop GPU 8032MB

### RAM

16051MB

### Kernel Version

desktop-1.0.103960-20230418125811.commit-3ee87bc

### Unity Version

desktop-1.0.103960-20230418125811.commit-3ee87bc

### Realm

dclonboarding.dcl.eth

### NameTag

Guest#b506

**Comment by kwsskulinski** [comment]
Hello, would you be able to describe the issue in English and provide screenshots/video showing the issue? Thank you.

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
