### ISSUE TITLE
Stuck Animation in Backpack when changing tabs.

### ISSUE THREAD

**Issue by ShibuyaMartin** [decentraland/issues#631]
### What happened?

When players selects a wearable an emote starts to play. If the player select another tab like settings, map, etc while the emote is playing it gets freeze in the last position. 

The desire behavior when changing tabs should be the avatar starting in idle pose again.

https://user-images.githubusercontent.com/25348765/233895902-bd614a5c-f5a9-4dd4-a9b6-3116461ff99d.mp4

### Steps to reproduce

1) Open Backpack
2) Select Wearable and change tab to Settings or Map when the emote it's playing.
3) Change again to Backpack.

### Operating System

Mac OS X 13.3.1

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz

### GPU

AMD Radeon Pro 5600M 8176MB

### RAM

16384MB

### Kernel Version

desktop-1.0.105111-20230420181712.commit-9d1da0a

### Unity Version

desktop-1.0.105111-20230420181712.commit-9d1da0a

### Realm

heimdallr

### NameTag

Shibu

**Comment by kwsskulinski** [comment]
Hello, thank you for bringing this issue to our attention. This is already known and being tracked at https://github.com/decentraland/unity-renderer/issues/4696
