### ISSUE TITLE
golf

### ISSUE THREAD

**Issue by zhor4k** [decentraland/issues#632]
### What happened?

i was playing mission in golf regime and after i hit the ball onto the mine, it explode and disappeared

### Steps to reproduce

fix level or mines and im waiting for compensation

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 7 2700 Eight-Core Processor 

### GPU

NVIDIA GeForce GTX 1080 Ti 11120MB

### RAM

16315MB

### Kernel Version

desktop-1.0.106064-20230424164124.commit-fdcdf1a

### Unity Version

desktop-1.0.106064-20230424164124.commit-fdcdf1a

### Realm

heimdallr

### NameTag

thin#fcca

**Comment by kwsskulinski** [comment]
Hello, thank you for bringing this issue to our attention. Would you be able to provide us with more information to debug this issue? We'd be especially grateful for scene coordinates and a video showing the problem. Thank you.

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
