### ISSUE TITLE
Still haven't receive my OG Community Collection NFTs for over a month after claiming

### ISSUE THREAD

**Issue by blackcoyote89** [decentraland/issues#633]
### What happened?

So over a month ago I found those og nfts at the og stage of the Meteverse Music Festival area at -60,88

I claim those wearable like any other and they are in my reward section with a "Queued To Send" status, but I haven't receive my nfts.

It been over a month since I claimed them and I still haven't receive those OG Community Collection NFTs or even The Voice Winners T-Shirt or the Rage MNFT or even the Hourglass Festival Tee 2022.

I want to know if I'll ever gonna receive those DCL wearable nfts or are they completely gone?

please help me
blackcoyote89

### Steps to reproduce

I went to the OG Stage at -60,88

I claim those wearables, I got confirmation that they are on their way.

But I have no received them and they are still Queued To Send after over a month after I claimed them.

### Operating System

Windows 10  (10.0.19045) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

### GPU

NVIDIA GeForce GTX 1070 8081MB

### RAM

32670MB

### Kernel Version

desktop-1.0.106064-20230424164124.commit-fdcdf1a

### Unity Version

desktop-1.0.106064-20230424164124.commit-fdcdf1a

### Realm

heimdallr

### NameTag

blackcoyote89#7dad

**Comment by kwsskulinski** [comment]
Hello and thank you for bringing this issue to our attention. In order to get this issue resolved please contact the issuers of the NFT collection directly. Thank you.
