### ISSUE TITLE
Dead end on the Toki Land

### ISSUE THREAD

**Issue by matiasmelendi** [decentraland/issues#634]
### What happened?

I was exploring the Toki Land jumping on the floating platforms, then I fell and reached a dead end on a pine that is on the right side of the entrance.
<img width="1512" alt="Screenshot 2023-05-02 at 21 46 19" src="https://user-images.githubusercontent.com/8699460/235814248-834d13a7-c761-41b4-a026-d415e7d5aeb5.png">

### Steps to reproduce

1. Enter the Toki Land
2. Jump on the floating platforms until you pass the first orange platform.
3. Jump to the pine below the floating platform.
4. Try to move outside the pine and you won't be able to escape.

<img width="1512" alt="Screenshot 2023-05-02 at 21 51 31" src="https://user-images.githubusercontent.com/8699460/235814655-33fc6563-5a6a-4120-9548-82ec49f41060.png">

### Operating System

Mac OS X 13.1.0

### Wallet

None, played as guest

### CPU

Apple M1 Pro

### GPU

Apple M1 Pro 10922MB

### RAM

16384MB

### Kernel Version

desktop-1.0.106064-20230424164124.commit-fdcdf1a

### Unity Version

desktop-1.0.106064-20230424164124.commit-fdcdf1a

### Realm

heimdallr

### NameTag

memonono#1f30

**Comment by kwssbocian** [comment]
Hello and thank you for bringing this issue to our attention. However this is a problem with the scene SDK implementation, not with Decentraland's client itself. Please try contacting the scene creator in order to fix the issue.
