### ISSUE TITLE
color scheme and contrast malfunction, also split screen

### ISSUE THREAD

**Issue by DCLRoots** [decentraland/issues#636]
### What happened?

Client/PC Colors are too dark and red, blue on one side and too bright and green, yellow on the other split in the North south axix (according to the map)

### Steps to reproduce

Enter DCL using client
![dcl client bug](https://user-images.githubusercontent.com/132593619/236257788-4c1ec165-15b0-48b1-af94-24efcbdfb703.png)

### Operating System

Windows 11  (10.0.22621) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 3600 6-Core Processor 

### GPU

NVIDIA GeForce GTX 1650 SUPER 3955MB

### RAM

16245MB

### Kernel Version

desktop-1.0.109301-20230504124034.commit-2dbd443

### Unity Version

desktop-1.0.109301-20230504124034.commit-2dbd443

### Realm

heimdallr

### NameTag

Roots

**Comment by kwsskulinski** [comment]
Hello, thank you for bringing this issue to our attention. Unfortunately we've been unable to reproduce it on our side. Could you please clear the contents of your `Local Storage` directory inside of `%appdata%/explorer-desktop-launcher` and then check if the issue still occurs? If it does then could you please provide us with a video showing the problem? Thank you.

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
