### ISSUE TITLE
Avatar Won't Move-Judges Room The Voice

### ISSUE THREAD

**Issue by brisco1016** [decentraland/issues#639]
### What happened?

Avatar will not move only turn in direction of the 4 directional keys on keyboard (W,A,S,D) but will not actually walk. Avatar stands in same spot and only turns in said direction, there is no movement from avatar. Also, as you can see what I run as far as my system goes and I should have no problems graphically running Decentraland but no matter what settings I put it on in Decentraland settings the application freezes frames every few seconds no matter what I do while running Decentraland. Of course it continues on as normal but cause me to not succeed in most of the games here because of this which in turn causes me to not be able achieve maximum performance and my winnings are not as they can be if this was not happening. What do you recommend as settings go according to my system. I understand that this is not what you are suppose to do so.....what settings would you run if you were running the same system hardware as I am? 

### Steps to reproduce

Not sure how you would reproduce this error but what I did was come back from the NBC room and walk in front of the judges and all of a sudden my avatar just stopped and then would not move. 

### Operating System

Windows 11  (10.0.22621) 64bit

### Wallet

Wallet Connect

### CPU

AMD Ryzen 7 5800X 8-Core Processor 

### GPU

NVIDIA GeForce RTX 3060 Ti 8038MB

### RAM

32678MB

### Kernel Version

1.0.114572-20230517133140.commit-5b10003

### Unity Version

1.0.114572-20230517133140.commit-5b10003

### Realm

baldr

### NameTag

Zcoobis#6112

**Comment by kwssbocian** [comment]
Hello and thank you for your patience regarding this issue. We have so far been unable to reproduce this on our side. Could we ask you to try and clear the contents of `Local Storage` directory inside `%appdata%\explorer-desktop-launcher` then try again and see if it still occurs? If it does then could you please provide us with a video showing the issue and coordinates of the scene this happened on? Thank you!

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.

**Comment by brisco1016** [comment]
I do apologize for no response regarding this issue. I have since been busy starting my 3D printing company. I no longer have Decentraland downloaded to my PC. I am planning on re-downloading soon and will open another issue on this topic if I can go back and recreate this for you. Thank you for your response and I again I do apologize for not responding sooner. Thank you.
