### ISSUE TITLE
Tablet support

### ISSUE THREAD

**Issue by beenzzz** [decentraland/issues#64]
### What happened?

I cant change my POV using my tablet. I use a tablet instead of a mouse as my input device and it seems to be ignored on decentraland. makes the experience unplayable, sadly.

### Steps to reproduce

I'm using a Wacom Intuos Pro S  PTH-451

### Operating System

Chrome Version 95.0.4638.54 OS 10.15.7 Catalina

### Wallet

Metamask

### CPU

2.5 GHz Quad-Core Intel Core i7

### GPU

NVIDIA GeForce GT 750M 2 GB Intel Iris Pro 1536 MB

### RAM

8 gb

### Kernel Version

1.0.0-1399994176.commit-9bd8e36

### Unity Version

1.0.18188-20211030153253.commit-2d4df83

### Realm

dg

### NameTag

Benz#85f6

**Comment by olavra** [comment]
Hi @beenzzz! Thanks for your feedback! At the moment we only support control using traditional mice and keyboard. Unfortunately we do not support the use of tablets as a substitute for mouse control, and we do not expect to be able to support it any time soon. However, we are testing alternative control methods that may help mitigate your situation, which we will announce in future system updates. I am sorry for any inconvenience this may cause you. Best regards.
