### ISSUE TITLE
Golfcraft Minigolf game unable to work while in middle of golf game and invisible ball

### ISSUE THREAD

**Issue by blackcoyote89** [decentraland/issues#640]
### What happened?

I was going to play a game of golf in decentraland Goftcraft Minigolf

First hole plays normally except for my ball being invisible which makes it harder to know where my ball was.

But on the second hole the game just completely stop all together, none of the players loaded up, no prompter on the timer, even the controls for the club is not responding anymore.

Can you please fix this big in Golfcraft in decentraland?
blackcoyote89
![Decentraland 6_27_2023 5_25_49 PM](https://github.com/decentraland/issues/assets/130799683/33ce0cfb-1705-4459-8920-5618524f18d9)

### Steps to reproduce

All I did was playing the game, I also adjusted my scenes load radius to try to fix it.

### Operating System

Windows 10  (10.0.19045) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

### GPU

NVIDIA GeForce GTX 1070 8081MB

### RAM

32670MB

### Kernel Version

1.0.126638-20230627080458.commit-63bc9a9

### Unity Version

1.0.126638-20230627080458.commit-63bc9a9

### Realm

heimdallr

### NameTag

Blackcoyote89#7dad

**Comment by kwssbocian** [comment]
Hello and thank you for your report. This is already being tracked under [#3819](https://github.com/decentraland/unity-renderer/issues/3819).
