### ISSUE TITLE
when loading space, the character jumps endlessly jumps and the map does not load

### ISSUE THREAD

**Issue by bcbhdfguw** [decentraland/issues#641]
### What happened?

1

### Steps to reproduce

2

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz

### GPU

NVIDIA GeForce RTX 3060 12129MB

### RAM

16254MB

### Kernel Version

1.0.133538-20230727203021.commit-0e352e5

### Unity Version

1.0.133538-20230727203021.commit-0e352e5

### Realm

dclonboarding.dcl.eth

### NameTag

Cinderella#2996

**Comment by kwssbocian** [comment]
Hello, thank you for bringing this issue to our attention. Unfortunately, we were unable to reproduce it on our side. Would you be able to provide us with more information to debug this issue? We'd be especially grateful for scene coordinates and a video showing the problem. Thank you

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
