### ISSUE TITLE
"Unable to get avatar wearable data"

### ISSUE THREAD

**Issue by SeptemberPASSION** [decentraland/issues#642]
### What happened?

The game won't let me play poker. It just keeps saying "unable to get avatar wearable data. Try again later". I waited a day to see if this would resolve. But it hasn't.

### Steps to reproduce

Just try to play poker (Metaverse, NOT arcade).

### Operating System

Windows 11  (10.0.22621) 64bit

### Wallet

Metamask

### CPU

11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz

### GPU

Intel(R) Iris(R) Xe Graphics 8053MB

### RAM

16106MB

### Kernel Version

1.0.134748-20230802140013.commit-b843135

### Unity Version

1.0.134748-20230802140013.commit-b843135

### Realm

heimdallr

### NameTag

SeptembrPASSION#d2e1

**Comment by kwssbocian** [comment]
Hello, thank you for bringing this issue to our attention. If possible, could you check if the issue still occurs after relogging with your wallet and then logging into the platform with it again? A reinstall of the Decentraland client app could also potentially be of help.
If the problem will persist, please provide us with a screenshot, or a video showing the issue. Thank you

**Comment by kwssbocian** [comment]
Closing this issue due to a lack of response for two weeks.
