### ISSUE TITLE
API Error after completing quest.

### ISSUE THREAD

**Issue by yzaragoza** [decentraland/issues#65]
### What happened?

After I completed the quest searching and placing the 5 gears for Anna, she says thank you for completing the quest followed by a 404 error.

### Steps to reproduce

Find and place the 5 gears in the quest and talk to Anna. 

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36

### Wallet

Metamask

### CPU

Think Pad 

### GPU

ANGLE (Intel, Intel(R) HD Graphics P630 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.9320) 512MB

### RAM

16GB

### Kernel Version

1.0.0-1399994176.commit-9bd8e36

### Unity Version

1.0.18188-20211030153253.commit-2d4df83

### Realm

loki

### NameTag

Elix#1f43

**Comment by nearnshaw** [comment]
Hi!

The issue with this quest has now been resolved, thanks for reporting

If you enter the scene with the same account you originally used, you should now be able to talk to the NPC to complete the final step, and this time you'll receive the reward for completing the quest.

https://play.decentraland.org/?position=38%2C12
