### ISSUE TITLE
Can't finish quiz

### ISSUE THREAD

**Issue by 13LD** [decentraland/issues#66]
### What happened?

![Uploading Screenshot 2021-11-02 at 23.11.24.png…]()

### Steps to reproduce

finished all tasks but receive nothing 

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36

### Wallet

Metamask

### CPU

I7

### GPU

ANGLE (Intel Inc., Intel(R) HD Graphics 630, OpenGL 4.1 INTEL-16.5.2) 512MB

### RAM

16

### Kernel Version

1.0.0-1399994176.commit-9bd8e36

### Unity Version

1.0.18370-20211102125328.commit-8157454

### Realm

loki

### NameTag

era3eld#e0c5

**Comment by nearnshaw** [comment]
Hi @13LD ! Is this regarding the DappCraft CyberPunk quest?

If so, the issue with this quest has now been resolved, thanks for reporting

If you enter the scene with the same account you originally used, you should now be able to talk to the NPC to complete the final step, and this time you'll receive the reward for completing the quest.

https://play.decentraland.org/?position=38%2C12

**Comment by moliva** [comment]
Closing this issue because of not having a response for two weeks.
