### ISSUE TITLE
POAP Error

### ISSUE THREAD

**Issue by CXRF** [decentraland/issues#67]
### What happened?

POAP Task (Talk to Anna) is not working

### Steps to reproduce

Fix it to collect my POAP

### Operating System

Google Chrome

### Wallet

Metamask

### CPU

Intel i5

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 3050 Ti Laptop GPU Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6262) 512MB

### RAM

16GB  

### Kernel Version

1.0.0-1399994176.commit-9bd8e36 

### Unity Version

1.0.18370-20211102125328.commit-8157454 

### Realm

loki 

### NameTag

CXRF#2299

**Comment by CXRF** [comment]
Thank you

**Comment by nearnshaw** [comment]
Hi!

The issue with this quest has now been resolved, thanks for reporting

If you enter the scene with the same account you originally used, you should now be able to talk to the NPC to complete the final step, and this time you'll receive the reward for completing the quest.

https://play.decentraland.org/?position=38%2C12

**Comment by CXRF** [comment]
Hi Nicolas,

I went and tried to get my POAP and for some reason I 'm still getting an
error message.
