### ISSUE TITLE
Collecting coin is impossible in the Highline

### ISSUE THREAD

**Issue by Sheryl0926** [decentraland/issues#68]
### What happened?

I found a coin, got the hand symbol with "collect the coin" as a message, but it's impossible to collect the coin.

### Steps to reproduce

Found a coin in the Highline and try to collect it

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36

### Wallet

Metamask

### CPU

HP Probook 440

### GPU

ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8853) 512MB

### RAM

32GB

### Kernel Version

1.0.0-1399994176.commit-9bd8e36

### Unity Version

1.0.18370-20211102125328.commit-8157454

### Realm

loki

### NameTag

Sheryl#01d9

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
