### ISSUE TITLE
Steampunk Quest

### ISSUE THREAD

**Issue by DarkWillow1404** [decentraland/issues#69]
### What happened?

After the quest when we talk to Anna for the reward, there is a message with API error

### Steps to reproduce

just try to finish the steampunk quest

### Operating System

Chrome

### Wallet

Wallet Connect

### CPU

I7

### GPU

MSI GTX 1070

### RAM

16

### Kernel Version

1.0.0-1399994176.commit-9bd8e36

### Unity Version

1.0.18370-20211102125328.commit-8157454

### Realm

loki

### NameTag

DarkWillow#11b7

**Comment by nearnshaw** [comment]
Hi!

The issue with this quest has now been resolved, thanks for reporting

If you enter the scene with the same account you originally used, you should now be able to talk to the NPC to complete the final step, and this time you'll receive the reward for completing the quest.

https://play.decentraland.org/?island=I3pe5d&position=38%2C12
