### ISSUE TITLE
collision box missing!?

### ISSUE THREAD

**Issue by IzHB** [decentraland/issues#70]
### What happened?

trapped in game. Bounding box not working well.

### Steps to reproduce

walk into the blue handlebars. 2nd floor

![Trapped](https://user-images.githubusercontent.com/84233449/140342279-8397692e-f873-4641-af76-1dbd487a27b2.JPG)

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Metamask

### CPU

intel 9th Gen

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5763) 512MB

### RAM

32

### Kernel Version

1.0.0-1399994176.commit-9bd8e36

### Unity Version

1.0.18370-20211102125328.commit-8157454

### Realm

loki

### NameTag

Iz#7a15

**Comment by olavra** [comment]
Hi @IzHB! Thank you for reporting this issue. The scenes, their geometry and colliders are completely generated by the community and the owners of the Lands, so they are out of our control over their content. However, we will try to get in touch with their owners to report this problem.
Thank you very much for your time! I hope you have a great experience in Decentraland.
