### ISSUE TITLE
Polygonal Coin Hunt Reward missing.

### ISSUE THREAD

**Issue by AtlantisKC** [decentraland/issues#71]
### What happened?

Hi, I have completed the required hunts and the green ticks confirm this, but I did not receive a POAP.  I tried logging in and out and also went to our Discord.  I was advised to check on app.poap.xyz and this confirmed no POAP.  Please can you help?

### Steps to reproduce

Check my account?

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Fortmatic

### CPU

intel core i5

### GPU

ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-26.20.100.7926) 512MB

### RAM

32g

### Kernel Version

1.0.0-1399994176.commit-9bd8e36

### Unity Version

1.0.18370-20211102125328.commit-8157454

### Realm

loki

### NameTag

Atlantis#44dc

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
