### ISSUE TITLE
Some errors with quest API

### ISSUE THREAD

**Issue by lupita2305** [decentraland/issues#72]
### What happened?

I successfully completed a quest but there was an error when I tried to collect my reward (POAP). 

--> SetQuestProgressState:717faa62-4116-4402-9658-05e16863308ahttp:500 details: unexpected error

### Steps to reproduce

Not sure. 

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36

### Wallet

Metamask

### CPU

2,3 GHz Dual-Core Intel Core i5

### GPU

Intel(R) Iris(TM) Plus Graphics 640 512MB

### RAM

8 GB 2133 MHz LPDDR3

### Kernel Version

1.0.0-1399994176.commit-9bd8e36

### Unity Version

1.0.18370-20211102125328.commit-8157454

### Realm

loki

### NameTag

Lupita#c419

**Comment by nearnshaw** [comment]
Hi!

The issue with this quest has now been resolved, thanks for reporting

If you enter the scene with the same account you originally used, you should now be able to talk to the NPC to complete the final step, and this time you'll receive the reward for completing the quest.

https://play.decentraland.org/?island=I3pe5d&position=38%2C12
