### ISSUE TITLE
Got stuck in water/ice in asian plaza.

### ISSUE THREAD

**Issue by Zeetastic** [decentraland/issues#73]
### What happened?

Hi there!

I was at asian plaza, 57, -57. where i fell over into the water (ice?) that the path goes into and could not get out. I tried jumping many many times in all corners. Now going to teleport away. Just wanted to report the bug. byeeeee

### Steps to reproduce

Go to 57, -57 and fall over into the water

### Operating System

windows 10

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz   2.30 GHz

### GPU

ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.9268) 512MB

### RAM

16.0 GB

### Kernel Version

1.0.0-1399994176.commit-9bd8e36

### Unity Version

1.0.18677-20211104161823.commit-31fb7ad

### Realm

asian plaza? (it's my first day sorry)

### NameTag

Zee#d6a9

**Comment by olavra** [comment]
Hi @Zeetastic ! Thank you for reporting this issue. The scenes, their geometry and colliders are completely generated by the community and the owners of the Lands, so they are out of our control over their content. However, we will try to get in touch with their owners to report this problem.
Thank you very much for your time! I hope you have a great experience in Decentraland.
