### ISSUE TITLE
Coin Collecting (Highline) not functioning

### ISSUE THREAD

**Issue by djacquescousteau** [decentraland/issues#75]
### What happened?

Whenever clicking to 'collect coin,' there is no response. I've tried re-teleporting, collecting various nearby coins, none of which seem to help. Was wondering what the potential problem may be. Thanks in advance!

### Steps to reproduce

<img width="1438" alt="Screen Shot 2021-11-06 at 2 43 38 PM" src="https://user-images.githubusercontent.com/93827826/140611870-d238d116-a261-4809-ad22-18a1509ca3e9.png">

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36

### Wallet

Metamask

### CPU

MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)

### GPU

Intel(R) Iris(TM) Plus Graphics 655 512MB

### RAM

16 GB

### Kernel Version

1.0.0-1399994176.commit-9bd8e36

### Unity Version

1.0.18875-20211105145659.commit-5cea412

### Realm

Highline

### NameTag

DJacques#ec80

**Comment by davidejensen** [comment]
This issue will be closed because the quest system is not active
