### ISSUE TITLE
Steampunk Quest

### ISSUE THREAD

**Issue by ZaryLion** [decentraland/issues#76]
### What happened?

After the quest when i talk to Anna for the reward there is a message " Some errors with Quests API. SetQuestProgressState:717faa62-4116-4402-9658-05e1686330a8http:500 details:Unexpected error"

### Steps to reproduce

Just by making the quest

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Metamask

### CPU

AMD Ryzen 5 3600XT 6-Core 

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6181) 512MB

### RAM

16

### Kernel Version

1.0.0-1399994176.commit-9bd8e36

### Unity Version

1.0.18875-20211105145659.commit-5cea412

### Realm

dg

### NameTag

ZaryLion#b410

**Comment by nearnshaw** [comment]
Hi!

The issue with this quest has now been resolved, thanks for reporting

If you enter the scene with the same account you originally used, you should now be able to talk to the NPC to complete the final step, and this time you'll receive the reward for completing the quest.

https://play.decentraland.org/?island=I3pe5d&position=38%2C12
