### ISSUE TITLE
SteamPunk Quest 

### ISSUE THREAD

**Issue by keyvand** [decentraland/issues#77]
### What happened?

I finished the quest and Anna told me thank you and that my reward is waiting but i never received my token.

### Steps to reproduce

Check in my account and see whats the Quest Error API message is and please fix it so I can recieve my POAP

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Metamask

### CPU

M1 chip

### GPU

Apple M1 Pro 512MB

### RAM

512GB

### Kernel Version

1.0.0-1399994176.commit-9bd8e36

### Unity Version

1.0.18875-20211105145659.commit-5cea412

### Realm

loki

### NameTag

DecentralJesus#242f

**Comment by nearnshaw** [comment]
Hi!

The issue with this quest has now been resolved, thanks for reporting

If you enter the scene with the same account you originally used, you should now be able to talk to the NPC to complete the final step, and this time you'll receive the reward for completing the quest.

https://play.decentraland.org/?island=I3pe5d&position=38%2C12
