### ISSUE TITLE
Polygonal Coin Hunt BUG 

### ISSUE THREAD

**Issue by PVBLO888** [decentraland/issues#78]
### What happened?

I fulfilled all the criteria but I have not gotten my poap plus everytime i log in it says I havent completed the quest then i jump in for the quest and it all starts green baring fulfilled says the quest is complete but still NO POAP 

### Steps to reproduce

fulfill quest

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Metamask

### CPU

Mac pro 

### GPU

Apple M1 512MB

### RAM

256

### Kernel Version

1.0.0-1399994176.commit-9bd8e36

### Unity Version

1.0.18875-20211105145659.commit-5cea412

### Realm

loki

### NameTag

PVBLO#dc19

**Comment by pravusjif** [comment]
We close this issue since the Quests service has been disabled for several months now. It will be reimplemented in the future.
