### ISSUE TITLE
keyboard layout

### ISSUE THREAD

**Issue by jaimelop** [decentraland/issues#79]
### What happened?

movement in the game is for qwerty keyboards, what about azerty?

### Steps to reproduce

have azerty keyboard and try to move

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Fortmatic

### CPU

doesn't matter

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 760 (192-bit) Direct3D11 vs_5_0 ps_5_0, D3D11-26.21.14.4280) 512MB

### RAM

doesn't matter

### Kernel Version

1.0.0-1435962399.commit-67d3765

### Unity Version

1.0.18875-20211105145659.commit-5cea412

### Realm

loki

### NameTag

Jaime#08e7

**Comment by olavra** [comment]
Hi @jaimelop! Thank you for reporting this issue. We will be working on the keyboard bindings soon, allowing players to customize the keys for every action and solve this problem.

**Comment by davidejensen** [comment]
duplicate https://github.com/decentraland/unity-renderer/issues/72
