### ISSUE TITLE
SteamPunk by DappCraft Quest (Not Fixed)

### ISSUE THREAD

**Issue by Preisolauphenonputenic** [decentraland/issues#80]
### What happened?

I sent a fix request for the POAP ending to SteamPunk by DappCraft Quest.  I received a notice in email that it was fixed.  I started the request again (as it required me to...), but every step of the quest (picking things up, opening boxes), I received the same error message, including when I got to the end.  Pictures of said issues added.

### Steps to reproduce

Starting and going through the quest (again) (for me) brings these bubbles up for every step in the quest
![DL - SteamPunk by DappCraft Quest 1](https://user-images.githubusercontent.com/80160391/140961689-0564082b-9d9a-468a-a949-8f80ed6adf5f.jpg)
![DL - SteamPunk by DappCraft Quest 2](https://user-images.githubusercontent.com/80160391/140961703-0f426a66-9c86-4224-a03a-013b831eeb10.jpg)
.

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Metamask

### CPU

2.6 GHz 6-Core Intel Core i7

### GPU

AMD Radeon Pro 5500M OpenGL Engine 512MB

### RAM

16 GB 2667 MHz DDR4

### Kernel Version

1.0.0-1440198849.commit-ba75666

### Unity Version

1.0.18875-20211105145659.commit-5cea412

### Realm

loki

### NameTag

Preisolauphenon#fd26

**Comment by pravusjif** [comment]
We close this issue since the Quests service has been disabled for several months now. It will be reimplemented in the future.
