### ISSUE TITLE
Polygonal coin hunt

### ISSUE THREAD

**Issue by DarkWillow1404** [decentraland/issues#81]
### What happened?

Quest finished but no reward. It says me "Quest not found"

### Steps to reproduce

Finish the quest

### Operating System

Chrome

### Wallet

Metamask

### CPU

I5

### GPU

Rtx 2070

### RAM

16

### Kernel Version

1.0.0-1440198849.commit-ba75666

### Unity Version

1.0.18875-20211105145659.commit-5cea412

### Realm

dg

### NameTag

DarkWillow#11b7

**Comment by pravusjif** [comment]
We close this issue since the Quests service has been disabled for several months now. It will be reimplemented in the future.
