### ISSUE TITLE
golf craft is very buggy

### ISSUE THREAD

**Issue by vanackerglenn** [decentraland/issues#82]
### What happened?

very often falling through colliders, sometimes a goal doesn't register, my ball got stuck in a collider.
![Schermafbeelding 2021-11-09 213558](https://user-images.githubusercontent.com/28847460/141000661-aba6d0ed-99f2-43a4-a8b0-3a98be2e32a5.png)

### Steps to reproduce

This happens often with games with multiple levels in height, like the one in the screenshot. Just play and you will experience sooner or later. it's never happened on games that are only on the ground.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Metamask

### CPU

Ryzen 7

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671) 512MB

### RAM

16GB

### Kernel Version

1.0.0-1440198849.commit-ba75666

### Unity Version

1.0.18875-20211105145659.commit-5cea412

### Realm

loki

### NameTag

Raven#1f66

**Comment by pravusjif** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client. You could try contacting the scene creator to fix the issue.
