### ISSUE TITLE
another collider issue

### ISSUE THREAD

**Issue by vanackerglenn** [decentraland/issues#83]
### What happened?

needed to hit 3 shiny things in the golf craft, and even after putting the ball in the final collider, it would not register.
![Schermafbeelding 2021-11-09 224855](https://user-images.githubusercontent.com/28847460/141010418-fb1239fd-48f0-413c-83b5-3ed84f0062fb.png)

### Steps to reproduce

Not sure if it can be reproduced, maybe it's a fluke, but it's happened to me before on goals, where the goal wouldn't register. And on collisions, where the ball or my character would glitch inside a collider or through it.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Metamask

### CPU

Ryzen 7

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671) 512MB

### RAM

16GB

### Kernel Version

1.0.0-1440198849.commit-ba75666

### Unity Version

1.0.18875-20211105145659.commit-5cea412

### Realm

loki

### NameTag

Eagle#1f66

**Comment by vanackerglenn** [comment]
I managed to reproduce this, it happens if you hit multiple colliders in a row with a hard shot. It seems there is an issue with the way the game registers a hit on those colliders, because the target stayed visible, but the collider itself was disabled. after hitting the collider where the next target should be visible, it enabled the renderer on the next target.

**Comment by pravusjif** [comment]
This is a problem with the scene SDK implementation, not with Decentraland's client. You could try contacting the scene creator to fix the issue.

**Comment by pabloes** [comment]
This was solved time ago
