### ISSUE TITLE
stuck on the rocks

### ISSUE THREAD

**Issue by garonglpg** [decentraland/issues#84]
### What happened?

I broke through the rocks and couldn't get out, coordinates -5, 81
![bugcaptur](https://user-images.githubusercontent.com/48933971/141038997-647790c2-a205-4a7b-920e-e190a8c4b463.PNG)

### Steps to reproduce

maybe make the rocks solid

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Metamask

### CPU

Intel i3 10th gen

### GPU

ANGLE (NVIDIA, NVIDIA GeForce MX110 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6259) 512MB

### RAM

8GB

### Kernel Version

1.0.0-1440198849.commit-ba75666

### Unity Version

1.0.18875-20211105145659.commit-5cea412

### Realm

dg

### NameTag

Nabila#ec2a

**Comment by D4rWiNSS** [comment]
This can't be fixed on our end since this bug is related to the scene. The content creator should fix it. Please contact the content creator in order to have this issue fixed
