### ISSUE TITLE
quests are not showing up 

### ISSUE THREAD

**Issue by nemohoes13** [decentraland/issues#85]
### What happened?

was in the middle of quest.. it froze... i loaded back up and all quests are now gone

### Steps to reproduce

give me more quests 

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Metamask

### CPU

rizen 7 3700x

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9649) 512MB

### RAM

32

### Kernel Version

1.0.0-1440198849.commit-ba75666

### Unity Version

1.0.18875-20211105145659.commit-5cea412

### Realm

dg

### NameTag

Nemohoes#07db

**Comment by pravusjif** [comment]
We close this issue since the Quests service has been disabled for several months now. It will be reimplemented in the future.
