### ISSUE TITLE
View is stuck

### ISSUE THREAD

**Issue by psycho-princess** [decentraland/issues#86]
### What happened?

I got stucked in one view. 

### Steps to reproduce

This happened during introduction when I try to jump in new groups. 

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Metamask

### CPU

Intel i9

### GPU

AMD Radeon Pro 5500M OpenGL Engine 512MB

### RAM

32

### Kernel Version

1.0.0-1440198849.commit-ba75666

### Unity Version

1.0.18875-20211105145659.commit-5cea412

### Realm

dg

### NameTag

PsychoPrincess#025a

**Comment by davidejensen** [comment]
Could you please provide additional informations on how to reproduce this issue?

**Comment by pravusjif** [comment]
Closing this issue because of not having a response for two weeks.
