### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by CXRF** [decentraland/issues#87]
### What happened?

![Untitled](https://user-images.githubusercontent.com/93418666/141666459-f13b6ab1-1829-42b8-bd8a-81154a684846.png)

### Steps to reproduce

Fix the POAP issue

### Operating System

Chrome/95.0.4638.69 

### Wallet

Metamask

### CPU

Intel i5

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 3050 Ti Laptop GPU Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6262) 512MB

### RAM

16GB  

### Kernel Version

1.0.0-1440198849.commit-ba75666

### Unity Version

1.0.18875-20211105145659.commit-5cea412

### Realm

dg

### NameTag

CXRF#2299

**Comment by CXRF** [comment]
I was told last time problem was fix, but still can't finish quest. Please help

**Comment by pravusjif** [comment]
We close this issue since the Quests service has been disabled for several months now. It will be reimplemented in the future.
