### ISSUE TITLE
cat Hair

### ISSUE THREAD

**Issue by Tobix282** [decentraland/issues#88]
### What happened?

i cant pick the cats hair.
every time i press E Nothing Happens

### Steps to reproduce

make the oktobusbar mission 

### Operating System

chrome

### Wallet

Metamask

### CPU

i3

### GPU

idk

### RAM

idk

### Kernel Version

idk

### Unity Version

idk

### Realm

dg

### NameTag

Iapaya#c7f1

**Comment by beebe4** [comment]
Same issue

**Comment by pravusjif** [comment]
We are missing information to debug this (where did this happen? for example)
