### ISSUE TITLE
Drink of the Gods Quest cannot finish

### ISSUE THREAD

**Issue by Maserattti** [decentraland/issues#89]
Hi, I have finished all the quest, however there is duplicate quest of "Find 10 Crystals" doesn't check off.
It keeps my quest completion status to 11/12
Can anyone help?
![Screenshot 2021-11-15 234145](https://user-images.githubusercontent.com/94388885/141820115-137f17d0-d81d-4a13-b524-1788a8b57e56.png)

**Comment by pravusjif** [comment]
We close this issue since the Quests service has been disabled for several months now. It will be reimplemented in the future.
