### ISSUE TITLE
wondermine crafting game not loading 

### ISSUE THREAD

**Issue by gugucuk** [decentraland/issues#91]
### What happened?

map does not load when teleporting to this area
![Screenshot_1](https://user-images.githubusercontent.com/94402654/141848357-72b8f1d0-d18b-452a-8d6c-05879d6f73ca.png)

### Steps to reproduce

This error occurred yesterday and I missed the crafting event because of this error. I went really crazy yesterday. Because every day I entered the game and dig. I want my losses to be compensated. 

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.53

### Wallet

Metamask

### CPU

core i5

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GT 820M Direct3D11 vs_5_0 ps_5_0, D3D11-23.21.13.9135) 512MB

### RAM

16 gb

### Kernel Version

1.0.0-1440198849.commit-ba75666

### Unity Version

1.0.18875-20211105145659.commit-5cea412

### Realm

dg

### NameTag

GuGuCuK#350d

**Comment by pravusjif** [comment]
This issue has already been fixed.
