### ISSUE TITLE
The drink of the gods Bugged (Can't finish)

### ISSUE THREAD

**Issue by wirb** [decentraland/issues#92]
### What happened?

I was doing "The drink of the gods" and the quest was fine up until the part when I needed to collect the 10 crystals. I collected them, but I collected more than 10. I collected 12. I turned in the quest and everything went as intended. I collected the key and then got the cup. The issue is that the steps all confirmed EXCEPT for the 10 crystals being collected. I went on to drink and dance at the main hub where I should complete the quest, but it says I must go and collected the 10 crystals still. The quest is broken.

### Steps to reproduce

See above.

### Operating System

 Chrome/95.0.4638.69   BRAVE BROWSER

### Wallet

Metamask

### CPU

Intel i9 10 gen

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 2080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9649) 512MB

### RAM

64GB

### Kernel Version

1.0.0-1440198849.commit-ba75666

### Unity Version

1.0.18875-20211105145659.commit-5cea412

### Realm

unicorn

### NameTag

Wirb#1d73

**Comment by pravusjif** [comment]
We close this issue since the Quests service has been disabled for several months now. It will be reimplemented in the future.
