### ISSUE TITLE
Polygonal Coin Hunt Glitch

### ISSUE THREAD

**Issue by TrueLovesNFTs** [decentraland/issues#93]
### What happened?

I was completing the Polygonal Coin quest, I only had one more coin left to collect. It was at the top of the club at Highline but when I went to collect it it wouldn't let me. I would click on it, press E on it but there was no way to collect it. i refreshed my browser and when i was logged back in my coin hunt quest had appeared to have reset. i then jumped to highline and upon arrival my quest began to complete itself. It said I had collected 14 coins at highline and now the quest is finished but i did not receive a POAP. If I log out the quest resets itself only to complete itself upon arrival to either of the two locations.

### Steps to reproduce

collect coins in quest, possibly time out server or connection then refresh. attempt to collect coin
![Screenshot (108)](https://user-images.githubusercontent.com/94442418/141956805-07125787-e54c-4e03-bb17-f47f83c318c0.png)
.

### Operating System

Chrome/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz   3.19 GHz

### GPU

ANGLE (Intel, Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8681) 512MB

### RAM

8.00 GB (7.88 GB usable)

### Kernel Version

1.0.0-1440198849.commit-ba75666

### Unity Version

1.0.18875-20211105145659.commit-5cea412

### Realm

dg

### NameTag

TrueLove#2c42

**Comment by pravusjif** [comment]
We close this issue since the Quests service has been disabled for several months now. It will be reimplemented in the future.
