### ISSUE TITLE
Error in API when trying to complete quest.

### ISSUE THREAD

**Issue by Selorex** [decentraland/issues#94]
### What happened?

Can't complete the quest. When I speak to the guy again, it says I've completed, but an API error comes up thus rendering completion of the quest nulled.

### Steps to reproduce

Finishing the necessary steps causes the API issue.

![image](https://user-images.githubusercontent.com/33289196/142063744-d98e11e8-bbe3-44b5-99a0-d29ebfc1da10.png)

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Fortmatic

### CPU

Intel 11th gen i7-1195G7

### GPU

ANGLE (Intel, Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.100.9864) 512MB

### RAM

16

### Kernel Version

1.0.0-1466666616.commit-b3bf440

### Unity Version

1.0.18875-20211105145659.commit-5cea412

### Realm

dg

### NameTag

H4K3R#6215

**Comment by pravusjif** [comment]
We close this issue since the Quests service has been disabled for several months now. It will be reimplemented in the future.
