### ISSUE TITLE
API error in Steampunk DC Quest

### ISSUE THREAD

**Issue by parunev** [decentraland/issues#95]
### What happened?

I finished every single task. I went to talk to Anna when an API error appeared. That's it.

### Steps to reproduce

No idea.

### Operating System

Chrome, MacOS

### Wallet

Metamask

### CPU

Intel

### GPU

Intel(R) HD Graphics 6000 512MB

### RAM

4

### Kernel Version

1.0.0-1466666616.commit-b3bf440

### Unity Version

1.0.18875-20211105145659.commit-5cea412

### Realm

dg

### NameTag

MetaThug#09a3

**Comment by pravusjif** [comment]
We close this issue since the Quests service has been disabled for several months now. It will be reimplemented in the future.
