### ISSUE TITLE
i can´t see the wondermine

### ISSUE THREAD

**Issue by caqui33** [decentraland/issues#96]
### What happened?

I entered wonderzone because i was going to mine some meteors but all the zone is invisible and don´t load,please check it

### Steps to reproduce

reload the game pls

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Wallet

Metamask

### CPU

intel

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7141) 512MB

### RAM

150gb

### Kernel Version

1.0.0-1466666616.commit-b3bf440

### Unity Version

1.0.19738-20211116145921.commit-c19ffd6

### Realm

dg

### NameTag

caqui#b45a

**Comment by gugucuk** [comment]
yes man, i have the same problem. even that's why i couldn't do anything on craft day

**Comment by pravusjif** [comment]
This issue has already been fixed.
