### ISSUE TITLE
Polygonal Coin Hunt Bug

### ISSUE THREAD

**Issue by AlexGuay91** [decentraland/issues#97]
### What happened?

When completion of quest in decentraland, it does not reward me with poap. Relog the quest will show brand new but when entered the quest again it shows completed but no reward given.

### Steps to reproduce

Enter decentraland
click quest button
select coin hunt go jump in
quest will show completed
but no reward prompted

### Operating System

Chrome/96.0.4664.45 (Windows 10 Home OS 19042.1348)

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.81 GHz

### GPU

NVIDIA GeForce GTX1060

### RAM

16GB

### Kernel Version

1.0.0-1466666616.commit-b3bf440

### Unity Version

1.0.19738-20211116145921.commit-c19ffd6

### Realm

dg

### NameTag

AlexGZ#3673

**Comment by pravusjif** [comment]
We close this issue since the Quests service has been disabled for several months now. It will be reimplemented in the future.
