### ISSUE TITLE
Bug Quest

### ISSUE THREAD

**Issue by Capanhoto** [decentraland/issues#99]
### What happened?

I'm doing the quest, "The Drink of the Gods" but I can't get the last berrie, the other two took 2 minutes to rescue while I was fusing the "e" button and the last just doesn't want to rescue.
already I will enjoy to say that I have a pc well above the media, but still the game laga a lot in the browser, have any tips for this? need another browser??? use microsoft edge.

### Steps to reproduce

I'm doing the phase normally, the first two barries took 2 minutes to rescue, and this one does not rescue at all

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.53

### Wallet

Metamask

### CPU

intel 5 9400f

### GPU

ANGLE (AMD, Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.13033.5003) 512MB

### RAM

16

### Kernel Version

1.0.0-1466666616.commit-b3bf440

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

dg

### NameTag

Lila3Pontos#6d38

**Comment by pravusjif** [comment]
We close this issue since the Quests service has been disabled for several months now. It will be reimplemented in the future.
